QuEST: Unit tests
Unit tests
Unit tests of the QuEST API, using Catch2 in C++14.
Functions
TEST_CASE ("applyDiagonalOp", "[operators]")
TEST_CASE ("applyFullQFT", "[operators]")
TEST_CASE ("applyGateMatrixN", "[operators]")
TEST_CASE ("applyGateSubDiagonalOp", "[unitaries]")
TEST_CASE ("applyMatrix2", "[operators]")
TEST_CASE ("applyMatrix4", "[operators]")
TEST_CASE ("applyMatrixN", "[operators]")
TEST_CASE ("applyMultiControlledGateMatrixN", "[operators]")
TEST_CASE ("applyMultiControlledMatrixN", "[operators]")
TEST_CASE ("applyMultiVarPhaseFunc", "[operators]")
TEST_CASE ("applyMultiVarPhaseFuncOverrides", "[operators]")
TEST_CASE ("applyNamedPhaseFunc", "[operators]")
TEST_CASE ("applyNamedPhaseFuncOverrides", "[operators]")
TEST_CASE ("applyParamNamedPhaseFunc", "[operators]")
TEST_CASE ("applyParamNamedPhaseFuncOverrides", "[operators]")
TEST_CASE ("applyPauliHamil", "[operators]")
TEST_CASE ("applyPauliSum", "[operators]")
TEST_CASE ("applyPhaseFunc", "[operators]")
TEST_CASE ("applyPhaseFuncOverrides", "[operators]")
TEST_CASE ("applyProjector", "[operators]")
TEST_CASE ("applyQFT", "[operators]")
TEST_CASE ("applySubDiagonalOp", "[unitaries]")
TEST_CASE ("applyTrotterCircuit", "[operators]")
TEST_CASE ("calcDensityInnerProduct", "[calculations]")
TEST_CASE ("calcExpecDiagonalOp", "[calculations]")
TEST_CASE ("calcExpecPauliHamil", "[calculations]")
TEST_CASE ("calcExpecPauliProd", "[calculations]")
TEST_CASE ("calcExpecPauliSum", "[calculations]")
TEST_CASE ("calcFidelity", "[calculations]")
TEST_CASE ("calcHilbertSchmidtDistance", "[calculations]")
TEST_CASE ("calcInnerProduct", "[calculations]")
TEST_CASE ("calcProbOfAllOutcomes", "[calculations]")
TEST_CASE ("calcProbOfOutcome", "[calculations]")
TEST_CASE ("calcPurity", "[calculations]")
TEST_CASE ("calcTotalProb", "[calculations]")
TEST_CASE ("cloneQureg", "[state_initialisations]")
TEST_CASE ("collapseToOutcome", "[gates]")
TEST_CASE ("compactUnitary", "[unitaries]")
TEST_CASE ("controlledCompactUnitary", "[unitaries]")
TEST_CASE ("controlledMultiQubitUnitary", "[unitaries]")
TEST_CASE ("controlledNot", "[unitaries]")
TEST_CASE ("controlledPauliY", "[unitaries]")
TEST_CASE ("controlledPhaseFlip", "[unitaries]")
TEST_CASE ("controlledPhaseShift", "[unitaries]")
TEST_CASE ("controlledRotateAroundAxis", "[unitaries]")
TEST_CASE ("controlledRotateX", "[unitaries]")
TEST_CASE ("controlledRotateY", "[unitaries]")
TEST_CASE ("controlledRotateZ", "[unitaries]")
TEST_CASE ("controlledTwoQubitUnitary", "[unitaries]")
TEST_CASE ("controlledUnitary", "[unitaries]")
TEST_CASE ("createCloneQureg", "[data_structures]")
TEST_CASE ("createComplexMatrixN", "[data_structures]")
TEST_CASE ("createDensityQureg", "[data_structures]")
TEST_CASE ("createDiagonalOp", "[data_structures]")
TEST_CASE ("createDiagonalOpFromPauliHamilFile", "[data_structures]")
TEST_CASE ("createPauliHamil", "[data_structures]")
TEST_CASE ("createPauliHamilFromFile", "[data_structures]")
TEST_CASE ("createQuESTEnv", "[data_structures]")
TEST_CASE ("createQureg", "[data_structures]")
TEST_CASE ("createSubDiagonalOp", "[data_structures]")
TEST_CASE ("destroyComplexMatrixN", "[data_structures]")
TEST_CASE ("destroyDiagonalOp", "[data_structures]")
TEST_CASE ("destroyPauliHamil", "[data_structures]")
TEST_CASE ("destroyQuESTEnv", "[data_structures]")
TEST_CASE ("destroyQureg", "[data_structures]")
TEST_CASE ("destroySubDiagonalOp", "[data_structures]")
TEST_CASE ("diagonalUnitary", "[unitaries]")
TEST_CASE ("fromComplex", "[data_structures]")
TEST_CASE ("getAmp", "[calculations]")
TEST_CASE ("getDensityAmp", "[calculations]")
TEST_CASE ("getImagAmp", "[calculations]")
TEST_CASE ("getNumAmps", "[calculations]")
TEST_CASE ("getNumQubits", "[calculations]")
TEST_CASE ("getProbAmp", "[calculations]")
TEST_CASE ("getRealAmp", "[calculations]")
TEST_CASE ("getStaticComplexMatrixN", "[data_structures]")
TEST_CASE ("hadamard", "[unitaries]")
TEST_CASE ("initBlankState", "[state_initialisations]")
TEST_CASE ("initClassicalState", "[state_initialisations]")
TEST_CASE ("initComplexMatrixN", "[data_structures]")
TEST_CASE ("initDiagonalOp", "[data_structures]")
TEST_CASE ("initDiagonalOpFromPauliHamil", "[data_structures]")
TEST_CASE ("initPauliHamil", "[data_structures]")
TEST_CASE ("initPlusState", "[state_initialisations]")
TEST_CASE ("initPureState", "[state_initialisations]")
TEST_CASE ("initStateFromAmps", "[state_initialisations]")
TEST_CASE ("initZeroState", "[state_initialisations]")
TEST_CASE ("measure", "[gates]")
TEST_CASE ("measureWithStats", "[gates]")
TEST_CASE ("mixDamping", "[decoherence]")
TEST_CASE ("mixDensityMatrix", "[decoherence]")
TEST_CASE ("mixDephasing", "[decoherence]")
TEST_CASE ("mixDepolarising", "[decoherence]")
TEST_CASE ("mixKrausMap", "[decoherence]")
TEST_CASE ("mixMultiQubitKrausMap", "[decoherence]")
TEST_CASE ("mixNonTPKrausMap", "[decoherence]")
TEST_CASE ("mixNonTPMultiQubitKrausMap", "[decoherence]")
TEST_CASE ("mixNonTPTwoQubitKrausMap", "[decoherence]")
TEST_CASE ("mixPauli", "[decoherence]")
TEST_CASE ("mixTwoQubitDephasing", "[decoherence]")
TEST_CASE ("mixTwoQubitDepolarising", "[decoherence]")
TEST_CASE ("mixTwoQubitKrausMap", "[decoherence]")
TEST_CASE ("multiControlledMultiQubitNot", "[unitaries]")
TEST_CASE ("multiControlledMultiQubitUnitary", "[unitaries]")
TEST_CASE ("multiControlledMultiRotatePauli", "[unitaries]")
TEST_CASE ("multiControlledMultiRotateZ", "[unitaries]")
TEST_CASE ("multiControlledPhaseFlip", "[unitaries]")
TEST_CASE ("multiControlledPhaseShift", "[unitaries]")
TEST_CASE ("multiControlledTwoQubitUnitary", "[unitaries]")
TEST_CASE ("multiControlledUnitary", "[unitaries]")
TEST_CASE ("multiQubitNot", "[unitaries]")
TEST_CASE ("multiQubitUnitary", "[unitaries]")
TEST_CASE ("multiRotatePauli", "[unitaries]")
TEST_CASE ("multiRotateZ", "[unitaries]")
TEST_CASE ("multiStateControlledUnitary", "[unitaries]")
TEST_CASE ("pauliX", "[unitaries]")
TEST_CASE ("pauliY", "[unitaries]")
TEST_CASE ("pauliZ", "[unitaries]")
TEST_CASE ("phaseShift", "[unitaries]")
TEST_CASE ("rotateAroundAxis", "[unitaries]")
TEST_CASE ("rotateX", "[unitaries]")
TEST_CASE ("rotateY", "[unitaries]")
TEST_CASE ("rotateZ", "[unitaries]")
TEST_CASE ("setAmps", "[state_initialisations]")
TEST_CASE ("setDensityAmps", "[state_initialisations]")
TEST_CASE ("setDiagonalOpElems", "[data_structures]")
TEST_CASE ("setQuregToPauliHamil", "[state_initialisations]")
TEST_CASE ("setWeightedQureg", "[state_initialisations]")
TEST_CASE ("sGate", "[unitaries]")
TEST_CASE ("sqrtSwapGate", "[unitaries]")
TEST_CASE ("swapGate", "[unitaries]")
TEST_CASE ("syncDiagonalOp", "[data_structures]")
TEST_CASE ("tGate", "[unitaries]")
TEST_CASE ("toComplex", "[data_structures]")
TEST_CASE ("twoQubitUnitary", "[unitaries]")
TEST_CASE ("unitary", "[unitaries]")
Detailed Description
Unit tests of the QuEST API, using Catch2 in C++14.
Function Documentation
TEST_CASE() [1/136]
TEST_CASE ("applyDiagonalOp" , "" [operators])
See also
applyDiagonalOp
Author
Tyson Jones
Definition at line 37 of file test_operators.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    SECTION( "correctness" ) {
        // try 10 random operators
        GENERATE( range(0,10) );
        // make a totally random (non-Hermitian) diagonal oeprator
        DiagonalOp op = createDiagonalOp(NUM_QUBITS, QUEST_ENV);
        for (long long int i=0; i<op.numElemsPerChunk; i++) {
            op.real[i] = getRandomReal(-5, 5);
            op.imag[i] = getRandomReal(-5, 5);
        }
        syncDiagonalOp(op);
        SECTION( "state-vector" ) {
            QVector ref = toQMatrix(op) * refVec;
            applyDiagonalOp(quregVec, op);
            REQUIRE( areEqual(quregVec, ref) );
        }
        SECTION( "density-matrix" ) {
            QMatrix ref = toQMatrix(op) * refMatr;
            applyDiagonalOp(quregMatr, op);
            REQUIRE( areEqual(quregMatr, ref, 100*REAL_EPS) );
        }
        destroyDiagonalOp(op, QUEST_ENV);
    }
    SECTION( "input validation" ) {
        SECTION( "mismatching size" ) {
            DiagonalOp op = createDiagonalOp(NUM_QUBITS + 1, QUEST_ENV);
            REQUIRE_THROWS_WITH( applyDiagonalOp(quregVec, op), Contains("equal number of qubits"));
            REQUIRE_THROWS_WITH( applyDiagonalOp(quregMatr, op), Contains("equal number of qubits"));
            destroyDiagonalOp(op, QUEST_ENV);
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyDiagonalOp(), areEqual(), CLEANUP_TEST, createDiagonalOp(), destroyDiagonalOp(), getRandomReal(), DiagonalOp::imag, NUM_QUBITS, DiagonalOp::numElemsPerChunk, PREPARE_TEST, QUEST_ENV, DiagonalOp::real, syncDiagonalOp(), and toQMatrix().
TEST_CASE() [2/136]
TEST_CASE ("applyFullQFT" , "" [operators])
See also
applyFullQFT
Author
Tyson Jones
Definition at line 88 of file test_operators.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    SECTION( "correctness" ) {
        // try 10 times for each kind of input
        GENERATE( range(0,10) );
        SECTION( "state-vector" ) {
            SECTION( "normalised" ) {
                refVec = getRandomStateVector(NUM_QUBITS);
                toQureg(quregVec, refVec);
                refVec = getDFT(refVec);
                applyFullQFT(quregVec);
                REQUIRE( areEqual(quregVec, refVec) );
            }
            SECTION( "unnormalised" ) {
                refVec = getRandomQVector(1 << NUM_QUBITS);
                toQureg(quregVec, refVec);
                refVec = getDFT(refVec);
                applyFullQFT(quregVec);
                REQUIRE( areEqual(quregVec, refVec) );
            }
        }
        SECTION( "density-matrix" ) {
            SECTION( "pure" ) {
                /* a pure density matrix should be mapped to a pure state
                 * corresponding to the state-vector DFT
                 */
                refVec = getRandomStateVector(NUM_QUBITS);
                refMatr = getPureDensityMatrix(refVec);
                toQureg(quregMatr, refMatr);
                applyFullQFT(quregMatr);
                refVec = getDFT(refVec);
                refMatr = getPureDensityMatrix(refVec);
                REQUIRE( areEqual(quregMatr, refMatr) );
            }
            SECTION( "mixed" ) {
                /* a mixed density matrix, conceptualised as a mixture of orthogonal
                 * state-vectors, should be mapped to an equally weighted mixture
                 * of DFTs of each state-vector (because QFT is unitary and hence
                 * maintains state orthogonality)
                 */
                int numStates = (1 << NUM_QUBITS)/4; // quarter as many states as possible
                std::vector<QVector> states = getRandomOrthonormalVectors(NUM_QUBITS, numStates);
                std::vector<qreal> probs = getRandomProbabilities(numStates);
                // set qureg to random mixture
                refMatr = getMixedDensityMatrix(probs, states);
                toQureg(quregMatr, refMatr);
                // apply QFT to mixture
                applyFullQFT(quregMatr);
                // compute dft of mixture, via dft of each state
                refMatr = getZeroMatrix(1 << NUM_QUBITS);
                for (int i=0; i<numStates; i++)
                    refMatr += probs[i] * getPureDensityMatrix(getDFT(states[i]));
                REQUIRE( areEqual(quregMatr, refMatr) );
            }
            SECTION( "unnormalised" ) {
                /* repeat method above, except that we use unnormalised vectors,
                 * and mix them with arbitrary complex numbers instead of probabilities,
                 * yielding an unnormalised density matrix
                 */
                int numVecs = (1 << NUM_QUBITS)/4; // quarter as many states as possible
                std::vector<QVector> vecs;
                std::vector<qcomp> coeffs;
                for (int i=0; i<numVecs; i++) {
                    vecs.push_back(getRandomQVector(1 << NUM_QUBITS));
                    coeffs.push_back(getRandomComplex());
                }
                // produce unnormalised matrix
                refMatr = getZeroMatrix(1 << NUM_QUBITS);
                for (int i=0; i<numVecs; i++)
                    refMatr += coeffs[i] * getPureDensityMatrix(vecs[i]);
                toQureg(quregMatr, refMatr);
                applyFullQFT(quregMatr);
                // compute target matrix via dft of each unnormalised vector
                refMatr = getZeroMatrix(1 << NUM_QUBITS);
                for (int i=0; i<numVecs; i++)
                    refMatr += coeffs[i] * getPureDensityMatrix(getDFT(vecs[i]));
                REQUIRE( areEqual(quregMatr, refMatr) );
            }
        }
    }
    SECTION( "input validation" ) {
        SUCCEED( );
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyFullQFT(), areEqual(), CLEANUP_TEST, getDFT(), getMixedDensityMatrix(), getPureDensityMatrix(), getRandomComplex(), getRandomOrthonormalVectors(), getRandomProbabilities(), getRandomQVector(), getRandomStateVector(), getZeroMatrix(), NUM_QUBITS, PREPARE_TEST, and toQureg().
TEST_CASE() [3/136]
TEST_CASE ("applyGateMatrixN" , "" [operators])
See also
applyGateMatrixN
Author
Tyson Jones
Definition at line 208 of file test_operators.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    // figure out max-num (inclusive) targs allowed by hardware backend
    int maxNumTargs = calcLog2(quregVec.numAmpsPerChunk);
    SECTION( "correctness" ) {
        // generate all possible qubit arrangements
        int numTargs = GENERATE_COPY( range(1,maxNumTargs+1) ); // inclusive upper bound
        int* targs = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numTargs) );
        // for each qubit arrangement, use a new random unitary
        QMatrix op = getRandomQMatrix(1 << numTargs);
        ComplexMatrixN matr = createComplexMatrixN(numTargs);
        toComplexMatrixN(op, matr);
        SECTION( "state-vector" ) {
            applyGateMatrixN(quregVec, targs, numTargs, matr);
            applyReferenceOp(refVec, targs, numTargs, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            applyGateMatrixN(quregMatr, targs, numTargs, matr);
            applyReferenceOp(refMatr, targs, numTargs, op);
            REQUIRE( areEqual(quregMatr, refMatr, 1E4*REAL_EPS) );
        }
        destroyComplexMatrixN(matr);
    }
    SECTION( "input validation" ) {
        SECTION( "number of targets" ) {
            // there cannot be more targets than qubits in register
            int numTargs = GENERATE( -1, 0, NUM_QUBITS+1 );
            int targs[NUM_QUBITS+1]; // prevents seg-fault if validation doesn't trigger
            ComplexMatrixN matr = createComplexMatrixN(NUM_QUBITS+1); // prevent seg-fault
            REQUIRE_THROWS_WITH( applyGateMatrixN(quregVec, targs, numTargs, matr), Contains("Invalid number of target"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "repetition in targets" ) {
            int numTargs = 3;
            int targs[] = {1,2,2};
            ComplexMatrixN matr = createComplexMatrixN(numTargs); // prevents seg-fault if validation doesn't trigger
            REQUIRE_THROWS_WITH( applyGateMatrixN(quregVec, targs, numTargs, matr), Contains("target") && Contains("unique"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "qubit indices" ) {
            int numTargs = 3;
            int targs[] = {1,2,3};
            ComplexMatrixN matr = createComplexMatrixN(numTargs); // prevents seg-fault if validation doesn't trigger
            int inv = GENERATE( -1, NUM_QUBITS );
            targs[GENERATE_COPY( range(0,numTargs) )] = inv; // make invalid target
            REQUIRE_THROWS_WITH( applyGateMatrixN(quregVec, targs, numTargs, matr), Contains("Invalid target") );
            destroyComplexMatrixN(matr);
        }
        SECTION( "matrix creation" ) {
            int numTargs = 3;
            int targs[] = {1,2,3};
            /* compilers don't auto-initialise to NULL; the below circumstance
             * only really occurs when 'malloc' returns NULL in createComplexMatrixN,
             * which actually triggers its own validation. Hence this test is useless
             * currently.
             */
            ComplexMatrixN matr;
            matr.real = NULL;
            matr.imag = NULL;
            REQUIRE_THROWS_WITH( applyGateMatrixN(quregVec, targs, numTargs, matr), Contains("created") );
        }
        SECTION( "matrix dimensions" ) {
            int targs[2] = {1,2};
            ComplexMatrixN matr = createComplexMatrixN(3); // intentionally wrong size
            REQUIRE_THROWS_WITH( applyGateMatrixN(quregVec, targs, 2, matr), Contains("matrix size"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "matrix fits in node" ) {
            // pretend we have a very limited distributed memory (judged by matr size)
            quregVec.numAmpsPerChunk = 1;
            int qb[] = {1,2};
            ComplexMatrixN matr = createComplexMatrixN(2); // prevents seg-fault if validation doesn't trigger
            REQUIRE_THROWS_WITH( applyGateMatrixN(quregVec, qb, 2, matr), Contains("targets too many qubits"));
            destroyComplexMatrixN(matr);
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyGateMatrixN(), applyReferenceOp(), areEqual(), calcLog2(), CLEANUP_TEST, createComplexMatrixN(), destroyComplexMatrixN(), getRandomQMatrix(), ComplexMatrixN::imag, NUM_QUBITS, PREPARE_TEST, ComplexMatrixN::real, sublists(), and toComplexMatrixN().
TEST_CASE() [4/136]
TEST_CASE ("applyGateSubDiagonalOp" , "" [unitaries])
See also
applyGateSubDiagonalOp
Author
Tyson Jones
Definition at line 315 of file test_operators.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    SECTION( "correctness" ) {
        // generate all possible targets
        int numTargs = GENERATE( range(1,NUM_QUBITS+1) );
        int* targs = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numTargs) );
        // initialise a random non-unitary diagonal op
        SubDiagonalOp op = createSubDiagonalOp(numTargs);
        for (long long int i=0; i<op.numElems; i++) {
            op.real[i] = getRandomReal(-10,10);
            op.imag[i] = getRandomReal(-10,10);
        }
        QMatrix opMatr = toQMatrix(op);
        SECTION( "state-vector" ) {
            applyGateSubDiagonalOp(quregVec, targs, numTargs, op);
            applyReferenceOp(refVec, targs, numTargs, opMatr);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            applyGateSubDiagonalOp(quregMatr, targs, numTargs, op);
            applyReferenceOp(refMatr, targs, numTargs, opMatr);
            REQUIRE( areEqual(quregMatr, refMatr, 1E4*REAL_EPS) );
        }
        destroySubDiagonalOp(op);
    }
    SECTION( "input validation" ) {
        SECTION( "diagonal dimension" ) {
            int numTargs = 3;
            SubDiagonalOp op = createSubDiagonalOp(numTargs);
            int badNumTargs = GENERATE_COPY( numTargs-1, numTargs+1 );
            int badTargs[NUM_QUBITS+1];
            REQUIRE_THROWS_WITH( applyGateSubDiagonalOp(quregVec, badTargs, badNumTargs, op), Contains("incompatible dimension") );
            destroySubDiagonalOp(op);
        }
        SECTION( "number of targets" ) {
            // make too many targets (which are otherwise valid)
            SubDiagonalOp badOp = createSubDiagonalOp(NUM_QUBITS + 1);
            int targs[NUM_QUBITS + 1];
            for (int t=0; t<badOp.numQubits; t++)
                targs[t] = t;
            for (int i=0; i<badOp.numElems; i++)
                badOp.real[i] = 1;
            REQUIRE_THROWS_WITH( applyGateSubDiagonalOp(quregVec, targs, badOp.numQubits, badOp), Contains("Invalid number of target qubits") );
            destroySubDiagonalOp(badOp);
        }
        SECTION( "repetition in targets" ) {
            // make a valid unitary diagonal op
            SubDiagonalOp op = createSubDiagonalOp(3);
            for (int i=0; i<op.numElems; i++)
                op.real[i] = 1;
            // make a repetition in the target list
            int targs[] = {2,1,2};
            REQUIRE_THROWS_WITH( applyGateSubDiagonalOp(quregVec, targs, op.numQubits, op), Contains("target qubits must be unique") );
            destroySubDiagonalOp(op);
        }
        SECTION( "qubit indices" ) {
            // make a valid unitary diagonal op
            SubDiagonalOp op = createSubDiagonalOp(3);
            for (int i=0; i<op.numElems; i++)
                op.real[i] = 1;
            int targs[] = {0,1,2};
            // make each target in-turn invalid
            int badIndex = GENERATE( range(0,3) );
            int badValue = GENERATE( -1, NUM_QUBITS );
            targs[badIndex] = badValue;
            REQUIRE_THROWS_WITH( applyGateSubDiagonalOp(quregVec, targs, op.numQubits, op), Contains("Invalid target qubit") );
            destroySubDiagonalOp(op);
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyGateSubDiagonalOp(), applyReferenceOp(), areEqual(), createSubDiagonalOp(), destroySubDiagonalOp(), getRandomReal(), SubDiagonalOp::imag, NUM_QUBITS, SubDiagonalOp::numElems, SubDiagonalOp::numQubits, PREPARE_TEST, SubDiagonalOp::real, sublists(), and toQMatrix().
TEST_CASE() [5/136]
TEST_CASE ("applyMatrix2" , "" [operators])
See also
applyMatrix2
Author
Tyson Jones
Definition at line 414 of file test_operators.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    // every test will use a unique random matrix
    QMatrix op = getRandomQMatrix(2); // 2-by-2
    ComplexMatrix2 matr = toComplexMatrix2(op);
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        // reference boilerplate
        int* ctrls = NULL;
        int numCtrls = 0;
        int targs[] = {target};
        int numTargs = 1;
        SECTION( "state-vector" ) {
            applyMatrix2(quregVec, target, matr);
            applyReferenceMatrix(refVec, ctrls, numCtrls, targs, numTargs, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            applyMatrix2(quregMatr, target, matr);
            applyReferenceMatrix(refMatr, ctrls, numCtrls, targs, numTargs, op);
            REQUIRE( areEqual(quregMatr, refMatr, 10*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qubit indices" ) {
            int target = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( applyMatrix2(quregVec, target, matr), Contains("Invalid target") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyMatrix2(), applyReferenceMatrix(), areEqual(), CLEANUP_TEST, getRandomQMatrix(), NUM_QUBITS, PREPARE_TEST, and toComplexMatrix2().
TEST_CASE() [6/136]
TEST_CASE ("applyMatrix4" , "" [operators])
See also
applyMatrix4
Author
Tyson Jones
Definition at line 464 of file test_operators.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    // in distributed mode, each node must be able to fit all amps modified by matrix
    REQUIRE( quregVec.numAmpsPerChunk >= 4 );
    // every test will use a unique random matrix
    QMatrix op = getRandomQMatrix(4); // 4-by-4
    ComplexMatrix4 matr = toComplexMatrix4(op);
    SECTION( "correctness" ) {
        int targ1 = GENERATE( range(0,NUM_QUBITS) );
        int targ2 = GENERATE_COPY( filter([=](int t){ return t!=targ1; }, range(0,NUM_QUBITS)) );
        // reference boilerplate
        int* ctrls = NULL;
        int numCtrls = 0;
        int targs[] = {targ1, targ2};
        int numTargs = 2;
        SECTION( "state-vector" ) {
            applyMatrix4(quregVec, targ1, targ2, matr);
            applyReferenceMatrix(refVec, ctrls, numCtrls, targs, numTargs, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            applyMatrix4(quregMatr, targ1, targ2, matr);
            applyReferenceMatrix(refMatr, ctrls, numCtrls, targs, numTargs, op);
            REQUIRE( areEqual(quregMatr, refMatr, 10*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qubit indices" ) {
            int targ1 = GENERATE( -1, NUM_QUBITS );
            int targ2 = 0;
            REQUIRE_THROWS_WITH( applyMatrix4(quregVec, targ1, targ2, matr), Contains("Invalid target") );
            REQUIRE_THROWS_WITH( applyMatrix4(quregVec, targ2, targ1, matr), Contains("Invalid target") );
        }
        SECTION( "repetition of targets" ) {
            int qb = 0;
            REQUIRE_THROWS_WITH( applyMatrix4(quregVec, qb, qb, matr), Contains("target") && Contains("unique") );
        }
        SECTION( "matrix fits in node" ) {
            // pretend we have a very limited distributed memory
            quregVec.numAmpsPerChunk = 1;
            REQUIRE_THROWS_WITH( applyMatrix4(quregVec, 0, 1, matr), Contains("targets too many qubits"));
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyMatrix4(), applyReferenceMatrix(), areEqual(), CLEANUP_TEST, getRandomQMatrix(), NUM_QUBITS, PREPARE_TEST, and toComplexMatrix4().
TEST_CASE() [7/136]
TEST_CASE ("applyMatrixN" , "" [operators])
See also
applyMatrixN
Author
Tyson Jones
Definition at line 529 of file test_operators.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    // figure out max-num (inclusive) targs allowed by hardware backend
    int maxNumTargs = calcLog2(quregVec.numAmpsPerChunk);
    SECTION( "correctness" ) {
        // generate all possible qubit arrangements
        int numTargs = GENERATE_COPY( range(1,maxNumTargs+1) ); // inclusive upper bound
        int* targs = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numTargs) );
        // for each qubit arrangement, use a new random matrix
        QMatrix op = getRandomQMatrix(1 << numTargs);
        ComplexMatrixN matr = createComplexMatrixN(numTargs);
        toComplexMatrixN(op, matr);
        // reference boilerplate
        int* ctrls = NULL;
        int numCtrls = 0;
        SECTION( "state-vector" ) {
            applyMatrixN(quregVec, targs, numTargs, matr);
            applyReferenceMatrix(refVec, ctrls, numCtrls, targs, numTargs, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            applyMatrixN(quregMatr, targs, numTargs, matr);
            applyReferenceMatrix(refMatr, ctrls, numCtrls, targs, numTargs, op);
            REQUIRE( areEqual(quregMatr, refMatr, 100*REAL_EPS) );
        }
        destroyComplexMatrixN(matr);
    }
    SECTION( "input validation" ) {
        SECTION( "number of targets" ) {
            // there cannot be more targets than qubits in register
            int numTargs = GENERATE( -1, 0, NUM_QUBITS+1 );
            int targs[NUM_QUBITS+1]; // prevents seg-fault if validation doesn't trigger
            ComplexMatrixN matr = createComplexMatrixN(NUM_QUBITS+1); // prevent seg-fault
            REQUIRE_THROWS_WITH( applyMatrixN(quregVec, targs, numTargs, matr), Contains("Invalid number of target"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "repetition in targets" ) {
            int numTargs = 3;
            int targs[] = {1,2,2};
            ComplexMatrixN matr = createComplexMatrixN(numTargs); // prevents seg-fault if validation doesn't trigger
            REQUIRE_THROWS_WITH( applyMatrixN(quregVec, targs, numTargs, matr), Contains("target") && Contains("unique"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "qubit indices" ) {
            int numTargs = 3;
            int targs[] = {1,2,3};
            ComplexMatrixN matr = createComplexMatrixN(numTargs); // prevents seg-fault if validation doesn't trigger
            int inv = GENERATE( -1, NUM_QUBITS );
            targs[GENERATE_COPY( range(0,numTargs) )] = inv; // make invalid target
            REQUIRE_THROWS_WITH( applyMatrixN(quregVec, targs, numTargs, matr), Contains("Invalid target") );
            destroyComplexMatrixN(matr);
        }
        SECTION( "matrix creation" ) {
            int numTargs = 3;
            int targs[] = {1,2,3};
            /* compilers don't auto-initialise to NULL; the below circumstance
             * only really occurs when 'malloc' returns NULL in createComplexMatrixN,
             * which actually triggers its own validation. Hence this test is useless
             * currently.
             */
            ComplexMatrixN matr;
            matr.real = NULL;
            matr.imag = NULL;
            REQUIRE_THROWS_WITH( applyMatrixN(quregVec, targs, numTargs, matr), Contains("created") );
        }
        SECTION( "matrix dimensions" ) {
            int targs[2] = {1,2};
            ComplexMatrixN matr = createComplexMatrixN(3); // intentionally wrong size
            REQUIRE_THROWS_WITH( applyMatrixN(quregVec, targs, 2, matr), Contains("matrix size"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "matrix fits in node" ) {
            // pretend we have a very limited distributed memory (judged by matr size)
            quregVec.numAmpsPerChunk = 1;
            int qb[] = {1,2};
            ComplexMatrixN matr = createComplexMatrixN(2); // prevents seg-fault if validation doesn't trigger
            REQUIRE_THROWS_WITH( applyMatrixN(quregVec, qb, 2, matr), Contains("targets too many qubits"));
            destroyComplexMatrixN(matr);
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyMatrixN(), applyReferenceMatrix(), areEqual(), calcLog2(), CLEANUP_TEST, createComplexMatrixN(), destroyComplexMatrixN(), getRandomQMatrix(), ComplexMatrixN::imag, NUM_QUBITS, PREPARE_TEST, ComplexMatrixN::real, sublists(), and toComplexMatrixN().
TEST_CASE() [8/136]
TEST_CASE ("applyMultiControlledGateMatrixN" , "" [operators])
See also
applyMultiControlledGateMatrixN
Author
Tyson Jones
Definition at line 640 of file test_operators.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    // figure out max-num targs (inclusive) allowed by hardware backend
    int maxNumTargs = calcLog2(quregVec.numAmpsPerChunk);
    if (maxNumTargs >= NUM_QUBITS)
        maxNumTargs = NUM_QUBITS - 1; // leave room for min-number of control qubits
    SECTION( "correctness" ) {
        // try all possible numbers of targets and controls
        int numTargs = GENERATE_COPY( range(1,maxNumTargs+1) );
        int maxNumCtrls = NUM_QUBITS - numTargs;
        int numCtrls = GENERATE_COPY( range(1,maxNumCtrls+1) );
        // generate all possible valid qubit arrangements
        int* targs = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numTargs) );
        int* ctrls = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numCtrls, targs, numTargs) );
        // for each qubit arrangement, use a new random unitary
        QMatrix op = getRandomQMatrix(1 << numTargs);
        ComplexMatrixN matr = createComplexMatrixN(numTargs);
        toComplexMatrixN(op, matr);
        SECTION( "state-vector" ) {
            applyMultiControlledGateMatrixN(quregVec, ctrls, numCtrls, targs, numTargs, matr);
            applyReferenceOp(refVec, ctrls, numCtrls, targs, numTargs, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            applyMultiControlledGateMatrixN(quregMatr, ctrls, numCtrls, targs, numTargs, matr);
            applyReferenceOp(refMatr, ctrls, numCtrls, targs, numTargs, op);
            REQUIRE( areEqual(quregMatr, refMatr, 1E4*REAL_EPS) );
        }
        destroyComplexMatrixN(matr);
    }
    SECTION( "input validation" ) {
        SECTION( "number of targets" ) {
            // there cannot be more targets than qubits in register
            // (numTargs=NUM_QUBITS is caught elsewhere, because that implies ctrls are invalid)
            int numTargs = GENERATE( -1, 0, NUM_QUBITS+1 );
            int targs[NUM_QUBITS+1]; // prevents seg-fault if validation doesn't trigger
            int ctrls[] = {0};
            ComplexMatrixN matr = createComplexMatrixN(NUM_QUBITS+1); // prevent seg-fault
            toComplexMatrixN(getRandomUnitary(NUM_QUBITS+1), matr); // ensure unitary
            REQUIRE_THROWS_WITH( applyMultiControlledGateMatrixN(quregVec, ctrls, 1, targs, numTargs, matr), Contains("Invalid number of target"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "repetition in targets" ) {
            int ctrls[] = {0};
            int numTargs = 3;
            int targs[] = {1,2,2};
            ComplexMatrixN matr = createComplexMatrixN(numTargs); // prevents seg-fault if validation doesn't trigger
            toComplexMatrixN(getRandomUnitary(numTargs), matr); // ensure unitary
            REQUIRE_THROWS_WITH( applyMultiControlledGateMatrixN(quregVec, ctrls, 1, targs, numTargs, matr), Contains("target") && Contains("unique"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "number of controls" ) {
            int numCtrls = GENERATE( -1, 0, NUM_QUBITS, NUM_QUBITS+1 );
            int ctrls[NUM_QUBITS+1]; // avoids seg-fault if validation not triggered
            int targs[1] = {0};
            ComplexMatrixN matr = createComplexMatrixN(1);
            toComplexMatrixN(getRandomUnitary(1), matr); // ensure unitary
            REQUIRE_THROWS_WITH( applyMultiControlledGateMatrixN(quregVec, ctrls, numCtrls, targs, 1, matr), Contains("Invalid number of control"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "repetition in controls" ) {
            int ctrls[] = {0,1,1};
            int targs[] = {3};
            ComplexMatrixN matr = createComplexMatrixN(1);
            toComplexMatrixN(getRandomUnitary(1), matr); // ensure unitary
            REQUIRE_THROWS_WITH( applyMultiControlledGateMatrixN(quregVec, ctrls, 3, targs, 1, matr), Contains("control") && Contains("unique"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "control and target collision" ) {
            int ctrls[] = {0,1,2};
            int targs[] = {3,1,4};
            ComplexMatrixN matr = createComplexMatrixN(3);
            toComplexMatrixN(getRandomUnitary(3), matr); // ensure unitary
            REQUIRE_THROWS_WITH( applyMultiControlledGateMatrixN(quregVec, ctrls, 3, targs, 3, matr), Contains("Control") && Contains("target") && Contains("disjoint"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "qubit indices" ) {
            // valid inds
            int numQb = 2;
            int qb1[2] = {0,1};
            int qb2[2] = {2,3};
            ComplexMatrixN matr = createComplexMatrixN(numQb);
            toComplexMatrixN(getRandomUnitary(numQb), matr); // ensure unitary
            // make qb1 invalid
            int inv = GENERATE( -1, NUM_QUBITS );
            qb1[GENERATE_COPY(range(0,numQb))] = inv;
            REQUIRE_THROWS_WITH( applyMultiControlledGateMatrixN(quregVec, qb1, numQb, qb2, numQb, matr), Contains("Invalid control") );
            REQUIRE_THROWS_WITH( applyMultiControlledGateMatrixN(quregVec, qb2, numQb, qb1, numQb, matr), Contains("Invalid target") );
            destroyComplexMatrixN(matr);
        }
        SECTION( "matrix creation" ) {
            int ctrls[1] = {0};
            int targs[3] = {1,2,3};
            /* compilers don't auto-initialise to NULL; the below circumstance
             * only really occurs when 'malloc' returns NULL in createComplexMatrixN,
             * which actually triggers its own validation. Hence this test is useless
             * currently.
             */
            ComplexMatrixN matr;
            matr.real = NULL;
            matr.imag = NULL;
            REQUIRE_THROWS_WITH( applyMultiControlledGateMatrixN(quregVec, ctrls, 1, targs, 3, matr), Contains("created") );
        }
        SECTION( "matrix dimensions" ) {
            int ctrls[1] = {0};
            int targs[2] = {1,2};
            ComplexMatrixN matr = createComplexMatrixN(3); // intentionally wrong size
            toComplexMatrixN(getRandomUnitary(3), matr); // ensure unitary
            REQUIRE_THROWS_WITH( applyMultiControlledGateMatrixN(quregVec, ctrls, 1, targs, 2, matr), Contains("matrix size"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "matrix fits in node" ) {
            // pretend we have a very limited distributed memory (judged by matr size)
            quregVec.numAmpsPerChunk = 1;
            int ctrls[1] = {0};
            int targs[2] = {1,2};
            ComplexMatrixN matr = createComplexMatrixN(2);
            toComplexMatrixN(getRandomUnitary(2), matr); // ensure unitary
            REQUIRE_THROWS_WITH( applyMultiControlledGateMatrixN(quregVec, ctrls, 1, targs, 2, matr), Contains("targets too many qubits"));
            destroyComplexMatrixN(matr);
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyMultiControlledGateMatrixN(), applyReferenceOp(), areEqual(), calcLog2(), CLEANUP_TEST, createComplexMatrixN(), destroyComplexMatrixN(), getRandomQMatrix(), getRandomUnitary(), ComplexMatrixN::imag, NUM_QUBITS, PREPARE_TEST, ComplexMatrixN::real, sublists(), and toComplexMatrixN().
TEST_CASE() [9/136]
TEST_CASE ("applyMultiControlledMatrixN" , "" [operators])
See also
applyMultiControlledMatrixN
Author
Tyson Jones
Definition at line 800 of file test_operators.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    // figure out max-num targs (inclusive) allowed by hardware backend
    int maxNumTargs = calcLog2(quregVec.numAmpsPerChunk);
    if (maxNumTargs >= NUM_QUBITS)
        maxNumTargs = NUM_QUBITS - 1; // leave room for min-number of control qubits
    SECTION( "correctness" ) {
        // try all possible numbers of targets and controls
        int numTargs = GENERATE_COPY( range(1,maxNumTargs+1) );
        int maxNumCtrls = NUM_QUBITS - numTargs;
        int numCtrls = GENERATE_COPY( range(1,maxNumCtrls+1) );
        // generate all possible valid qubit arrangements
        int* targs = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numTargs) );
        int* ctrls = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numCtrls, targs, numTargs) );
        // for each qubit arrangement, use a new random unitary
        QMatrix op = getRandomQMatrix(1 << numTargs);
        ComplexMatrixN matr = createComplexMatrixN(numTargs);
        toComplexMatrixN(op, matr);
        SECTION( "state-vector" ) {
            applyMultiControlledMatrixN(quregVec, ctrls, numCtrls, targs, numTargs, matr);
            applyReferenceMatrix(refVec, ctrls, numCtrls, targs, numTargs, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            applyMultiControlledMatrixN(quregMatr, ctrls, numCtrls, targs, numTargs, matr);
            applyReferenceMatrix(refMatr, ctrls, numCtrls, targs, numTargs, op);
            REQUIRE( areEqual(quregMatr, refMatr, 100*REAL_EPS) );
        }
        destroyComplexMatrixN(matr);
    }
    SECTION( "input validation" ) {
        SECTION( "number of targets" ) {
            // there cannot be more targets than qubits in register
            // (numTargs=NUM_QUBITS is caught elsewhere, because that implies ctrls are invalid)
            int numTargs = GENERATE( -1, 0, NUM_QUBITS+1 );
            int targs[NUM_QUBITS+1]; // prevents seg-fault if validation doesn't trigger
            int ctrls[] = {0};
            ComplexMatrixN matr = createComplexMatrixN(NUM_QUBITS+1); // prevent seg-fault
            toComplexMatrixN(getRandomQMatrix( 1 << (NUM_QUBITS+1)), matr);
            REQUIRE_THROWS_WITH( applyMultiControlledMatrixN(quregVec, ctrls, 1, targs, numTargs, matr), Contains("Invalid number of target"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "repetition in targets" ) {
            int ctrls[] = {0};
            int numTargs = 3;
            int targs[] = {1,2,2};
            ComplexMatrixN matr = createComplexMatrixN(numTargs); // prevents seg-fault if validation doesn't trigger
            toComplexMatrixN(getRandomQMatrix(1 << numTargs), matr);
            REQUIRE_THROWS_WITH( applyMultiControlledMatrixN(quregVec, ctrls, 1, targs, numTargs, matr), Contains("target") && Contains("unique"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "number of controls" ) {
            int numCtrls = GENERATE( -1, 0, NUM_QUBITS, NUM_QUBITS+1 );
            int ctrls[NUM_QUBITS+1]; // avoids seg-fault if validation not triggered
            int targs[1] = {0};
            ComplexMatrixN matr = createComplexMatrixN(1);
            toComplexMatrixN(getRandomQMatrix(1 << 1), matr);
            REQUIRE_THROWS_WITH( applyMultiControlledMatrixN(quregVec, ctrls, numCtrls, targs, 1, matr), Contains("Invalid number of control"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "repetition in controls" ) {
            int ctrls[] = {0,1,1};
            int targs[] = {3};
            ComplexMatrixN matr = createComplexMatrixN(1);
            toComplexMatrixN(getRandomQMatrix(1 << 1), matr);
            REQUIRE_THROWS_WITH( applyMultiControlledMatrixN(quregVec, ctrls, 3, targs, 1, matr), Contains("control") && Contains("unique"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "control and target collision" ) {
            int ctrls[] = {0,1,2};
            int targs[] = {3,1,4};
            ComplexMatrixN matr = createComplexMatrixN(3);
            toComplexMatrixN(getRandomQMatrix(1 << 3), matr);
            REQUIRE_THROWS_WITH( applyMultiControlledMatrixN(quregVec, ctrls, 3, targs, 3, matr), Contains("Control") && Contains("target") && Contains("disjoint"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "qubit indices" ) {
            // valid inds
            int numQb = 2;
            int qb1[2] = {0,1};
            int qb2[2] = {2,3};
            ComplexMatrixN matr = createComplexMatrixN(numQb);
            toComplexMatrixN(getRandomQMatrix(1 << numQb), matr);
            // make qb1 invalid
            int inv = GENERATE( -1, NUM_QUBITS );
            qb1[GENERATE_COPY(range(0,numQb))] = inv;
            REQUIRE_THROWS_WITH( applyMultiControlledMatrixN(quregVec, qb1, numQb, qb2, numQb, matr), Contains("Invalid control") );
            REQUIRE_THROWS_WITH( applyMultiControlledMatrixN(quregVec, qb2, numQb, qb1, numQb, matr), Contains("Invalid target") );
            destroyComplexMatrixN(matr);
        }
        SECTION( "matrix creation" ) {
            int ctrls[1] = {0};
            int targs[3] = {1,2,3};
            /* compilers don't auto-initialise to NULL; the below circumstance
             * only really occurs when 'malloc' returns NULL in createComplexMatrixN,
             * which actually triggers its own validation. Hence this test is useless
             * currently.
             */
            ComplexMatrixN matr;
            matr.real = NULL;
            matr.imag = NULL;
            REQUIRE_THROWS_WITH( applyMultiControlledMatrixN(quregVec, ctrls, 1, targs, 3, matr), Contains("created") );
        }
        SECTION( "matrix dimensions" ) {
            int ctrls[1] = {0};
            int targs[2] = {1,2};
            ComplexMatrixN matr = createComplexMatrixN(3); // intentionally wrong size
            toComplexMatrixN(getRandomQMatrix(1 << 3), matr);
            REQUIRE_THROWS_WITH( applyMultiControlledMatrixN(quregVec, ctrls, 1, targs, 2, matr), Contains("matrix size"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "matrix fits in node" ) {
            // pretend we have a very limited distributed memory (judged by matr size)
            quregVec.numAmpsPerChunk = 1;
            int ctrls[1] = {0};
            int targs[2] = {1,2};
            ComplexMatrixN matr = createComplexMatrixN(2);
            toComplexMatrixN(getRandomQMatrix(1 << 2), matr);
            REQUIRE_THROWS_WITH( applyMultiControlledMatrixN(quregVec, ctrls, 1, targs, 2, matr), Contains("targets too many qubits"));
            destroyComplexMatrixN(matr);
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyMultiControlledMatrixN(), applyReferenceMatrix(), areEqual(), calcLog2(), CLEANUP_TEST, createComplexMatrixN(), destroyComplexMatrixN(), getRandomQMatrix(), ComplexMatrixN::imag, NUM_QUBITS, PREPARE_TEST, ComplexMatrixN::real, sublists(), and toComplexMatrixN().
TEST_CASE() [10/136]
TEST_CASE ("applyMultiVarPhaseFunc" , "" [operators])
See also
applyMultiVarPhaseFunc
Author
Tyson Jones
Definition at line 960 of file test_operators.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    SECTION( "correctness" ) {
        // try every kind of binary encodings
        enum bitEncoding encoding = GENERATE( UNSIGNED,TWOS_COMPLEMENT );
        // try every possible number of registers
        // (between #qubits containing 1, and 1 containing #qubits)
        int numRegs;
        int maxNumRegs = 0;
        if (encoding == UNSIGNED)
            maxNumRegs = NUM_QUBITS;
        if (encoding == TWOS_COMPLEMENT)
            maxNumRegs = NUM_QUBITS/2;  // floors
        numRegs = GENERATE_COPY( range(1, maxNumRegs+1) );
        // try every possible total number of involed qubits
        int totalNumQubits;
        int minTotalQubits = 0;
        if (encoding == UNSIGNED)
            // each register must contain at least 1 qubit
            minTotalQubits = numRegs;
        if (encoding == TWOS_COMPLEMENT)
            // each register must contain at least 2 qubits
            minTotalQubits = 2*numRegs;
        totalNumQubits = GENERATE_COPY( range(minTotalQubits,NUM_QUBITS+1) );
        // try every qubits subset and ordering
        int* regs = GENERATE_COPY( sublists(range(0,NUM_QUBITS), totalNumQubits) );
        // assign each sub-reg its minimum length
        int unallocQubits = totalNumQubits;
        VLA(int, numQubitsPerReg, numRegs);
        for (int i=0; i<numRegs; i++)
            if (encoding == UNSIGNED) {
                numQubitsPerReg[i] = 1;
                unallocQubits -= 1;
            }
            else if (encoding == TWOS_COMPLEMENT) {
                numQubitsPerReg[i] = 2;
                unallocQubits -= 2;
            }
        // and randomly allocate the remaining qubits between the registers
        while (unallocQubits > 0) {
            numQubitsPerReg[getRandomInt(0,numRegs)] += 1;
            unallocQubits--;
        }
        // each register gets a random number of terms in the full phase function
        VLA(int, numTermsPerReg, numRegs);
        int numTermsTotal = 0;
        for (int r=0; r<numRegs; r++) {
            int numTerms = getRandomInt(1,5);
            numTermsPerReg[r] = numTerms;
            numTermsTotal += numTerms;
        }
        // populate the multi-var phase function with random but POSITIVE-power terms,
        // which must further be integers in two's complement
        int flatInd = 0;
        VLA(qreal, coeffs, numTermsTotal);
        VLA(qreal, expons, numTermsTotal);
        for (int r=0; r<numRegs; r++) {
            for (int t=0; t<numTermsPerReg[r]; t++) {
                coeffs[flatInd] = getRandomReal(-10,10);
                if (encoding == TWOS_COMPLEMENT)
                    expons[flatInd] = getRandomInt(0, 3+1);
                else if (encoding == UNSIGNED)
                    expons[flatInd] = getRandomReal(0, 3);
                flatInd++;
            }
        }
        /* To perform this calculation more distinctly from the QuEST
         * core method, we can exploit that
         * exp(i (f1[x1] + f2[x2]))|x2>|x1> = exp(i f2[x2])|x2> (x) exp(i f1[x1])|x1>
         * and so compute a separate diagonal matrix for each sub-register with
         * phases determined only by its own variable, and Kronecker multiply
         * them together. The target qubits of the Kronecker product is then
         * just the full register, stored in *regs.
         */
        QMatrix allRegMatr{{1}};
        int startInd = 0;
        for (int r=0; r<numRegs; r++) {
            QMatrix singleRegMatr = getZeroMatrix( 1 << numQubitsPerReg[r] );
            for (size_t i=0; i<singleRegMatr.size(); i++) {
                long long int ind = 0;
                if (encoding == UNSIGNED)
                    ind = i;
                if (encoding == TWOS_COMPLEMENT)
                    ind = getTwosComplement(i, numQubitsPerReg[r]);
                qreal phase = 0;
                for (int t=0; t<numTermsPerReg[r]; t++)
                    phase += coeffs[t+startInd] * pow(ind, expons[t+startInd]);
                singleRegMatr[i][i] = expI(phase);
            }
            allRegMatr = getKroneckerProduct(singleRegMatr, allRegMatr);
            startInd += numTermsPerReg[r];
        }
        SECTION( "state-vector" ) {
            applyMultiVarPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, encoding, coeffs, expons, numTermsPerReg);
            applyReferenceOp(refVec, regs, totalNumQubits, allRegMatr);
            REQUIRE( areEqual(quregVec, refVec, 1E4*REAL_EPS) );
        }
        SECTION( "density-matrix" ) {
            applyMultiVarPhaseFunc(quregMatr, regs, numQubitsPerReg, numRegs, encoding, coeffs, expons, numTermsPerReg);
            applyReferenceOp(refMatr, regs, totalNumQubits, allRegMatr);
            REQUIRE( areEqual(quregMatr, refMatr, 1E6*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        int numRegs = 2;
        int numQubitsPerReg[] = {2,3};
        int qubits[] = {0,1,2,3,4};
        SECTION( "number of registers" ) {
            numRegs = GENERATE_COPY( -1, 0, 1+MAX_NUM_REGS_APPLY_ARBITRARY_PHASE );
            REQUIRE_THROWS_WITH( applyMultiVarPhaseFunc(quregVec, qubits, numQubitsPerReg, numRegs, UNSIGNED, NULL, NULL, NULL), Contains("Invalid number of qubit subregisters") );
        }
        SECTION( "number of qubits" ) {
            numQubitsPerReg[GENERATE_COPY(range(0,numRegs))] = GENERATE( -1, 0, 1+NUM_QUBITS );
            REQUIRE_THROWS_WITH( applyMultiVarPhaseFunc(quregVec, qubits, numQubitsPerReg, numRegs, UNSIGNED, NULL, NULL, NULL), Contains("Invalid number of qubits") );
        }
        SECTION( "repetition of qubits" ) {
            qubits[GENERATE(2,3,4)] = qubits[1];
            REQUIRE_THROWS_WITH( applyMultiVarPhaseFunc(quregVec, qubits, numQubitsPerReg, numRegs, UNSIGNED, NULL, NULL, NULL), Contains("The qubits must be unique") );
        }
        SECTION( "qubit indices" ) {
            qubits[GENERATE(range(0,NUM_QUBITS))] = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( applyMultiVarPhaseFunc(quregVec, qubits, numQubitsPerReg, numRegs, UNSIGNED, NULL, NULL, NULL), Contains("Invalid qubit index") );
        }
        SECTION( "number of terms" ) {
            int numTermsPerReg[] = {3, 3};
            numTermsPerReg[GENERATE_COPY(range(0,numRegs))] = GENERATE( -1, 0 );
            REQUIRE_THROWS_WITH( applyMultiVarPhaseFunc(quregVec, qubits, numQubitsPerReg, numRegs, UNSIGNED, NULL, NULL, numTermsPerReg), Contains("Invalid number of terms in the phase function") );
        }
        SECTION( "bit encoding name" ) {
            enum bitEncoding enc = (enum bitEncoding) GENERATE( -1, 2 );
            REQUIRE_THROWS_WITH( applyMultiVarPhaseFunc(quregVec, qubits, numQubitsPerReg, numRegs, enc, NULL, NULL, NULL), Contains("Invalid bit encoding") );
        }
        SECTION( "two's complement register" ) {
            numQubitsPerReg[GENERATE_COPY(range(0,numRegs))] = 1;
            REQUIRE_THROWS_WITH( applyMultiVarPhaseFunc(quregVec, qubits, numQubitsPerReg, numRegs, TWOS_COMPLEMENT, NULL, NULL, NULL), Contains("A sub-register contained too few qubits to employ TWOS_COMPLEMENT encoding") );
        }
        SECTION( "fractional exponent" ) {
            int numTermsPerReg[] = {3, 3};
            qreal coeffs[] = {0,0,0,  0,0,0};
            qreal expos[] =  {1,2,3,  1,2,3};
            expos[GENERATE(range(0,6))] = GENERATE( 0.5, 1.999, 5.0001 );
            REQUIRE_THROWS_WITH( applyMultiVarPhaseFunc(quregVec, qubits, numQubitsPerReg, numRegs, TWOS_COMPLEMENT, coeffs, expos, numTermsPerReg), Contains("The phase function contained a fractional exponent, which is illegal in TWOS_COMPLEMENT") );
            // ensure fractional exponents are valid in unsigned mode however
            REQUIRE_NOTHROW( applyMultiVarPhaseFunc(quregVec, qubits, numQubitsPerReg, numRegs, UNSIGNED, coeffs, expos, numTermsPerReg) );
        }
        SECTION( "negative exponent" ) {
            int numTermsPerReg[] = {3, 3};
            qreal coeffs[] = {0,0,0,  0,0,0};
            qreal expos[] =  {1,2,3,  1,2,3};
            expos[GENERATE(range(0,6))] = GENERATE( -1, -2, -2.5 );
            enum bitEncoding enc = GENERATE( UNSIGNED, TWOS_COMPLEMENT );
            REQUIRE_THROWS_WITH( applyMultiVarPhaseFunc(quregVec, qubits, numQubitsPerReg, numRegs, enc, coeffs, expos, numTermsPerReg), Contains("The phase function contained an illegal negative exponent") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyMultiVarPhaseFunc(), applyReferenceOp(), areEqual(), CLEANUP_TEST, expI(), getKroneckerProduct(), getRandomInt(), getRandomReal(), getTwosComplement(), getZeroMatrix(), MAX_NUM_REGS_APPLY_ARBITRARY_PHASE, NUM_QUBITS, PREPARE_TEST, qreal, sublists(), TWOS_COMPLEMENT, UNSIGNED, and VLA.
TEST_CASE() [11/136]
TEST_CASE ("applyMultiVarPhaseFuncOverrides" , "" [operators])
See also
applyMultiVarPhaseFuncOverrides
Author
Tyson Jones
Definition at line 1161 of file test_operators.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    SECTION( "correctness" ) {
        // try every kind of binary encodings
        enum bitEncoding encoding = GENERATE( UNSIGNED,TWOS_COMPLEMENT );
        // try every possible number of registers
        // (between #qubits containing 1, and 1 containing #qubits)
        int numRegs;
        int maxNumRegs = 0;
        if (encoding == UNSIGNED)
            maxNumRegs = NUM_QUBITS;
        if (encoding == TWOS_COMPLEMENT)
            maxNumRegs = NUM_QUBITS/2;  // floors
        numRegs = GENERATE_COPY( range(1, maxNumRegs+1) );
        // try every possible total number of involed qubits
        int totalNumQubits;
        int minTotalQubits = 0;
        if (encoding == UNSIGNED)
            // each register must contain at least 1 qubit
            minTotalQubits = numRegs;
        if (encoding == TWOS_COMPLEMENT)
            // each register must contain at least 2 qubits
            minTotalQubits = 2*numRegs;
        totalNumQubits = GENERATE_COPY( range(minTotalQubits,NUM_QUBITS+1) );
        // try every qubits subset and ordering
        int* regs = GENERATE_COPY( sublists(range(0,NUM_QUBITS), totalNumQubits) );
        // assign each sub-reg its minimum length
        int unallocQubits = totalNumQubits;
        VLA(int, numQubitsPerReg, numRegs);
        for (int i=0; i<numRegs; i++)
            if (encoding == UNSIGNED) {
                numQubitsPerReg[i] = 1;
                unallocQubits -= 1;
            }
            else if (encoding == TWOS_COMPLEMENT) {
                numQubitsPerReg[i] = 2;
                unallocQubits -= 2;
            }
        // and randomly allocate the remaining qubits between the registers
        while (unallocQubits > 0) {
            numQubitsPerReg[getRandomInt(0,numRegs)] += 1;
            unallocQubits--;
        }
        // each register gets a random number of terms in the full phase function
        VLA(int, numTermsPerReg, numRegs);
        int numTermsTotal = 0;
        for (int r=0; r<numRegs; r++) {
            int numTerms = getRandomInt(1,5);
            numTermsPerReg[r] = numTerms;
            numTermsTotal += numTerms;
        }
        // populate the multi-var phase function with random but POSITIVE-power terms,
        // which must further be integers in two's complement
        int flatInd = 0;
        VLA(qreal, coeffs, numTermsTotal);
        VLA(qreal, expons, numTermsTotal);
        for (int r=0; r<numRegs; r++) {
            for (int t=0; t<numTermsPerReg[r]; t++) {
                coeffs[flatInd] = getRandomReal(-10,10);
                if (encoding == TWOS_COMPLEMENT)
                    expons[flatInd] = getRandomInt(0, 3+1);
                else if (encoding == UNSIGNED)
                    expons[flatInd] = getRandomReal(0, 3);
                flatInd++;
            }
        }
        // choose a random number of overrides (even overriding every amplitude)
        int numOverrides = getRandomInt(0, (1<<totalNumQubits) + 1);
        // randomise each override index (uniqueness isn't checked)
        VLA(long long int, overrideInds, numOverrides*numRegs);
        flatInd = 0;
        for (int v=0; v<numOverrides; v++) {
            for (int r=0; r<numRegs; r++) {
                if (encoding == UNSIGNED)
                    overrideInds[flatInd] = getRandomInt(0, 1<<numQubitsPerReg[r]);
                else if (encoding == TWOS_COMPLEMENT)
                    overrideInds[flatInd] = getRandomInt(-(1<<(numQubitsPerReg[r]-1)), (1<<(numQubitsPerReg[r]-1))-1);
                flatInd++;
            }
        }
        // override to a random phase
        VLA(qreal, overridePhases, numOverrides);
        for (int v=0; v<numOverrides; v++)
            overridePhases[v] = getRandomReal(-4, 4); // periodic in [-pi, pi]
        /* To perform this calculation more distinctly from the QuEST
         * core method, we can exploit that
         * exp(i (f1[x1] + f2[x2]))|x2>|x1> = exp(i f2[x2])|x2> (x) exp(i f1[x1])|x1>
         * and so compute a separate diagonal matrix for each sub-register with
         * phases determined only by its own variable, and Kronecker multiply
         * them together. The target qubits of the Kronecker product is then
         * just the full register, stored in *regs. We do this, then iterate
         * the list of overrides directly to overwrite the ultimate diagonal
         * entries
         */
        QMatrix allRegMatr{{1}};
        int startInd = 0;
        for (int r=0; r<numRegs; r++) {
            QMatrix singleRegMatr = getZeroMatrix( 1 << numQubitsPerReg[r] );
            for (size_t i=0; i<singleRegMatr.size(); i++) {
                long long int ind = 0;
                if (encoding == UNSIGNED)
                    ind = i;
                if (encoding == TWOS_COMPLEMENT)
                    ind = getTwosComplement(i, numQubitsPerReg[r]);
                qreal phase = 0;
                for (int t=0; t<numTermsPerReg[r]; t++)
                    phase += coeffs[t+startInd] * pow(ind, expons[t+startInd]);
                singleRegMatr[i][i] = expI(phase);
            }
            allRegMatr = getKroneckerProduct(singleRegMatr, allRegMatr);
            startInd += numTermsPerReg[r];
        }
        setDiagMatrixOverrides(allRegMatr, numQubitsPerReg, numRegs, encoding, overrideInds, overridePhases, numOverrides);
        SECTION( "state-vector" ) {
            applyMultiVarPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, encoding, coeffs, expons, numTermsPerReg, overrideInds, overridePhases, numOverrides);
            applyReferenceOp(refVec, regs, totalNumQubits, allRegMatr);
            REQUIRE( areEqual(quregVec, refVec, 1E4*REAL_EPS) );
        }
        SECTION( "density-matrix" ) {
            applyMultiVarPhaseFuncOverrides(quregMatr, regs, numQubitsPerReg, numRegs, encoding, coeffs, expons, numTermsPerReg, overrideInds, overridePhases, numOverrides);
            applyReferenceOp(refMatr, regs, totalNumQubits, allRegMatr);
            REQUIRE( areEqual(quregMatr, refMatr, 1E6*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        int numRegs = 2;
        int numQubitsPerReg[] = {2,3};
        int qubits[] = {0,1,2,3,4};
        SECTION( "number of registers" ) {
            numRegs = GENERATE_COPY( -1, 0, 1+MAX_NUM_REGS_APPLY_ARBITRARY_PHASE );
            REQUIRE_THROWS_WITH( applyMultiVarPhaseFuncOverrides(quregVec, qubits, numQubitsPerReg, numRegs, UNSIGNED, NULL, NULL, NULL, NULL, NULL, 0), Contains("Invalid number of qubit subregisters") );
        }
        SECTION( "number of qubits" ) {
            numQubitsPerReg[GENERATE_COPY(range(0,numRegs))] = GENERATE( -1, 0, 1+NUM_QUBITS );
            REQUIRE_THROWS_WITH( applyMultiVarPhaseFuncOverrides(quregVec, qubits, numQubitsPerReg, numRegs, UNSIGNED, NULL, NULL, NULL, NULL, NULL, 0), Contains("Invalid number of qubits") );
        }
        SECTION( "repetition of qubits" ) {
            qubits[GENERATE(2,3,4)] = qubits[1];
            REQUIRE_THROWS_WITH( applyMultiVarPhaseFuncOverrides(quregVec, qubits, numQubitsPerReg, numRegs, UNSIGNED, NULL, NULL, NULL, NULL, NULL, 0), Contains("The qubits must be unique") );
        }
        SECTION( "qubit indices" ) {
            qubits[GENERATE(range(0,NUM_QUBITS))] = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( applyMultiVarPhaseFuncOverrides(quregVec, qubits, numQubitsPerReg, numRegs, UNSIGNED, NULL, NULL, NULL, NULL, NULL, 0), Contains("Invalid qubit index") );
        }
        SECTION( "number of terms" ) {
            int numTermsPerReg[] = {3, 3};
            numTermsPerReg[GENERATE_COPY(range(0,numRegs))] = GENERATE( -1, 0 );
            REQUIRE_THROWS_WITH( applyMultiVarPhaseFuncOverrides(quregVec, qubits, numQubitsPerReg, numRegs, UNSIGNED, NULL, NULL, numTermsPerReg, NULL, NULL, 0), Contains("Invalid number of terms in the phase function") );
        }
        SECTION( "bit encoding name" ) {
            enum bitEncoding enc = (enum bitEncoding) GENERATE( -1, 2 );
            REQUIRE_THROWS_WITH( applyMultiVarPhaseFuncOverrides(quregVec, qubits, numQubitsPerReg, numRegs, enc, NULL, NULL, NULL, NULL, NULL, 0), Contains("Invalid bit encoding") );
        }
        SECTION( "two's complement register" ) {
            numQubitsPerReg[GENERATE_COPY(range(0,numRegs))] = 1;
            REQUIRE_THROWS_WITH( applyMultiVarPhaseFuncOverrides(quregVec, qubits, numQubitsPerReg, numRegs, TWOS_COMPLEMENT, NULL, NULL, NULL, NULL, NULL, 0), Contains("A sub-register contained too few qubits to employ TWOS_COMPLEMENT encoding") );
        }
        SECTION( "fractional exponent" ) {
            int numTermsPerReg[] = {3, 3};
            qreal coeffs[] = {0,0,0,  0,0,0};
            qreal expos[] =  {1,2,3,  1,2,3};
            expos[GENERATE(range(0,6))] = GENERATE( 0.5, 1.999, 5.0001 );
            REQUIRE_THROWS_WITH( applyMultiVarPhaseFuncOverrides(quregVec, qubits, numQubitsPerReg, numRegs, TWOS_COMPLEMENT, coeffs, expos, numTermsPerReg, NULL, NULL, 0), Contains("The phase function contained a fractional exponent, which is illegal in TWOS_COMPLEMENT") );
            // ensure fractional exponents are valid in unsigned mode however
            REQUIRE_NOTHROW( applyMultiVarPhaseFuncOverrides(quregVec, qubits, numQubitsPerReg, numRegs, UNSIGNED, coeffs, expos, numTermsPerReg, NULL, NULL, 0) );
        }
        SECTION( "negative exponent" ) {
            int numTermsPerReg[] = {3, 3};
            qreal coeffs[] = {0,0,0,  0,0,0};
            qreal expos[] =  {1,2,3,  1,2,3};
            expos[GENERATE(range(0,6))] = GENERATE( -1, -2, -2.5 );
            enum bitEncoding enc = GENERATE( UNSIGNED, TWOS_COMPLEMENT );
            REQUIRE_THROWS_WITH( applyMultiVarPhaseFuncOverrides(quregVec, qubits, numQubitsPerReg, numRegs, enc, coeffs, expos, numTermsPerReg, NULL, NULL, 0), Contains("The phase function contained an illegal negative exponent") );
        }
        SECTION( "number of overrides" ) {
            int numTermsPerReg[] = {3, 3};
            qreal coeffs[] = {0,0,0,  0,0,0};
            qreal expos[] =  {1,2,3,  1,2,3};
            int numOverrides = -1;
            REQUIRE_THROWS_WITH( applyMultiVarPhaseFuncOverrides(quregVec, qubits, numQubitsPerReg, numRegs, UNSIGNED, coeffs, expos, numTermsPerReg, NULL, NULL, numOverrides), Contains("Invalid number of phase function overrides specified") );
        }
        SECTION( "override indices" ) {
            int numTermsPerReg[] = {3, 3};
            qreal coeffs[] = {0,0,0,  0,0,0};
            qreal expos[] =  {1,2,3,  1,2,3};
            // numQubitsPerReg = {2, 3}
            int numOverrides = 3;
            long long int overrideInds[] = {0,0, 0,0, 0,0}; // repetition not checked
            qreal overridePhases[]       = {.1,  .1,  .1};
            // first element of overrideInds coordinate is a 2 qubit register
            enum bitEncoding enc = UNSIGNED;
            int badInd = GENERATE(0, 2, 4);
            overrideInds[badInd] = GENERATE( -1, (1<<2) );
            REQUIRE_THROWS_WITH( applyMultiVarPhaseFuncOverrides(quregVec, qubits, numQubitsPerReg, numRegs, enc, coeffs, expos, numTermsPerReg, overrideInds, overridePhases, numOverrides), Contains("Invalid phase function override index, in the UNSIGNED encoding") );
            overrideInds[badInd] = 0;
            // second element of overrideInds coordinate is a 3 qubit register
            badInd += 1;
            overrideInds[badInd] = GENERATE( -1, (1<<3) );
            REQUIRE_THROWS_WITH( applyMultiVarPhaseFuncOverrides(quregVec, qubits, numQubitsPerReg, numRegs, enc, coeffs, expos, numTermsPerReg, overrideInds, overridePhases, numOverrides), Contains("Invalid phase function override index, in the UNSIGNED encoding") );
            overrideInds[badInd] = 0;
            badInd -= 1;
            enc = TWOS_COMPLEMENT;
            int minInd = -(1<<(numQubitsPerReg[0]-1));
            int maxInd = (1<<(numQubitsPerReg[0]-1)) - 1;
            overrideInds[badInd] = GENERATE_COPY( minInd-1, maxInd+1 );
            REQUIRE_THROWS_WITH( applyMultiVarPhaseFuncOverrides(quregVec, qubits, numQubitsPerReg, numRegs, enc, coeffs, expos, numTermsPerReg, overrideInds, overridePhases, numOverrides), Contains("Invalid phase function override index, in the TWOS_COMPLEMENT encoding") );
            overrideInds[badInd] = 0;
            badInd++;
            minInd = -(1<<(numQubitsPerReg[1]-1));
            maxInd = (1<<(numQubitsPerReg[1]-1)) -1;
            overrideInds[badInd] = GENERATE_COPY( minInd-1, maxInd+1 );
            REQUIRE_THROWS_WITH( applyMultiVarPhaseFuncOverrides(quregVec, qubits, numQubitsPerReg, numRegs, enc, coeffs, expos, numTermsPerReg, overrideInds, overridePhases, numOverrides), Contains("Invalid phase function override index, in the TWOS_COMPLEMENT encoding") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyMultiVarPhaseFuncOverrides(), applyReferenceOp(), areEqual(), CLEANUP_TEST, expI(), getKroneckerProduct(), getRandomInt(), getRandomReal(), getTwosComplement(), getZeroMatrix(), MAX_NUM_REGS_APPLY_ARBITRARY_PHASE, NUM_QUBITS, PREPARE_TEST, qreal, setDiagMatrixOverrides(), sublists(), TWOS_COMPLEMENT, UNSIGNED, and VLA.
TEST_CASE() [12/136]
TEST_CASE ("applyNamedPhaseFunc" , "" [operators])
See also
applyNamedPhaseFunc
Author
Tyson Jones
Definition at line 1432 of file test_operators.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    SECTION( "correctness" ) {
        // try every kind of binary encoding
        enum bitEncoding encoding = GENERATE( UNSIGNED,TWOS_COMPLEMENT );
        // try every possible number of registers
        // (between #qubits containing 1, and 1 containing #qubits)
        int numRegs;
        int maxNumRegs = 0;
        if (encoding == UNSIGNED)
            maxNumRegs = NUM_QUBITS;
        if (encoding == TWOS_COMPLEMENT)
            maxNumRegs = NUM_QUBITS/2;  // floors
        numRegs = GENERATE_COPY( range(1, maxNumRegs+1) );
        // try every possible total number of involved qubits
        int totalNumQubits;
        int minTotalQubits = 0;
        if (encoding == UNSIGNED)
            // each register must contain at least 1 qubit
            minTotalQubits = numRegs;
        if (encoding == TWOS_COMPLEMENT)
            // each register must contain at least 2 qubits
            minTotalQubits = 2*numRegs;
        totalNumQubits = GENERATE_COPY( range(minTotalQubits,NUM_QUBITS+1) );
        // try every qubits subset and ordering
        int* regs = GENERATE_COPY( sublists(range(0,NUM_QUBITS), totalNumQubits) );
        // assign each sub-reg its minimum length
        int unallocQubits = totalNumQubits;
        VLA(int, numQubitsPerReg, numRegs);
        for (int i=0; i<numRegs; i++)
            if (encoding == UNSIGNED) {
                numQubitsPerReg[i] = 1;
                unallocQubits -= 1;
            }
            else if (encoding == TWOS_COMPLEMENT) {
                numQubitsPerReg[i] = 2;
                unallocQubits -= 2;
            }
        // and randomly allocate the remaining qubits between the registers
        while (unallocQubits > 0) {
            numQubitsPerReg[getRandomInt(0,numRegs)] += 1;
            unallocQubits--;
        }
        // for reference, determine the values corresponding to each register for all basis states
        std::vector<std::vector<qreal>> regVals(1<<totalNumQubits, std::vector<qreal>(numRegs));
        for (long long int i=0; i<(1<<totalNumQubits); i++) {
            long long int bits = i;
            for (int r=0; r<numRegs; r++) {
                regVals[i][r] = bits % (1 << numQubitsPerReg[r]);
                bits = bits >> numQubitsPerReg[r];
                if (encoding == TWOS_COMPLEMENT)
                    regVals[i][r] = getTwosComplement(regVals[i][r], numQubitsPerReg[r]);
            }
        }
        /* the reference diagonal matrix which assumes the qubits are
         * contiguous and strictly increasing between the registers, and hence
         * only depends on the number of qubits in each register.
         */
        QMatrix diagMatr = getZeroMatrix(1 << totalNumQubits);
        SECTION( "NORM" ) {
            for (size_t i=0; i<diagMatr.size(); i++) {
                qreal phase = 0;
                for (int r=0; r<numRegs; r++)
                    phase += pow(regVals[i][r], 2);
                phase = sqrt(phase);
                diagMatr[i][i] = expI(phase);
            }
            SECTION( "state-vector" ) {
                applyNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, encoding, NORM);
                applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
            }
            SECTION( "density-matrix" ) {
                applyNamedPhaseFunc(quregMatr, regs, numQubitsPerReg, numRegs, encoding, NORM);
                applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregMatr, refMatr, 142*REAL_EPS) );
            }
        }
        SECTION( "PRODUCT" ) {
            for (size_t i=0; i<diagMatr.size(); i++) {
                qreal phase = 1;
                for (int r=0; r<numRegs; r++)
                    phase *= regVals[i][r];
                diagMatr[i][i] = expI(phase);
            }
            SECTION( "state-vector" ) {
                applyNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, encoding, PRODUCT);
                applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
            }
            SECTION( "density-matrix" ) {
                applyNamedPhaseFunc(quregMatr, regs, numQubitsPerReg, numRegs, encoding, PRODUCT);
                applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregMatr, refMatr, 142*REAL_EPS) );
            }
        }
        SECTION( "DISTANCE" ) {
            // test only if there are an even number of registers
            if (numRegs%2 == 0) {
                for (size_t i=0; i<diagMatr.size(); i++) {
                    qreal phase = 0;
                    for (int r=0; r<numRegs; r+=2)
                        phase += pow(regVals[i][r+1]-regVals[i][r], 2);
                    phase = sqrt(phase);
                    diagMatr[i][i] = expI(phase);
                }
            }
            SECTION( "state-vector" ) {
                if (numRegs%2 == 0) {
                    applyNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, encoding, DISTANCE);
                    applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                    REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
                }
            }
            SECTION( "density-matrix" ) {
                if (numRegs%2 == 0) {
                    applyNamedPhaseFunc(quregMatr, regs, numQubitsPerReg, numRegs, encoding, DISTANCE);
                    applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                    REQUIRE( areEqual(quregMatr, refMatr, 142*REAL_EPS) );
                }
            }
        }
    }
    SECTION( "input validation" ) {
        int numRegs = 2;
        int numQubitsPerReg[] = {2,3};
        int regs[] = {0,1,2,3,4};
        SECTION( "number of registers" ) {
            numRegs = GENERATE_COPY( -1, 0, 1+MAX_NUM_REGS_APPLY_ARBITRARY_PHASE );
            REQUIRE_THROWS_WITH( applyNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, NORM), Contains("Invalid number of qubit subregisters") );
        }
        SECTION( "number of qubits" ) {
            numQubitsPerReg[GENERATE_COPY(range(0,numRegs))] = GENERATE( -1, 0, 1+NUM_QUBITS );
            REQUIRE_THROWS_WITH( applyNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, NORM), Contains("Invalid number of qubits") );
        }
        SECTION( "repetition of qubits" ) {
            regs[GENERATE(2,3,4)] = regs[1];
            REQUIRE_THROWS_WITH( applyNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, NORM), Contains("The qubits must be unique") );
        }
        SECTION( "qubit indices" ) {
            regs[GENERATE(range(0,NUM_QUBITS))] = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( applyNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, NORM), Contains("Invalid qubit index") );
        }
        SECTION( "bit encoding name" ) {
            enum bitEncoding enc = (enum bitEncoding) GENERATE( -1, 2 );
            REQUIRE_THROWS_WITH( applyNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, enc, NORM), Contains("Invalid bit encoding") );
        }
        SECTION( "two's complement register" ) {
            numQubitsPerReg[GENERATE_COPY(range(0,numRegs))] = 1;
            REQUIRE_THROWS_WITH( applyNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, TWOS_COMPLEMENT, NORM), Contains("A sub-register contained too few qubits to employ TWOS_COMPLEMENT encoding") );
        }
        SECTION( "phase function name" ) {
            enum phaseFunc func = (enum phaseFunc) GENERATE( -1, MAX_INDEX_PHASE_FUNC + 1 );
            REQUIRE_THROWS_WITH( applyNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, func), Contains("Invalid named phase function") );
        }
        SECTION( "phase function parameters" ) {
            enum phaseFunc func = GENERATE( SCALED_NORM, INVERSE_NORM, SCALED_INVERSE_NORM, SCALED_INVERSE_SHIFTED_NORM, SCALED_PRODUCT, INVERSE_PRODUCT, SCALED_INVERSE_PRODUCT, SCALED_DISTANCE, INVERSE_DISTANCE, SCALED_INVERSE_DISTANCE, SCALED_INVERSE_SHIFTED_DISTANCE );
            REQUIRE_THROWS_WITH( applyNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, func), Contains("Invalid number of parameters") );
        }
        SECTION( "distance pair registers" ) {
            int numQb[] = {1,1,1,1,1};
            int qb[] = {0,1,2,3,4};
            numRegs = GENERATE( 1, 3, 5 );
            REQUIRE_THROWS_WITH( applyNamedPhaseFunc(quregVec, qb, numQb, numRegs, UNSIGNED, DISTANCE), Contains("Phase functions DISTANCE") && Contains("even number of sub-registers") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyNamedPhaseFunc(), applyReferenceOp(), areEqual(), CLEANUP_TEST, DISTANCE, expI(), getRandomInt(), getTwosComplement(), getZeroMatrix(), INVERSE_DISTANCE, INVERSE_NORM, INVERSE_PRODUCT, MAX_INDEX_PHASE_FUNC, MAX_NUM_REGS_APPLY_ARBITRARY_PHASE, NORM, NUM_QUBITS, PREPARE_TEST, PRODUCT, qreal, SCALED_DISTANCE, SCALED_INVERSE_DISTANCE, SCALED_INVERSE_NORM, SCALED_INVERSE_PRODUCT, SCALED_INVERSE_SHIFTED_DISTANCE, SCALED_INVERSE_SHIFTED_NORM, SCALED_NORM, SCALED_PRODUCT, sublists(), TWOS_COMPLEMENT, UNSIGNED, and VLA.
TEST_CASE() [13/136]
TEST_CASE ("applyNamedPhaseFuncOverrides" , "" [operators])
See also
applyNamedPhaseFuncOverrides
Author
Tyson Jones
Definition at line 1644 of file test_operators.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    SECTION( "correctness" ) {
        // try every kind of binary encoding
        enum bitEncoding encoding = GENERATE( UNSIGNED,TWOS_COMPLEMENT );
        // try every possible number of registers
        // (between #qubits containing 1, and 1 containing #qubits)
        int numRegs;
        int maxNumRegs = 0;
        if (encoding == UNSIGNED)
            maxNumRegs = NUM_QUBITS;
        if (encoding == TWOS_COMPLEMENT)
            maxNumRegs = NUM_QUBITS/2;  // floors
        numRegs = GENERATE_COPY( range(1, maxNumRegs+1) );
        // try every possible total number of involved qubits
        int totalNumQubits;
        int minTotalQubits = 0;
        if (encoding == UNSIGNED)
            // each register must contain at least 1 qubit
            minTotalQubits = numRegs;
        if (encoding == TWOS_COMPLEMENT)
            // each register must contain at least 2 qubits
            minTotalQubits = 2*numRegs;
        totalNumQubits = GENERATE_COPY( range(minTotalQubits,NUM_QUBITS+1) );
        // try every qubits subset and ordering
        int* regs = GENERATE_COPY( sublists(range(0,NUM_QUBITS), totalNumQubits) );
        // assign each sub-reg its minimum length
        int unallocQubits = totalNumQubits;
        VLA(int, numQubitsPerReg, numRegs);
        for (int i=0; i<numRegs; i++)
            if (encoding == UNSIGNED) {
                numQubitsPerReg[i] = 1;
                unallocQubits -= 1;
            }
            else if (encoding == TWOS_COMPLEMENT) {
                numQubitsPerReg[i] = 2;
                unallocQubits -= 2;
            }
        // and randomly allocate the remaining qubits between the registers
        while (unallocQubits > 0) {
            numQubitsPerReg[getRandomInt(0,numRegs)] += 1;
            unallocQubits--;
        }
        // choose a random number of overrides (even overriding every amplitude)
        int numOverrides = getRandomInt(0, (1<<totalNumQubits) + 1);
        // randomise each override index (uniqueness isn't checked)
        VLA(long long int, overrideInds, numOverrides*numRegs);
        int flatInd = 0;
        for (int v=0; v<numOverrides; v++) {
            for (int r=0; r<numRegs; r++) {
                if (encoding == UNSIGNED)
                    overrideInds[flatInd] = getRandomInt(0, 1<<numQubitsPerReg[r]);
                else if (encoding == TWOS_COMPLEMENT)
                    overrideInds[flatInd] = getRandomInt(-(1<<(numQubitsPerReg[r]-1)), (1<<(numQubitsPerReg[r]-1))-1);
                flatInd++;
            }
        }
        // override to a random phase
        VLA(qreal, overridePhases, numOverrides);
        for (int v=0; v<numOverrides; v++)
            overridePhases[v] = getRandomReal(-4, 4); // periodic in [-pi, pi]
        // determine the values corresponding to each register for all basis states
        std::vector<std::vector<qreal>> regVals(1<<totalNumQubits, std::vector<qreal>(numRegs));
        for (long long int i=0; i<(1<<totalNumQubits); i++) {
            long long int bits = i;
            for (int r=0; r<numRegs; r++) {
                regVals[i][r] = bits % (1 << numQubitsPerReg[r]);
                bits = bits >> numQubitsPerReg[r];
                if (encoding == TWOS_COMPLEMENT)
                    regVals[i][r] = getTwosComplement(regVals[i][r], numQubitsPerReg[r]);
            }
        }
        /* a reference diagonal matrix which assumes the qubits are
         * contiguous and strictly increasing between the registers, and hence
         * only depends on the number of qubits in each register.
         */
        QMatrix diagMatr = getZeroMatrix(1 << totalNumQubits);
        SECTION( "NORM" ) {
            for (size_t i=0; i<diagMatr.size(); i++) {
                qreal phase = 0;
                for (int r=0; r<numRegs; r++)
                    phase += pow(regVals[i][r], 2);
                phase = sqrt(phase);
                diagMatr[i][i] = expI(phase);
            }
            setDiagMatrixOverrides(diagMatr, numQubitsPerReg, numRegs, encoding, overrideInds, overridePhases, numOverrides);
            SECTION( "state-vector" ) {
                applyNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, encoding, NORM, overrideInds, overridePhases, numOverrides);
                applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
            }
            SECTION( "density-matrix" ) {
                applyNamedPhaseFuncOverrides(quregMatr, regs, numQubitsPerReg, numRegs, encoding, NORM, overrideInds, overridePhases, numOverrides);
                applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregMatr, refMatr, 1E4*REAL_EPS) );
            }
        }
        SECTION( "PRODUCT" ) {
            for (size_t i=0; i<diagMatr.size(); i++) {
                qreal phase = 1;
                for (int r=0; r<numRegs; r++)
                    phase *= regVals[i][r];
                diagMatr[i][i] = expI(phase);
            }
            setDiagMatrixOverrides(diagMatr, numQubitsPerReg, numRegs, encoding, overrideInds, overridePhases, numOverrides);
            SECTION( "state-vector" ) {
                applyNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, encoding, PRODUCT, overrideInds, overridePhases, numOverrides);
                applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
            }
            SECTION( "density-matrix" ) {
                applyNamedPhaseFuncOverrides(quregMatr, regs, numQubitsPerReg, numRegs, encoding, PRODUCT, overrideInds, overridePhases, numOverrides);
                applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregMatr, refMatr, 1E4*REAL_EPS) );
            }
        }
        SECTION( "DISTANCE" ) {
            // test only if there are an even number of registers
            if (numRegs%2 == 0) {
                for (size_t i=0; i<diagMatr.size(); i++) {
                    qreal phase = 0;
                    for (int r=0; r<numRegs; r+=2)
                        phase += pow(regVals[i][r+1]-regVals[i][r], 2);
                    phase = sqrt(phase);
                    diagMatr[i][i] = expI(phase);
                }
                setDiagMatrixOverrides(diagMatr, numQubitsPerReg, numRegs, encoding, overrideInds, overridePhases, numOverrides);
            }
            SECTION( "state-vector" ) {
                if (numRegs%2 == 0) {
                    applyNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, encoding, DISTANCE, overrideInds, overridePhases, numOverrides);
                    applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                    REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
                }
            }
            SECTION( "density-matrix" ) {
                if (numRegs%2 == 0) {
                    applyNamedPhaseFuncOverrides(quregMatr, regs, numQubitsPerReg, numRegs, encoding, DISTANCE, overrideInds, overridePhases, numOverrides);
                    applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                    REQUIRE( areEqual(quregMatr, refMatr, 1E4*REAL_EPS) );
                }
            }
        }
    }
    SECTION( "input validation" ) {
        int numRegs = 2;
        int numQubitsPerReg[] = {2,3};
        int regs[] = {0,1,2,3,4};
        SECTION( "number of registers" ) {
            numRegs = GENERATE_COPY( -1, 0, 1+MAX_NUM_REGS_APPLY_ARBITRARY_PHASE );
            REQUIRE_THROWS_WITH( applyNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, NORM, NULL, NULL, 0), Contains("Invalid number of qubit subregisters") );
        }
        SECTION( "number of qubits" ) {
            numQubitsPerReg[GENERATE_COPY(range(0,numRegs))] = GENERATE( -1, 0, 1+NUM_QUBITS );
            REQUIRE_THROWS_WITH( applyNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, NORM, NULL, NULL, 0), Contains("Invalid number of qubits") );
        }
        SECTION( "repetition of qubits" ) {
            regs[GENERATE(2,3,4)] = regs[1];
            REQUIRE_THROWS_WITH( applyNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, NORM, NULL, NULL, 0), Contains("The qubits must be unique") );
        }
        SECTION( "qubit indices" ) {
            regs[GENERATE(range(0,NUM_QUBITS))] = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( applyNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, NORM, NULL, NULL, 0), Contains("Invalid qubit index") );
        }
        SECTION( "bit encoding name" ) {
            enum bitEncoding enc = (enum bitEncoding) GENERATE( -1, 2 );
            REQUIRE_THROWS_WITH( applyNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, enc, NORM, NULL, NULL, 0), Contains("Invalid bit encoding") );
        }
        SECTION( "two's complement register" ) {
            numQubitsPerReg[GENERATE_COPY(range(0,numRegs))] = 1;
            REQUIRE_THROWS_WITH( applyNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, TWOS_COMPLEMENT, NORM, NULL, NULL, 0), Contains("A sub-register contained too few qubits to employ TWOS_COMPLEMENT encoding") );
        }
        SECTION( "phase function name" ) {
            enum phaseFunc func = (enum phaseFunc) GENERATE( -1, MAX_INDEX_PHASE_FUNC + 1 );
            REQUIRE_THROWS_WITH( applyNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, func, NULL, NULL, 0), Contains("Invalid named phase function") );
        }
        SECTION( "phase function parameters" ) {
            enum phaseFunc func = GENERATE( SCALED_NORM, INVERSE_NORM, SCALED_INVERSE_NORM, SCALED_INVERSE_SHIFTED_NORM, SCALED_PRODUCT, INVERSE_PRODUCT, SCALED_INVERSE_PRODUCT, SCALED_DISTANCE, INVERSE_DISTANCE, SCALED_INVERSE_DISTANCE, SCALED_INVERSE_SHIFTED_DISTANCE );
            REQUIRE_THROWS_WITH( applyNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, func, NULL, NULL, 0), Contains("Invalid number of parameters") );
        }
        SECTION( "distance pair registers" ) {
            int numQb[] = {1,1,1,1,1};
            int qb[] = {0,1,2,3,4};
            numRegs = GENERATE( 1, 3, 5 );
            REQUIRE_THROWS_WITH( applyNamedPhaseFuncOverrides(quregVec, qb, numQb, numRegs, UNSIGNED, DISTANCE, NULL, NULL, 0), Contains("Phase functions DISTANCE") && Contains("even number of sub-registers") );
        }
        SECTION( "number of overrides" ) {
            int numOverrides = -1;
            REQUIRE_THROWS_WITH( applyNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, NORM, NULL, NULL, numOverrides), Contains("Invalid number of phase function overrides specified") );
        }
        SECTION( "override indices" ) {
            // numQubitsPerReg = {2, 3}
            int numOverrides = 3;
            long long int overrideInds[] = {0,0, 0,0, 0,0}; // repetition not checked
            qreal overridePhases[]       = {.1,  .1,  .1};
            // first element of overrideInds coordinate is a 2 qubit register
            enum bitEncoding enc = UNSIGNED;
            int badInd = GENERATE(0, 2, 4);
            overrideInds[badInd] = GENERATE( -1, (1<<2) );
            REQUIRE_THROWS_WITH( applyNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, enc, NORM, overrideInds, overridePhases, numOverrides), Contains("Invalid phase function override index, in the UNSIGNED encoding") );
            overrideInds[badInd] = 0;
            // second element of overrideInds coordinate is a 3 qubit register
            badInd += 1;
            overrideInds[badInd] = GENERATE( -1, (1<<3) );
            REQUIRE_THROWS_WITH( applyNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, enc, NORM, overrideInds, overridePhases, numOverrides), Contains("Invalid phase function override index, in the UNSIGNED encoding") );
            overrideInds[badInd] = 0;
            badInd -= 1;
            enc = TWOS_COMPLEMENT;
            int minInd = -(1<<(numQubitsPerReg[0]-1));
            int maxInd = (1<<(numQubitsPerReg[0]-1)) - 1;
            overrideInds[badInd] = GENERATE_COPY( minInd-1, maxInd+1 );
            REQUIRE_THROWS_WITH( applyNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, enc, NORM, overrideInds, overridePhases, numOverrides), Contains("Invalid phase function override index, in the TWOS_COMPLEMENT encoding") );
            overrideInds[badInd] = 0;
            badInd++;
            minInd = -(1<<(numQubitsPerReg[1]-1));
            maxInd = (1<<(numQubitsPerReg[1]-1)) -1;
            overrideInds[badInd] = GENERATE_COPY( minInd-1, maxInd+1 );
            REQUIRE_THROWS_WITH( applyNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, enc, NORM, overrideInds, overridePhases, numOverrides), Contains("Invalid phase function override index, in the TWOS_COMPLEMENT encoding") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyNamedPhaseFuncOverrides(), applyReferenceOp(), areEqual(), CLEANUP_TEST, DISTANCE, expI(), getRandomInt(), getRandomReal(), getTwosComplement(), getZeroMatrix(), INVERSE_DISTANCE, INVERSE_NORM, INVERSE_PRODUCT, MAX_INDEX_PHASE_FUNC, MAX_NUM_REGS_APPLY_ARBITRARY_PHASE, NORM, NUM_QUBITS, PREPARE_TEST, PRODUCT, qreal, SCALED_DISTANCE, SCALED_INVERSE_DISTANCE, SCALED_INVERSE_NORM, SCALED_INVERSE_PRODUCT, SCALED_INVERSE_SHIFTED_DISTANCE, SCALED_INVERSE_SHIFTED_NORM, SCALED_NORM, SCALED_PRODUCT, setDiagMatrixOverrides(), sublists(), TWOS_COMPLEMENT, UNSIGNED, and VLA.
TEST_CASE() [14/136]
TEST_CASE ("applyParamNamedPhaseFunc" , "" [operators])
See also
applyParamNamedPhaseFunc
Author
Tyson Jones
Definition at line 1923 of file test_operators.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    SECTION( "correctness" ) {
        // try every kind of binary encoding
        enum bitEncoding encoding = GENERATE( UNSIGNED,TWOS_COMPLEMENT );
        // try every possible number of registers
        // (between #qubits containing 1, and 1 containing #qubits)
        int numRegs;
        int maxNumRegs = 0;
        if (encoding == UNSIGNED)
            maxNumRegs = NUM_QUBITS;
        if (encoding == TWOS_COMPLEMENT)
            maxNumRegs = NUM_QUBITS/2;  // floors
        numRegs = GENERATE_COPY( range(1, maxNumRegs+1) );
        // try every possible total number of involved qubits
        int totalNumQubits;
        int minTotalQubits = 0;
        if (encoding == UNSIGNED)
            // each register must contain at least 1 qubit
            minTotalQubits = numRegs;
        if (encoding == TWOS_COMPLEMENT)
            // each register must contain at least 2 qubits
            minTotalQubits = 2*numRegs;
        totalNumQubits = GENERATE_COPY( range(minTotalQubits,NUM_QUBITS+1) );
        // Previously, we would try every qubits subset and ordering, via:
        //      int* regs = GENERATE_COPY( sublists(range(0,NUM_QUBITS), totalNumQubits) );
        // Alas, this is too many tests and times out Ubuntu unit testing. So instead, we
        // randomly choose some qubits, 10 times.
        GENERATE( range(0, 10) );
        VLA(int, regs, totalNumQubits);
        setRandomTargets(regs, totalNumQubits, NUM_QUBITS);
        // assign each sub-reg its minimum length
        int unallocQubits = totalNumQubits;
        VLA(int, numQubitsPerReg, numRegs);
        for (int i=0; i<numRegs; i++)
            if (encoding == UNSIGNED) {
                numQubitsPerReg[i] = 1;
                unallocQubits -= 1;
            }
            else if (encoding == TWOS_COMPLEMENT) {
                numQubitsPerReg[i] = 2;
                unallocQubits -= 2;
            }
        // and randomly allocate the remaining qubits between the registers
        while (unallocQubits > 0) {
            numQubitsPerReg[getRandomInt(0,numRegs)] += 1;
            unallocQubits--;
        }
        /* produce a reference diagonal matrix which assumes the qubits are
         * contiguous and strictly increasing between the registers, and hence
         * only depends on the number of qubits in each register.
         */
        QMatrix diagMatr = getZeroMatrix(1 << totalNumQubits);
        // determine the values corresponding to each register for all basis states
        std::vector<std::vector<qreal>> regVals(1<<totalNumQubits, std::vector<qreal>(numRegs));
        for (long long int i=0; i<(1<<totalNumQubits); i++) {
            long long int bits = i;
            for (int r=0; r<numRegs; r++) {
                regVals[i][r] = bits % (1 << numQubitsPerReg[r]);
                bits = bits >> numQubitsPerReg[r];
                if (encoding == TWOS_COMPLEMENT)
                    regVals[i][r] = getTwosComplement(regVals[i][r], numQubitsPerReg[r]);
            }
        }
        SECTION( "INVERSE_NORM" ) {
            enum phaseFunc func = INVERSE_NORM;
            qreal divPhase = getRandomReal(-4, 4);
            for (size_t i=0; i<diagMatr.size(); i++) {
                qreal phase = 0;
                for (int r=0; r<numRegs; r++)
                    phase += pow(regVals[i][r], 2);
                phase = (phase == 0.)? divPhase : 1/sqrt(phase);
                diagMatr[i][i] = expI(phase);
            }
            qreal params[] = {divPhase};
            int numParams = 1;
            SECTION( "state-vector" ) {
                applyParamNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams);
                applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
            }
            SECTION( "density-matrix" ) {
                applyParamNamedPhaseFunc(quregMatr, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams);
                applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregMatr, refMatr, 1E2*REAL_EPS) );
            }
        }
        SECTION( "SCALED_NORM" ) {
            enum phaseFunc func = SCALED_NORM;
            qreal coeff = getRandomReal(-10, 10);
            for (size_t i=0; i<diagMatr.size(); i++) {
                qreal phase = 0;
                for (int r=0; r<numRegs; r++)
                    phase += pow(regVals[i][r], 2);
                phase = coeff * sqrt(phase);
                diagMatr[i][i] = expI(phase);
            }
            qreal params[] = {coeff};
            int numParams = 1;
            SECTION( "state-vector" ) {
                applyParamNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams);
                applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
            }
            SECTION( "density-matrix" ) {
                applyParamNamedPhaseFunc(quregMatr, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams);
                applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregMatr, refMatr, 1E2*REAL_EPS) );
            }
        }
        SECTION( "SCALED_INVERSE_NORM" ) {
            enum phaseFunc func = SCALED_INVERSE_NORM;
            qreal coeff = getRandomReal(-10, 10);
            qreal divPhase = getRandomReal(-4, 4);
            for (size_t i=0; i<diagMatr.size(); i++) {
                qreal phase = 0;
                for (int r=0; r<numRegs; r++)
                    phase += pow(regVals[i][r], 2);
                phase = (phase == 0.)? divPhase : coeff/sqrt(phase);
                diagMatr[i][i] = expI(phase);
            }
            qreal params[] = {coeff, divPhase};
            int numParams = 2;
            SECTION( "state-vector" ) {
                applyParamNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams);
                applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
            }
            SECTION( "density-matrix" ) {
                applyParamNamedPhaseFunc(quregMatr, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams);
                applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregMatr, refMatr, 1E2*REAL_EPS) );
            }
        }
        SECTION( "SCALED_INVERSE_SHIFTED_NORM" ) {
            enum phaseFunc func = SCALED_INVERSE_SHIFTED_NORM;
            int numParams = 2 + numRegs;
            VLA(qreal, params, numParams);
            params[0] = getRandomReal(-10, 10); // scaling
            params[1] = getRandomReal(-4, 4); // divergence override
            for (int r=0; r<numRegs; r++)
                params[2+r] = getRandomReal(-8, 8); // shifts
            for (size_t i=0; i<diagMatr.size(); i++) {
                qreal phase = 0;
                for (int r=0; r<numRegs; r++)
                    phase += pow(regVals[i][r] - params[2+r], 2);
                phase = sqrt(phase);
                phase = (phase <= REAL_EPS)? params[1] : params[0]/phase;
                diagMatr[i][i] = expI(phase);
            }
            SECTION( "state-vector" ) {
                applyParamNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams);
                applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
            }
            SECTION( "density-matrix" ) {
                applyParamNamedPhaseFunc(quregMatr, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams);
                applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregMatr, refMatr, 1E2*REAL_EPS) );
            }
        }
        SECTION( "INVERSE_PRODUCT" ) {
            enum phaseFunc func = INVERSE_PRODUCT;
            qreal divPhase = getRandomReal(-4, 4);
            for (size_t i=0; i<diagMatr.size(); i++) {
                qreal phase = 1;
                for (int r=0; r<numRegs; r++)
                    phase *= regVals[i][r];
                phase = (phase == 0.)? divPhase : 1. / phase;
                diagMatr[i][i] = expI(phase);
            }
            qreal params[] = {divPhase};
            int numParams = 1;
            SECTION( "state-vector" ) {
                applyParamNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams);
                applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
            }
            SECTION( "density-matrix" ) {
                applyParamNamedPhaseFunc(quregMatr, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams);
                applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregMatr, refMatr, 1E2*REAL_EPS) );
            }
        }
        SECTION( "SCALED_PRODUCT" ) {
            enum phaseFunc func = SCALED_PRODUCT;
            qreal coeff = getRandomReal(-10, 10);
            for (size_t i=0; i<diagMatr.size(); i++) {
                qreal phase = 1;
                for (int r=0; r<numRegs; r++)
                    phase *= regVals[i][r];
                diagMatr[i][i] = expI(coeff * phase);
            }
            qreal params[] = {coeff};
            int numParams = 1;
            SECTION( "state-vector" ) {
                applyParamNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams);
                applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
            }
            SECTION( "density-matrix" ) {
                applyParamNamedPhaseFunc(quregMatr, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams);
                applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregMatr, refMatr, 1E2*REAL_EPS) );
            }
        }
        SECTION( "SCALED_INVERSE_PRODUCT" ) {
            enum phaseFunc func = SCALED_INVERSE_PRODUCT;
            qreal coeff = getRandomReal(-10, 10);
            qreal divPhase = getRandomReal(-4, 4);
            qreal params[] = {coeff, divPhase};
            int numParams = 2;
            for (size_t i=0; i<diagMatr.size(); i++) {
                qreal phase = 1;
                for (int r=0; r<numRegs; r++)
                    phase *= regVals[i][r];
                phase = (phase == 0)? divPhase : coeff / phase;
                diagMatr[i][i] = expI(phase);
            }
            SECTION( "state-vector" ) {
                applyParamNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams);
                applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
            }
            SECTION( "density-matrix" ) {
                applyParamNamedPhaseFunc(quregMatr, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams);
                applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregMatr, refMatr, 1E2*REAL_EPS) );
            }
        }
        SECTION( "INVERSE_DISTANCE" ) {
            enum phaseFunc func = INVERSE_DISTANCE;
            qreal divPhase = getRandomReal( -4, 4 );
            qreal params[] = {divPhase};
            int numParams = 1;
            // test only if there are an even number of registers
            if (numRegs%2 == 0) {
                for (size_t i=0; i<diagMatr.size(); i++) {
                    qreal phase = 0;
                    for (int r=0; r<numRegs; r+=2)
                        phase += pow(regVals[i][r+1]-regVals[i][r], 2);
                    phase = (phase == 0.)? divPhase : 1./sqrt(phase);
                    diagMatr[i][i] = expI(phase);
                }
            }
            SECTION( "state-vector" ) {
                if (numRegs%2 == 0) {
                    applyParamNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams);
                    applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                    REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
                }
            }
            SECTION( "density-matrix" ) {
                if (numRegs%2 == 0) {
                    applyParamNamedPhaseFunc(quregMatr, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams);
                    applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                    REQUIRE( areEqual(quregMatr, refMatr, 1E2*REAL_EPS) );
                }
            }
        }
        SECTION( "SCALED_DISTANCE" ) {
            enum phaseFunc func = SCALED_DISTANCE;
            qreal coeff = getRandomReal( -10, 10 );
            qreal params[] = {coeff};
            int numParams = 1;
            // test only if there are an even number of registers
            if (numRegs%2 == 0) {
                for (size_t i=0; i<diagMatr.size(); i++) {
                    qreal phase = 0;
                    for (int r=0; r<numRegs; r+=2)
                        phase += pow(regVals[i][r+1]-regVals[i][r], 2);
                    phase = coeff * sqrt(phase);
                    diagMatr[i][i] = expI(phase);
                }
            }
            SECTION( "state-vector" ) {
                if (numRegs%2 == 0) {
                    applyParamNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams);
                    applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                    REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
                }
            }
            SECTION( "density-matrix" ) {
                if (numRegs%2 == 0) {
                    applyParamNamedPhaseFunc(quregMatr, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams);
                    applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                    REQUIRE( areEqual(quregMatr, refMatr, 1E2*REAL_EPS) );
                }
            }
        }
        SECTION( "SCALED_INVERSE_DISTANCE" ) {
            enum phaseFunc func = SCALED_INVERSE_DISTANCE;
            qreal coeff = getRandomReal( -10, 10 );
            qreal divPhase = getRandomReal( -4, 4 );
            qreal params[] = {coeff, divPhase};
            int numParams = 2;
            // test only if there are an even number of registers
            if (numRegs%2 == 0) {
                for (size_t i=0; i<diagMatr.size(); i++) {
                    qreal phase = 0;
                    for (int r=0; r<numRegs; r+=2)
                        phase += pow(regVals[i][r+1]-regVals[i][r], 2);
                    phase = (phase == 0.)? divPhase : coeff/sqrt(phase);
                    diagMatr[i][i] = expI(phase);
                }
            }
            SECTION( "state-vector" ) {
                if (numRegs%2 == 0) {
                    applyParamNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams);
                    applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                    REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
                }
            }
            SECTION( "density-matrix" ) {
                if (numRegs%2 == 0) {
                    applyParamNamedPhaseFunc(quregMatr, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams);
                    applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                    REQUIRE( areEqual(quregMatr, refMatr, 1E2*REAL_EPS) );
                }
            }
        }
        SECTION( "SCALED_INVERSE_SHIFTED_DISTANCE" ) {
            enum phaseFunc func = SCALED_INVERSE_SHIFTED_DISTANCE;
            int numParams = 2 + numRegs/2;
            VLA(qreal, params, numParams);
            // test only if there are an even number of registers
            if (numRegs%2 == 0) {
                params[0] = getRandomReal( -10, 10 ); // scaling
                params[1] = getRandomReal( -4, 4 ); // divergence override
                for (int r=0; r<numRegs/2; r++)
                    params[2+r] = getRandomReal( -8, 8 ); // shifts
                for (size_t i=0; i<diagMatr.size(); i++) {
                    qreal phase = 0;
                    for (int r=0; r<numRegs; r+=2)
                        phase += pow(regVals[i][r]-regVals[i][r+1]-params[2+r/2], 2);
                    phase = sqrt(phase);
                    phase = (phase <= REAL_EPS)? params[1] : params[0]/phase;
                    diagMatr[i][i] = expI(phase);
                }
            }
            SECTION( "state-vector" ) {
                if (numRegs%2 == 0) {
                    applyParamNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams);
                    applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                    REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
                }
            }
            SECTION( "density-matrix" ) {
                if (numRegs%2 == 0) {
                    applyParamNamedPhaseFunc(quregMatr, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams);
                    applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                    REQUIRE( areEqual(quregMatr, refMatr, 1E2*REAL_EPS) );
                }
            }
        }
        SECTION( "SCALED_INVERSE_SHIFTED_WEIGHTED_DISTANCE" ) {
            enum phaseFunc func = SCALED_INVERSE_SHIFTED_WEIGHTED_DISTANCE;
            int numParams = 2 + numRegs;
            VLA(qreal, params, numParams);
            // test only if there are an even number of registers
            if (numRegs%2 == 0) {
                params[0] = getRandomReal( -10, 10 ); // scaling
                params[1] = getRandomReal( -4, 4 ); // divergence override
                for (int r=0; r<numRegs; r+=2) {
                    params[2+r] = getRandomReal( -10, 10 ); // factor
                    params[2+r+1] = getRandomReal( -8, 8 ); // shift
                }
                for (size_t i=0; i<diagMatr.size(); i++) {
                    qreal phase = 0;
                    for (int r=0; r<numRegs; r+=2)
                        phase += params[2+r] * pow(regVals[i][r]-regVals[i][r+1]-params[2+r+1], 2);
                    if (phase < 0)
                        phase = 0;
                    phase = sqrt(phase);
                    phase = (phase <= REAL_EPS)? params[1] : params[0]/phase;
                    diagMatr[i][i] = expI(phase);
                }
            }
            SECTION( "state-vector" ) {
                if (numRegs%2 == 0) {
                    applyParamNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams);
                    applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                    REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
                }
            }
            SECTION( "density-matrix" ) {
                if (numRegs%2 == 0) {
                    applyParamNamedPhaseFunc(quregMatr, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams);
                    applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                    REQUIRE( areEqual(quregMatr, refMatr, 1E4*REAL_EPS) );
                }
            }
        }
    }
    SECTION( "input validation" ) {
        int numRegs = 2;
        int numQubitsPerReg[] = {2,3};
        int regs[] = {0,1,2,3,4};
        SECTION( "number of registers" ) {
            numRegs = GENERATE_COPY( -1, 0, 1+MAX_NUM_REGS_APPLY_ARBITRARY_PHASE );
            REQUIRE_THROWS_WITH( applyParamNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, NORM, NULL, 0), Contains("Invalid number of qubit subregisters") );
        }
        SECTION( "number of qubits" ) {
            numQubitsPerReg[GENERATE_COPY(range(0,numRegs))] = GENERATE( -1, 0, 1+NUM_QUBITS );
            REQUIRE_THROWS_WITH( applyParamNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, NORM, NULL, 0), Contains("Invalid number of qubits") );
        }
        SECTION( "repetition of qubits" ) {
            regs[GENERATE(2,3,4)] = regs[1];
            REQUIRE_THROWS_WITH( applyParamNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, NORM, NULL, 0), Contains("The qubits must be unique") );
        }
        SECTION( "qubit indices" ) {
            regs[GENERATE(range(0,NUM_QUBITS))] = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( applyParamNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, NORM, NULL, 0), Contains("Invalid qubit index") );
        }
        SECTION( "bit encoding name" ) {
            enum bitEncoding enc = (enum bitEncoding) GENERATE( -1, 2 );
            REQUIRE_THROWS_WITH( applyParamNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, enc, NORM, NULL, 0), Contains("Invalid bit encoding") );
        }
        SECTION( "two's complement register" ) {
            numQubitsPerReg[GENERATE_COPY(range(0,numRegs))] = 1;
            REQUIRE_THROWS_WITH( applyParamNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, TWOS_COMPLEMENT, NORM, NULL, 0), Contains("A sub-register contained too few qubits to employ TWOS_COMPLEMENT encoding") );
        }
        SECTION( "phase function name" ) {
            enum phaseFunc func = (enum phaseFunc) GENERATE( -1, MAX_INDEX_PHASE_FUNC + 1 );
            REQUIRE_THROWS_WITH( applyParamNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, func, NULL, 0), Contains("Invalid named phase function") );
        }
        SECTION( "phase function parameters" ) {
            VLA(qreal, params, numRegs + 3);
            for (int r=0; r<numRegs + 3; r++)
                params[r] = 0;
            SECTION( "no parameter functions" ) {
                enum phaseFunc func = GENERATE( NORM, PRODUCT, DISTANCE  );
                int numParams = GENERATE( -1, 1, 2 );
                REQUIRE_THROWS_WITH( applyParamNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, func, params, numParams), Contains("Invalid number of parameters") );
            }
            SECTION( "single parameter functions" ) {
                enum phaseFunc func = GENERATE( SCALED_NORM, INVERSE_NORM, SCALED_PRODUCT, INVERSE_PRODUCT, SCALED_DISTANCE, INVERSE_DISTANCE );
                int numParams = GENERATE( -1, 0, 2 );
                REQUIRE_THROWS_WITH( applyParamNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, func, params, numParams), Contains("Invalid number of parameters") );
            }
            SECTION( "two parameter functions" ) {
                enum phaseFunc func = GENERATE( SCALED_INVERSE_NORM, SCALED_INVERSE_PRODUCT, SCALED_INVERSE_DISTANCE );
                int numParams = GENERATE( 0, 1, 3 );
                REQUIRE_THROWS_WITH( applyParamNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, func, params, numParams), Contains("Invalid number of parameters") );
            }
            SECTION( "shifted distance" ) {
                if (numRegs%2 == 0) {
                    enum phaseFunc func = SCALED_INVERSE_SHIFTED_DISTANCE;
                    int numParams = GENERATE_COPY( 0, 1, numRegs/2 - 1, numRegs/2, numRegs/2 + 1, numRegs/2 + 3 );
                    REQUIRE_THROWS_WITH( applyParamNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, func, params, numParams), Contains("Invalid number of parameters") );
                }
            }
            SECTION( "shifted norm" ) {
                enum phaseFunc func = SCALED_INVERSE_SHIFTED_NORM;
                int numParams = GENERATE_COPY( 0, 1, numRegs-1, numRegs, numRegs+1, numRegs+3 );
                REQUIRE_THROWS_WITH( applyParamNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, func, params, numParams), Contains("Invalid number of parameters") );
            }
            SECTION( "shifted weighted distance" ) {
                if (numRegs%2 == 0) {
                    enum phaseFunc func = SCALED_INVERSE_SHIFTED_WEIGHTED_DISTANCE;
                    int numParams = GENERATE_COPY( 0, 1, 2 + numRegs - 1, 2 + numRegs + 1 );
                    REQUIRE_THROWS_WITH( applyParamNamedPhaseFunc(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, func, params, numParams), Contains("Invalid number of parameters") );
                }
            }
        }
        SECTION( "distance pair registers" ) {
            int numQb[] = {1,1,1,1,1};
            int qb[] = {0,1,2,3,4};
            numRegs = GENERATE( 1, 3, 5 );
            REQUIRE_THROWS_WITH( applyParamNamedPhaseFunc(quregVec, qb, numQb, numRegs, UNSIGNED, DISTANCE, NULL, 0), Contains("Phase functions DISTANCE") && Contains("even number of sub-registers") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyParamNamedPhaseFunc(), applyReferenceOp(), areEqual(), CLEANUP_TEST, DISTANCE, expI(), getRandomInt(), getRandomReal(), getTwosComplement(), getZeroMatrix(), INVERSE_DISTANCE, INVERSE_NORM, INVERSE_PRODUCT, MAX_INDEX_PHASE_FUNC, MAX_NUM_REGS_APPLY_ARBITRARY_PHASE, NORM, NUM_QUBITS, PREPARE_TEST, PRODUCT, qreal, SCALED_DISTANCE, SCALED_INVERSE_DISTANCE, SCALED_INVERSE_NORM, SCALED_INVERSE_PRODUCT, SCALED_INVERSE_SHIFTED_DISTANCE, SCALED_INVERSE_SHIFTED_NORM, SCALED_INVERSE_SHIFTED_WEIGHTED_DISTANCE, SCALED_NORM, SCALED_PRODUCT, setRandomTargets(), TWOS_COMPLEMENT, UNSIGNED, and VLA.
TEST_CASE() [15/136]
TEST_CASE ("applyParamNamedPhaseFuncOverrides" , "" [operators])
See also
applyParamNamedPhaseFuncOverrides
Author
Tyson Jones
Definition at line 2508 of file test_operators.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    SECTION( "correctness" ) {
        // try every kind of binary encoding
        enum bitEncoding encoding = GENERATE( UNSIGNED,TWOS_COMPLEMENT );
        // try every possible number of registers
        // (between #qubits containing 1, and 1 containing #qubits)
        int numRegs;
        int maxNumRegs = 0;
        if (encoding == UNSIGNED)
            maxNumRegs = NUM_QUBITS;
        if (encoding == TWOS_COMPLEMENT)
            maxNumRegs = NUM_QUBITS/2;  // floors
        numRegs = GENERATE_COPY( range(1, maxNumRegs+1) );
        // try every possible total number of involved qubits
        int totalNumQubits;
        int minTotalQubits = 0;
        if (encoding == UNSIGNED)
            // each register must contain at least 1 qubit
            minTotalQubits = numRegs;
        if (encoding == TWOS_COMPLEMENT)
            // each register must contain at least 2 qubits
            minTotalQubits = 2*numRegs;
        totalNumQubits = GENERATE_COPY( range(minTotalQubits,NUM_QUBITS+1) );
        // Previously, we would try every qubits subset and ordering, via:
        //      int* regs = GENERATE_COPY( sublists(range(0,NUM_QUBITS), totalNumQubits) );
        // Alas, this is too many tests and times out Ubuntu unit testing. So instead, we
        // randomly choose some qubits, 10 times.
        GENERATE( range(0, 10) );
        VLA(int, regs, totalNumQubits);
        setRandomTargets(regs, totalNumQubits, NUM_QUBITS);
        // assign each sub-reg its minimum length
        int unallocQubits = totalNumQubits;
        VLA(int, numQubitsPerReg, numRegs);
        for (int i=0; i<numRegs; i++)
            if (encoding == UNSIGNED) {
                numQubitsPerReg[i] = 1;
                unallocQubits -= 1;
            }
            else if (encoding == TWOS_COMPLEMENT) {
                numQubitsPerReg[i] = 2;
                unallocQubits -= 2;
            }
        // and randomly allocate the remaining qubits between the registers
        while (unallocQubits > 0) {
            numQubitsPerReg[getRandomInt(0,numRegs)] += 1;
            unallocQubits--;
        }
        // choose a random number of overrides (even overriding every amplitude)
        int numOverrides = getRandomInt(0, (1<<totalNumQubits) + 1);
        // randomise each override index (uniqueness isn't checked)
        VLA(long long int, overrideInds, numOverrides*numRegs);
        int flatInd = 0;
        for (int v=0; v<numOverrides; v++) {
            for (int r=0; r<numRegs; r++) {
                if (encoding == UNSIGNED)
                    overrideInds[flatInd] = getRandomInt(0, 1<<numQubitsPerReg[r]);
                else if (encoding == TWOS_COMPLEMENT)
                    overrideInds[flatInd] = getRandomInt(-(1<<(numQubitsPerReg[r]-1)), (1<<(numQubitsPerReg[r]-1))-1);
                flatInd++;
            }
        }
        // override to a random phase
        VLA(qreal, overridePhases, numOverrides);
        for (int v=0; v<numOverrides; v++)
            overridePhases[v] = getRandomReal(-4, 4); // periodic in [-pi, pi]
        // determine the values corresponding to each register for all basis states
        std::vector<std::vector<qreal>> regVals(1<<totalNumQubits, std::vector<qreal>(numRegs));
        for (long long int i=0; i<(1<<totalNumQubits); i++) {
            long long int bits = i;
            for (int r=0; r<numRegs; r++) {
                regVals[i][r] = bits % (1 << numQubitsPerReg[r]);
                bits = bits >> numQubitsPerReg[r];
                if (encoding == TWOS_COMPLEMENT)
                    regVals[i][r] = getTwosComplement(regVals[i][r], numQubitsPerReg[r]);
            }
        }
        /* produce a reference diagonal matrix which assumes the qubits are
         * contiguous and strictly increasing between the registers, and hence
         * only depends on the number of qubits in each register.
         */
        QMatrix diagMatr = getZeroMatrix(1 << totalNumQubits);
        SECTION( "INVERSE_NORM" ) {
            enum phaseFunc func = INVERSE_NORM;
            qreal divPhase = getRandomReal(-4, 4);
            qreal params[] = {divPhase};
            int numParams = 1;
            for (size_t i=0; i<diagMatr.size(); i++) {
                qreal phase = 0;
                for (int r=0; r<numRegs; r++)
                    phase += pow(regVals[i][r], 2);
                phase = (phase == 0.)? divPhase : 1/sqrt(phase);
                diagMatr[i][i] = expI(phase);
            }
            setDiagMatrixOverrides(diagMatr, numQubitsPerReg, numRegs, encoding, overrideInds, overridePhases, numOverrides);
            SECTION( "state-vector" ) {
                applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams, overrideInds, overridePhases, numOverrides);
                applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
            }
            SECTION( "density-matrix" ) {
                applyParamNamedPhaseFuncOverrides(quregMatr, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams, overrideInds, overridePhases, numOverrides);
                applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregMatr, refMatr, 1E2*REAL_EPS) );
            }
        }
        SECTION( "SCALED_NORM" ) {
            enum phaseFunc func = SCALED_NORM;
            qreal coeff = getRandomReal(-10, 10);
            qreal params[] = {coeff};
            int numParams = 1;
            for (size_t i=0; i<diagMatr.size(); i++) {
                qreal phase = 0;
                for (int r=0; r<numRegs; r++)
                    phase += pow(regVals[i][r], 2);
                phase = coeff * sqrt(phase);
                diagMatr[i][i] = expI(phase);
            }
            setDiagMatrixOverrides(diagMatr, numQubitsPerReg, numRegs, encoding, overrideInds, overridePhases, numOverrides);
            SECTION( "state-vector" ) {
                applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams, overrideInds, overridePhases, numOverrides);
                applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
            }
            SECTION( "density-matrix" ) {
                applyParamNamedPhaseFuncOverrides(quregMatr, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams, overrideInds, overridePhases, numOverrides);
                applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregMatr, refMatr, 1E2*REAL_EPS) );
            }
        }
        SECTION( "SCALED_INVERSE_NORM" ) {
            enum phaseFunc func = SCALED_INVERSE_NORM;
            qreal coeff = getRandomReal(-10, 10);
            qreal divPhase = getRandomReal(-4, 4);
            qreal params[] = {coeff, divPhase};
            int numParams = 2;
            for (size_t i=0; i<diagMatr.size(); i++) {
                qreal phase = 0;
                for (int r=0; r<numRegs; r++)
                    phase += pow(regVals[i][r], 2);
                phase = (phase == 0.)? divPhase : coeff/sqrt(phase);
                diagMatr[i][i] = expI(phase);
            }
            setDiagMatrixOverrides(diagMatr, numQubitsPerReg, numRegs, encoding, overrideInds, overridePhases, numOverrides);
            SECTION( "state-vector" ) {
                applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams, overrideInds, overridePhases, numOverrides);
                applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
            }
            SECTION( "density-matrix" ) {
                applyParamNamedPhaseFuncOverrides(quregMatr, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams, overrideInds, overridePhases, numOverrides);
                applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregMatr, refMatr, 1E2*REAL_EPS) );
            }
        }
        SECTION( "SCALED_INVERSE_SHIFTED_NORM" ) {
            enum phaseFunc func = SCALED_INVERSE_SHIFTED_NORM;
            int numParams = 2 + numRegs;
            VLA(qreal, params, numParams);
            params[0] = getRandomReal(-10, 10); // scaling
            params[1] = getRandomReal(-4, 4); // divergence override
            for (int r=0; r<numRegs; r++)
                params[2+r] = getRandomReal(-8, 8); // shifts
            for (size_t i=0; i<diagMatr.size(); i++) {
                qreal phase = 0;
                for (int r=0; r<numRegs; r++)
                    phase += pow(regVals[i][r] - params[2+r], 2);
                phase = sqrt(phase);
                phase = (phase <= REAL_EPS)? params[1] : params[0]/phase;
                diagMatr[i][i] = expI(phase);
            }
            setDiagMatrixOverrides(diagMatr, numQubitsPerReg, numRegs, encoding, overrideInds, overridePhases, numOverrides);
            SECTION( "state-vector" ) {
                applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams, overrideInds, overridePhases, numOverrides);
                applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
            }
            SECTION( "density-matrix" ) {
                applyParamNamedPhaseFuncOverrides(quregMatr, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams, overrideInds, overridePhases, numOverrides);
                applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregMatr, refMatr, 1E2*REAL_EPS) );
            }
        }
        SECTION( "INVERSE_PRODUCT" ) {
            enum phaseFunc func = INVERSE_PRODUCT;
            qreal divPhase = getRandomReal(-4, 4);
            qreal params[] = {divPhase};
            int numParams = 1;
            for (size_t i=0; i<diagMatr.size(); i++) {
                qreal phase = 1;
                for (int r=0; r<numRegs; r++)
                    phase *= regVals[i][r];
                phase = (phase == 0.)? divPhase : 1. / phase;
                diagMatr[i][i] = expI(phase);
            }
            setDiagMatrixOverrides(diagMatr, numQubitsPerReg, numRegs, encoding, overrideInds, overridePhases, numOverrides);
            SECTION( "state-vector" ) {
                applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams, overrideInds, overridePhases, numOverrides);
                applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
            }
            SECTION( "density-matrix" ) {
                applyParamNamedPhaseFuncOverrides(quregMatr, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams, overrideInds, overridePhases, numOverrides);
                applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregMatr, refMatr, 1E2*REAL_EPS) );
            }
        }
        SECTION( "SCALED_PRODUCT" ) {
            enum phaseFunc func = SCALED_PRODUCT;
            qreal coeff = getRandomReal(-10, 10);
            qreal params[] = {coeff};
            int numParams = 1;
            for (size_t i=0; i<diagMatr.size(); i++) {
                qreal phase = 1;
                for (int r=0; r<numRegs; r++)
                    phase *= regVals[i][r];
                diagMatr[i][i] = expI(coeff * phase);
            }
            setDiagMatrixOverrides(diagMatr, numQubitsPerReg, numRegs, encoding, overrideInds, overridePhases, numOverrides);
            SECTION( "state-vector" ) {
                applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams, overrideInds, overridePhases, numOverrides);
                applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
            }
            SECTION( "density-matrix" ) {
                applyParamNamedPhaseFuncOverrides(quregMatr, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams, overrideInds, overridePhases, numOverrides);
                applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregMatr, refMatr, 1E2*REAL_EPS) );
            }
        }
        SECTION( "SCALED_INVERSE_PRODUCT" ) {
            enum phaseFunc func = SCALED_INVERSE_PRODUCT;
            qreal coeff = getRandomReal(-10, 10);
            qreal divPhase = getRandomReal(-4, 4);
            qreal params[] = {coeff, divPhase};
            int numParams = 2;
            for (size_t i=0; i<diagMatr.size(); i++) {
                qreal phase = 1;
                for (int r=0; r<numRegs; r++)
                    phase *= regVals[i][r];
                phase = (phase == 0)? divPhase : coeff / phase;
                diagMatr[i][i] = expI(phase);
            }
            setDiagMatrixOverrides(diagMatr, numQubitsPerReg, numRegs, encoding, overrideInds, overridePhases, numOverrides);
            SECTION( "state-vector" ) {
                applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams, overrideInds, overridePhases, numOverrides);
                applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
            }
            SECTION( "density-matrix" ) {
                applyParamNamedPhaseFuncOverrides(quregMatr, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams, overrideInds, overridePhases, numOverrides);
                applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                REQUIRE( areEqual(quregMatr, refMatr, 1E2*REAL_EPS) );
            }
        }
        SECTION( "INVERSE_DISTANCE" ) {
            enum phaseFunc func = INVERSE_DISTANCE;
            qreal divPhase = getRandomReal( -4, 4 );
            qreal params[] = {divPhase};
            int numParams = 1;
            // test only if there are an even number of registers
            if (numRegs%2 == 0) {
                for (size_t i=0; i<diagMatr.size(); i++) {
                    qreal phase = 0;
                    for (int r=0; r<numRegs; r+=2)
                        phase += pow(regVals[i][r+1]-regVals[i][r], 2);
                    phase = (phase == 0.)? divPhase : 1./sqrt(phase);
                    diagMatr[i][i] = expI(phase);
                }
                setDiagMatrixOverrides(diagMatr, numQubitsPerReg, numRegs, encoding, overrideInds, overridePhases, numOverrides);
            }
            SECTION( "state-vector" ) {
                if (numRegs%2 == 0) {
                    applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams, overrideInds, overridePhases, numOverrides);
                    applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                    REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
                }
            }
            SECTION( "density-matrix" ) {
                if (numRegs%2 == 0) {
                    applyParamNamedPhaseFuncOverrides(quregMatr, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams, overrideInds, overridePhases, numOverrides);
                    applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                    REQUIRE( areEqual(quregMatr, refMatr, 1E2*REAL_EPS) );
                }
            }
        }
        SECTION( "SCALED_DISTANCE" ) {
            enum phaseFunc func = SCALED_DISTANCE;
            qreal coeff = getRandomReal( -10, 10 );
            qreal params[] = {coeff};
            int numParams = 1;
            // test only if there are an even number of registers
            if (numRegs%2 == 0) {
                for (size_t i=0; i<diagMatr.size(); i++) {
                    qreal phase = 0;
                    for (int r=0; r<numRegs; r+=2)
                        phase += pow(regVals[i][r+1]-regVals[i][r], 2);
                    phase = coeff * sqrt(phase);
                    diagMatr[i][i] = expI(phase);
                }
                setDiagMatrixOverrides(diagMatr, numQubitsPerReg, numRegs, encoding, overrideInds, overridePhases, numOverrides);
            }
            SECTION( "state-vector" ) {
                if (numRegs%2 == 0) {
                    applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams, overrideInds, overridePhases, numOverrides);
                    applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                    REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
                }
            }
            SECTION( "density-matrix" ) {
                if (numRegs%2 == 0) {
                    applyParamNamedPhaseFuncOverrides(quregMatr, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams, overrideInds, overridePhases, numOverrides);
                    applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                    REQUIRE( areEqual(quregMatr, refMatr, 1E2*REAL_EPS) );
                }
            }
        }
        SECTION( "SCALED_INVERSE_DISTANCE" ) {
            enum phaseFunc func = SCALED_INVERSE_DISTANCE;
            qreal coeff = getRandomReal( -10, 10 );
            qreal divPhase = getRandomReal( -4, 4 );
            qreal params[] = {coeff, divPhase};
            int numParams = 2;
            // test only if there are an even number of registers
            if (numRegs%2 == 0) {
                for (size_t i=0; i<diagMatr.size(); i++) {
                    qreal phase = 0;
                    for (int r=0; r<numRegs; r+=2)
                        phase += pow(regVals[i][r+1]-regVals[i][r], 2);
                    phase = (phase == 0.)? divPhase : coeff/sqrt(phase);
                    diagMatr[i][i] = expI(phase);
                }
                setDiagMatrixOverrides(diagMatr, numQubitsPerReg, numRegs, encoding, overrideInds, overridePhases, numOverrides);
            }
            SECTION( "state-vector" ) {
                if (numRegs%2 == 0) {
                    applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams, overrideInds, overridePhases, numOverrides);
                    applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                    REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
                }
            }
            SECTION( "density-matrix" ) {
                if (numRegs%2 == 0) {
                    applyParamNamedPhaseFuncOverrides(quregMatr, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams, overrideInds, overridePhases, numOverrides);
                    applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                    REQUIRE( areEqual(quregMatr, refMatr, 1E2*REAL_EPS) );
                }
            }
        }
        SECTION( "SCALED_INVERSE_SHIFTED_DISTANCE" ) {
            enum phaseFunc func = SCALED_INVERSE_SHIFTED_DISTANCE;
            int numParams = 2 + numRegs/2;
            VLA(qreal, params, numParams);
            // test only if there are an even number of registers
            if (numRegs%2 == 0) {
                params[0] = getRandomReal( -10, 10 ); // scaling
                params[1] = getRandomReal( -4, 4 ); // divergence override
                for (int r=0; r<numRegs/2; r++)
                    params[2+r] = getRandomReal( -8, 8 ); // shifts
                for (size_t i=0; i<diagMatr.size(); i++) {
                    qreal phase = 0;
                    for (int r=0; r<numRegs; r+=2)
                        phase += pow(regVals[i][r]-regVals[i][r+1]-params[2+r/2], 2);
                    phase = sqrt(phase);
                    phase = (phase <= REAL_EPS)? params[1] : params[0]/phase;
                    diagMatr[i][i] = expI(phase);
                }
                setDiagMatrixOverrides(diagMatr, numQubitsPerReg, numRegs, encoding, overrideInds, overridePhases, numOverrides);
            }
            SECTION( "state-vector" ) {
                if (numRegs%2 == 0) {
                    applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams, overrideInds, overridePhases, numOverrides);
                    applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                    REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
                }
            }
            SECTION( "density-matrix" ) {
                if (numRegs%2 == 0) {
                    applyParamNamedPhaseFuncOverrides(quregMatr, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams, overrideInds, overridePhases, numOverrides);
                    applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                    REQUIRE( areEqual(quregMatr, refMatr, 1E2*REAL_EPS) );
                }
            }
        }
        SECTION( "SCALED_INVERSE_SHIFTED_WEIGHTED_DISTANCE" ) {
            enum phaseFunc func = SCALED_INVERSE_SHIFTED_WEIGHTED_DISTANCE;
            int numParams = 2 + numRegs;
            VLA(qreal, params, numParams);
            // test only if there are an even number of registers
            if (numRegs%2 == 0) {
                params[0] = getRandomReal( -10, 10 ); // scaling
                params[1] = getRandomReal( -4, 4 ); // divergence override
                for (int r=0; r<numRegs; r+=2) {
                    params[2+r] = getRandomReal( -10, 10 ); // factor
                    params[2+r+1] = getRandomReal( -8, 8 ); // shift
                }
                for (size_t i=0; i<diagMatr.size(); i++) {
                    qreal phase = 0;
                    for (int r=0; r<numRegs; r+=2)
                        phase += params[2+r] * pow(regVals[i][r]-regVals[i][r+1]-params[2+r+1], 2);
                    if (phase < 0)
                        phase = 0;
                    phase = sqrt(phase);
                    phase = (phase <= REAL_EPS)? params[1] : params[0]/phase;
                    diagMatr[i][i] = expI(phase);
                }
                setDiagMatrixOverrides(diagMatr, numQubitsPerReg, numRegs, encoding, overrideInds, overridePhases, numOverrides);
            }
            SECTION( "state-vector" ) {
                if (numRegs%2 == 0) {
                    applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams, overrideInds, overridePhases, numOverrides);
                    applyReferenceOp(refVec, regs, totalNumQubits, diagMatr);
                    REQUIRE( areEqual(quregVec, refVec, 1E2*REAL_EPS) );
                }
            }
            SECTION( "density-matrix" ) {
                if (numRegs%2 == 0) {
                    applyParamNamedPhaseFuncOverrides(quregMatr, regs, numQubitsPerReg, numRegs, encoding, func, params, numParams, overrideInds, overridePhases, numOverrides);
                    applyReferenceOp(refMatr, regs, totalNumQubits, diagMatr);
                    REQUIRE( areEqual(quregMatr, refMatr, 1E4*REAL_EPS) );
                }
            }
        }
    }
    SECTION( "input validation" ) {
        int numRegs = 2;
        int numQubitsPerReg[] = {2,3};
        int regs[] = {0,1,2,3,4};
        SECTION( "number of registers" ) {
            numRegs = GENERATE_COPY( -1, 0, 1+MAX_NUM_REGS_APPLY_ARBITRARY_PHASE );
            REQUIRE_THROWS_WITH( applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, NORM, NULL, 0, NULL, NULL, 0), Contains("Invalid number of qubit subregisters") );
        }
        SECTION( "number of qubits" ) {
            numQubitsPerReg[GENERATE_COPY(range(0,numRegs))] = GENERATE( -1, 0, 1+NUM_QUBITS );
            REQUIRE_THROWS_WITH( applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, NORM, NULL, 0, NULL, NULL, 0), Contains("Invalid number of qubits") );
        }
        SECTION( "repetition of qubits" ) {
            regs[GENERATE(2,3,4)] = regs[1];
            REQUIRE_THROWS_WITH( applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, NORM, NULL, 0, NULL, NULL, 0), Contains("The qubits must be unique") );
        }
        SECTION( "qubit indices" ) {
            regs[GENERATE(range(0,NUM_QUBITS))] = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, NORM, NULL, 0, NULL, NULL, 0), Contains("Invalid qubit index") );
        }
        SECTION( "bit encoding name" ) {
            enum bitEncoding enc = (enum bitEncoding) GENERATE( -1, 2 );
            REQUIRE_THROWS_WITH( applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, enc, NORM, NULL, 0, NULL, NULL, 0), Contains("Invalid bit encoding") );
        }
        SECTION( "two's complement register" ) {
            numQubitsPerReg[GENERATE_COPY(range(0,numRegs))] = 1;
            REQUIRE_THROWS_WITH( applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, TWOS_COMPLEMENT, NORM, NULL, 0, NULL, NULL, 0), Contains("A sub-register contained too few qubits to employ TWOS_COMPLEMENT encoding") );
        }
        SECTION( "phase function name" ) {
            enum phaseFunc func = (enum phaseFunc) GENERATE( -1, MAX_INDEX_PHASE_FUNC + 1 );
            REQUIRE_THROWS_WITH( applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, func, NULL, 0, NULL, NULL, 0), Contains("Invalid named phase function") );
        }
        SECTION( "phase function parameters" ) {
            VLA(qreal, params, numRegs + 3);
            for (int r=0; r<numRegs + 3; r++)
                params[r] = 0;
            SECTION( "no parameter functions" ) {
                enum phaseFunc func = GENERATE( NORM, PRODUCT, DISTANCE  );
                int numParams = GENERATE( -1, 1, 2 );
                REQUIRE_THROWS_WITH( applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, func, params, numParams, NULL, NULL, 0), Contains("Invalid number of parameters") );
            }
            SECTION( "single parameter functions" ) {
                enum phaseFunc func = GENERATE( SCALED_NORM, INVERSE_NORM, SCALED_PRODUCT, INVERSE_PRODUCT, SCALED_DISTANCE, INVERSE_DISTANCE );
                int numParams = GENERATE( -1, 0, 2 );
                REQUIRE_THROWS_WITH( applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, func, params, numParams, NULL, NULL, 0), Contains("Invalid number of parameters") );
            }
            SECTION( "two parameter functions" ) {
                enum phaseFunc func = GENERATE( SCALED_INVERSE_NORM, SCALED_INVERSE_PRODUCT, SCALED_INVERSE_DISTANCE );
                int numParams = GENERATE( 0, 1, 3 );
                REQUIRE_THROWS_WITH( applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, func, params, numParams, NULL, NULL, 0), Contains("Invalid number of parameters") );
            }
            SECTION( "shifted distance" ) {
                if (numRegs%2 == 0) {
                    enum phaseFunc func = SCALED_INVERSE_SHIFTED_DISTANCE;
                    int numParams = GENERATE_COPY( 0, 1, numRegs/2 - 1, numRegs/2, numRegs/2 + 1, numRegs/2 + 3 );
                    REQUIRE_THROWS_WITH( applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, func, params, numParams, NULL, NULL, 0), Contains("Invalid number of parameters") );
                }
            }
            SECTION( "shifted weighted distance" ) {
                if (numRegs%2 == 0) {
                    enum phaseFunc func = SCALED_INVERSE_SHIFTED_WEIGHTED_DISTANCE;
                    int numParams = GENERATE_COPY( 0, 1, 2 + numRegs - 1, 2 + numRegs + 1 );
                    REQUIRE_THROWS_WITH( applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, func, params, numParams, NULL, NULL, 0), Contains("Invalid number of parameters") );
                }
            }
            SECTION( "shifted norm" ) {
                enum phaseFunc func = SCALED_INVERSE_SHIFTED_NORM;
                int numParams = GENERATE_COPY( 0, 1, numRegs-1, numRegs, numRegs+1, numRegs+3 );
                REQUIRE_THROWS_WITH( applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, func, params, numParams, NULL, NULL, 0), Contains("Invalid number of parameters") );
            }
        }
        SECTION( "distance pair registers" ) {
            int numQb[] = {1,1,1,1,1};
            int qb[] = {0,1,2,3,4};
            numRegs = GENERATE( 1, 3, 5 );
            REQUIRE_THROWS_WITH( applyParamNamedPhaseFuncOverrides(quregVec, qb, numQb, numRegs, UNSIGNED, DISTANCE, NULL, 0, NULL, NULL, 0), Contains("Phase functions DISTANCE") && Contains("even number of sub-registers") );
        }
        SECTION( "number of overrides" ) {
            int numOverrides = -1;
            REQUIRE_THROWS_WITH( applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, UNSIGNED, NORM, NULL, 0, NULL, NULL, numOverrides), Contains("Invalid number of phase function overrides specified") );
        }
        SECTION( "override indices" ) {
            // numQubitsPerReg = {2, 3}
            int numOverrides = 3;
            long long int overrideInds[] = {0,0, 0,0, 0,0}; // repetition not checked
            qreal overridePhases[]       = {.1,  .1,  .1};
            // first element of overrideInds coordinate is a 2 qubit register
            enum bitEncoding enc = UNSIGNED;
            int badInd = GENERATE(0, 2, 4);
            overrideInds[badInd] = GENERATE( -1, (1<<2) );
            REQUIRE_THROWS_WITH( applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, enc, NORM, NULL, 0, overrideInds, overridePhases, numOverrides), Contains("Invalid phase function override index, in the UNSIGNED encoding") );
            overrideInds[badInd] = 0;
            // second element of overrideInds coordinate is a 3 qubit register
            badInd += 1;
            overrideInds[badInd] = GENERATE( -1, (1<<3) );
            REQUIRE_THROWS_WITH( applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, enc, NORM, NULL, 0, overrideInds, overridePhases, numOverrides), Contains("Invalid phase function override index, in the UNSIGNED encoding") );
            overrideInds[badInd] = 0;
            badInd -= 1;
            enc = TWOS_COMPLEMENT;
            int minInd = -(1<<(numQubitsPerReg[0]-1));
            int maxInd = (1<<(numQubitsPerReg[0]-1)) - 1;
            overrideInds[badInd] = GENERATE_COPY( minInd-1, maxInd+1 );
            REQUIRE_THROWS_WITH( applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, enc, NORM, NULL, 0, overrideInds, overridePhases, numOverrides), Contains("Invalid phase function override index, in the TWOS_COMPLEMENT encoding") );
            overrideInds[badInd] = 0;
            badInd++;
            minInd = -(1<<(numQubitsPerReg[1]-1));
            maxInd = (1<<(numQubitsPerReg[1]-1)) -1;
            overrideInds[badInd] = GENERATE_COPY( minInd-1, maxInd+1 );
            REQUIRE_THROWS_WITH( applyParamNamedPhaseFuncOverrides(quregVec, regs, numQubitsPerReg, numRegs, enc, NORM, NULL, 0, overrideInds, overridePhases, numOverrides), Contains("Invalid phase function override index, in the TWOS_COMPLEMENT encoding") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyParamNamedPhaseFuncOverrides(), applyReferenceOp(), areEqual(), CLEANUP_TEST, DISTANCE, expI(), getRandomInt(), getRandomReal(), getTwosComplement(), getZeroMatrix(), INVERSE_DISTANCE, INVERSE_NORM, INVERSE_PRODUCT, MAX_INDEX_PHASE_FUNC, MAX_NUM_REGS_APPLY_ARBITRARY_PHASE, NORM, NUM_QUBITS, PREPARE_TEST, PRODUCT, qreal, SCALED_DISTANCE, SCALED_INVERSE_DISTANCE, SCALED_INVERSE_NORM, SCALED_INVERSE_PRODUCT, SCALED_INVERSE_SHIFTED_DISTANCE, SCALED_INVERSE_SHIFTED_NORM, SCALED_INVERSE_SHIFTED_WEIGHTED_DISTANCE, SCALED_NORM, SCALED_PRODUCT, setDiagMatrixOverrides(), setRandomTargets(), TWOS_COMPLEMENT, UNSIGNED, and VLA.
TEST_CASE() [16/136]
TEST_CASE ("applyPauliHamil" , "" [operators])
See also
applyPauliHamil
Author
Tyson Jones
Definition at line 3164 of file test_operators.cpp.
{
    Qureg vecIn = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg vecOut = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg matIn = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    Qureg matOut = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    initDebugState(vecIn);
    initDebugState(matIn);
    SECTION( "correctness" ) {
        /* it's too expensive to try every possible Pauli configuration, so
         * we'll try 10 random codes, and for each, random coefficients
         */
        GENERATE( range(0,10) );
        int numTerms = GENERATE( 1, 2, 10, 15 );
        PauliHamil hamil = createPauliHamil(NUM_QUBITS, numTerms);
        setRandomPauliSum(hamil);
        QMatrix refHamil = toQMatrix(hamil);
        SECTION( "state-vector" ) {
            QVector vecRef = toQVector(vecIn);
            applyPauliHamil(vecIn, hamil, vecOut);
            // ensure vecIn barely changes under precision
            REQUIRE( areEqual(vecIn, vecRef) );
            // ensure vecOut changed correctly
            REQUIRE( areEqual(vecOut, refHamil * vecRef) );
        }
        SECTION( "density-matrix" ) {
            QMatrix matRef = toQMatrix(matIn);
            applyPauliHamil(matIn, hamil, matOut);
            // ensure matIn barely changes under precision
            REQUIRE( areEqual(matIn, matRef) );
            // ensure matOut changed correctly
            REQUIRE( areEqual(matOut, refHamil * matRef, 1E2*REAL_EPS) );
        }
        destroyPauliHamil(hamil);
    }
    SECTION( "input validation" ) {
        SECTION( "pauli codes" ) {
            int numTerms = 3;
            PauliHamil hamil = createPauliHamil(NUM_QUBITS, numTerms);
            // make one pauli code wrong
            hamil.pauliCodes[GENERATE_COPY( range(0,numTerms*NUM_QUBITS) )] = (pauliOpType) GENERATE( -1, 4 );
            REQUIRE_THROWS_WITH( applyPauliHamil(vecIn, hamil, vecOut), Contains("Invalid Pauli code") );
            destroyPauliHamil(hamil);
        }
        SECTION( "qureg dimensions" ) {
            Qureg badVec = createQureg(NUM_QUBITS+1, QUEST_ENV);
            PauliHamil hamil = createPauliHamil(NUM_QUBITS, 1);
            REQUIRE_THROWS_WITH( applyPauliHamil(vecIn, hamil, badVec), Contains("Dimensions of the qubit registers don't match") );
            destroyQureg(badVec, QUEST_ENV);
            destroyPauliHamil(hamil);
        }
        SECTION( "qureg types" ) {
            PauliHamil hamil = createPauliHamil(NUM_QUBITS, 1);
            REQUIRE_THROWS_WITH( applyPauliHamil(vecIn, hamil, matOut), Contains("Registers must both be state-vectors or both be density matrices") );
            destroyPauliHamil(hamil);
        }
        SECTION( "matching hamiltonian qubits" ) {
            PauliHamil hamil = createPauliHamil(NUM_QUBITS + 1, 1);
            REQUIRE_THROWS_WITH( applyPauliHamil(vecIn, hamil, vecOut), Contains("same number of qubits") );
            REQUIRE_THROWS_WITH( applyPauliHamil(matIn, hamil, matOut), Contains("same number of qubits") );
            destroyPauliHamil(hamil);
        }
    }
    destroyQureg(vecIn, QUEST_ENV);
    destroyQureg(vecOut, QUEST_ENV);
    destroyQureg(matIn, QUEST_ENV);
    destroyQureg(matOut, QUEST_ENV);
}
References applyPauliHamil(), areEqual(), createDensityQureg(), createPauliHamil(), createQureg(), destroyPauliHamil(), destroyQureg(), initDebugState(), NUM_QUBITS, PauliHamil::pauliCodes, QUEST_ENV, setRandomPauliSum(), toQMatrix(), and toQVector().
TEST_CASE() [17/136]
TEST_CASE ("applyPauliSum" , "" [operators])
See also
applyPauliSum
Author
Tyson Jones
Definition at line 3264 of file test_operators.cpp.
{
    Qureg vecIn = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg vecOut = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg matIn = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    Qureg matOut = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    initDebugState(vecIn);
    initDebugState(matIn);
    SECTION( "correctness" ) {
        /* it's too expensive to try ALL Pauli sequences, via
         *      pauliOpType* paulis = GENERATE_COPY( pauliseqs(numPaulis) );.
         * Furthermore, take(10, pauliseqs(numTargs)) will try the same pauli codes.
         * Hence, we instead opt to repeatedly randomly generate pauliseqs
         */
        GENERATE( range(0,10) ); // gen 10 random pauli-codes
        int numTerms = GENERATE( 1, 2, 10, 15);
        int numPaulis = numTerms * NUM_QUBITS;
        // each test will use random coefficients
        VLA(qreal, coeffs, numTerms);
        VLA(pauliOpType, paulis, numPaulis);
        setRandomPauliSum(coeffs, paulis, NUM_QUBITS, numTerms);
        QMatrix pauliSum = toQMatrix(coeffs, paulis, NUM_QUBITS, numTerms);
        SECTION( "state-vector" ) {
            QVector vecRef = toQVector(vecIn);
            applyPauliSum(vecIn, paulis, coeffs, numTerms, vecOut);
            // ensure vecIn barely changes under precision
            REQUIRE( areEqual(vecIn, vecRef) );
            // ensure vecOut changed correctly
            REQUIRE( areEqual(vecOut, pauliSum * vecRef) );
        }
        SECTION( "density-matrix" ) {
            QMatrix matRef = toQMatrix(matIn);
            applyPauliSum(matIn, paulis, coeffs, numTerms, matOut);
            // ensure matIn barely changes under precision
            REQUIRE( areEqual(matIn, matRef) );
            // ensure matOut changed correctly
            REQUIRE( areEqual(matOut, pauliSum * matRef, 1E2*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "number of terms" ) {
            int numTerms = GENERATE( -1, 0 );
            REQUIRE_THROWS_WITH( applyPauliSum(vecIn, NULL, NULL, numTerms, vecOut), Contains("Invalid number of terms") );
        }
        SECTION( "pauli codes" ) {
            // valid codes
            int numTerms = 3;
            int numPaulis = numTerms*NUM_QUBITS;
            VLA(pauliOpType, paulis, numPaulis);
            for (int i=0; i<numPaulis; i++)
                paulis[i] = PAULI_I;
            // make one invalid
            paulis[GENERATE_COPY( range(0,numPaulis) )] = (pauliOpType) GENERATE( -1, 4 );
            REQUIRE_THROWS_WITH( applyPauliSum(vecIn, paulis, NULL, numTerms, vecOut), Contains("Invalid Pauli code") );
        }
        SECTION( "qureg dimensions" ) {
            Qureg badVec = createQureg(NUM_QUBITS+1, QUEST_ENV);
            pauliOpType paulis[NUM_QUBITS];
            REQUIRE_THROWS_WITH( applyPauliSum(vecIn, paulis, NULL, 1, badVec), Contains("Dimensions of the qubit registers don't match") );
            destroyQureg(badVec, QUEST_ENV);
        }
        SECTION( "qureg types" ) {
            pauliOpType paulis[NUM_QUBITS];
            REQUIRE_THROWS_WITH( applyPauliSum(vecIn, paulis, NULL, 1, matOut), Contains("Registers must both be state-vectors or both be density matrices") );
        }
    }
    destroyQureg(vecIn, QUEST_ENV);
    destroyQureg(vecOut, QUEST_ENV);
    destroyQureg(matIn, QUEST_ENV);
    destroyQureg(matOut, QUEST_ENV);
}
References applyPauliSum(), areEqual(), createDensityQureg(), createQureg(), destroyQureg(), initDebugState(), NUM_QUBITS, PAULI_I, qreal, QUEST_ENV, setRandomPauliSum(), toQMatrix(), toQVector(), and VLA.
TEST_CASE() [18/136]
TEST_CASE ("applyPhaseFunc" , "" [operators])
See also
applyPhaseFunc
Author
Tyson Jones
Definition at line 3360 of file test_operators.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    SECTION( "correctness" ) {
        // try every kind of binary encodings
        enum bitEncoding encoding = GENERATE( UNSIGNED,TWOS_COMPLEMENT );
        // try every sub-register size
        int numQubits = GENERATE_COPY( range(1,NUM_QUBITS+1) );
        // force at least 2 qubits in two's compement though
        if (encoding == TWOS_COMPLEMENT && numQubits == 1)
            numQubits++;
        // try every possible sub-register
        int* qubits = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numQubits) );
        // choose a random number of terms in the phase function
        int numTerms = getRandomInt(1, 5);
        // populate the phase function with random but POSITIVE-power terms,
        // and in two's complement mode, strictly integer powers
        VLA(qreal, coeffs, numTerms);
        VLA(qreal, expons, numTerms);
        for (int t=0; t<numTerms; t++) {
            coeffs[t] = getRandomReal(-10,10);
            if (encoding == TWOS_COMPLEMENT)
                expons[t] = getRandomInt(0, 3+1);  // repetition of power is ok
            else
                expons[t] = getRandomReal(0, 3);
        }
        // build a reference diagonal matrix, on the reduced Hilbert space
        QMatrix matr = getZeroMatrix( 1 << numQubits );
        for (size_t i=0; i<matr.size(); i++) {
            long long int ind = 0;
            if (encoding == UNSIGNED)
                ind = i;
            if (encoding == TWOS_COMPLEMENT)
                ind = getTwosComplement(i, numQubits);
            qreal phase = 0;
            for (int t=0; t<numTerms; t++)
                phase += coeffs[t] * pow(ind, expons[t]);
            matr[i][i] = expI(phase);
        }
        SECTION( "state-vector" ) {
            applyPhaseFunc(quregVec, qubits, numQubits, encoding, coeffs, expons, numTerms);
            applyReferenceOp(refVec, qubits, numQubits, matr);
            REQUIRE( areEqual(quregVec, refVec, 1E4*REAL_EPS) );
        }
        SECTION( "density-matrix" ) {
            applyPhaseFunc(quregMatr, qubits, numQubits, encoding, coeffs, expons, numTerms);
            applyReferenceOp(refMatr, qubits, numQubits, matr);
            REQUIRE( areEqual(quregMatr, refMatr, 1E6*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        int numQubits = 3;
        int qubits[] = {0,1,2};
        SECTION( "number of qubits" ) {
            numQubits = GENERATE_COPY( -1, 0, NUM_QUBITS+1 );
            REQUIRE_THROWS_WITH( applyPhaseFunc(quregVec, NULL, numQubits, UNSIGNED, NULL, NULL, 1), Contains("Invalid number of qubits") );
        }
        SECTION( "repetition of qubits" ) {
            qubits[GENERATE(1,2)] = qubits[0];
            REQUIRE_THROWS_WITH( applyPhaseFunc(quregVec, qubits, numQubits, UNSIGNED, NULL, NULL, 1), Contains("The qubits must be unique") );
        }
        SECTION( "qubit indices" ) {
            int inv = GENERATE( -1, NUM_QUBITS );
            qubits[ GENERATE_COPY( range(0,numQubits) )] = inv;
            REQUIRE_THROWS_WITH( applyPhaseFunc(quregVec, qubits, numQubits, UNSIGNED, NULL, NULL, 1), Contains("Invalid qubit index") );
        }
        SECTION( "number of terms" ) {
            int numTerms = GENERATE( -1, 0 );
            REQUIRE_THROWS_WITH( applyPhaseFunc(quregVec, qubits, numQubits, UNSIGNED, NULL, NULL, numTerms), Contains("Invalid number of terms in the phase function") );
        }
        SECTION( "bit encoding name" ) {
            enum bitEncoding enc = (enum bitEncoding) GENERATE( -1,2 );
            REQUIRE_THROWS_WITH( applyPhaseFunc(quregVec, qubits, numQubits, enc, NULL, NULL, 1), Contains("Invalid bit encoding") );
        }
        SECTION( "two's complement register" ) {
            numQubits = 1;
            REQUIRE_THROWS_WITH( applyPhaseFunc(quregVec, qubits, numQubits, TWOS_COMPLEMENT, NULL, NULL, 1), Contains("too few qubits to employ TWOS_COMPLEMENT") );
        }
        SECTION( "fractional exponent" ) {
            int numTerms = 3;
            qreal coeffs[] = {0,0,0};
            qreal expos[] = {1,2,3};
            expos[GENERATE_COPY( range(0,numTerms) )] = GENERATE( 0.5, 1.999, 5.0001 );
            REQUIRE_THROWS_WITH( applyPhaseFunc(quregVec, qubits, numQubits, TWOS_COMPLEMENT, coeffs, expos, numTerms), Contains("fractional exponent") && Contains("TWOS_COMPLEMENT") && Contains("negative indices were not overriden") );
        }
        SECTION( "negative exponent" ) {
            int numTerms = 3;
            qreal coeffs[] = {0,0,0};
            qreal expos[] = {1,2,3};
            expos[GENERATE_COPY( range(0,numTerms) )] = GENERATE( -1, -2, -1.5 );
            enum bitEncoding encoding = GENERATE( UNSIGNED, TWOS_COMPLEMENT );
            REQUIRE_THROWS_WITH( applyPhaseFunc(quregVec, qubits, numQubits, encoding, coeffs, expos, numTerms), Contains("The phase function contained a negative exponent which would diverge at zero, but the zero index was not overriden") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyPhaseFunc(), applyReferenceOp(), areEqual(), CLEANUP_TEST, expI(), getRandomInt(), getRandomReal(), getTwosComplement(), getZeroMatrix(), NUM_QUBITS, PREPARE_TEST, qreal, sublists(), TWOS_COMPLEMENT, UNSIGNED, and VLA.
TEST_CASE() [19/136]
TEST_CASE ("applyPhaseFuncOverrides" , "" [operators])
See also
applyPhaseFuncOverrides
Author
Tyson Jones
Definition at line 3490 of file test_operators.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    SECTION( "correctness" ) {
        // try every kind of binary encodings
        enum bitEncoding encoding = GENERATE( UNSIGNED,TWOS_COMPLEMENT );
        // try every sub-register size
        int numQubits = GENERATE_COPY( range(1,NUM_QUBITS+1) );
        // force at least 2 qubits in two's compement though
        if (encoding == TWOS_COMPLEMENT && numQubits == 1)
            numQubits++;
        // try every possible sub-register
        int* qubits = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numQubits) );
        // choose a random number of terms in the phase function
        int numTerms = getRandomInt(1, 21);
        // populate the phase function with random powers.
        // this includes negative powers, so we must always override 0.
        // in two's complement, we must use only integer powers
        VLA(qreal, coeffs, numTerms);
        VLA(qreal, expons, numTerms);
        for (int t=0; t<numTerms; t++) {
            coeffs[t] = getRandomReal(-10,10);
            if (encoding == TWOS_COMPLEMENT)
                expons[t] = getRandomInt(-3, 3+1); // note we COULD do getRandomReal(), and override all negatives
            else
                expons[t] = getRandomReal(-3, 3);
        }
        // choose a random number of overrides (even overriding every amplitude)
        int numOverrides = getRandomInt(1, (1<<numQubits) + 1);
        // randomise each override index (uniqueness isn't checked)
        VLA(long long int, overrideInds, numOverrides);
        overrideInds[0] = 0LL;
        for (int i=1; i<numOverrides; i++)
            if (encoding == UNSIGNED)
                overrideInds[i] = getRandomInt(0, 1<<numQubits);
            else if (encoding == TWOS_COMPLEMENT)
                overrideInds[i] = getRandomInt(-(1<<(numQubits-1)), (1<<(numQubits-1))-1);
        // override to a random phase
        VLA(qreal, overridePhases, numOverrides);
        for (int i=0; i<numOverrides; i++)
            overridePhases[i] = getRandomReal(-4, 4); // periodic in [-pi, pi]
        // build a reference diagonal matrix, on the reduced Hilbert space
        QMatrix matr = getZeroMatrix( 1 << numQubits );
        for (size_t i=0; i<matr.size(); i++) {
            long long int ind = 0;
            if (encoding == UNSIGNED)
                ind = i;
            if (encoding == TWOS_COMPLEMENT)
                ind = getTwosComplement(i, numQubits);
            // reference diagonal matrix incorporates overriden phases
            qreal phase;
            bool overriden = false;
            for (int v=0; v<numOverrides; v++) {
                if (ind == overrideInds[v]) {
                    phase = overridePhases[v];
                    overriden = true;
                    break;
                }
            }
            if (!overriden) {
                phase = 0;
                for (int t=0; t<numTerms; t++)
                    phase += coeffs[t] * pow(ind, expons[t]);
            }
            matr[i][i] = expI(phase);
        }
        SECTION( "state-vector" ) {
            applyPhaseFuncOverrides(quregVec, qubits, numQubits, encoding, coeffs, expons, numTerms, overrideInds, overridePhases, numOverrides);
            applyReferenceOp(refVec, qubits, numQubits, matr);
            REQUIRE( areEqual(quregVec, refVec, 1E4*REAL_EPS) );
        }
        SECTION( "density-matrix" ) {
            applyPhaseFuncOverrides(quregMatr, qubits, numQubits, encoding, coeffs, expons, numTerms, overrideInds, overridePhases, numOverrides);
            applyReferenceOp(refMatr, qubits, numQubits, matr);
            REQUIRE( areEqual(quregMatr, refMatr, 1E6*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        int numQubits = 3;
        int qubits[] = {0,1,2};
        SECTION( "number of qubits" ) {
            int numQubits = GENERATE_COPY( -1, 0, NUM_QUBITS+1 );
            REQUIRE_THROWS_WITH( applyPhaseFuncOverrides(quregVec, NULL, numQubits, UNSIGNED, NULL, NULL, 1, NULL, NULL, 0), Contains("Invalid number of qubits") );
        }
        SECTION( "repetition qubits" ) {
            qubits[GENERATE(1,2)] = qubits[0];
            REQUIRE_THROWS_WITH( applyPhaseFuncOverrides(quregVec, qubits, numQubits, UNSIGNED, NULL, NULL, 1, NULL, NULL, 0), Contains("The qubits must be unique") );
        }
        SECTION( "qubit indices" ) {
            int inv = GENERATE( -1, NUM_QUBITS );
            qubits[ GENERATE_COPY( range(0,numQubits) )] = inv;
            REQUIRE_THROWS_WITH( applyPhaseFuncOverrides(quregVec, qubits, numQubits, UNSIGNED, NULL, NULL, 1, NULL, NULL, 0), Contains("Invalid qubit index") );
        }
        SECTION( "number of terms" ) {
            int numTerms = GENERATE( -1, 0 );
            REQUIRE_THROWS_WITH( applyPhaseFuncOverrides(quregVec, qubits, numQubits, UNSIGNED, NULL, NULL, numTerms, NULL, NULL, 0), Contains("Invalid number of terms in the phase function") );
        }
        SECTION( "bit encoding name" ) {
            enum bitEncoding enc = (enum bitEncoding) GENERATE( -1,2 );
            REQUIRE_THROWS_WITH( applyPhaseFuncOverrides(quregVec, qubits, numQubits, enc, NULL, NULL, 1, NULL, NULL, 0), Contains("Invalid bit encoding") );
        }
        SECTION( "two's complement register" ) {
            numQubits = 1;
            REQUIRE_THROWS_WITH( applyPhaseFuncOverrides(quregVec, qubits, numQubits, TWOS_COMPLEMENT, NULL, NULL, 1, NULL, NULL, 0), Contains("too few qubits to employ TWOS_COMPLEMENT") );
        }
        SECTION( "number of overrides" ) {
            qreal dummyTerms[] = {0};
            int numOverrides = GENERATE_COPY( -1, 1 + (1<<numQubits) );
            REQUIRE_THROWS_WITH( applyPhaseFuncOverrides(quregVec, qubits, numQubits, UNSIGNED, dummyTerms, dummyTerms, 1, NULL, NULL, numOverrides), Contains("Invalid number of phase function overrides") );
        }
        SECTION( "override indices" ) {
            int numOverrides = 3;
            long long int overrideInds[] = {0,1,2};
            qreal overridePhases[] = {.1,.1,.1};
            qreal dummyTerms[] = {0};
            enum bitEncoding encoding = UNSIGNED;
            overrideInds[GENERATE(0,1,2)] = GENERATE_COPY( -1, (1<<numQubits) );
            REQUIRE_THROWS_WITH( applyPhaseFuncOverrides(quregVec, qubits, numQubits, encoding, dummyTerms, dummyTerms, 1, overrideInds, overridePhases, numOverrides), Contains("Invalid phase function override index, in the UNSIGNED encoding") );
            encoding = TWOS_COMPLEMENT;
            long long int newInds[] = {0,1,2};
            int minInd = -(1<<(numQubits-1));
            int maxInd = (1<<(numQubits-1)) -1;
            newInds[GENERATE(0,1,2)] = GENERATE_COPY( minInd-1, maxInd+1 );
            REQUIRE_THROWS_WITH( applyPhaseFuncOverrides(quregVec, qubits, numQubits, encoding, dummyTerms, dummyTerms, 1, newInds, overridePhases, numOverrides), Contains("Invalid phase function override index, in the TWOS_COMPLEMENT encoding") );
        }
        SECTION( "fractional exponent" ) {
            int numTerms = 3;
            qreal coeffs[] = {0,0,0};
            qreal expos[] = {1,2,3};
            // make one exponent fractional, thereby requiring negative overrides
            expos[GENERATE_COPY( range(0,numTerms) )] = GENERATE( 0.5, 1.999, 5.0001 );
            // catch when no negative indices are overridden
            REQUIRE_THROWS_WITH( applyPhaseFuncOverrides(quregVec, qubits, numQubits, TWOS_COMPLEMENT, coeffs, expos, numTerms, NULL, NULL, 0), Contains("fractional exponent") && Contains("TWOS_COMPLEMENT") && Contains("negative indices were not overriden") );
            int numNegs = 1 << (numQubits-1);
            VLA(long long int, overrideInds, numNegs);
            VLA(qreal, overridePhases, numNegs);
            for (int i=0; i<numNegs; i++) {
                overrideInds[i] = -(i+1);
                overridePhases[i] = 0;
            }
            // ensure no throw when all are overriden
            REQUIRE_NOTHROW( applyPhaseFuncOverrides(quregVec, qubits, numQubits, TWOS_COMPLEMENT, coeffs, expos, numTerms, overrideInds, overridePhases, numNegs) );
            // catch when at least one isn't overriden
            overrideInds[GENERATE_COPY( range(0,numNegs) )] = 0; // override a non-negative
            REQUIRE_THROWS_WITH( applyPhaseFuncOverrides(quregVec, qubits, numQubits, TWOS_COMPLEMENT, coeffs, expos, numTerms, overrideInds, overridePhases, numNegs), Contains("fractional exponent") && Contains("TWOS_COMPLEMENT") && Contains("negative indices were not overriden") );
        }
        SECTION( "negative exponent" ) {
            int numTerms = 3;
            qreal coeffs[] = {0,0,0};
            qreal expos[] = {1,2,3};
            expos[GENERATE_COPY( range(0,numTerms) )] = GENERATE( -1, -2 );
            enum bitEncoding encoding = GENERATE( UNSIGNED, TWOS_COMPLEMENT );
            // test both when giving no overrides, and giving all non-zero overrides
            int numOverrides = GENERATE( 0, 3 );
            long long int overrideInds[] = {1,2,3};
            qreal overridePhases[] = {0,0,0};
            REQUIRE_THROWS_WITH( applyPhaseFuncOverrides(quregVec, qubits, numQubits, encoding, coeffs, expos, numTerms, overrideInds, overridePhases, numOverrides), Contains("The phase function contained a negative exponent which would diverge at zero, but the zero index was not overriden") );
            // but ensure that when the zero IS overriden (anywhere), there's no error
            numOverrides = 3;
            overrideInds[GENERATE_COPY(range(0,numOverrides))] = 0;
            REQUIRE_NOTHROW( applyPhaseFuncOverrides(quregVec, qubits, numQubits, encoding, coeffs, expos, numTerms, overrideInds, overridePhases, numOverrides) );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyPhaseFuncOverrides(), applyReferenceOp(), areEqual(), CLEANUP_TEST, expI(), getRandomInt(), getRandomReal(), getTwosComplement(), getZeroMatrix(), NUM_QUBITS, PREPARE_TEST, qreal, sublists(), TWOS_COMPLEMENT, UNSIGNED, and VLA.
TEST_CASE() [20/136]
TEST_CASE ("applyProjector" , "" [operators])
See also
applyProjector
Author
Tyson Jones
Definition at line 3703 of file test_operators.cpp.
{
    Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        int qubit = GENERATE( range(0,NUM_QUBITS) );
        int outcome = GENERATE( 0, 1 );
        // repeat these random tests 10 times on every qubit, and for both outcomes
        GENERATE( range(0,10) );
        SECTION( "state-vector" ) {
            SECTION( "normalised" ) {
                // use a random L2 state for every qubit & outcome
                QVector vecRef = getRandomStateVector(NUM_QUBITS);
                toQureg(vec, vecRef);
                // zero non-outcome reference amps
                for (size_t ind=0; ind<vecRef.size(); ind++) {
                    int bit = (ind >> qubit) & 1; // target-th bit
                    if (bit != outcome)
                        vecRef[ind] = 0;
                }
                applyProjector(vec, qubit, outcome);
                REQUIRE( areEqual(vec, vecRef) );
            }
            SECTION( "unnormalised" ) {
                // use a random non-physical state for every qubit & outcome
                QVector vecRef = getRandomQVector(1 << NUM_QUBITS);
                toQureg(vec, vecRef);
                // zero non-outcome reference amps
                for (size_t ind=0; ind<vecRef.size(); ind++) {
                    int bit = (ind >> qubit) & 1; // target-th bit
                    if (bit != outcome)
                        vecRef[ind] = 0;
                }
                applyProjector(vec, qubit, outcome);
                REQUIRE( areEqual(vec, vecRef) );
            }
        }
        SECTION( "density-matrix" ) {
            SECTION( "pure" ) {
                QVector vecRef = getRandomStateVector(NUM_QUBITS);
                QMatrix matRef = getPureDensityMatrix(vecRef);
                toQureg(mat, matRef);
                applyProjector(mat, qubit, outcome);
                // zero any amplitudes that aren't |outcome><outcome|
                for (size_t r=0; r<matRef.size(); r++) {
                    for (size_t c=0; c<matRef.size(); c++) {
                        int ketBit = (c >> qubit) & 1;
                        int braBit = (r >> qubit) & 1;
                        if (!(ketBit == outcome && braBit == outcome))
                            matRef[r][c] = 0;
                    }
                }
                REQUIRE( areEqual(mat, matRef) );
            }
            SECTION( "mixed" ) {
                QMatrix matRef = getRandomDensityMatrix(NUM_QUBITS);
                toQureg(mat, matRef);
                applyProjector(mat, qubit, outcome);
                // zero any amplitudes that aren't |outcome><outcome|
                for (size_t r=0; r<matRef.size(); r++) {
                    for (size_t c=0; c<matRef.size(); c++) {
                        int ketBit = (c >> qubit) & 1;
                        int braBit = (r >> qubit) & 1;
                        if (!(ketBit == outcome && braBit == outcome))
                            matRef[r][c] = 0;
                    }
                }
                REQUIRE( areEqual(mat, matRef) );
            }
            SECTION( "unnormalised" ) {
                QMatrix matRef = getRandomQMatrix(1 << NUM_QUBITS);
                toQureg(mat, matRef);
                applyProjector(mat, qubit, outcome);
                // zero any amplitudes that aren't |outcome><outcome|
                for (size_t r=0; r<matRef.size(); r++) {
                    for (size_t c=0; c<matRef.size(); c++) {
                        int ketBit = (c >> qubit) & 1;
                        int braBit = (r >> qubit) & 1;
                        if (!(ketBit == outcome && braBit == outcome))
                            matRef[r][c] = 0;
                    }
                }
                REQUIRE( areEqual(mat, matRef) );
            }
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qubit index" ) {
            int qubit = GENERATE( -1, NUM_QUBITS );
            int outcome = 0;
            REQUIRE_THROWS_WITH( applyProjector(mat, qubit, outcome), Contains("Invalid target qubit") );
        }
        SECTION( "outcome value" ) {
            int qubit = 0;
            int outcome = GENERATE( -1, 2 );
            REQUIRE_THROWS_WITH( applyProjector(mat, qubit, outcome), Contains("Invalid measurement outcome") );
        }
    }
    destroyQureg(vec, QUEST_ENV);
    destroyQureg(mat, QUEST_ENV);
}
References applyProjector(), areEqual(), createDensityQureg(), createQureg(), destroyQureg(), getPureDensityMatrix(), getRandomDensityMatrix(), getRandomQMatrix(), getRandomQVector(), getRandomStateVector(), NUM_QUBITS, QUEST_ENV, and toQureg().
TEST_CASE() [21/136]
TEST_CASE ("applyQFT" , "" [operators])
See also
applyQFT
Author
Tyson Jones
Definition at line 3838 of file test_operators.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    SECTION( "correctness" ) {
        // try every sub-register size
        int numQubits = GENERATE_COPY( range(1,NUM_QUBITS+1) );
        // try every possible sub-register
        int* qubits = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numQubits) );
        SECTION( "state-vector" ) {
            SECTION( "normalised" ) {
                QVector refVec = getRandomStateVector(NUM_QUBITS);
                toQureg(quregVec, refVec);
                applyQFT(quregVec, qubits, numQubits);
                refVec = getDFT(refVec, qubits, numQubits);
                REQUIRE( areEqual(quregVec, refVec) );
            }
            SECTION( "unnormalised" ) {
                QVector refVec = getRandomQVector(1 << NUM_QUBITS);
                toQureg(quregVec, refVec);
                applyQFT(quregVec, qubits, numQubits);
                refVec = getDFT(refVec, qubits, numQubits);
                REQUIRE( areEqual(quregVec, refVec) );
            }
        }
        SECTION( "density-matrix" ) {
            SECTION( "pure" ) {
                /* a pure density matrix should be mapped to a pure state
                 * corresponding to the state-vector DFT
                 */
                refVec = getRandomStateVector(NUM_QUBITS);
                refMatr = getPureDensityMatrix(refVec);
                toQureg(quregMatr, refMatr);
                applyQFT(quregMatr, qubits, numQubits);
                refVec = getDFT(refVec, qubits, numQubits);
                refMatr = getPureDensityMatrix(refVec);
                REQUIRE( areEqual(quregMatr, refMatr) );
            }
            SECTION( "mixed" ) {
                /* a mixed density matrix, conceptualised as a mixture of orthogonal
                 * state-vectors, should be mapped to an equally weighted mixture
                 * of DFTs of each state-vector (because QFT is unitary and hence
                 * maintains state orthogonality)
                 */
                int numStates = (1 << NUM_QUBITS)/4; // a quarter of as many states as are possible
                std::vector<QVector> states = getRandomOrthonormalVectors(NUM_QUBITS, numStates);
                std::vector<qreal> probs = getRandomProbabilities(numStates);
                // set qureg to random mixture of state-vectors
                refMatr = getMixedDensityMatrix(probs, states);
                toQureg(quregMatr, refMatr);
                // apply QFT to mixture
                applyQFT(quregMatr, qubits, numQubits);
                // compute dft of mixture, via dft of each state
                refMatr = getZeroMatrix(1 << NUM_QUBITS);
                for (int i=0; i<numStates; i++) {
                    QVector dft = getDFT(states[i], qubits, numQubits);
                    refMatr += probs[i] * getPureDensityMatrix(dft);
                }
                REQUIRE( areEqual(quregMatr, refMatr) );
            }
            SECTION( "unnormalised" ) {
                /* repeat method above, except that we use unnormalised vectors,
                 * and mix them with arbitrary complex numbers instead of probabilities,
                 * yielding an unnormalised density matrix
                 */
                int numVecs = (1 << NUM_QUBITS)/4; // a quarter of as many states as are possible
                std::vector<QVector> vecs;
                std::vector<qcomp> coeffs;
                for (int i=0; i<numVecs; i++) {
                    vecs.push_back(getRandomQVector(1 << NUM_QUBITS));
                    coeffs.push_back(getRandomComplex());
                }
                // produce unnormalised matrix via random complex sum of random unnormalised vectors
                refMatr = getZeroMatrix(1 << NUM_QUBITS);
                for (int i=0; i<numVecs; i++)
                    refMatr += coeffs[i] * getPureDensityMatrix(vecs[i]);
                toQureg(quregMatr, refMatr);
                applyQFT(quregMatr, qubits, numQubits);
                // compute target matrix via dft of each unnormalised vector
                refMatr = getZeroMatrix(1 << NUM_QUBITS);
                for (int i=0; i<numVecs; i++) {
                    QVector dft = getDFT(vecs[i], qubits, numQubits);
                    refMatr += coeffs[i] * getPureDensityMatrix(dft);
                }
                REQUIRE( areEqual(quregMatr, refMatr) );
            }
        }
    }
    SECTION( "input validation" ) {
        SECTION( "number of targets" ) {
            // there cannot be more targets than qubits in register
            int numQubits = GENERATE( -1, 0, NUM_QUBITS+1 );
            int qubits[NUM_QUBITS+1];
            REQUIRE_THROWS_WITH( applyQFT(quregVec, qubits, numQubits), Contains("Invalid number of target"));
        }
        SECTION( "repetition in targets" ) {
            int numQubits = 3;
            int qubits[] = {1,2,2};
            REQUIRE_THROWS_WITH( applyQFT(quregVec, qubits, numQubits), Contains("target") && Contains("unique"));
        }
        SECTION( "qubit indices" ) {
            int numQubits = 3;
            int qubits[] = {1,2,3};
            int inv = GENERATE( -1, NUM_QUBITS );
            qubits[GENERATE_COPY( range(0,numQubits) )] = inv; // make invalid target
            REQUIRE_THROWS_WITH( applyQFT(quregVec, qubits, numQubits), Contains("Invalid target") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyQFT(), areEqual(), CLEANUP_TEST, getDFT(), getMixedDensityMatrix(), getPureDensityMatrix(), getRandomComplex(), getRandomOrthonormalVectors(), getRandomProbabilities(), getRandomQVector(), getRandomStateVector(), getZeroMatrix(), NUM_QUBITS, PREPARE_TEST, sublists(), and toQureg().
TEST_CASE() [22/136]
TEST_CASE ("applySubDiagonalOp" , "" [unitaries])
See also
applySubDiagonalOp
Author
Tyson Jones
Definition at line 3989 of file test_operators.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    SECTION( "correctness" ) {
        // generate all possible targets
        int numTargs = GENERATE( range(1,NUM_QUBITS+1) );
        int* targs = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numTargs) );
        // initialise a random non-unitary diagonal op
        SubDiagonalOp op = createSubDiagonalOp(numTargs);
        for (long long int i=0; i<op.numElems; i++) {
            op.real[i] = getRandomReal(-10,10);
            op.imag[i] = getRandomReal(-10,10);
        }
        QMatrix opMatr = toQMatrix(op);
        SECTION( "state-vector" ) {
            applySubDiagonalOp(quregVec, targs, numTargs, op);
            applyReferenceMatrix(refVec, targs, numTargs, opMatr);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            applySubDiagonalOp(quregMatr, targs, numTargs, op);
            applyReferenceMatrix(refMatr, targs, numTargs, opMatr);
            REQUIRE( areEqual(quregMatr, refMatr, 100*REAL_EPS) );
        }
        destroySubDiagonalOp(op);
    }
    SECTION( "input validation" ) {
        SECTION( "diagonal dimension" ) {
            int numTargs = 3;
            SubDiagonalOp op = createSubDiagonalOp(numTargs);
            int badNumTargs = GENERATE_COPY( numTargs-1, numTargs+1 );
            int badTargs[NUM_QUBITS+1];
            REQUIRE_THROWS_WITH( applySubDiagonalOp(quregVec, badTargs, badNumTargs, op), Contains("incompatible dimension") );
            destroySubDiagonalOp(op);
        }
        SECTION( "number of targets" ) {
            // make too many targets (which are otherwise valid)
            SubDiagonalOp badOp = createSubDiagonalOp(NUM_QUBITS + 1);
            int targs[NUM_QUBITS + 1];
            for (int t=0; t<badOp.numQubits; t++)
                targs[t] = t;
            for (int i=0; i<badOp.numElems; i++)
                badOp.real[i] = 1;
            REQUIRE_THROWS_WITH( applySubDiagonalOp(quregVec, targs, badOp.numQubits, badOp), Contains("Invalid number of target qubits") );
            destroySubDiagonalOp(badOp);
        }
        SECTION( "repetition in targets" ) {
            // make a valid unitary diagonal op
            SubDiagonalOp op = createSubDiagonalOp(3);
            for (int i=0; i<op.numElems; i++)
                op.real[i] = 1;
            // make a repetition in the target list
            int targs[] = {2,1,2};
            REQUIRE_THROWS_WITH( applySubDiagonalOp(quregVec, targs, op.numQubits, op), Contains("target qubits must be unique") );
            destroySubDiagonalOp(op);
        }
        SECTION( "qubit indices" ) {
            // make a valid unitary diagonal op
            SubDiagonalOp op = createSubDiagonalOp(3);
            for (int i=0; i<op.numElems; i++)
                op.real[i] = 1;
            int targs[] = {0,1,2};
            // make each target in-turn invalid
            int badIndex = GENERATE( range(0,3) );
            int badValue = GENERATE( -1, NUM_QUBITS );
            targs[badIndex] = badValue;
            REQUIRE_THROWS_WITH( applySubDiagonalOp(quregVec, targs, op.numQubits, op), Contains("Invalid target qubit") );
            destroySubDiagonalOp(op);
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceMatrix(), applySubDiagonalOp(), areEqual(), createSubDiagonalOp(), destroySubDiagonalOp(), getRandomReal(), SubDiagonalOp::imag, NUM_QUBITS, SubDiagonalOp::numElems, SubDiagonalOp::numQubits, PREPARE_TEST, SubDiagonalOp::real, sublists(), and toQMatrix().
TEST_CASE() [23/136]
TEST_CASE ("applyTrotterCircuit" , "" [operators])
See also
applyTrotterCircuit
Author
Tyson Jones
Definition at line 4088 of file test_operators.cpp.
{
    Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    initDebugState(vec);
    initDebugState(mat);
    Qureg vecRef = createCloneQureg(vec, QUEST_ENV);
    Qureg matRef = createCloneQureg(mat, QUEST_ENV);
    SECTION( "correctness" ) {
        SECTION( "one term" ) {
            // a Hamiltonian with one term has an exact (trivial) Trotterisation
            PauliHamil hamil = createPauliHamil(NUM_QUBITS, 1);
            // H = coeff X Y Z (on qubits 0,1,2)
            qreal coeff = getRandomReal(-5, 5);
            int numTargs = 3;
            int targs[] =  {0, 1, 2};
            pauliOpType codes[] = {PAULI_X, PAULI_Y, PAULI_Z};
            hamil.termCoeffs[0] = coeff;
            for (int i=0; i<numTargs; i++)
                hamil.pauliCodes[targs[i]] = codes[i];
            // time can be negative
            qreal time = getRandomReal(-2,2);
            // by commutation, all reps & orders yield the same total unitary
            int reps = GENERATE( range(1,5) );
            // applyTrotter(t, 1, 1) = exp(-i t coeff paulis)
            // multiRotatePauli(a) = exp(- i a / 2 paulis)
            SECTION( "state-vector" ) {
                int order = GENERATE( 1, 2, 4 );
                applyTrotterCircuit(vec, hamil, time, order, reps);
                multiRotatePauli(vecRef, targs, codes, numTargs, 2*time*coeff);
                REQUIRE( areEqual(vec, vecRef, 10*REAL_EPS) );
            }
            SECTION( "density-matrix" ) {
                int order = GENERATE( 1, 2 ); // precision bites density-matrices quickly
                applyTrotterCircuit(mat, hamil, time, order, reps);
                multiRotatePauli(matRef, targs, codes, numTargs, 2*time*coeff);
                REQUIRE( areEqual(mat, matRef, 1E2*REAL_EPS) );
            }
            destroyPauliHamil(hamil);
        }
        SECTION( "commuting terms" ) {
            // a Hamiltonian of commuting terms, Trotterises exactly
            PauliHamil hamil = createPauliHamil(NUM_QUBITS, 2);
            // H = c0 X Y I + c1 X I Z (on qubits 0,1,2)
            int targs[] = {0, 1, 2};
            hamil.pauliCodes[0] = PAULI_X;
            hamil.pauliCodes[0 + NUM_QUBITS] = PAULI_X;
            hamil.pauliCodes[1] = PAULI_Y;
            hamil.pauliCodes[1 + NUM_QUBITS] = PAULI_I;
            hamil.pauliCodes[2] = PAULI_I;
            hamil.pauliCodes[2 + NUM_QUBITS] = PAULI_Z;
            for (int i=0; i<hamil.numSumTerms; i++)
                hamil.termCoeffs[i] = getRandomReal(-5,5);
            // time can be negative
            qreal time = getRandomReal(-2,2);
            // applyTrotter(t, 1, 1) = exp(-i t c0 paulis0) exp(-i t c1 paulis1)
            // multiRotatePauli(a) = exp(- i a / 2 paulis)
            SECTION( "state-vector" ) {
                int reps = GENERATE( range(1,5) );
                int order = GENERATE( 1, 2, 4 );
                applyTrotterCircuit(vec, hamil, time, order, reps);
                multiRotatePauli(vecRef, targs, hamil.pauliCodes, 3, 2*time*hamil.termCoeffs[0]);
                multiRotatePauli(vecRef, targs, &(hamil.pauliCodes[NUM_QUBITS]), 3, 2*time*hamil.termCoeffs[1]);
                REQUIRE( areEqual(vec, vecRef, 10*REAL_EPS) );
            }
            SECTION( "density-matrix" ) {
                int reps = GENERATE( range(1,5) );
                int order = GENERATE( 1, 2 ); // precision hurts density matrices quickly
                applyTrotterCircuit(mat, hamil, time, order, reps);
                multiRotatePauli(matRef, targs, hamil.pauliCodes, 3, 2*time*hamil.termCoeffs[0]);
                multiRotatePauli(matRef, targs, &(hamil.pauliCodes[NUM_QUBITS]), 3, 2*time*hamil.termCoeffs[1]);
                REQUIRE( areEqual(mat, matRef, 1E2*REAL_EPS) );
            }
            destroyPauliHamil(hamil);
        }
        SECTION( "general" ) {
            /* We'll consider an analytic time-evolved state, so that we can avoid
             * comparing applyTrotterCircuit to other numerical approximations.
             * We can construct such a state, by using a Hamiltonian with known
             * analytic eigenvalues, and hence a known period. Time evolution of the
             * period will just yield the input state.
             *
             * E.g. H = pi sqrt(2) X Y Z X Y + pi Y Z X Y Z + pi Z X Y Z X
             * has (degenerate) eigenvalues +- 2 pi, so the period
             * of the Hamiltonian is t=1.
             */
            // hardcoded 5 qubits here in the Pauli codes
            REQUIRE( NUM_QUBITS == 5 );
            PauliHamil hamil = createPauliHamil(NUM_QUBITS, 3);
            qreal coeffs[] = {(qreal) (M_PI * sqrt(2.0)), M_PI, M_PI};
            enum pauliOpType codes[] = {
                PAULI_X, PAULI_Y, PAULI_Z, PAULI_X, PAULI_Y,
                PAULI_Y, PAULI_Z, PAULI_X, PAULI_Y, PAULI_Z,
                PAULI_Z, PAULI_X, PAULI_Y, PAULI_Z, PAULI_X};
            initPauliHamil(hamil, coeffs, codes);
            // evolving to t=1 should leave the input state unchanged
            qreal time = 1;
            // since unnormalised (initDebugState), max fid is 728359.8336
            qreal fidNorm = 728359.8336;
            SECTION( "absolute" ) {
                // such a high order and reps should yield precise solution
                int order = 4;
                int reps = 20;
                applyTrotterCircuit(vec, hamil, time, 4, 20);
                qreal fid = calcFidelity(vec, vecRef) / fidNorm;
                REQUIRE( fid == Approx(1).epsilon(1E-8) );
            }
            SECTION( "repetitions scaling" ) {
                // exclude order 1; too few reps for monotonic increase of accuracy
                int order = GENERATE( 2, 4, 6 );
                // accuracy should increase with increasing repetitions
                int reps[] = {1, 5, 10};
                qreal prevFid = 0;
                for (int i=0; i<3; i++) {
                    initDebugState(vec);
                    applyTrotterCircuit(vec, hamil, time, order, reps[i]);
                    qreal fid = calcFidelity(vec, vecRef) / fidNorm;
                    REQUIRE( fid >= prevFid );
                    prevFid = fid;
                }
            }
            SECTION( "order scaling" ) {
                // exclude order 1; too few reps for monotonic increase of accuracy
                int reps = GENERATE( 5, 10 );
                // accuracy should increase with increasing repetitions
                int orders[] = {1, 2, 4, 6};
                qreal prevFid = 0;
                for (int i=0; i<4; i++) {
                    initDebugState(vec);
                    applyTrotterCircuit(vec, hamil, time, orders[i], reps);
                    qreal fid = calcFidelity(vec, vecRef) / fidNorm;
                    REQUIRE( fid >= prevFid );
                    prevFid = fid;
                }
            }
            destroyPauliHamil(hamil);
        }
    }
    SECTION( "input validation" ) {
        SECTION( "repetitions" ) {
            PauliHamil hamil = createPauliHamil(NUM_QUBITS, 1);
            int reps = GENERATE( -1, 0 );
            REQUIRE_THROWS_WITH( applyTrotterCircuit(vec, hamil, 1, 1, reps), Contains("repetitions must be >=1") );
            destroyPauliHamil(hamil);
        }
        SECTION( "order" ) {
            PauliHamil hamil = createPauliHamil(NUM_QUBITS, 1);
            int order = GENERATE( -1, 0, 3, 5, 7 );
            REQUIRE_THROWS_WITH( applyTrotterCircuit(vec, hamil, 1, order, 1), Contains("order must be 1, or an even number") );
            destroyPauliHamil(hamil);
        }
        SECTION( "pauli codes" ) {
            int numTerms = 3;
            PauliHamil hamil = createPauliHamil(NUM_QUBITS, numTerms);
            // make one pauli code wrong
            hamil.pauliCodes[GENERATE_COPY( range(0,numTerms*NUM_QUBITS) )] = (pauliOpType) GENERATE( -1, 4 );
            REQUIRE_THROWS_WITH( applyTrotterCircuit(vec, hamil, 1, 1, 1), Contains("Invalid Pauli code") );
            destroyPauliHamil(hamil);
        }
        SECTION( "matching hamiltonian qubits" ) {
            PauliHamil hamil = createPauliHamil(NUM_QUBITS + 1, 1);
            REQUIRE_THROWS_WITH( applyTrotterCircuit(vec, hamil, 1, 1, 1), Contains("same number of qubits") );
            REQUIRE_THROWS_WITH( applyTrotterCircuit(mat, hamil, 1, 1, 1), Contains("same number of qubits") );
            destroyPauliHamil(hamil);
        }
    }
    destroyQureg(vec, QUEST_ENV);
    destroyQureg(mat, QUEST_ENV);
    destroyQureg(vecRef, QUEST_ENV);
    destroyQureg(matRef, QUEST_ENV);
}
References applyTrotterCircuit(), areEqual(), calcFidelity(), createCloneQureg(), createDensityQureg(), createPauliHamil(), createQureg(), destroyPauliHamil(), destroyQureg(), getRandomReal(), initDebugState(), initPauliHamil(), M_PI, multiRotatePauli(), NUM_QUBITS, PauliHamil::numSumTerms, PAULI_I, PAULI_X, PAULI_Y, PAULI_Z, PauliHamil::pauliCodes, qreal, QUEST_ENV, and PauliHamil::termCoeffs.
TEST_CASE() [24/136]
TEST_CASE ("calcDensityInnerProduct" , "" [calculations])
See also
calcDensityInnerProduct
Author
Tyson Jones
Definition at line 15 of file test_calculations.cpp.
{
    Qureg mat1 = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    Qureg mat2 = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        // repeat these random tests 10 times
        GENERATE( range(0,10) );
        SECTION( "density-matrix" ) {
            SECTION( "pure" ) {
                // mat1 = |r1><r1|
                QVector r1 = getRandomStateVector(NUM_QUBITS);
                toQureg(mat1, getKetBra(r1,r1));
                // mat2 = |r2><r2|
                QVector r2 = getRandomStateVector(NUM_QUBITS);
                toQureg(mat2, getKetBra(r2,r2));
                // prod( |r1><r1|, |r2><r2| ) = |<r1|r2>|^2
                qcomp prod = 0;
                for (size_t i=0; i<r1.size(); i++)
                    prod += conj(r1[i]) * r2[i];
                qreal densProd = pow(abs(prod),2);
                REQUIRE( calcDensityInnerProduct(mat1,mat2) == Approx(densProd) );
            }
            SECTION( "mixed" ) {
                QMatrix ref1 = getRandomDensityMatrix(NUM_QUBITS);
                QMatrix ref2 = getRandomDensityMatrix(NUM_QUBITS);
                toQureg(mat1, ref1);
                toQureg(mat2, ref2);
                // prod(mat1, mat2) = sum_{ij} conj(mat1_{ij}) * mat2_{ij}
                qcomp refProd = 0;
                for (size_t i=0; i<ref1.size(); i++)
                    for (size_t j=0; j<ref1.size(); j++)
                        refProd += conj(ref1[i][j]) * ref2[i][j];
                REQUIRE( imag(refProd) == Approx(0).margin(REAL_EPS) );
                REQUIRE( calcDensityInnerProduct(mat1,mat2) == Approx(real(refProd)) );
                // should be invariant under ordering
                REQUIRE( calcDensityInnerProduct(mat1,mat2) == Approx(calcDensityInnerProduct(mat2,mat1)) );
            }
            SECTION( "unnormalised" ) {
                // set both to random (non-Hermitian) complex matrices
                QMatrix ref1 = getRandomQMatrix(1<<NUM_QUBITS);
                QMatrix ref2 = getRandomQMatrix(1<<NUM_QUBITS);
                toQureg(mat1, ref1);
                toQureg(mat2, ref2);
                // prod(mat1, mat2) = real(sum_{ij} conj(mat1_{ij}) * mat2_{ij})
                qcomp refProd = 0;
                for (size_t i=0; i<ref1.size(); i++)
                    for (size_t j=0; j<ref1.size(); j++)
                        refProd += conj(ref1[i][j]) * ref2[i][j];
                REQUIRE( calcDensityInnerProduct(mat1,mat2) == Approx(real(refProd)) );
            }
        }
    }
    SECTION( "input validation" ) {
        SECTION( "dimensions" ) {
            Qureg mat3 = createDensityQureg(NUM_QUBITS + 1, QUEST_ENV);
            REQUIRE_THROWS_WITH( calcDensityInnerProduct(mat1,mat3), Contains("Dimensions") && Contains("don't match") );
            destroyQureg(mat3, QUEST_ENV);
        }
        SECTION( "state-vectors" ) {
            Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
            REQUIRE_THROWS_WITH( calcDensityInnerProduct(mat1,vec), Contains("valid only for density matrices") );
            REQUIRE_THROWS_WITH( calcDensityInnerProduct(vec,mat1), Contains("valid only for density matrices") );
            REQUIRE_THROWS_WITH( calcDensityInnerProduct(vec,vec),  Contains("valid only for density matrices") );
            destroyQureg(vec, QUEST_ENV);
        }
    }
    destroyQureg(mat1, QUEST_ENV);
    destroyQureg(mat2, QUEST_ENV);
}
References calcDensityInnerProduct(), createDensityQureg(), createQureg(), destroyQureg(), getKetBra(), getRandomDensityMatrix(), getRandomQMatrix(), getRandomStateVector(), NUM_QUBITS, qcomp, qreal, QUEST_ENV, and toQureg().
TEST_CASE() [25/136]
TEST_CASE ("calcExpecDiagonalOp" , "" [calculations])
See also
calcExpecDiagonalOp
Author
Tyson Jones
Definition at line 111 of file test_calculations.cpp.
{
    Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    initDebugState(vec);
    initDebugState(mat);
    QVector vecRef = toQVector(vec);
    QMatrix matRef = toQMatrix(mat);
    SECTION( "correctness" ) {
        // try 10 random operators
        GENERATE( range(0,10) );
        // make a totally random (non-Hermitian) diagonal oeprator
        DiagonalOp op = createDiagonalOp(NUM_QUBITS, QUEST_ENV);
        for (long long int i=0; i<op.numElemsPerChunk; i++) {
            op.real[i] = getRandomReal(-5, 5);
            op.imag[i] = getRandomReal(-5, 5);
        }
        syncDiagonalOp(op);
        SECTION( "state-vector" ) {
            /* calcExpecDiagOp calculates <qureg|diag|qureg> */
            QVector sumRef = toQMatrix(op) * vecRef;
            qcomp prod = 0;
            for (size_t i=0; i<vecRef.size(); i++)
                prod += conj(vecRef[i]) * sumRef[i];
            Complex res = calcExpecDiagonalOp(vec, op);
            REQUIRE( res.real == Approx(real(prod)).margin(REAL_EPS) );
            REQUIRE( res.imag == Approx(imag(prod)).margin(REAL_EPS) );
        }
        SECTION( "density-matrix" ) {
            /* calcExpecDiagOp calculates Trace( diag * qureg ) */
            matRef = toQMatrix(op) * matRef;
            qcomp tr = 0;
            for (size_t i=0; i<matRef.size(); i++)
                tr += matRef[i][i];
            Complex res = calcExpecDiagonalOp(mat, op);
            REQUIRE( res.real == Approx(real(tr)).margin(100*REAL_EPS) );
            REQUIRE( res.imag == Approx(imag(tr)).margin(100*REAL_EPS) );
        }
        destroyDiagonalOp(op, QUEST_ENV);
    }
    SECTION( "input validation" ) {
        SECTION( "mismatching size" ) {
            DiagonalOp op = createDiagonalOp(NUM_QUBITS + 1, QUEST_ENV);
            REQUIRE_THROWS_WITH( calcExpecDiagonalOp(vec, op), Contains("equal number of qubits"));
            REQUIRE_THROWS_WITH( calcExpecDiagonalOp(mat, op), Contains("equal number of qubits"));
            destroyDiagonalOp(op, QUEST_ENV);
        }
    }
    destroyQureg(vec, QUEST_ENV);
    destroyQureg(mat, QUEST_ENV);
}
References calcExpecDiagonalOp(), createDensityQureg(), createDiagonalOp(), createQureg(), destroyDiagonalOp(), destroyQureg(), getRandomReal(), Complex::imag, DiagonalOp::imag, initDebugState(), NUM_QUBITS, DiagonalOp::numElemsPerChunk, qcomp, QUEST_ENV, Complex::real, DiagonalOp::real, syncDiagonalOp(), toQMatrix(), and toQVector().
TEST_CASE() [26/136]
TEST_CASE ("calcExpecPauliHamil" , "" [calculations])
See also
calcExpecPauliHamil
Author
Tyson Jones
Definition at line 183 of file test_calculations.cpp.
{
    Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    initDebugState(vec);
    initDebugState(mat);
    QVector vecRef = toQVector(vec);
    QMatrix matRef = toQMatrix(mat);
    Qureg vecWork = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg matWork = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        /* it's too expensive to try every possible Pauli configuration, so
         * we'll try 10 random codes, and for each, random coefficients
         */
        GENERATE( range(0,10) );
        int numTerms = GENERATE( 1, 2, 10, 15 );
        PauliHamil hamil = createPauliHamil(NUM_QUBITS, numTerms);
        setRandomPauliSum(hamil);
        QMatrix refHamil = toQMatrix(hamil);
        SECTION( "state-vector" ) {
            /* calcExpecPauliHamil calculates <qureg|pauliHum|qureg> */
            QVector sumRef = refHamil * vecRef;
            qcomp prod = 0;
            for (size_t i=0; i<vecRef.size(); i++)
                prod += conj(vecRef[i]) * sumRef[i];
            REQUIRE( imag(prod) == Approx(0).margin(10*REAL_EPS) );
            qreal res = calcExpecPauliHamil(vec, hamil, vecWork);
            REQUIRE( res == Approx(real(prod)).margin(10*REAL_EPS) );
        }
        SECTION( "density-matrix" ) {
            /* calcExpecPauliHamil calculates Trace( pauliHamil * qureg ) */
            matRef = refHamil * matRef;
            qreal tr = 0;
            for (size_t i=0; i<matRef.size(); i++)
                tr += real(matRef[i][i]);
            // (get real, since we start in a non-Hermitian state, hence diagonal isn't real)
            qreal res = calcExpecPauliHamil(mat, hamil, matWork);
            REQUIRE( res == Approx(tr).margin(1E2*REAL_EPS) );
        }
        destroyPauliHamil(hamil);
    }
    SECTION( "input validation" ) {
        SECTION( "pauli codes" ) {
            int numTerms = 3;
            PauliHamil hamil = createPauliHamil(NUM_QUBITS, numTerms);
            // make one pauli code wrong
            hamil.pauliCodes[GENERATE_COPY( range(0,numTerms*NUM_QUBITS) )] = (pauliOpType) GENERATE( -1, 4 );
            REQUIRE_THROWS_WITH( calcExpecPauliHamil(vec, hamil, vecWork), Contains("Invalid Pauli code") );
            destroyPauliHamil(hamil);
        }
        SECTION( "workspace type" ) {
            int numTerms = 1;
            PauliHamil hamil = createPauliHamil(NUM_QUBITS, numTerms);
            REQUIRE_THROWS_WITH( calcExpecPauliHamil(vec, hamil, mat), Contains("Registers must both be state-vectors or both be density matrices") );
            REQUIRE_THROWS_WITH( calcExpecPauliHamil(mat, hamil, vec), Contains("Registers must both be state-vectors or both be density matrices") );
            destroyPauliHamil(hamil);
        }
        SECTION( "workspace dimensions" ) {
            int numTerms = 1;
            PauliHamil hamil = createPauliHamil(NUM_QUBITS, numTerms);
            Qureg vec2 = createQureg(NUM_QUBITS + 1, QUEST_ENV);
            REQUIRE_THROWS_WITH( calcExpecPauliHamil(vec, hamil, vec2), Contains("Dimensions") && Contains("don't match") );
            destroyQureg(vec2, QUEST_ENV);
            Qureg mat2 = createDensityQureg(NUM_QUBITS + 1, QUEST_ENV);
            REQUIRE_THROWS_WITH( calcExpecPauliHamil(mat, hamil, mat2), Contains("Dimensions") && Contains("don't match") );
            destroyQureg(mat2, QUEST_ENV);
            destroyPauliHamil(hamil);
        }
        SECTION( "matching hamiltonian qubits" ) {
            int numTerms = 1;
            PauliHamil hamil = createPauliHamil(NUM_QUBITS + 1, numTerms);
            REQUIRE_THROWS_WITH( calcExpecPauliHamil(vec, hamil, vecWork), Contains("same number of qubits") );
            REQUIRE_THROWS_WITH( calcExpecPauliHamil(mat, hamil, matWork), Contains("same number of qubits") );
            destroyPauliHamil(hamil);
        }
    }
    destroyQureg(vec, QUEST_ENV);
    destroyQureg(mat, QUEST_ENV);
    destroyQureg(vecWork, QUEST_ENV);
    destroyQureg(matWork, QUEST_ENV);
}
References calcExpecPauliHamil(), createDensityQureg(), createPauliHamil(), createQureg(), destroyPauliHamil(), destroyQureg(), initDebugState(), NUM_QUBITS, PauliHamil::pauliCodes, qcomp, qreal, QUEST_ENV, setRandomPauliSum(), toQMatrix(), and toQVector().
TEST_CASE() [27/136]
TEST_CASE ("calcExpecPauliProd" , "" [calculations])
See also
calcExpecPauliProd
Author
Tyson Jones
Definition at line 296 of file test_calculations.cpp.
{
    Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    initDebugState(vec);
    initDebugState(mat);
    QVector vecRef = toQVector(vec);
    QMatrix matRef = toQMatrix(mat);
    Qureg vecWork = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg matWork = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        int numTargs = GENERATE( range(1,NUM_QUBITS+1) );
        int* targs = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numTargs) );
        /* it's too expensive to try ALL Pauli sequences, via
         *      pauliOpType* paulis = GENERATE_COPY( pauliseqs(numTargs) );.
         * Furthermore, take(10, pauliseqs(numTargs)) will try the same pauli codes.
         * Hence, we instead opt to repeatedlyrandomly generate pauliseqs
         */
        GENERATE( range(0,10) ); // gen 10 random pauli-codes for every targs
        VLA(pauliOpType, paulis, numTargs);
        for (int i=0; i<numTargs; i++)
            paulis[i] = (pauliOpType) getRandomInt(0,4);
        // produce a numTargs-big matrix 'pauliProd' by pauli-matrix tensoring
        QMatrix iMatr{{1,0},{0,1}};
        QMatrix xMatr{{0,1},{1,0}};
        QMatrix yMatr{{0,-qcomp(0,1)},{qcomp(0,1),0}};
        QMatrix zMatr{{1,0},{0,-1}};
        QMatrix pauliProd{{1}};
        for (int i=0; i<numTargs; i++) {
            QMatrix fac;
            if (paulis[i] == PAULI_I) fac = iMatr;
            if (paulis[i] == PAULI_X) fac = xMatr;
            if (paulis[i] == PAULI_Y) fac = yMatr;
            if (paulis[i] == PAULI_Z) fac = zMatr;
            pauliProd = getKroneckerProduct(fac, pauliProd);
        }
        SECTION( "state-vector" ) {
            /* calcExpecPauliProd calculates <qureg|pauliProd|qureg> */
            QVector prodRef = vecRef;
            applyReferenceOp(prodRef, targs, numTargs, pauliProd);
            qcomp prod = 0;
            for (size_t i=0; i<vecRef.size(); i++)
                prod += conj(vecRef[i]) * prodRef[i];
            REQUIRE( imag(prod) == Approx(0).margin(REAL_EPS) );
            qreal res = calcExpecPauliProd(vec, targs, paulis, numTargs, vecWork);
            REQUIRE( res == Approx(real(prod)).margin(REAL_EPS) );
        }
        SECTION( "density-matrix" ) {
            /* calcExpecPauliProd calculates Trace( pauliProd * qureg ) */
            // produce (pauliProd * mat)
            QMatrix fullOp = getFullOperatorMatrix(NULL, 0, targs, numTargs, pauliProd, NUM_QUBITS);
            matRef = fullOp * matRef;
            // compute real(trace(pauliProd * mat))
            qreal tr = 0;
            for (size_t i=0; i<matRef.size(); i++)
                tr += real(matRef[i][i]);
            // (get real, since we start in a non-Hermitian state, hence diagonal isn't real)
            qreal res = calcExpecPauliProd(mat, targs, paulis, numTargs, matWork);
            REQUIRE( res == Approx(tr).margin(10*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "number of targets" ) {
            int numTargs = GENERATE( -1, 0, NUM_QUBITS+1 );
            REQUIRE_THROWS_WITH( calcExpecPauliProd(vec, NULL, NULL, numTargs, vecWork), Contains("Invalid number of target") );
        }
        SECTION( "target indices" ) {
            int numTargs = 3;
            int targs[3] = {0, 1, 2};
            // make one index wrong
            targs[GENERATE( range(0,3) )] = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( calcExpecPauliProd(vec, targs, NULL, numTargs, vecWork), Contains("Invalid target qubit") );
        }
        SECTION( "repetition in targets" ) {
            int numTargs = 3;
            int targs[3] = {0, 1, 1};
            REQUIRE_THROWS_WITH( calcExpecPauliProd(vec, targs, NULL, numTargs, vecWork), Contains("target qubits must be unique") );
        }
        SECTION( "pauli codes" ) {
            int numTargs = 3;
            int targs[3] = {0, 1, 2};
            pauliOpType codes[3] = {PAULI_X, PAULI_Y, PAULI_Z};
            // make one pauli wrong
            codes[GENERATE( range(0,3) )] = (pauliOpType) GENERATE( -1, 4 );
            REQUIRE_THROWS_WITH( calcExpecPauliProd(vec, targs, codes, numTargs, vecWork), Contains("Invalid Pauli code") );
        }
        SECTION( "workspace type" ) {
            int numTargs = 1;
            int targs[1] = {0};
            pauliOpType codes[1] = {PAULI_I};
            REQUIRE_THROWS_WITH( calcExpecPauliProd(vec, targs, codes, numTargs, matWork), Contains("Registers must both be state-vectors or both be density matrices") );
            REQUIRE_THROWS_WITH( calcExpecPauliProd(mat, targs, codes, numTargs, vecWork), Contains("Registers must both be state-vectors or both be density matrices") );
        }
        SECTION( "workspace dimensions" ) {
            int numTargs = 1;
            int targs[1] = {0};
            pauliOpType codes[1] = {PAULI_I};
            Qureg vec2 = createQureg(NUM_QUBITS + 1, QUEST_ENV);
            REQUIRE_THROWS_WITH( calcExpecPauliProd(vec, targs, codes, numTargs, vec2), Contains("Dimensions") && Contains("don't match") );
            destroyQureg(vec2, QUEST_ENV);
            Qureg mat2 = createDensityQureg(NUM_QUBITS + 1, QUEST_ENV);
            REQUIRE_THROWS_WITH( calcExpecPauliProd(mat, targs, codes, numTargs, mat2), Contains("Dimensions") && Contains("don't match") );
            destroyQureg(mat2, QUEST_ENV);
        }
    }
    destroyQureg(vec, QUEST_ENV);
    destroyQureg(mat, QUEST_ENV);
    destroyQureg(vecWork, QUEST_ENV);
    destroyQureg(matWork, QUEST_ENV);
}
References applyReferenceOp(), calcExpecPauliProd(), createDensityQureg(), createQureg(), destroyQureg(), getFullOperatorMatrix(), getKroneckerProduct(), getRandomInt(), initDebugState(), NUM_QUBITS, PAULI_I, PAULI_X, PAULI_Y, PAULI_Z, qcomp, qreal, QUEST_ENV, sublists(), toQMatrix(), toQVector(), and VLA.
TEST_CASE() [28/136]
TEST_CASE ("calcExpecPauliSum" , "" [calculations])
See also
calcExpecPauliSum
Author
Tyson Jones
Definition at line 438 of file test_calculations.cpp.
{
    Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    initDebugState(vec);
    initDebugState(mat);
    QVector vecRef = toQVector(vec);
    QMatrix matRef = toQMatrix(mat);
    Qureg vecWork = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg matWork = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        int numSumTerms = GENERATE( 1, 2, 10, 15 );
        /* it's too expensive to try every possible Pauli configuration, so
         * we'll try 10 random codes, and for each, random coefficients
         */
        GENERATE( range(0,10) );
        int totNumCodes = numSumTerms*NUM_QUBITS;
        VLA(pauliOpType, paulis, totNumCodes);
        VLA(qreal, coeffs, numSumTerms);
        setRandomPauliSum(coeffs, paulis, NUM_QUBITS, numSumTerms);
        // produce a numTargs-big matrix 'pauliSum' by pauli-matrix tensoring and summing
        QMatrix pauliSum = toQMatrix(coeffs, paulis, NUM_QUBITS, numSumTerms);
        SECTION( "state-vector" ) {
            /* calcExpecPauliSum calculates <qureg|pauliSum|qureg> */
            QVector sumRef = pauliSum * vecRef;
            qcomp prod = 0;
            for (size_t i=0; i<vecRef.size(); i++)
                prod += conj(vecRef[i]) * sumRef[i];
            REQUIRE( imag(prod) == Approx(0).margin(10*REAL_EPS) );
            qreal res = calcExpecPauliSum(vec, paulis, coeffs, numSumTerms, vecWork);
            REQUIRE( res == Approx(real(prod)).margin(10*REAL_EPS) );
        }
        SECTION( "density-matrix" ) {
            /* calcExpecPauliSum calculates Trace( pauliSum * qureg ) */
            matRef = pauliSum * matRef;
            qreal tr = 0;
            for (size_t i=0; i<matRef.size(); i++)
                tr += real(matRef[i][i]);
            // (get real, since we start in a non-Hermitian state, hence diagonal isn't real)
            qreal res = calcExpecPauliSum(mat, paulis, coeffs, numSumTerms, matWork);
            REQUIRE( res == Approx(tr).margin(1E2*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "number of sum terms" ) {
            int numSumTerms = GENERATE( -1, 0 );
            REQUIRE_THROWS_WITH( calcExpecPauliSum(vec, NULL, NULL, numSumTerms, vecWork), Contains("Invalid number of terms in the Pauli sum") );
        }
        SECTION( "pauli codes" ) {
            // make valid params
            int numSumTerms = 3;
            VLA(qreal, coeffs, numSumTerms);
            VLA(pauliOpType, codes, numSumTerms*NUM_QUBITS);
            for (int i=0; i<numSumTerms*NUM_QUBITS; i++)
                codes[i] = PAULI_I;
            // make one pauli wrong
            codes[GENERATE_COPY( range(0,numSumTerms*NUM_QUBITS) )] = (pauliOpType) GENERATE( -1, 4 );
            REQUIRE_THROWS_WITH( calcExpecPauliSum(vec, codes, coeffs, numSumTerms, vecWork), Contains("Invalid Pauli code") );
        }
        SECTION( "workspace type" ) {
            // make valid params
            int numSumTerms = 1;
            qreal coeffs[1] = {0};
            pauliOpType codes[NUM_QUBITS];
            for (int i=0; i<NUM_QUBITS; i++)
                codes[i] = PAULI_I;
            REQUIRE_THROWS_WITH( calcExpecPauliSum(vec, codes, coeffs, numSumTerms, mat), Contains("Registers must both be state-vectors or both be density matrices") );
            REQUIRE_THROWS_WITH( calcExpecPauliSum(mat, codes, coeffs, numSumTerms, vec), Contains("Registers must both be state-vectors or both be density matrices") );
        }
        SECTION( "workspace dimensions" ) {
            // make valid params
            int numSumTerms = 1;
            qreal coeffs[1] = {0};
            pauliOpType codes[NUM_QUBITS];
            for (int i=0; i<NUM_QUBITS; i++)
                codes[i] = PAULI_I;
            Qureg vec2 = createQureg(NUM_QUBITS + 1, QUEST_ENV);
            REQUIRE_THROWS_WITH( calcExpecPauliSum(vec, codes, coeffs, numSumTerms, vec2), Contains("Dimensions") && Contains("don't match") );
            destroyQureg(vec2, QUEST_ENV);
            Qureg mat2 = createDensityQureg(NUM_QUBITS + 1, QUEST_ENV);
            REQUIRE_THROWS_WITH( calcExpecPauliSum(mat, codes, coeffs, numSumTerms, mat2), Contains("Dimensions") && Contains("don't match") );
            destroyQureg(mat2, QUEST_ENV);
        }
    }
    destroyQureg(vec, QUEST_ENV);
    destroyQureg(mat, QUEST_ENV);
    destroyQureg(vecWork, QUEST_ENV);
    destroyQureg(matWork, QUEST_ENV);
}
References calcExpecPauliSum(), createDensityQureg(), createQureg(), destroyQureg(), initDebugState(), NUM_QUBITS, PAULI_I, qcomp, qreal, QUEST_ENV, setRandomPauliSum(), toQMatrix(), toQVector(), and VLA.
TEST_CASE() [29/136]
TEST_CASE ("calcFidelity" , "" [calculations])
See also
calcFidelity
Author
Tyson Jones
Definition at line 554 of file test_calculations.cpp.
{
    Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    Qureg pure = createQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        // repeat the below random tests 10 times
        GENERATE( range(0,10) );
        SECTION( "state-vector" ) {
            /* calcFidelity computes |<vec|pure>|^2 */
            SECTION( "normalised" ) {
                // random L2 vectors
                QVector vecRef = getRandomStateVector(NUM_QUBITS);
                QVector pureRef = getRandomStateVector(NUM_QUBITS);
                toQureg(vec, vecRef);
                toQureg(pure, pureRef);
                // |<vec|vec>|^2 = |1|^2 = 1
                REQUIRE( calcFidelity(vec,vec) == Approx(1) );
                // |<vec|pure>|^2 = |sum_j conj(vec_j) * pure_j|^2
                qcomp dotProd = 0;
                for (size_t i=0; i<vecRef.size(); i++)
                    dotProd += conj(vecRef[i]) * pureRef[i];
                qreal refFid = pow(abs(dotProd), 2);
                REQUIRE( calcFidelity(vec,pure) == Approx(refFid) );
            }
            SECTION( "unnormalised" ) {
                // random unnormalised vectors
                QVector vecRef = getRandomQVector(1<<NUM_QUBITS);
                QVector pureRef = getRandomQVector(1<<NUM_QUBITS);
                toQureg(vec, vecRef);
                toQureg(pure, pureRef);
                // Let nv be magnitude of vec, hence |unit-vec> = 1/sqrt(nv)|vec>
                qreal nv = 0;
                for (size_t i=0; i<vecRef.size(); i++)
                    nv += pow(abs(vecRef[i]), 2);
                // then <vec|vec> = sqrt(nv)*sqrt(nv) <unit-vec|unit-vec> = nv,
                // hence |<vec|vec>|^2 = nv*nv
                REQUIRE( calcFidelity(vec,vec) == Approx( nv*nv ) );
                qcomp dotProd = 0;
                for (size_t i=0; i<vecRef.size(); i++)
                    dotProd += conj(vecRef[i]) * pureRef[i];
                qreal refFid = pow(abs(dotProd), 2);
                REQUIRE( calcFidelity(vec,pure) == Approx(refFid) );
            }
        }
        SECTION( "density-matrix" ) {
            /* calcFidelity computes <pure|mat|pure> */
            SECTION( "pure" ) {
                QVector pureRef = getRandomStateVector(NUM_QUBITS);
                toQureg(pure, pureRef);
                // test when density matrix is the same pure state
                QMatrix matRef = getKetBra(pureRef, pureRef);
                toQureg(mat, matRef);
                REQUIRE( calcFidelity(mat,pure) == Approx(1) );
                // test when density matrix is a random pure state
                QVector r1 = getRandomStateVector(NUM_QUBITS);
                matRef = getKetBra(r1, r1); // actually pure |r1><r1|
                toQureg(mat, matRef);
                // <pure|r1><r1|pure> = |<r1|pure>|^2 = |sum_j conj(r1_j) * pure_j|^2
                qcomp dotProd = 0;
                for (size_t i=0; i<r1.size(); i++)
                    dotProd += conj(r1[i]) * pureRef[i];
                qreal refFid = pow(abs(dotProd), 2);
                REQUIRE( calcFidelity(mat,pure) == Approx(refFid) );
            }
            SECTION( "mixed" ) {
                QVector pureRef = getRandomStateVector(NUM_QUBITS);
                toQureg(pure, pureRef);
                // test when density matrix is mixed
                QMatrix matRef = getRandomDensityMatrix(NUM_QUBITS);
                toQureg(mat, matRef);
                // <pure|mat|pure> = <pure| (Mat|pure>)
                QVector rhs = matRef * pureRef;
                qcomp dotProd = 0;
                for (size_t i=0; i<rhs.size(); i++)
                    dotProd += conj(pureRef[i]) * rhs[i];
                REQUIRE( imag(dotProd) == Approx(0).margin(REAL_EPS) );
                REQUIRE( calcFidelity(mat,pure) == Approx(real(dotProd)) );
            }
            SECTION( "unnormalised" ) {
                // test when both density matrix and pure state are unnormalised
                QVector pureRef = getRandomQVector(1<<NUM_QUBITS);
                QMatrix matRef = getRandomQMatrix(1<<NUM_QUBITS);
                toQureg(pure, pureRef);
                toQureg(mat, matRef);
                // real[ <pure|mat|pure> ] = real[ <pure| (Mat|pure>) ]
                QVector rhs = matRef * pureRef;
                qcomp dotProd = 0;
                for (size_t i=0; i<rhs.size(); i++)
                    dotProd += conj(pureRef[i]) * rhs[i];
                REQUIRE( calcFidelity(mat,pure) == Approx(real(dotProd)) );
            }
        }
    }
    SECTION( "input validation" ) {
        SECTION( "dimensions" ) {
            // two state-vectors
            Qureg vec2 = createQureg(vec.numQubitsRepresented + 1, QUEST_ENV);
            REQUIRE_THROWS_WITH( calcFidelity(vec2,vec), Contains("Dimensions") && Contains("don't match") );
            destroyQureg(vec2, QUEST_ENV);
            // density-matrix and state-vector
            Qureg mat2 = createDensityQureg(vec.numQubitsRepresented + 1, QUEST_ENV);
            REQUIRE_THROWS_WITH( calcFidelity(mat2,vec), Contains("Dimensions") && Contains("don't match") );
            destroyQureg(mat2, QUEST_ENV);
        }
        SECTION( "density-matrices" ) {
            // two mixed statess
            REQUIRE_THROWS_WITH( calcFidelity(mat,mat), Contains("Second argument must be a state-vector") );
        }
    }
    destroyQureg(vec, QUEST_ENV);
    destroyQureg(mat, QUEST_ENV);
    destroyQureg(pure, QUEST_ENV);
}
References calcFidelity(), createDensityQureg(), createQureg(), destroyQureg(), getKetBra(), getRandomDensityMatrix(), getRandomQMatrix(), getRandomQVector(), getRandomStateVector(), NUM_QUBITS, Qureg::numQubitsRepresented, qcomp, qreal, QUEST_ENV, and toQureg().
TEST_CASE() [30/136]
TEST_CASE ("calcHilbertSchmidtDistance" , "" [calculations])
See also
calcHilbertSchmidtDistance
Author
Tyson Jones
Definition at line 706 of file test_calculations.cpp.
{
    Qureg mat1 = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    Qureg mat2 = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        // perform these random tests 10 times
        GENERATE( range(0,10) );
        SECTION( "density-matrix" ) {
            SECTION( "pure" ) {
                // create random |r1><r1| and |r2><r2| states
                QVector r1 = getRandomStateVector(NUM_QUBITS);
                QMatrix m1 = getKetBra(r1,r1);
                toQureg(mat1, m1);
                QVector r2 = getRandomStateVector(NUM_QUBITS);
                QMatrix m2 = getKetBra(r2,r2);
                toQureg(mat2, m2);
                // Tr{ (a-b)(a-b)^dagger } =  sum_{ij} |a_{ij} - b_{ij}|^2
                qreal tr = 0;
                for (size_t i=0; i<m1.size(); i++)
                    for (size_t j=0; j<m1.size(); j++)
                        tr += pow(abs(m1[i][j] - m2[i][j]), 2);
                qreal res = calcHilbertSchmidtDistance(mat1, mat2);
                REQUIRE( res == Approx(sqrt(tr)) );
            }
            SECTION( "normalised" ) {
                QMatrix ref1 = getRandomDensityMatrix(NUM_QUBITS);
                QMatrix ref2 = getRandomDensityMatrix(NUM_QUBITS);
                toQureg(mat1, ref1);
                toQureg(mat2, ref2);
                // Tr{ (a-b)(a-b)^dagger } =  sum_{ij} |a_{ij} - b_{ij}|^2
                qreal tr = 0;
                for (size_t i=0; i<ref1.size(); i++)
                    for (size_t j=0; j<ref1.size(); j++)
                        tr += pow(abs(ref1[i][j] - ref2[i][j]), 2);
                qreal res = calcHilbertSchmidtDistance(mat1, mat2);
                REQUIRE( res == Approx(sqrt(tr)) );
            }
            SECTION( "unnormalised" ) {
                // mat1 and mat2 are both random matrices
                QMatrix ref1 = getRandomQMatrix(1<<NUM_QUBITS);
                QMatrix ref2 = getRandomQMatrix(1<<NUM_QUBITS);
                toQureg(mat1, ref1);
                toQureg(mat2, ref2);
                // Tr{ (a-b)(a-b)^dagger } =  sum_{ij} |a_{ij} - b_{ij}|^2
                qreal tr = 0;
                for (size_t i=0; i<ref1.size(); i++)
                    for (size_t j=0; j<ref1.size(); j++)
                        tr += pow(abs(ref1[i][j] - ref2[i][j]), 2);
                qreal res = calcHilbertSchmidtDistance(mat1, mat2);
                REQUIRE( res == Approx(sqrt(tr)) );
            }
        }
    }
    SECTION( "input validation") {
        SECTION( "dimensions" ) {
            Qureg mat3 = createDensityQureg(NUM_QUBITS + 1, QUEST_ENV);
            REQUIRE_THROWS_WITH( calcHilbertSchmidtDistance(mat1,mat3), Contains("Dimensions") && Contains("don't match") );
            destroyQureg(mat3, QUEST_ENV);
        }
        SECTION( "state-vector" ) {
            Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
            REQUIRE_THROWS_WITH( calcHilbertSchmidtDistance(vec,mat1), Contains("valid only for density matrices") );
            REQUIRE_THROWS_WITH( calcHilbertSchmidtDistance(mat1,vec), Contains("valid only for density matrices") );
            REQUIRE_THROWS_WITH( calcHilbertSchmidtDistance(vec,vec), Contains("valid only for density matrices") );
            destroyQureg(vec, QUEST_ENV);
        }
    }
    destroyQureg(mat1, QUEST_ENV);
    destroyQureg(mat2, QUEST_ENV);
}
References calcHilbertSchmidtDistance(), createDensityQureg(), createQureg(), destroyQureg(), getKetBra(), getRandomDensityMatrix(), getRandomQMatrix(), getRandomStateVector(), NUM_QUBITS, qreal, QUEST_ENV, and toQureg().
TEST_CASE() [31/136]
TEST_CASE ("calcInnerProduct" , "" [calculations])
See also
calcInnerProduct
Author
Tyson Jones
Definition at line 802 of file test_calculations.cpp.
{
    Qureg vec1 = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg vec2 = createQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        // perform these random tests 10 times
        GENERATE( range(0,10) );
        SECTION( "state-vector" ) {
            SECTION( "normalised" ) {
                // <r1|r2> = sum_j conj(r1_j) * r2_j
                QVector r1 = getRandomStateVector(NUM_QUBITS);
                QVector r2 = getRandomStateVector(NUM_QUBITS);
                qcomp prod = 0;
                for (size_t i=0; i<r1.size(); i++)
                    prod += conj(r1[i]) * r2[i];
                toQureg(vec1, r1);
                toQureg(vec2, r2);
                Complex res = calcInnerProduct(vec1,vec2);
                REQUIRE( res.real == Approx(real(prod)) );
                REQUIRE( res.imag == Approx(imag(prod)) );
            }
            SECTION( "unnormalised" ) {
                // <r1|r2> = sum_j conj(r1_j) * r2_j
                QVector r1 = getRandomQVector(1<<NUM_QUBITS);
                QVector r2 = getRandomQVector(1<<NUM_QUBITS);
                qcomp prod = 0;
                for (size_t i=0; i<r1.size(); i++)
                    prod += conj(r1[i]) * r2[i];
                toQureg(vec1, r1);
                toQureg(vec2, r2);
                Complex res = calcInnerProduct(vec1,vec2);
                REQUIRE( res.real == Approx(real(prod)) );
                REQUIRE( res.imag == Approx(imag(prod)) );
            }
        }
    }
    SECTION( "input validation" ) {
        SECTION( "dimensions" ) {
            Qureg vec3 = createQureg(NUM_QUBITS + 1, QUEST_ENV);
            REQUIRE_THROWS_WITH( calcInnerProduct(vec1,vec3), Contains("Dimensions") && Contains("don't match") );
            destroyQureg(vec3, QUEST_ENV);
        }
        SECTION( "density-matrix" ) {
            Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
            REQUIRE_THROWS_WITH( calcInnerProduct(vec1,mat), Contains("valid only for state-vectors") );
            REQUIRE_THROWS_WITH( calcInnerProduct(mat,vec1), Contains("valid only for state-vectors") );
            REQUIRE_THROWS_WITH( calcInnerProduct(mat,mat), Contains("valid only for state-vectors") );
            destroyQureg(mat, QUEST_ENV);
        }
    }
    destroyQureg(vec1, QUEST_ENV);
    destroyQureg(vec2, QUEST_ENV);
}
References calcInnerProduct(), createDensityQureg(), createQureg(), destroyQureg(), getRandomQVector(), getRandomStateVector(), Complex::imag, NUM_QUBITS, qcomp, QUEST_ENV, Complex::real, and toQureg().
TEST_CASE() [32/136]
TEST_CASE ("calcProbOfAllOutcomes" , "" [calculations])
See also
calcProbOfAllOutcomes
Author
Tyson Jones
Definition at line 877 of file test_calculations.cpp.
{
    Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        // generate all possible qubit arrangements
        int numQubits = GENERATE_COPY( range(1,NUM_QUBITS+1) );
        int* qubits = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numQubits) );
        int numOutcomes = 1<<numQubits;
        VLA(qreal, probs, numOutcomes);
        QVector refProbs = QVector(numOutcomes);
        SECTION( "state-vector" ) {
            SECTION( "normalised" ) {
                QVector ref = getRandomStateVector(NUM_QUBITS);
                toQureg(vec, ref);
                // prob is sum of |amp|^2 of basis states which encode outcome
                for (size_t i=0; i<ref.size(); i++) {
                    int outcome = 0;
                    for (int q=0; q<numQubits; q++) {
                        int bit = (i >> qubits[q]) & 1;
                        outcome += bit * (1 << q);
                    }
                    refProbs[outcome] += pow(abs(ref[i]), 2);
                }
                calcProbOfAllOutcomes(probs, vec, qubits, numQubits);
                REQUIRE( areEqual(refProbs, probs) );
            }
            SECTION( "unnormalised" ) {
                QVector ref = getRandomQVector(1<<NUM_QUBITS);
                toQureg(vec, ref);
                // prob is sum of |amp|^2 of basis states which encode outcome
                for (size_t i=0; i<ref.size(); i++) {
                    int outcome = 0;
                    for (int q=0; q<numQubits; q++) {
                        int bit = (i >> qubits[q]) & 1;
                        outcome += bit * (1 << q);
                    }
                    refProbs[outcome] += pow(abs(ref[i]), 2);
                }
                calcProbOfAllOutcomes(probs, vec, qubits, numQubits);
                REQUIRE( areEqual(refProbs, probs) );
            }
        }
        SECTION( "density-matrix" ) {
            SECTION( "normalised" ) {
                QMatrix ref = getRandomDensityMatrix(NUM_QUBITS);
                toQureg(mat, ref);
                // prob is sum of diagonals which encode outcome
                for (size_t i=0; i<ref.size(); i++) {
                    int outcome = 0;
                    for (int q=0; q<numQubits; q++) {
                        int bit = (i >> qubits[q]) & 1;
                        outcome += bit * (1 << q);
                    }
                    refProbs[outcome] += real(ref[i][i]);
                }
                calcProbOfAllOutcomes(probs, mat, qubits, numQubits);
                REQUIRE( areEqual(refProbs, probs) );
            }
            SECTION( "unnormalised" ) {
                QMatrix ref = getRandomQMatrix(1<<NUM_QUBITS);
                toQureg(mat, ref);
                // prob is sum of diagonals which encode outcome
                for (size_t i=0; i<ref.size(); i++) {
                    int outcome = 0;
                    for (int q=0; q<numQubits; q++) {
                        int bit = (i >> qubits[q]) & 1;
                        outcome += bit * (1 << q);
                    }
                    refProbs[outcome] += real(ref[i][i]);
                }
                calcProbOfAllOutcomes(probs, mat, qubits, numQubits);
                REQUIRE( areEqual(refProbs, probs) );
            }
        }
    }
    SECTION( "input validation" ) {
        int numQubits = 3;
        int qubits[] = {0, 1, 2};
        qreal probs[8];
        SECTION( "number of qubits" ) {
            numQubits = GENERATE( -1, 0, NUM_QUBITS+1 );
            REQUIRE_THROWS_WITH( calcProbOfAllOutcomes(probs, mat, qubits, numQubits), Contains("Invalid number of target qubits") );
        }
        SECTION( "qubit indices" ) {
            qubits[GENERATE_COPY(range(0,numQubits))] = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( calcProbOfAllOutcomes(probs, mat, qubits, numQubits), Contains("Invalid target qubit") );
        }
        SECTION( "repetition of qubits" ) {
            qubits[GENERATE_COPY(1,2)] = qubits[0];
            REQUIRE_THROWS_WITH( calcProbOfAllOutcomes(probs, mat, qubits, numQubits), Contains("qubits must be unique") );
        }
    }
    destroyQureg(vec, QUEST_ENV);
    destroyQureg(mat, QUEST_ENV);
}
References areEqual(), calcProbOfAllOutcomes(), createDensityQureg(), createQureg(), destroyQureg(), getRandomDensityMatrix(), getRandomQMatrix(), getRandomQVector(), getRandomStateVector(), NUM_QUBITS, qreal, QUEST_ENV, sublists(), toQureg(), and VLA.
TEST_CASE() [33/136]
TEST_CASE ("calcProbOfOutcome" , "" [calculations])
See also
calcProbOfOutcome
Author
Tyson Jones
Definition at line 1004 of file test_calculations.cpp.
{
    Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        int outcome = GENERATE( 0, 1 );
        SECTION( "state-vector" ) {
            SECTION( "normalised" ) {
                QVector ref = getRandomStateVector(NUM_QUBITS);
                toQureg(vec, ref);
                // prob is sum of |amp|^2 of amplitudes where target bit is outcome
                qreal prob = 0;
                for (size_t ind=0; ind<ref.size(); ind++) {
                    int bit = (ind >> target) & 1; // target-th bit
                    if (bit == outcome)
                        prob += pow(abs(ref[ind]), 2);
                }
                REQUIRE( calcProbOfOutcome(vec, target, outcome) == Approx(prob) );
            }
            SECTION( "unnormalised" ) {
                QVector ref = getRandomQVector(1<<NUM_QUBITS);
                toQureg(vec, ref);
                // prob is (sum of |amp|^2 of amplitudes where target bit is zero)
                // or 1 - (this) if outcome == 1
                qreal prob = 0;
                for (size_t ind=0; ind<ref.size(); ind++) {
                    int bit = (ind >> target) & 1; // target-th bit
                    if (bit == 0)
                        prob += pow(abs(ref[ind]), 2);
                }
                if (outcome == 1)
                    prob = 1 - prob;
                REQUIRE( calcProbOfOutcome(vec, target, outcome) == Approx(prob) );
            }
        }
        SECTION( "density-matrix" ) {
            SECTION( "pure" ) {
                // set mat to a random |r><r|
                QVector ref = getRandomStateVector(NUM_QUBITS);
                toQureg(mat, getKetBra(ref, ref));
                // calc prob of the state-vector
                qreal prob = 0;
                for (size_t ind=0; ind<ref.size(); ind++) {
                    int bit = (ind >> target) & 1; // target-th bit
                    if (bit == outcome)
                        prob += pow(abs(ref[ind]), 2);
                }
                REQUIRE( calcProbOfOutcome(mat, target, outcome) == Approx(prob) );
            }
            SECTION( "mixed" ) {
                QMatrix ref = getRandomDensityMatrix(NUM_QUBITS);
                toQureg(mat, ref);
                // prob is sum of diagonal amps (should be real) where target bit is outcome
                qcomp tr = 0;
                for (size_t ind=0; ind<ref.size(); ind++) {
                    int bit = (ind >> target) & 1; // target-th bit
                    if (bit == outcome)
                        tr += ref[ind][ind];
                }
                REQUIRE( imag(tr) == Approx(0).margin(REAL_EPS) );
                REQUIRE( calcProbOfOutcome(mat, target, outcome) == Approx(real(tr)) );
            }
            SECTION( "unnormalised" ) {
                QMatrix ref = getRandomQMatrix(1<<NUM_QUBITS);
                toQureg(mat, ref);
                // prob is (sum of real of diagonal amps where target bit is outcome)
                // or 1 - (this) if outcome == 1
                qreal tr = 0;
                for (size_t ind=0; ind<ref.size(); ind++) {
                    int bit = (ind >> target) & 1; // target-th bit
                    if (bit == 0)
                        tr += real(ref[ind][ind]);
                }
                if (outcome == 1)
                    tr = 1 - tr;
                REQUIRE( calcProbOfOutcome(mat, target, outcome) == Approx(tr) );
            }
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qubit indices" ) {
            int target = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( calcProbOfOutcome(vec, target, 0), Contains("Invalid target qubit") );
        }
        SECTION( "outcome value" ) {
            int outcome = GENERATE( -1, 2 );
            REQUIRE_THROWS_WITH( calcProbOfOutcome(vec, 0, outcome), Contains("Invalid measurement outcome") );
        }
    }
    destroyQureg(vec, QUEST_ENV);
    destroyQureg(mat, QUEST_ENV);
}
References calcProbOfOutcome(), createDensityQureg(), createQureg(), destroyQureg(), getKetBra(), getRandomDensityMatrix(), getRandomQMatrix(), getRandomQVector(), getRandomStateVector(), NUM_QUBITS, qcomp, qreal, QUEST_ENV, and toQureg().
TEST_CASE() [34/136]
TEST_CASE ("calcPurity" , "" [calculations])
See also
calcPurity
Author
Tyson Jones
Definition at line 1127 of file test_calculations.cpp.
{
    Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        // perform the following random tests 10 times
        GENERATE( range(1,10) );
        SECTION( "density-matrix" ) {
            SECTION( "pure" ) {
                // pure states have unity purity
                initZeroState(mat);
                REQUIRE( calcPurity(mat) == 1 );
                // (try also a pure random L2-vector)
                QVector r1 = getRandomStateVector(NUM_QUBITS); // |r>
                QMatrix m1 = getKetBra(r1, r1); // |r><r|
                toQureg(mat, m1);
                REQUIRE( calcPurity(mat) == Approx(1) );
            }
            SECTION( "mixed" ) {
                // mixed states have 1/2^N < purity < 1
                QMatrix ref = getRandomDensityMatrix(NUM_QUBITS);
                toQureg(mat, ref);
                qreal purity = calcPurity(mat);
                REQUIRE( purity < 1 );
                REQUIRE( purity >= 1/pow(2.,NUM_QUBITS) );
                // compare to Tr(rho^2)
                QMatrix prod = ref*ref;
                qreal tr = 0;
                for (size_t i=0; i<prod.size(); i++)
                    tr += real(prod[i][i]);
                REQUIRE( purity == Approx(tr) );
            }
            SECTION( "unnormalised" ) {
                // unphysical states give sum_{ij} |rho_ij|^2
                QMatrix ref = getRandomQMatrix(1<<NUM_QUBITS);
                qreal tot = 0;
                for (size_t i=0; i<ref.size(); i++)
                    for (size_t j=0; j<ref.size(); j++)
                        tot += pow(abs(ref[i][j]), 2);
                toQureg(mat, ref);
                REQUIRE( calcPurity(mat) == Approx(tot) );
            }
        }
    }
    SECTION( "input validation" ) {
        SECTION( "state-vector" ) {
            Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
            REQUIRE_THROWS_WITH( calcPurity(vec), Contains("valid only for density matrices") );
            destroyQureg(vec, QUEST_ENV);
        }
    }
    destroyQureg(mat, QUEST_ENV);
}
References calcPurity(), createDensityQureg(), createQureg(), destroyQureg(), getKetBra(), getRandomDensityMatrix(), getRandomQMatrix(), getRandomStateVector(), initZeroState(), NUM_QUBITS, qreal, QUEST_ENV, and toQureg().
TEST_CASE() [35/136]
TEST_CASE ("calcTotalProb" , "" [calculations])
See also
calcTotalProb
Author
Tyson Jones
Definition at line 1199 of file test_calculations.cpp.
{
    Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        SECTION( "state-vector" ) {
            // normalised: prob(vec) = 1
            initPlusState(vec);
            REQUIRE( calcTotalProb(vec) == Approx(1) );
            // zero norm: prob(vec) = 0
            initBlankState(vec);
            REQUIRE( calcTotalProb(vec) == 0 );
            // random L2 state: prob(vec) = 1
            toQureg(vec, getRandomStateVector(NUM_QUBITS));
            REQUIRE( calcTotalProb(vec) == Approx(1) );
            // unnormalised: prob(vec) = sum_i |vec_i|^2
            initDebugState(vec);
            QVector ref = toQVector(vec);
            qreal refProb = 0;
            for (size_t i=0; i<ref.size(); i++)
                refProb += pow(abs(ref[i]), 2);
            REQUIRE( calcTotalProb(vec) == Approx(refProb) );
        }
        SECTION( "density-matrix" ) {
            // normalised: prob(mat) = 1
            initPlusState(mat);
            REQUIRE( calcTotalProb(mat) == Approx(1) );
            // zero norm: prob(mat) = 0
            initBlankState(mat);
            REQUIRE( calcTotalProb(mat) == 0 );
            // random density matrix: prob(mat) = 1
            toQureg(mat, getRandomDensityMatrix(NUM_QUBITS));
            REQUIRE( calcTotalProb(mat) == Approx(1) );
            // unnormalised: prob(mat) = sum_i real(mat_{ii})
            initDebugState(mat);
            QMatrix ref = toQMatrix(mat);
            qreal refProb = 0;
            for (size_t i=0; i<ref.size(); i++)
                refProb += real(ref[i][i]);
            REQUIRE( calcTotalProb(mat) == Approx(refProb) );
        }
    }
    SECTION( "input validation" ) {
        // no validation
        SUCCEED();
    }
    destroyQureg(vec, QUEST_ENV);
    destroyQureg(mat, QUEST_ENV);
}
References calcTotalProb(), createDensityQureg(), createQureg(), destroyQureg(), getRandomDensityMatrix(), getRandomStateVector(), initBlankState(), initDebugState(), initPlusState(), NUM_QUBITS, qreal, QUEST_ENV, toQMatrix(), toQureg(), and toQVector().
TEST_CASE() [36/136]
TEST_CASE ("cloneQureg" , "" [state_initialisations])
See also
cloneQureg
Author
Tyson Jones
Definition at line 15 of file test_state_initialisations.cpp.
{
    Qureg vec1 = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg mat1 = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        SECTION( "state-vector" ) {
            Qureg vec2 = createQureg(NUM_QUBITS, QUEST_ENV);
            // make sure states start differently
            initDebugState(vec1);
            initBlankState(vec2);
            REQUIRE( !areEqual(vec1, vec2) );
            // make sure vec2 is changed
            QVector copy1 = toQVector(vec1);
            cloneQureg(vec2, vec1);
            REQUIRE( areEqual(vec1, vec2) );
            // make sure vec1 unaffected
            REQUIRE( areEqual(vec1, copy1) );
            destroyQureg(vec2, QUEST_ENV);
        }
        SECTION( "density-matrix" ) {
            Qureg mat2 = createDensityQureg(NUM_QUBITS, QUEST_ENV);
            // make sure states start differently
            initDebugState(mat1);
            initBlankState(mat2);
            REQUIRE( !areEqual(mat1, mat2) );
            // make sure vec2 is changed
            QMatrix copy1 = toQMatrix(mat1);
            cloneQureg(mat2, mat1);
            REQUIRE( areEqual(mat1, mat2) );
            // make sure vec1 unaffected
            REQUIRE( areEqual(mat1, copy1) );
            destroyQureg(mat2, QUEST_ENV);
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qureg type" ) {
            REQUIRE_THROWS_WITH( cloneQureg(mat1, vec1),  Contains("both be state-vectors") && Contains("density matrices") );
            REQUIRE_THROWS_WITH( cloneQureg(vec1, mat1),  Contains("both be state-vectors") && Contains("density matrices") );
        }
        SECTION( "qureg dimensions" ) {
            Qureg vec3 = createQureg(vec1.numQubitsRepresented + 1, QUEST_ENV);
            Qureg mat3 = createDensityQureg(mat1.numQubitsRepresented + 1, QUEST_ENV);
            REQUIRE_THROWS_WITH( cloneQureg(vec1, vec3), Contains("Dimensions") && Contains("don't match") );
            REQUIRE_THROWS_WITH( cloneQureg(mat1, mat3), Contains("Dimensions") && Contains("don't match") );
            destroyQureg(vec3, QUEST_ENV);
            destroyQureg(mat3, QUEST_ENV);
        }
    }
    destroyQureg(vec1, QUEST_ENV);
    destroyQureg(mat1, QUEST_ENV);
}
References areEqual(), cloneQureg(), createDensityQureg(), createQureg(), destroyQureg(), initBlankState(), initDebugState(), NUM_QUBITS, Qureg::numQubitsRepresented, QUEST_ENV, toQMatrix(), and toQVector().
TEST_CASE() [37/136]
TEST_CASE ("collapseToOutcome" , "" [gates])
See also
collapseToOutcome
Author
Tyson Jones
Definition at line 15 of file test_gates.cpp.
{
    Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        int qubit = GENERATE( range(0,NUM_QUBITS) );
        int outcome = GENERATE( 0, 1 );
        // repeat these random tests 10 times on every qubit, and for both outcomes
        GENERATE( range(0,10) );
        SECTION( "state-vector" ) {
            // use a random L2 state for every qubit & outcome
            QVector vecRef = getRandomStateVector(NUM_QUBITS);
            toQureg(vec, vecRef);
            // calculate prob of outcome
            qreal prob = 0;
            for (size_t ind=0; ind<vecRef.size(); ind++) {
                int bit = (ind >> qubit) & 1; // target-th bit
                if (bit == outcome)
                    prob += pow(abs(vecRef[ind]), 2);
            }
            // renormalise by the outcome prob
            for (size_t ind=0; ind<vecRef.size(); ind++) {
                int bit = (ind >> qubit) & 1; // target-th bit
                if (bit == outcome)
                    vecRef[ind] /= sqrt(prob);
                else
                    vecRef[ind] = 0;
            }
            qreal res = collapseToOutcome(vec, qubit, outcome);
            REQUIRE( res == Approx(prob) );
            REQUIRE( areEqual(vec, vecRef) );
        }
        SECTION( "density-matrix" ) {
            // use a random density matrix for every qubit & outcome
            QMatrix matRef = getRandomDensityMatrix(NUM_QUBITS);
            toQureg(mat, matRef);
            // prob is sum of diagonal amps (should be real) where target bit is outcome
            qcomp tr = 0;
            for (size_t ind=0; ind<matRef.size(); ind++) {
                int bit = (ind >> qubit) & 1; // qubit-th bit
                if (bit == outcome)
                    tr += matRef[ind][ind];
            }
            REQUIRE( imag(tr) == Approx(0).margin(REAL_EPS) );
            qreal prob = real(tr);
            // renorm (/prob) every |*outcome*><*outcome*| state, zeroing all others
            for (size_t r=0; r<matRef.size(); r++) {
                for (size_t c=0; c<matRef.size(); c++) {
                    int ketBit = (c >> qubit) & 1;
                    int braBit = (r >> qubit) & 1;
                    if (ketBit == outcome && braBit == outcome)
                        matRef[r][c] /= prob;
                    else
                        matRef[r][c] = 0;
                }
            }
            qreal res = collapseToOutcome(mat, qubit, outcome);
            REQUIRE( res == Approx(prob) );
            REQUIRE( areEqual(mat, matRef) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qubit index" ) {
            int qubit = GENERATE( -1, NUM_QUBITS );
            int outcome = 0;
            REQUIRE_THROWS_WITH( collapseToOutcome(mat, qubit, outcome), Contains("Invalid target qubit") );
        }
        SECTION( "outcome value" ) {
            int qubit = 0;
            int outcome = GENERATE( -1, 2 );
            REQUIRE_THROWS_WITH( collapseToOutcome(mat, qubit, outcome), Contains("Invalid measurement outcome") );
        }
        SECTION( "outcome probability" ) {
            initZeroState(vec);
            REQUIRE_THROWS_WITH( collapseToOutcome(vec, 0, 1), Contains("Can't collapse to state with zero probability") );
            initClassicalState(vec, 1);
            REQUIRE_THROWS_WITH( collapseToOutcome(vec, 0, 0), Contains("Can't collapse to state with zero probability") );
        }
    }
    destroyQureg(vec, QUEST_ENV);
    destroyQureg(mat, QUEST_ENV);
}
References areEqual(), collapseToOutcome(), createDensityQureg(), createQureg(), destroyQureg(), getRandomDensityMatrix(), getRandomStateVector(), initClassicalState(), initZeroState(), NUM_QUBITS, qcomp, qreal, QUEST_ENV, and toQureg().
TEST_CASE() [38/136]
TEST_CASE ("compactUnitary" , "" [unitaries])
See also
compactUnitary
Author
Tyson Jones
Definition at line 46 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    qcomp a = getRandomReal(-1,1) * expI(getRandomReal(0,2*M_PI));
    qcomp b = sqrt(1-abs(a)*abs(a)) * expI(getRandomReal(0,2*M_PI));
    Complex alpha; alpha.real = real(a); alpha.imag = imag(a);
    Complex beta; beta.real = real(b); beta.imag = imag(b);
    QMatrix op = toQMatrix(alpha, beta);
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        SECTION( "state-vector" ) {
            compactUnitary(quregVec, target, alpha, beta);
            applyReferenceOp(refVec, target, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            compactUnitary(quregMatr, target, alpha, beta);
            applyReferenceOp(refMatr, target, op);
            REQUIRE( areEqual(quregMatr, refMatr, 10*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qubit indices" ) {
            int target = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( compactUnitary(quregVec, target, alpha, beta), Contains("Invalid target") );
        }
        SECTION( "unitarity" ) {
            // unitary when |alpha|^2 + |beta|^2 = 1
            alpha.real=1; alpha.imag=2;
            beta.real=3; beta.imag=4;
            REQUIRE_THROWS_WITH( compactUnitary(quregVec, 0, alpha, beta), Contains("unitary") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, compactUnitary(), expI(), getRandomReal(), Complex::imag, M_PI, NUM_QUBITS, PREPARE_TEST, qcomp, Complex::real, and toQMatrix().
TEST_CASE() [39/136]
TEST_CASE ("controlledCompactUnitary" , "" [unitaries])
See also
controlledCompactUnitary
Author
Tyson Jones
Definition at line 217 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    qcomp a = getRandomReal(-1,1) * expI(getRandomReal(0,2*M_PI));
    qcomp b = sqrt(1-abs(a)*abs(a)) * expI(getRandomReal(0,2*M_PI));
    Complex alpha; alpha.real = real(a); alpha.imag = imag(a);
    Complex beta; beta.real = real(b); beta.imag = imag(b);
    QMatrix op = toQMatrix(alpha, beta);
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        int control = GENERATE_COPY( filter([=](int c){ return c!=target; }, range(0,NUM_QUBITS)) );
        SECTION( "state-vector" ) {
            controlledCompactUnitary(quregVec, control, target, alpha, beta);
            applyReferenceOp(refVec, control, target, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            controlledCompactUnitary(quregMatr, control, target, alpha, beta);
            applyReferenceOp(refMatr, control, target, op);
            REQUIRE( areEqual(quregMatr, refMatr, 10*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "control and target collision" ) {
            int qb = 0;
            REQUIRE_THROWS_WITH( controlledCompactUnitary(quregVec, qb, qb, alpha, beta), Contains("Control") && Contains("target") );
        }
        SECTION( "qubit indices" ) {
            int qb = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( controlledCompactUnitary(quregVec, qb, 0, alpha, beta), Contains("Invalid control") );
            REQUIRE_THROWS_WITH( controlledCompactUnitary(quregVec, 0, qb, alpha, beta), Contains("Invalid target") );
        }
        SECTION( "unitarity" ) {
            // unitary when |a|^2 + |b^2 = 1
            alpha.real=1; alpha.imag=2;
            beta.real=3; beta.imag=4;
            REQUIRE_THROWS_WITH( controlledCompactUnitary(quregVec, 0, 1, alpha, beta), Contains("unitary") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, controlledCompactUnitary(), expI(), getRandomReal(), Complex::imag, M_PI, NUM_QUBITS, PREPARE_TEST, qcomp, Complex::real, and toQMatrix().
TEST_CASE() [40/136]
TEST_CASE ("controlledMultiQubitUnitary" , "" [unitaries])
See also
controlledMultiQubitUnitary
Author
Tyson Jones
Definition at line 275 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    // figure out max-num targs (inclusive) allowed by hardware backend
    int maxNumTargs = calcLog2(quregVec.numAmpsPerChunk);
    if (maxNumTargs >= NUM_QUBITS)
        maxNumTargs = NUM_QUBITS - 1; // make space for control qubit
    SECTION( "correctness" ) {
        // generate all possible qubit arrangements
        int ctrl = GENERATE( range(0,NUM_QUBITS) );
        int numTargs = GENERATE_COPY( range(1,maxNumTargs+1) );
        int* targs = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numTargs, ctrl) );
        // for each qubit arrangement, use a new random unitary
        QMatrix op = getRandomUnitary(numTargs);
        ComplexMatrixN matr = createComplexMatrixN(numTargs);
        toComplexMatrixN(op, matr);
        SECTION( "state-vector" ) {
            controlledMultiQubitUnitary(quregVec, ctrl, targs, numTargs, matr);
            applyReferenceOp(refVec, ctrl, targs, numTargs, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            controlledMultiQubitUnitary(quregMatr, ctrl, targs, numTargs, matr);
            applyReferenceOp(refMatr, ctrl, targs, numTargs, op);
            REQUIRE( areEqual(quregMatr, refMatr, 10*REAL_EPS) );
        }
        destroyComplexMatrixN(matr);
    }
    SECTION( "input validation" ) {
        SECTION( "number of targets" ) {
            // there cannot be more targets than qubits in register
            // (numTargs=NUM_QUBITS is caught elsewhere, because that implies ctrl is invalid)
            int numTargs = GENERATE( -1, 0, NUM_QUBITS+1 );
            int targs[NUM_QUBITS+1]; // prevents seg-fault if validation doesn't trigger
            ComplexMatrixN matr = createComplexMatrixN(NUM_QUBITS+1); // prevent seg-fault
            REQUIRE_THROWS_WITH( controlledMultiQubitUnitary(quregVec, 0, targs, numTargs, matr), Contains("Invalid number of target"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "repetition in targets" ) {
            int ctrl = 0;
            int numTargs = 3;
            int targs[] = {1,2,2};
            ComplexMatrixN matr = createComplexMatrixN(numTargs); // prevents seg-fault if validation doesn't trigger
            REQUIRE_THROWS_WITH( controlledMultiQubitUnitary(quregVec, ctrl, targs, numTargs, matr), Contains("target") && Contains("unique"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "control and target collision" ) {
            int numTargs = 3;
            int targs[] = {0,1,2};
            int ctrl = targs[GENERATE_COPY( range(0,numTargs) )];
            ComplexMatrixN matr = createComplexMatrixN(numTargs); // prevents seg-fault if validation doesn't trigger
            REQUIRE_THROWS_WITH( controlledMultiQubitUnitary(quregVec, ctrl, targs, numTargs, matr), Contains("Control") && Contains("target"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "qubit indices" ) {
            int ctrl = 0;
            int numTargs = 3;
            int targs[] = {1,2,3};
            ComplexMatrixN matr = createComplexMatrixN(numTargs); // prevents seg-fault if validation doesn't trigger
            int inv = GENERATE( -1, NUM_QUBITS );
            ctrl = inv;
            REQUIRE_THROWS_WITH( controlledMultiQubitUnitary(quregVec, ctrl, targs, numTargs, matr), Contains("Invalid control") );
            ctrl = 0; // restore valid ctrl
            targs[GENERATE_COPY( range(0,numTargs) )] = inv; // make invalid target
            REQUIRE_THROWS_WITH( controlledMultiQubitUnitary(quregVec, ctrl, targs, numTargs, matr), Contains("Invalid target") );
            destroyComplexMatrixN(matr);
        }
        SECTION( "unitarity" ) {
            int ctrl = 0;
            int numTargs = GENERATE_COPY( range(1,maxNumTargs+1) );
            ComplexMatrixN matr = createComplexMatrixN(numTargs); // initially zero, hence not-unitary
            VLA(int, targs, numTargs);
            for (int i=0; i<numTargs; i++)
                targs[i] = i+1;
            REQUIRE_THROWS_WITH( controlledMultiQubitUnitary(quregVec, ctrl, targs, numTargs, matr), Contains("unitary") );
            destroyComplexMatrixN(matr);
        }
        SECTION( "unitary creation" ) {
            int numTargs = 3;
            int targs[] = {1,2,3};
            /* compilers don't auto-initialise to NULL; the below circumstance
             * only really occurs when 'malloc' returns NULL in createComplexMatrixN,
             * which actually triggers its own validation. Hence this test is useless
             * currently.
             */
            ComplexMatrixN matr;
            matr.real = NULL;
            matr.imag = NULL;
            REQUIRE_THROWS_WITH( controlledMultiQubitUnitary(quregVec, 0, targs, numTargs, matr), Contains("created") );
        }
        SECTION( "unitary dimensions" ) {
            int ctrl = 0;
            int targs[2] = {1,2};
            ComplexMatrixN matr = createComplexMatrixN(3);
            REQUIRE_THROWS_WITH( controlledMultiQubitUnitary(quregVec, ctrl, targs, 2, matr), Contains("matrix size"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "unitary fits in node" ) {
            // pretend we have a very limited distributed memory (judged by matr size)
            quregVec.numAmpsPerChunk = 1;
            int qb[] = {1,2};
            ComplexMatrixN matr = createComplexMatrixN(2); // prevents seg-fault if validation doesn't trigger
            REQUIRE_THROWS_WITH( controlledMultiQubitUnitary(quregVec, 0, qb, 2, matr), Contains("targets too many qubits"));
            destroyComplexMatrixN(matr);
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), calcLog2(), CLEANUP_TEST, controlledMultiQubitUnitary(), createComplexMatrixN(), destroyComplexMatrixN(), getRandomUnitary(), ComplexMatrixN::imag, NUM_QUBITS, PREPARE_TEST, ComplexMatrixN::real, sublists(), toComplexMatrixN(), and VLA.
TEST_CASE() [41/136]
TEST_CASE ("controlledNot" , "" [unitaries])
See also
controlledNot
Author
Tyson Jones
Definition at line 415 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    QMatrix op{{0,1},{1,0}};
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        int control = GENERATE_COPY( filter([=](int c){ return c!=target; }, range(0,NUM_QUBITS)) );
        SECTION( "state-vector" ) {
            controlledNot(quregVec, control, target);
            applyReferenceOp(refVec, control, target, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            controlledNot(quregMatr, control, target);
            applyReferenceOp(refMatr, control, target, op);
            REQUIRE( areEqual(quregMatr, refMatr) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "control and target collision" ) {
            int qb = GENERATE( range(0,NUM_QUBITS) );
            REQUIRE_THROWS_WITH( controlledNot(quregVec, qb, qb), Contains("Control") && Contains("target") );
        }
        SECTION( "qubit indices" ) {
            int qb = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( controlledNot(quregVec, qb, 0), Contains("Invalid control") );
            REQUIRE_THROWS_WITH( controlledNot(quregVec, 0, qb), Contains("Invalid target") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, controlledNot(), NUM_QUBITS, and PREPARE_TEST.
TEST_CASE() [42/136]
TEST_CASE ("controlledPauliY" , "" [unitaries])
See also
controlledPauliY
Author
Tyson Jones
Definition at line 461 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    QMatrix op{{0,-qcomp(0,1)},{qcomp(0,1),0}};
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        int control = GENERATE_COPY( filter([=](int c){ return c!=target; }, range(0,NUM_QUBITS)) );
        SECTION( "state-vector" ) {
            controlledPauliY(quregVec, control, target);
            applyReferenceOp(refVec, control, target, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            controlledPauliY(quregMatr, control, target);
            applyReferenceOp(refMatr, control, target, op);
            REQUIRE( areEqual(quregMatr, refMatr) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "control and target collision" ) {
            int qb = GENERATE( range(0,NUM_QUBITS) );
            REQUIRE_THROWS_WITH( controlledPauliY(quregVec, qb, qb), Contains("Control") && Contains("target") );
        }
        SECTION( "qubit indices" ) {
            int qb = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( controlledPauliY(quregVec, qb, 0), Contains("Invalid control") );
            REQUIRE_THROWS_WITH( controlledPauliY(quregVec, 0, qb), Contains("Invalid target") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, controlledPauliY(), NUM_QUBITS, PREPARE_TEST, and qcomp.
TEST_CASE() [43/136]
TEST_CASE ("controlledPhaseFlip" , "" [unitaries])
See also
controlledPhaseFlip
Author
Tyson Jones
Definition at line 507 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    QMatrix op{{1,0},{0,-1}};
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        int control = GENERATE_COPY( filter([=](int c){ return c!=target; }, range(0,NUM_QUBITS)) );
        SECTION( "state-vector" ) {
            controlledPhaseFlip(quregVec, control, target);
            applyReferenceOp(refVec, control, target, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            controlledPhaseFlip(quregMatr, control, target);
            applyReferenceOp(refMatr, control, target, op);
            REQUIRE( areEqual(quregMatr, refMatr) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "control and target collision" ) {
            int qb = GENERATE( range(0,NUM_QUBITS) );
            REQUIRE_THROWS_WITH( controlledPhaseFlip(quregVec, qb, qb), Contains("Control") && Contains("target") );
        }
        SECTION( "qubit indices" ) {
            int qb = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( controlledPhaseFlip(quregVec, qb, 0), Contains("Invalid control") );
            REQUIRE_THROWS_WITH( controlledPhaseFlip(quregVec, 0, qb), Contains("Invalid target") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, controlledPhaseFlip(), NUM_QUBITS, and PREPARE_TEST.
TEST_CASE() [44/136]
TEST_CASE ("controlledPhaseShift" , "" [unitaries])
See also
controlledPhaseShift
Author
Tyson Jones
Definition at line 553 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    qreal param = getRandomReal(-2*M_PI, 2*M_PI);
    QMatrix op{{1,0},{0,expI(param)}};
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        int control = GENERATE_COPY( filter([=](int c){ return c!=target; }, range(0,NUM_QUBITS)) );
        SECTION( "state-vector" ) {
            controlledPhaseShift(quregVec, control, target, param);
            applyReferenceOp(refVec, control, target, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            controlledPhaseShift(quregMatr, control, target, param);
            applyReferenceOp(refMatr, control, target, op);
            REQUIRE( areEqual(quregMatr, refMatr) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "control and target collision" ) {
            int qb = GENERATE( range(0,NUM_QUBITS) );
            REQUIRE_THROWS_WITH( controlledPhaseShift(quregVec, qb, qb, param), Contains("Control") && Contains("target") );
        }
        SECTION( "qubit indices" ) {
            int qb = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( controlledPhaseShift(quregVec, qb, 0, param), Contains("Invalid control") );
            REQUIRE_THROWS_WITH( controlledPhaseShift(quregVec, 0, qb, param), Contains("Invalid target") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, controlledPhaseShift(), expI(), getRandomReal(), M_PI, NUM_QUBITS, PREPARE_TEST, and qreal.
TEST_CASE() [45/136]
TEST_CASE ("controlledRotateAroundAxis" , "" [unitaries])
See also
controlledRotateAroundAxis
Author
Tyson Jones
Definition at line 600 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    // each test will use a random parameter and axis vector
    qreal param = getRandomReal(-4*M_PI, 4*M_PI);
    Vector vec;
    vec.x=getRandomReal(-1,1);
    vec.y=getRandomReal(-1,1);
    vec.z=getRandomReal(-1,1);
    // Rn(a) = cos(a/2)I - i sin(a/2) n . paulivector
    // (pg 24 of vcpc.univie.ac.at/~ian/hotlist/qc/talks/bloch-sphere-rotations.pdf)
    qreal c = cos(param/2);
    qreal s = sin(param/2);
    qreal m = sqrt(vec.x*vec.x + vec.y*vec.y + vec.z*vec.z);
    QMatrix op{{c - qcomp(0,1)*vec.z*s/m, -(vec.y + qcomp(0,1)*vec.x)*s/m},
               {(vec.y - qcomp(0,1)*vec.x)*s/m, c + qcomp(0,1)*vec.z*s/m}};
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        int control = GENERATE_COPY( filter([=](int c){ return c!=target; }, range(0,NUM_QUBITS)) );
        SECTION( "state-vector" ) {
            controlledRotateAroundAxis(quregVec, control, target, param, vec);
            applyReferenceOp(refVec, control, target, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            controlledRotateAroundAxis(quregMatr, control, target, param, vec);
            applyReferenceOp(refMatr, control, target, op);
            REQUIRE( areEqual(quregMatr, refMatr, 10*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "control and target collision" ) {
            int qb = GENERATE( range(0,NUM_QUBITS) );
            REQUIRE_THROWS_WITH( controlledRotateAroundAxis(quregVec, qb, qb, param, vec), Contains("Control") && Contains("target") );
        }
        SECTION( "qubit indices" ) {
            int qb = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( controlledRotateAroundAxis(quregVec, qb, 0, param, vec), Contains("Invalid control") );
            REQUIRE_THROWS_WITH( controlledRotateAroundAxis(quregVec, 0, qb, param, vec), Contains("Invalid target") );
        }
        SECTION( "zero rotation axis" ) {
            vec.x=0; vec.y=0; vec.z=0;
            REQUIRE_THROWS_WITH( controlledRotateAroundAxis(quregVec, 0, 1, param, vec), Contains("Invalid axis") && Contains("zero") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, controlledRotateAroundAxis(), getRandomReal(), M_PI, NUM_QUBITS, PREPARE_TEST, qcomp, qreal, Vector::x, Vector::y, and Vector::z.
TEST_CASE() [46/136]
TEST_CASE ("controlledRotateX" , "" [unitaries])
See also
controlledRotateX
Author
Tyson Jones
Definition at line 665 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    qreal param = getRandomReal(-4*M_PI, 4*M_PI);
    QMatrix op{
        {cos(param/2), -sin(param/2)*qcomp(0,1)},
        {-sin(param/2)*qcomp(0,1), cos(param/2)}};
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        int control = GENERATE_COPY( filter([=](int c){ return c!=target; }, range(0,NUM_QUBITS)) );
        SECTION( "state-vector" ) {
            controlledRotateX(quregVec, control, target, param);
            applyReferenceOp(refVec, control, target, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            controlledRotateX(quregMatr, control, target, param);
            applyReferenceOp(refMatr, control, target, op);
            REQUIRE( areEqual(quregMatr, refMatr) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "control and target collision" ) {
            int qb = GENERATE( range(0,NUM_QUBITS) );
            REQUIRE_THROWS_WITH( controlledRotateX(quregVec, qb, qb, param), Contains("Control") && Contains("target") );
        }
        SECTION( "qubit indices" ) {
            int qb = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( controlledRotateX(quregVec, qb, 0, param), Contains("Invalid control") );
            REQUIRE_THROWS_WITH( controlledRotateX(quregVec, 0, qb, param), Contains("Invalid target") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, controlledRotateX(), getRandomReal(), M_PI, NUM_QUBITS, PREPARE_TEST, qcomp, and qreal.
TEST_CASE() [47/136]
TEST_CASE ("controlledRotateY" , "" [unitaries])
See also
controlledRotateY
Author
Tyson Jones
Definition at line 714 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    qreal param = getRandomReal(-4*M_PI, 4*M_PI);
    QMatrix op{{cos(param/2), -sin(param/2)},{sin(param/2), cos(param/2)}};
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        int control = GENERATE_COPY( filter([=](int c){ return c!=target; }, range(0,NUM_QUBITS)) );
        SECTION( "state-vector" ) {
            controlledRotateY(quregVec, control, target, param);
            applyReferenceOp(refVec, control, target, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            controlledRotateY(quregMatr, control, target, param);
            applyReferenceOp(refMatr, control, target, op);
            REQUIRE( areEqual(quregMatr, refMatr, 4*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "control and target collision" ) {
            int qb = GENERATE( range(0,NUM_QUBITS) );
            REQUIRE_THROWS_WITH( controlledRotateY(quregVec, qb, qb, param), Contains("Control") && Contains("target") );
        }
        SECTION( "qubit indices" ) {
            int qb = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( controlledRotateY(quregVec, qb, 0, param), Contains("Invalid control") );
            REQUIRE_THROWS_WITH( controlledRotateY(quregVec, 0, qb, param), Contains("Invalid target") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, controlledRotateY(), getRandomReal(), M_PI, NUM_QUBITS, PREPARE_TEST, and qreal.
TEST_CASE() [48/136]
TEST_CASE ("controlledRotateZ" , "" [unitaries])
See also
controlledRotateZ
Author
Tyson Jones
Definition at line 761 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    qreal param = getRandomReal(-4*M_PI, 4*M_PI);
    QMatrix op{{expI(-param/2.),0},{0,expI(param/2.)}};
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        int control = GENERATE_COPY( filter([=](int c){ return c!=target; }, range(0,NUM_QUBITS)) );
        SECTION( "state-vector" ) {
            controlledRotateZ(quregVec, control, target, param);
            applyReferenceOp(refVec, control, target, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            controlledRotateZ(quregMatr, control, target, param);
            applyReferenceOp(refMatr, control, target, op);
            REQUIRE( areEqual(quregMatr, refMatr, 10*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "control and target collision" ) {
            int qb = GENERATE( range(0,NUM_QUBITS) );
            REQUIRE_THROWS_WITH( controlledRotateZ(quregVec, qb, qb, param), Contains("Control") && Contains("target") );
        }
        SECTION( "qubit indices" ) {
            int qb = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( controlledRotateZ(quregVec, qb, 0, param), Contains("Invalid control") );
            REQUIRE_THROWS_WITH( controlledRotateZ(quregVec, 0, qb, param), Contains("Invalid target") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, controlledRotateZ(), expI(), getRandomReal(), M_PI, NUM_QUBITS, PREPARE_TEST, and qreal.
TEST_CASE() [49/136]
TEST_CASE ("controlledTwoQubitUnitary" , "" [unitaries])
See also
controlledTwoQubitUnitary
Author
Tyson Jones
Definition at line 808 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    // in distributed mode, each node must be able to fit all amps modified by unitary
    REQUIRE( quregVec.numAmpsPerChunk >= 4 );
    // every test will use a unique random matrix
    QMatrix op = getRandomUnitary(2);
    ComplexMatrix4 matr = toComplexMatrix4(op);
    SECTION( "correctness" ) {
        int targ1 = GENERATE( range(0,NUM_QUBITS) );
        int targ2 = GENERATE_COPY( filter([=](int t){ return t!=targ1; }, range(0,NUM_QUBITS)) );
        int control = GENERATE_COPY( filter([=](int c){ return c!=targ1 && c!=targ2; }, range(0,NUM_QUBITS)) );
        SECTION( "state-vector" ) {
            controlledTwoQubitUnitary(quregVec, control, targ1, targ2, matr);
            applyReferenceOp(refVec, control, targ1, targ2, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            controlledTwoQubitUnitary(quregMatr, control, targ1, targ2, matr);
            applyReferenceOp(refMatr, control, targ1, targ2, op);
            REQUIRE( areEqual(quregMatr, refMatr, 10*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "repetition of targets" ) {
            int targ = 0;
            int ctrl = 1;
            REQUIRE_THROWS_WITH( controlledTwoQubitUnitary(quregVec, ctrl, targ, targ, matr), Contains("target") && Contains("unique") );
        }
        SECTION( "control and target collision" ) {
            int targ1 = 1;
            int targ2 = 2;
            int ctrl = GENERATE( 1,2 ); // catch2 bug; can't do GENERATE_COPY( targ1, targ2 )
            REQUIRE_THROWS_WITH( controlledTwoQubitUnitary(quregVec, ctrl, targ1, targ2, matr), Contains("Control") && Contains("target") );
        }
        SECTION( "qubit indices" ) {
            // valid config
            int ctrl = 0;
            int targ1 = 1;
            int targ2 = 2;
            int qb = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( controlledTwoQubitUnitary(quregVec, qb, targ1, targ2, matr), Contains("Invalid control") );
            REQUIRE_THROWS_WITH( controlledTwoQubitUnitary(quregVec, ctrl, qb, targ2, matr), Contains("Invalid target") );
            REQUIRE_THROWS_WITH( controlledTwoQubitUnitary(quregVec, ctrl, targ1, qb, matr), Contains("Invalid target") );
        }
        SECTION( "unitarity" ) {
            matr.real[0][0] = 0; // break matr unitarity
            REQUIRE_THROWS_WITH( controlledTwoQubitUnitary(quregVec, 0, 1, 2, matr), Contains("unitary") );
        }
        SECTION( "unitary fits in node" ) {
            // pretend we have a very limited distributed memory
            quregVec.numAmpsPerChunk = 1;
            REQUIRE_THROWS_WITH( controlledTwoQubitUnitary(quregVec, 0, 1, 2, matr), Contains("targets too many qubits"));
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, controlledTwoQubitUnitary(), getRandomUnitary(), NUM_QUBITS, PREPARE_TEST, ComplexMatrix4::real, and toComplexMatrix4().
TEST_CASE() [50/136]
TEST_CASE ("controlledUnitary" , "" [unitaries])
See also
controlledUnitary
Author
Tyson Jones
Definition at line 885 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    QMatrix op = getRandomUnitary(1);
    ComplexMatrix2 matr = toComplexMatrix2(op);
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        int control = GENERATE_COPY( filter([=](int c){ return c!=target; }, range(0,NUM_QUBITS)) );
        SECTION( "state-vector" ) {
            controlledUnitary(quregVec, control, target, matr);
            applyReferenceOp(refVec, control, target, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            controlledUnitary(quregMatr, control, target, matr);
            applyReferenceOp(refMatr, control, target, op);
            REQUIRE( areEqual(quregMatr, refMatr, 10*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "control and target collision" ) {
            int qb = GENERATE( range(0,NUM_QUBITS) );
            REQUIRE_THROWS_WITH( controlledUnitary(quregVec, qb, qb, matr), Contains("Control") && Contains("target") );
        }
        SECTION( "qubit indices" ) {
            int qb = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( controlledUnitary(quregVec, qb, 0, matr), Contains("Invalid control") );
            REQUIRE_THROWS_WITH( controlledUnitary(quregVec, 0, qb, matr), Contains("Invalid target") );
        }
        SECTION( "unitarity" ) {
            matr.real[0][0] = 0; // break unitarity
            REQUIRE_THROWS_WITH( controlledUnitary(quregVec, 0, 1, matr), Contains("unitary") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, controlledUnitary(), getRandomUnitary(), NUM_QUBITS, PREPARE_TEST, ComplexMatrix2::real, and toComplexMatrix2().
TEST_CASE() [51/136]
TEST_CASE ("createCloneQureg" , "" [data_structures])
See also
createCloneQureg
Author
Tyson Jones
Definition at line 64 of file test_data_structures.cpp.
{
    SECTION( "state-vector" ) {
        Qureg a = createQureg(NUM_QUBITS, QUEST_ENV);
        Qureg b = createCloneQureg(a, QUEST_ENV);
        // check properties are the same
        REQUIRE( b.isDensityMatrix == a.isDensityMatrix );
        REQUIRE( b.numQubitsRepresented == a.numQubitsRepresented );
        REQUIRE( b.numQubitsInStateVec == a.numQubitsInStateVec );
        REQUIRE( b.numAmpsPerChunk == a.numAmpsPerChunk );
        REQUIRE( b.numAmpsTotal == a.numAmpsTotal );
        // check state-vector is the same (works for GPU and distributed)
        REQUIRE( areEqual(a, b) );
        destroyQureg(a, QUEST_ENV);
        destroyQureg(b, QUEST_ENV);
    }
    SECTION( "density-matrix" ) {
        Qureg a = createDensityQureg(NUM_QUBITS, QUEST_ENV);
        Qureg b = createCloneQureg(a, QUEST_ENV);
        // check properties are the same
        REQUIRE( b.isDensityMatrix == a.isDensityMatrix );
        REQUIRE( b.numQubitsRepresented == a.numQubitsRepresented );
        REQUIRE( b.numQubitsInStateVec == a.numQubitsInStateVec );
        REQUIRE( b.numAmpsPerChunk == a.numAmpsPerChunk );
        REQUIRE( b.numAmpsTotal == a.numAmpsTotal );
        // check state-vector is the same (works for GPU and distributed)
        REQUIRE( areEqual(a, b) );
        destroyQureg(a, QUEST_ENV);
        destroyQureg(b, QUEST_ENV);
    }
}
References areEqual(), createCloneQureg(), createDensityQureg(), createQureg(), destroyQureg(), Qureg::isDensityMatrix, NUM_QUBITS, Qureg::numAmpsPerChunk, Qureg::numAmpsTotal, Qureg::numQubitsInStateVec, Qureg::numQubitsRepresented, and QUEST_ENV.
TEST_CASE() [52/136]
TEST_CASE ("createComplexMatrixN" , "" [data_structures])
See also
createComplexMatrixN
Author
Tyson Jones
Definition at line 110 of file test_data_structures.cpp.
{
    SECTION( "correctness" ) {
        int numQb = GENERATE( range(1,10+1) );
        ComplexMatrixN m = createComplexMatrixN(numQb);
        // ensure elems are created and initialised to 0
        REQUIRE( areEqual(toQMatrix(m), getZeroMatrix(1<<numQb)) );
        destroyComplexMatrixN(m);
    }
    SECTION( "input validation" ) {
        SECTION( "number of qubits" ) {
            int numQb = GENERATE( -1, 0 );
            REQUIRE_THROWS_WITH( createComplexMatrixN(numQb), Contains("Invalid number of qubits") );
        }
    }
}
References areEqual(), createComplexMatrixN(), destroyComplexMatrixN(), getZeroMatrix(), and toQMatrix().
TEST_CASE() [53/136]
TEST_CASE ("createDensityQureg" , "" [data_structures])
See also
createDensityQureg
Author
Tyson Jones
Definition at line 138 of file test_data_structures.cpp.
{
    // must be at least one amplitude per node
    int minNumQb = calcLog2(QUEST_ENV.numRanks) - 1; // density matrix has 2*numQb in state-vec
    if (minNumQb <= 0)
        minNumQb = 1;
    SECTION( "correctness" ) {
        // try 10 valid number of qubits
        int numQb = GENERATE_COPY( range(minNumQb, minNumQb+10) );
        Qureg reg = createDensityQureg(numQb, QUEST_ENV);
        // ensure elems (CPU and/or GPU) are created, and reg begins in |0><0|
        QMatrix ref = getZeroMatrix(1<<numQb);
        ref[0][0] = 1; // |0><0|
        REQUIRE( areEqual(reg, ref) );
        destroyQureg(reg, QUEST_ENV);
    }
    SECTION( "input validation") {
        SECTION( "number of qubits" ) {
            int numQb = GENERATE( -1, 0 );
            REQUIRE_THROWS_WITH( createDensityQureg(numQb, QUEST_ENV), Contains("Invalid number of qubits") );
        }
        SECTION( "number of amplitudes" ) {
            // use local QuESTEnv to safely modify
            QuESTEnv env = QUEST_ENV;
            // too many amplitudes to store in type
            int maxQb = (int) calcLog2(SIZE_MAX) / 2;
            REQUIRE_THROWS_WITH( createDensityQureg(maxQb+1, env), Contains("Too many qubits") && Contains("size_t type") );
            /* n-qubit density matrix contains 2^(2n) amplitudes
             * so can be spread between at most 2^(2n) ranks
             */
            /* env.numRanks is an int, so maxQb must be capped at 16 for this
             * test to avoid an integer overflow when storing 2**(2*minQb) in it
             */
            maxQb = maxQb > 16 ? 16 : maxQb;
            int minQb = GENERATE_COPY( range(3,maxQb) );
            env.numRanks = (int) pow(2, 2*minQb);
            int numQb = GENERATE_COPY( range(1,minQb) );
            REQUIRE_THROWS_WITH( createDensityQureg(numQb, env), Contains("Too few qubits") );
        }
        SECTION( "available memory" ) {
            /* there is no reliable way to force the malloc statements to
             * fail, and hence trigger the matrixInit validation */
            SUCCEED( );
        }
    }
}
References areEqual(), calcLog2(), createDensityQureg(), destroyQureg(), getZeroMatrix(), QuESTEnv::numRanks, and QUEST_ENV.
TEST_CASE() [54/136]
TEST_CASE ("createDiagonalOp" , "" [data_structures])
See also
createDiagonalOp
Author
Tyson Jones
Definition at line 201 of file test_data_structures.cpp.
{
    // must be at least one amplitude per node
    int minNumQb = calcLog2(QUEST_ENV.numRanks);
    if (minNumQb == 0)
        minNumQb = 1;
    SECTION( "correctness" ) {
        // try 10 valid number of qubits
        int numQb = GENERATE_COPY( range(minNumQb, minNumQb+10) );
        DiagonalOp op = createDiagonalOp(numQb, QUEST_ENV);
        // check properties are correct
        REQUIRE( op.numQubits == numQb );
        REQUIRE( op.chunkId == QUEST_ENV.rank );
        REQUIRE( op.numChunks == QUEST_ENV.numRanks );
        REQUIRE( op.numElemsPerChunk == (1LL << numQb) / QUEST_ENV.numRanks );
        REQUIRE( op.real != NULL );
        REQUIRE( op.imag != NULL );
        // check all elements in CPU are zero
        REQUIRE( areEqual(toQVector(op), QVector(1LL << numQb)) );
        // (no concise way to check this for GPU)
        destroyDiagonalOp(op, QUEST_ENV);
    }
    SECTION( "input validation" ) {
        SECTION( "number of qubits" ) {
            int numQb = GENERATE( -1, 0 );
            REQUIRE_THROWS_WITH( createDiagonalOp(numQb, QUEST_ENV), Contains("Invalid number of qubits") );
        }
        SECTION( "number of elements" ) {
            // use local QuESTEnv to safely modify
            QuESTEnv env = QUEST_ENV;
            // too many amplitudes to store in type
            int maxQb = (int) calcLog2(SIZE_MAX);
            REQUIRE_THROWS_WITH( createDiagonalOp(maxQb+1, env), Contains("Too many qubits") && Contains("size_t type") );
            /* env.numRanks is an int, so maxQb must be capped at 32 for this
             * test to avoid an integer overflow when storing 2**minQb in it
             */
            maxQb = maxQb > 32 ? 32 : maxQb;
            // too few amplitudes to distribute
            int minQb = GENERATE_COPY( range(2,maxQb) );
            env.numRanks = (int) pow(2, minQb);
            int numQb = GENERATE_COPY( range(1,minQb) );
            REQUIRE_THROWS_WITH( createDiagonalOp(numQb, env), Contains("Too few qubits") && Contains("distributed"));
        }
        SECTION( "available memory" ) {
            /* there is no reliable way to force the malloc statements to
             * fail, and hence trigger the diagonalOpInit validation */
            SUCCEED( );
        }
    }
}
References areEqual(), calcLog2(), DiagonalOp::chunkId, createDiagonalOp(), destroyDiagonalOp(), DiagonalOp::imag, DiagonalOp::numChunks, DiagonalOp::numElemsPerChunk, DiagonalOp::numQubits, QuESTEnv::numRanks, QUEST_ENV, QuESTEnv::rank, DiagonalOp::real, and toQVector().
TEST_CASE() [55/136]
TEST_CASE ("createDiagonalOpFromPauliHamilFile" , "" [data_structures])
See also
createDiagonalOpFromPauliHamilFile
Author
Tyson Jones
Definition at line 270 of file test_data_structures.cpp.
{
    // files created & populated during the test, and deleted afterward
    char fnPrefix[] = "temp_createDiagonalOpFromPauliHamilFile";
    char fn[100];
    // each test uses a unique filename (managed by master node), to avoid file IO locks
    // (it's safe for sub-test to overwrite this, since after each test, all files
    //  with prefix fnPrefix are deleted)
    setUniqueFilename(fn, fnPrefix);
    // diagonal op must have at least one amplitude per node
    int minNumQb = calcLog2(QUEST_ENV.numRanks);
    if (minNumQb == 0)
        minNumQb = 1;
    SECTION( "correctness" ) {
        SECTION( "general" ) {
            // try several Pauli Hamiltonian sizes
            int numQb = GENERATE_COPY( range(minNumQb, 6+minNumQb) );
            int numTerms = GENERATE_COPY( 1, minNumQb, 10*minNumQb );
            // create a PauliHamil with random elements
            PauliHamil hamil = createPauliHamil(numQb, numTerms);
            setRandomDiagPauliHamil(hamil);
            // write the Hamiltonian to file (with trailing whitespace, and trailing newline)
            if (QUEST_ENV.rank == 0) {
                FILE* file = fopen(fn, "w");
                int i=0;
                for (int n=0; n<numTerms; n++) {
                    fprintf(file, REAL_STRING_FORMAT, hamil.termCoeffs[n]);
                    fprintf(file, " ");
                    for (int q=0; q<numQb; q++)
                        fprintf(file, "%d ", (int) hamil.pauliCodes[i++]);
                    fprintf(file, "\n");
                }
                fprintf(file, "\n");
                fclose(file);
            }
            syncQuESTEnv(QUEST_ENV);
            // load the file as a diagonal operator, and compare
            DiagonalOp op = createDiagonalOpFromPauliHamilFile(fn, QUEST_ENV);
            REQUIRE( areEqual(toQMatrix(op), toQMatrix(hamil)) );
            destroyPauliHamil(hamil);
            destroyDiagonalOp(op, QUEST_ENV);
        }
        SECTION( "edge cases" ) {
            // prepare a valid single-term diagonal Pauli Hamiltonian
            qreal coeffs[] = {.1};
            VLA(pauliOpType, codes, minNumQb);
            for (int q=0; q<minNumQb; q++)
                codes[q] = (q%2)? PAULI_I : PAULI_Z;
            QMatrix ref = toQMatrix(coeffs, codes, minNumQb, 1);
            // prepare basic encoding string
            string line = to_string(coeffs[0]) + " ";
            for (int q=0; q<minNumQb; q++)
                line += to_string(codes[q]) + ((q<minNumQb-1)? " ":"");
            SECTION( "no trailing newline or space" ) {
                writeToFileSynch(fn, line);
                DiagonalOp op = createDiagonalOpFromPauliHamilFile(fn, QUEST_ENV);
                REQUIRE( areEqual(ref, toQMatrix(op)) );
                destroyDiagonalOp(op, QUEST_ENV);
            }
            SECTION( "trailing newlines" ) {
                writeToFileSynch(fn, line + "\n\n\n");
                DiagonalOp op = createDiagonalOpFromPauliHamilFile(fn, QUEST_ENV);
                REQUIRE( areEqual(ref, toQMatrix(op)) );
                destroyDiagonalOp(op, QUEST_ENV);
            }
            SECTION( "trailing spaces" ) {
                writeToFileSynch(fn, line + "    ");
                DiagonalOp op = createDiagonalOpFromPauliHamilFile(fn, QUEST_ENV);
                REQUIRE( areEqual(ref, toQMatrix(op)) );
                destroyDiagonalOp(op, QUEST_ENV);
            }
        }
    }
    SECTION( "input validation") {
        SECTION( "number of qubits" ) {
            writeToFileSynch(fn, ".1 "); // 0 qubits
            REQUIRE_THROWS_WITH( createDiagonalOpFromPauliHamilFile(fn, QUEST_ENV), Contains("The number of qubits") && Contains("strictly positive"));
        }
        SECTION( "number of elements" ) {
            // too many amplitudes to store in type
            int maxQb = (int) calcLog2(SIZE_MAX);
            // encode one more qubit than legal to file
            string line = ".1 ";
            for (int q=0; q<(maxQb+1); q++)
                line += "3 "; // trailing space ok
            writeToFileSynch(fn, line);
            REQUIRE_THROWS_WITH( createDiagonalOpFromPauliHamilFile(fn, QUEST_ENV), Contains("Too many qubits") && Contains("size_t type") );
            // use local QuESTEnv to safely modify
            QuESTEnv env = QUEST_ENV;
            // too few elements to distribute
            /* env.numRanks is an int, so maxQb must be capped at 32 for this
             * test to avoid an integer overflow when storing 2**minQb in it
             */
            maxQb = maxQb > 32 ? 32 : maxQb;
            int minQb = GENERATE_COPY( range(2,maxQb) );
            env.numRanks = (int) pow(2, minQb);
            int numQb = GENERATE_COPY( range(1,minQb) );
            line = ".1 ";
            for (int q=0; q<numQb; q++)
                line += "3 "; // trailing space ok
            setUniqueFilename(fn, fnPrefix);
            writeToFileSynch(fn, line);
            REQUIRE_THROWS_WITH( createDiagonalOpFromPauliHamilFile(fn, env), Contains("Too few qubits") && Contains("distributed") );
        }
        SECTION( "coefficient type" ) {
            writeToFileSynch(fn, "notanumber 1 2 3");
            REQUIRE_THROWS_WITH( createDiagonalOpFromPauliHamilFile(fn, QUEST_ENV), Contains("Failed to parse") && Contains("coefficient"));
        }
        SECTION( "pauli code" ) {
            writeToFileSynch(fn, ".1 0 3 2");  // final is invalid Y
            REQUIRE_THROWS_WITH( createDiagonalOpFromPauliHamilFile(fn, QUEST_ENV), Contains("contained operators other than PAULI_Z and PAULI_I"));
            setUniqueFilename(fn, fnPrefix);
            writeToFileSynch(fn, ".1 0 1 3");  // second is invalid X
            REQUIRE_THROWS_WITH( createDiagonalOpFromPauliHamilFile(fn, QUEST_ENV), Contains("contained operators other than PAULI_Z and PAULI_I"));
            setUniqueFilename(fn, fnPrefix);
            writeToFileSynch(fn, ".1 0 1 4");  // final is invalid Pauli code
            REQUIRE_THROWS_WITH( createDiagonalOpFromPauliHamilFile(fn, QUEST_ENV), Contains("invalid pauli code"));
            setUniqueFilename(fn, fnPrefix);
            writeToFileSynch(fn, ".1 3 0 notanumber");  // final is invalid type
            REQUIRE_THROWS_WITH( createDiagonalOpFromPauliHamilFile(fn, QUEST_ENV), Contains("Failed to parse the next expected Pauli code"));
        }
    }
    // delete all files created above
    deleteFilesWithPrefixSynch(fnPrefix);
}
References areEqual(), calcLog2(), createDiagonalOpFromPauliHamilFile(), createPauliHamil(), deleteFilesWithPrefixSynch(), destroyDiagonalOp(), destroyPauliHamil(), file, fprintf(), line, QuESTEnv::numRanks, PAULI_I, PAULI_Z, PauliHamil::pauliCodes, qreal, QUEST_ENV, QuESTEnv::rank, setRandomDiagPauliHamil(), setUniqueFilename(), syncQuESTEnv(), PauliHamil::termCoeffs, toQMatrix(), VLA, and writeToFileSynch().
TEST_CASE() [56/136]
TEST_CASE ("createPauliHamil" , "" [data_structures])
See also
createPauliHamil
Author
Tyson Jones
Definition at line 439 of file test_data_structures.cpp.
{
    SECTION( "correctness" ) {
        int numQb = GENERATE( range(1,5) );
        int numTerms = GENERATE( range(1,5) );
        PauliHamil hamil = createPauliHamil(numQb, numTerms);
        // check fields are correct
        REQUIRE( hamil.numQubits == numQb );
        REQUIRE( hamil.numSumTerms == numTerms );
        // check all Pauli codes are identity
        int numPaulis = numQb * numTerms;
        for (int i=0; i<numPaulis; i++) {
            REQUIRE( hamil.pauliCodes[i] == PAULI_I );
        }
        // check all term coefficients can be written to (no seg fault)
        for (int j=0; j<numTerms; j++) {
            hamil.termCoeffs[j] = 1;
            REQUIRE( hamil.termCoeffs[j] == 1 );
        }
        destroyPauliHamil(hamil);
    }
    SECTION( "input validation") {
        SECTION( "number of qubits" ) {
            int numQb = GENERATE( -1, 0 );
            REQUIRE_THROWS_WITH( createPauliHamil(numQb, 1), Contains("The number of qubits and terms in the PauliHamil must be strictly positive.") );
        }
        SECTION( "number of terms" ) {
            int numTerms = GENERATE( -1, 0 );
            REQUIRE_THROWS_WITH( createPauliHamil(1, numTerms), Contains("The number of qubits and terms in the PauliHamil must be strictly positive.") );
        }
    }
}
References createPauliHamil(), destroyPauliHamil(), PauliHamil::numQubits, PauliHamil::numSumTerms, PAULI_I, PauliHamil::pauliCodes, and PauliHamil::termCoeffs.
TEST_CASE() [57/136]
TEST_CASE ("createPauliHamilFromFile" , "" [data_structures])
See also
createPauliHamilFromFile
Author
Tyson Jones
Definition at line 486 of file test_data_structures.cpp.
{
    // files created & populated during the test, and deleted afterward
    char fnPrefix[] = "temp_createPauliHamilFromFile";
    char fn[100];
    // each test uses a unique filename (managed by master node), to avoid file IO locks
    // (it's safe for sub-test to overwrite this, since after each test, all files
    //  with prefix fnPrefix are deleted)
    setUniqueFilename(fn, fnPrefix);
    SECTION( "correctness" ) {
        SECTION( "general" ) {
            // for several sizes...
            int numQb = GENERATE( 1, 5, 10, 15 );
            int numTerms = GENERATE( 1, 10, 30 );
            int numPaulis = numQb*numTerms;
            // create a PauliHamil with random elements
            VLA(qreal, coeffs, numTerms);
            VLA(pauliOpType, paulis, numPaulis);
            setRandomPauliSum(coeffs, paulis, numQb, numTerms);
            // write the Hamiltonian to file (with trailing whitespace, and trailing newline)
            if (QUEST_ENV.rank == 0) {
                FILE* file = fopen(fn, "w");
                int i=0;
                for (int n=0; n<numTerms; n++) {
                    fprintf(file, REAL_STRING_FORMAT, coeffs[n]);
                    fprintf(file, " ");
                    for (int q=0; q<numQb; q++)
                        fprintf(file, "%d ", (int) paulis[i++]);
                    fprintf(file, "\n");
                }
                fprintf(file, "\n");
                fclose(file);
            }
            syncQuESTEnv(QUEST_ENV);
            // load the file as a PauliHamil
            PauliHamil hamil = createPauliHamilFromFile(fn);
            // check fields agree
            REQUIRE( hamil.numQubits == numQb );
            REQUIRE( hamil.numSumTerms == numTerms );
            // check elements agree
            int j=0;
            for (int n=0; n<numTerms; n++) {
                REQUIRE( absReal(hamil.termCoeffs[n] - coeffs[n]) <= REAL_EPS );
                for (int q=0; q<numQb; q++) {
                    REQUIRE( hamil.pauliCodes[j] == paulis[j] );
                    j++;
                }
            }
            destroyPauliHamil(hamil);
        }
        SECTION( "edge cases" ) {
            SECTION( "no trailing newline or space" ) {
                writeToFileSynch(fn, ".1 1 0 1");
                PauliHamil hamil = createPauliHamilFromFile(fn);
                REQUIRE( hamil.numSumTerms == 1 );
                REQUIRE( hamil.numQubits == 3 );
                destroyPauliHamil(hamil);
            }
            SECTION( "trailing newlines" ) {
                writeToFileSynch(fn, ".1 1 0 1\n\n\n");
                PauliHamil hamil = createPauliHamilFromFile(fn);
                REQUIRE( hamil.numSumTerms == 1 );
                REQUIRE( hamil.numQubits == 3 );
                destroyPauliHamil(hamil);
            }
            SECTION( "trailing spaces" ) {
                writeToFileSynch(fn, ".1 1 0 1    ");
                PauliHamil hamil = createPauliHamilFromFile(fn);
                REQUIRE( hamil.numSumTerms == 1 );
                REQUIRE( hamil.numQubits == 3 );
                destroyPauliHamil(hamil);
            }
        }
    }
    SECTION( "input validation") {
        SECTION( "number of qubits" ) {
            writeToFileSynch(fn, ".1 ");
            REQUIRE_THROWS_WITH( createPauliHamilFromFile(fn), Contains("The number of qubits") && Contains("strictly positive"));
        }
        SECTION( "coefficient type" ) {
            writeToFileSynch(fn, "notanumber 1 2 3");
            REQUIRE_THROWS_WITH( createPauliHamilFromFile(fn), Contains("Failed to parse") && Contains("coefficient"));
        }
        SECTION( "pauli code" ) {
            writeToFileSynch(fn, ".1 1 2 4"); // invalid int
            REQUIRE_THROWS_WITH( createPauliHamilFromFile(fn), Contains("invalid pauli code"));
            setUniqueFilename(fn, fnPrefix);
            writeToFileSynch(fn, ".1 1 2 notanumber"); // invalid type
            REQUIRE_THROWS_WITH( createPauliHamilFromFile(fn), Contains("Failed to parse the next expected Pauli code"));
        }
    }
    // cleanup temp files
    deleteFilesWithPrefixSynch(fn);
}
References createPauliHamilFromFile(), deleteFilesWithPrefixSynch(), destroyPauliHamil(), file, fprintf(), PauliHamil::numQubits, PauliHamil::numSumTerms, PauliHamil::pauliCodes, qreal, QUEST_ENV, QuESTEnv::rank, setRandomPauliSum(), setUniqueFilename(), syncQuESTEnv(), PauliHamil::termCoeffs, VLA, and writeToFileSynch().
TEST_CASE() [58/136]
TEST_CASE ("createQuESTEnv" , "" [data_structures])
See also
createQuESTEnv
Author
Tyson Jones
Definition at line 617 of file test_data_structures.cpp.
{
    /* there is no meaningful way to test this */
    SUCCEED( );
}
TEST_CASE() [59/136]
TEST_CASE ("createQureg" , "" [data_structures])
See also
createQureg
Author
Tyson Jones
Definition at line 629 of file test_data_structures.cpp.
{
    // must be at least one amplitude per node
    int minNumQb = calcLog2(QUEST_ENV.numRanks);
    if (minNumQb == 0)
        minNumQb = 1;
    SECTION( "correctness" ) {
        // try 10 valid number of qubits
        int numQb = GENERATE_COPY( range(minNumQb, minNumQb+10) );
        Qureg reg = createQureg(numQb, QUEST_ENV);
        // ensure elems (CPU and/or GPU) are created, and reg begins in |0>
        QVector ref = QVector(1<<numQb);
        ref[0] = 1; // |0>
        REQUIRE( areEqual(reg, ref) );
        destroyQureg(reg, QUEST_ENV);
    }
    SECTION( "input validation") {
        SECTION( "number of qubits" ) {
            int numQb = GENERATE( -1, 0 );
            REQUIRE_THROWS_WITH( createQureg(numQb, QUEST_ENV), Contains("Invalid number of qubits") );
        }
        SECTION( "number of amplitudes" ) {
            // use local QuESTEnv to safely modify
            QuESTEnv env = QUEST_ENV;
            // too many amplitudes to store in type
            int maxQb = (int) calcLog2(SIZE_MAX);
            REQUIRE_THROWS_WITH( createQureg(maxQb+1, env), Contains("Too many qubits") && Contains("size_t type") );
            // too few amplitudes to distribute
            /* env.numRanks is an int, so maxQb must be capped at 32 for this
             * test to avoid an integer overflow when storing 2**minQb in it
             */
            maxQb = maxQb > 32 ? 32 : maxQb;
            int minQb = GENERATE_COPY( range(2,maxQb) );
            env.numRanks = (int) pow(2, minQb);
            int numQb = GENERATE_COPY( range(1,minQb) );
            REQUIRE_THROWS_WITH( createQureg(numQb, env), Contains("Too few qubits") );
        }
        SECTION( "available memory" ) {
            /* there is no reliable way to force the malloc statements to
             * fail, and hence trigger the matrixInit validation */
            SUCCEED( );
        }
    }
}
References areEqual(), calcLog2(), createQureg(), destroyQureg(), QuESTEnv::numRanks, and QUEST_ENV.
TEST_CASE() [60/136]
TEST_CASE ("createSubDiagonalOp" , "" [data_structures])
See also
createSubDiagonalOp
Author
Tyson Jones
Definition at line 690 of file test_data_structures.cpp.
{
    SECTION( "correctness" ) {
        int numQb = GENERATE( range(1,10+1) );
        SubDiagonalOp op = createSubDiagonalOp(numQb);
        // ensure elems are created and initialised to 0
        REQUIRE( areEqual(toQMatrix(op), getZeroMatrix(1<<numQb)) );
        destroySubDiagonalOp(op);
    }
    SECTION( "input validation" ) {
        SECTION( "number of qubits" ) {
            int numQb = GENERATE( -1, 0 );
            REQUIRE_THROWS_WITH( createSubDiagonalOp(numQb), Contains("Invalid number of qubits") );
            numQb = 100;
            REQUIRE_THROWS_WITH( createSubDiagonalOp(numQb), Contains("Too many qubits") );
        }
    }
}
References areEqual(), createSubDiagonalOp(), destroySubDiagonalOp(), getZeroMatrix(), and toQMatrix().
TEST_CASE() [61/136]
TEST_CASE ("destroyComplexMatrixN" , "" [data_structures])
See also
destroyComplexMatrixN
Author
Tyson Jones
Definition at line 721 of file test_data_structures.cpp.
{
    SECTION( "correctness" ) {
        /* there is no meaningful way to test this */
        SUCCEED( );
    }
    SECTION( "input validation" ) {
        SECTION( "matrix not created" ) {
            /* this is an artificial test case since nothing in the QuEST API
             * automatically sets un-initialised ComplexMatrixN fields to
             * the NULL pointer.
             */
             ComplexMatrixN m;
             m.real = NULL;
             /* the error message is also somewhat unrelated, but oh well
              */
             REQUIRE_THROWS_WITH( destroyComplexMatrixN(m), Contains("The ComplexMatrixN was not successfully created") );
        }
    }
}
References destroyComplexMatrixN(), and ComplexMatrixN::real.
TEST_CASE() [62/136]
TEST_CASE ("destroyDiagonalOp" , "" [data_structures])
See also
destroyDiagonalOp
Author
Tyson Jones
Definition at line 752 of file test_data_structures.cpp.
{
    /* there is no meaningful way to test this */
    SUCCEED( );
}
TEST_CASE() [63/136]
TEST_CASE ("destroyPauliHamil" , "" [data_structures])
See also
destroyPauliHamil
Author
Tyson Jones
Definition at line 764 of file test_data_structures.cpp.
{
    /* there is no meaningful way to test this.
     * We e.g. cannot check that the pointers are NULL because
     * they are not updated; this function passes the struct by value,
     * not by reference. We also cannot reliably monitor the
     * memory used in the heap at runtime.
     */
    SUCCEED( );
}
TEST_CASE() [64/136]
TEST_CASE ("destroyQuESTEnv" , "" [data_structures])
See also
destroyQuESTEnv
Author
Tyson Jones
Definition at line 781 of file test_data_structures.cpp.
{
    /* there is no meaningful way to test this */
    SUCCEED( );
}
TEST_CASE() [65/136]
TEST_CASE ("destroyQureg" , "" [data_structures])
See also
destroyQureg
Author
Tyson Jones
Definition at line 793 of file test_data_structures.cpp.
{
    /* there is no meaningful way to test this.
     * We e.g. cannot check that the pointers are NULL because
     * they are not updated; this function passes the struct by value,
     * not by reference. We also cannot reliably monitor the
     * memory used in the heap at runtime.
     */
    SUCCEED( );
}
TEST_CASE() [66/136]
TEST_CASE ("destroySubDiagonalOp" , "" [data_structures])
See also
destroySubDiagonalOp
Author
Tyson Jones
Definition at line 810 of file test_data_structures.cpp.
{
    /* there is no meaningful way to test this */
    SUCCEED( );
}
TEST_CASE() [67/136]
TEST_CASE ("diagonalUnitary" , "" [unitaries])
See also
diagonalUnitary
Author
Tyson Jones
Definition at line 97 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    SECTION( "correctness" ) {
        // generate all possible targets
        int numTargs = GENERATE( range(1,NUM_QUBITS+1) );
        int* targs = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numTargs) );
        // initialise a random unitary diagonal op
        SubDiagonalOp op = createSubDiagonalOp(numTargs);
        for (long long int i=0; i<op.numElems; i++) {
            qcomp elem = getRandomComplex();
            elem /= abs(elem);
            op.real[i] = real(elem);
            op.imag[i] = imag(elem);
        }
        QMatrix opMatr = toQMatrix(op);
        SECTION( "state-vector" ) {
            diagonalUnitary(quregVec, targs, numTargs, op);
            applyReferenceOp(refVec, targs, numTargs, opMatr);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            diagonalUnitary(quregMatr, targs, numTargs, op);
            applyReferenceOp(refMatr, targs, numTargs, opMatr);
            REQUIRE( areEqual(quregMatr, refMatr, 100*REAL_EPS) );
        }
        destroySubDiagonalOp(op);
    }
    SECTION( "input validation" ) {
        SECTION( "diagonal dimension" ) {
            int numTargs = 3;
            SubDiagonalOp op = createSubDiagonalOp(numTargs);
            int badNumTargs = GENERATE_COPY( numTargs-1, numTargs+1 );
            int badTargs[NUM_QUBITS+1];
            REQUIRE_THROWS_WITH( diagonalUnitary(quregVec, badTargs, badNumTargs, op), Contains("incompatible dimension") );
            destroySubDiagonalOp(op);
        }
        SECTION( "number of targets" ) {
            // make too many targets (which are otherwise valid)
            SubDiagonalOp badOp = createSubDiagonalOp(NUM_QUBITS + 1);
            int targs[NUM_QUBITS + 1];
            for (int t=0; t<badOp.numQubits; t++)
                targs[t] = t;
            for (int i=0; i<badOp.numElems; i++)
                badOp.real[i] = 1;
            REQUIRE_THROWS_WITH( diagonalUnitary(quregVec, targs, badOp.numQubits, badOp), Contains("Invalid number of target qubits") );
            destroySubDiagonalOp(badOp);
        }
        SECTION( "repetition in targets" ) {
            // make a valid unitary diagonal op
            SubDiagonalOp op = createSubDiagonalOp(3);
            for (int i=0; i<op.numElems; i++)
                op.real[i] = 1;
            // make a repetition in the target list
            int targs[] = {2,1,2};
            REQUIRE_THROWS_WITH( diagonalUnitary(quregVec, targs, op.numQubits, op), Contains("target qubits must be unique") );
            destroySubDiagonalOp(op);
        }
        SECTION( "qubit indices" ) {
            // make a valid unitary diagonal op
            SubDiagonalOp op = createSubDiagonalOp(3);
            for (int i=0; i<op.numElems; i++)
                op.real[i] = 1;
            int targs[] = {0,1,2};
            // make each target in-turn invalid
            int badIndex = GENERATE( range(0,3) );
            int badValue = GENERATE( -1, NUM_QUBITS );
            targs[badIndex] = badValue;
            REQUIRE_THROWS_WITH( diagonalUnitary(quregVec, targs, op.numQubits, op), Contains("Invalid target qubit") );
            destroySubDiagonalOp(op);
        }
        SECTION( "unitarity" ) {
            // make a valid unitary diagonal op
            SubDiagonalOp op = createSubDiagonalOp(3);
            int targs[] = {0,1,2};
            for (int i=0; i<op.numElems; i++)
                op.real[i] = 1;
            // break unitarity via reals
            op.real[2] = -.1;
            REQUIRE_THROWS_WITH( diagonalUnitary(quregVec, targs, op.numQubits, op), Contains("unitary") );
            // restore reals and break unitarity via imag
            op.real[2] = 1;
            op.imag[3] = -3.5;
            REQUIRE_THROWS_WITH( diagonalUnitary(quregVec, targs, op.numQubits, op), Contains("unitary") );
            destroySubDiagonalOp(op);
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), createSubDiagonalOp(), destroySubDiagonalOp(), diagonalUnitary(), getRandomComplex(), SubDiagonalOp::imag, NUM_QUBITS, SubDiagonalOp::numElems, SubDiagonalOp::numQubits, PREPARE_TEST, qcomp, SubDiagonalOp::real, sublists(), and toQMatrix().
TEST_CASE() [68/136]
TEST_CASE ("fromComplex" , "" [data_structures])
See also
fromComplex
Author
Tyson Jones
Definition at line 15 of file test_data_structures.cpp.
{
    Complex a;
    a.real= .5;
    a.imag= -.2;
    qcomp b = fromComplex(a);
    REQUIRE( a.real == real(b) );
    REQUIRE( a.imag == imag(b) );
}
References fromComplex, Complex::imag, qcomp, and Complex::real.
TEST_CASE() [69/136]
TEST_CASE ("getAmp" , "" [calculations])
See also
getAmp
Author
Tyson Jones
Definition at line 1266 of file test_calculations.cpp.
{
    Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        SECTION( "state-vector" ) {
            initDebugState(vec);
            QVector ref = toQVector(vec);
            int ind = GENERATE( range(0,1<<NUM_QUBITS) );
            Complex amp = getAmp(vec,ind);
            REQUIRE( fromComplex(amp) == ref[ind] );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "state index" ) {
            int ind = GENERATE( -1, 1<<NUM_QUBITS );
            REQUIRE_THROWS_WITH( getAmp(vec,ind), Contains("Invalid amplitude index") );
        }
        SECTION( "density-matrix" ) {
            Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
            REQUIRE_THROWS_WITH( getAmp(mat,0), Contains("valid only for state-vectors") );
            destroyQureg(mat, QUEST_ENV);
        }
    }
    destroyQureg(vec, QUEST_ENV);
}
References createDensityQureg(), createQureg(), destroyQureg(), fromComplex, getAmp(), initDebugState(), NUM_QUBITS, QUEST_ENV, and toQVector().
TEST_CASE() [70/136]
TEST_CASE ("getDensityAmp" , "" [calculations])
See also
getDensityAmp
Author
Tyson Jones
Definition at line 1305 of file test_calculations.cpp.
{
    Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        SECTION( "density-matrix" ) {
            initDebugState(mat);
            QMatrix ref = toQMatrix(mat);
            int row = GENERATE( range(0,1<<NUM_QUBITS) );
            int col = GENERATE( range(0,1<<NUM_QUBITS) );
            Complex amp = getDensityAmp(mat,row,col);
            REQUIRE( fromComplex(amp) == ref[row][col] );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "state index" ) {
            int ind = GENERATE( -1, 1<<NUM_QUBITS );
            REQUIRE_THROWS_WITH( getDensityAmp(mat,ind,0), Contains("Invalid amplitude index") );
            REQUIRE_THROWS_WITH( getDensityAmp(mat,0,ind), Contains("Invalid amplitude index") );
        }
        SECTION( "state-vector" ) {
            Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
            REQUIRE_THROWS_WITH( getDensityAmp(vec,0,0), Contains("valid only for density matrices") );
            destroyQureg(vec, QUEST_ENV);
        }
    }
    destroyQureg(mat, QUEST_ENV);
}
References createDensityQureg(), createQureg(), destroyQureg(), fromComplex, getDensityAmp(), initDebugState(), NUM_QUBITS, QUEST_ENV, and toQMatrix().
TEST_CASE() [71/136]
TEST_CASE ("getImagAmp" , "" [calculations])
See also
getImagAmp
Author
Tyson Jones
Definition at line 1348 of file test_calculations.cpp.
{
    Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        SECTION( "state-vector" ) {
            initDebugState(vec);
            QVector ref = toQVector(vec);
            int ind = GENERATE( range(0,1<<NUM_QUBITS) );
            REQUIRE( getImagAmp(vec,ind) == imag(ref[ind]) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "state index" ) {
            int ind = GENERATE( -1, 1<<NUM_QUBITS );
            REQUIRE_THROWS_WITH( getImagAmp(vec,ind), Contains("Invalid amplitude index") );
        }
        SECTION( "density-matrix" ) {
            Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
            REQUIRE_THROWS_WITH( getImagAmp(mat,0), Contains("valid only for state-vectors") );
            destroyQureg(mat, QUEST_ENV);
        }
    }
    destroyQureg(vec, QUEST_ENV);
}
References createDensityQureg(), createQureg(), destroyQureg(), getImagAmp(), initDebugState(), NUM_QUBITS, QUEST_ENV, and toQVector().
TEST_CASE() [72/136]
TEST_CASE ("getNumAmps" , "" [calculations])
See also
getNumAmps
Author
Tyson Jones
Definition at line 1386 of file test_calculations.cpp.
{
    SECTION( "correctness" ) {
        // test >= NUM_QUBITS so as not to limit distribution size
        int numQb = GENERATE( range(NUM_QUBITS, NUM_QUBITS+10) );
        SECTION( "state-vector" ) {
            Qureg vec = createQureg(numQb, QUEST_ENV);
            REQUIRE( getNumAmps(vec) == (1<<numQb) );
            destroyQureg(vec, QUEST_ENV);
        }
    }
    SECTION( "input validation" ) {
        SECTION( "density-matrix" ) {
            Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
            REQUIRE_THROWS_WITH( getNumAmps(mat), Contains("valid only for state-vectors") );
            destroyQureg(mat, QUEST_ENV);
        }
    }
}
References createDensityQureg(), createQureg(), destroyQureg(), getNumAmps(), NUM_QUBITS, and QUEST_ENV.
TEST_CASE() [73/136]
TEST_CASE ("getNumQubits" , "" [calculations])
See also
getNumQubits
Author
Tyson Jones
Definition at line 1416 of file test_calculations.cpp.
{
    SECTION( "correctness" ) {
        // test >= NUM_QUBITS so as not to limit distribution size
        int numQb = GENERATE( range(NUM_QUBITS, NUM_QUBITS+10) );
        SECTION( "state-vector" ) {
            Qureg vec = createQureg(numQb, QUEST_ENV);
            REQUIRE( getNumQubits(vec) == numQb );
            destroyQureg(vec, QUEST_ENV);
        }
        SECTION( "density-matrix" ) {
            // density matrices use square as much memory; we must be careful not to seg-fault!
            if (2*numQb > 25)
                numQb = 13; // max size
            Qureg mat = createDensityQureg(numQb, QUEST_ENV);
            REQUIRE( getNumQubits(mat) == numQb );
            destroyQureg(mat, QUEST_ENV);
        }
    }
    SECTION( "input validation" ) {
        // no validation
        SUCCEED();
    }
}
References createDensityQureg(), createQureg(), destroyQureg(), getNumQubits(), NUM_QUBITS, and QUEST_ENV.
TEST_CASE() [74/136]
TEST_CASE ("getProbAmp" , "" [calculations])
See also
getProbAmp
Author
Tyson Jones
Definition at line 1453 of file test_calculations.cpp.
{
    Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        SECTION( "state-vector" ) {
            initDebugState(vec);
            QVector ref = toQVector(vec);
            int ind = GENERATE( range(0,1<<NUM_QUBITS) );
            qreal refCalc = pow(abs(ref[ind]), 2);
            REQUIRE( getProbAmp(vec,ind) == Approx(refCalc) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "state index" ) {
            int ind = GENERATE( -1, 1<<NUM_QUBITS );
            REQUIRE_THROWS_WITH( getProbAmp(vec,ind), Contains("Invalid amplitude index") );
        }
        SECTION( "density-matrix" ) {
            Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
            REQUIRE_THROWS_WITH( getProbAmp(mat,0), Contains("valid only for state-vectors") );
            destroyQureg(mat, QUEST_ENV);
        }
    }
    destroyQureg(vec, QUEST_ENV);
}
References createDensityQureg(), createQureg(), destroyQureg(), getProbAmp(), initDebugState(), NUM_QUBITS, qreal, QUEST_ENV, and toQVector().
TEST_CASE() [75/136]
TEST_CASE ("getRealAmp" , "" [calculations])
See also
getRealAmp
Author
Tyson Jones
Definition at line 1492 of file test_calculations.cpp.
{
    Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        SECTION( "state-vector" ) {
            initDebugState(vec);
            QVector ref = toQVector(vec);
            int ind = GENERATE( range(0,1<<NUM_QUBITS) );
            REQUIRE( getRealAmp(vec,ind) == real(ref[ind]) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "state index" ) {
            int ind = GENERATE( -1, 1<<NUM_QUBITS );
            REQUIRE_THROWS_WITH( getRealAmp(vec,ind), Contains("Invalid amplitude index") );
        }
        SECTION( "density-matrix" ) {
            Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
            REQUIRE_THROWS_WITH( getRealAmp(mat,0), Contains("valid only for state-vectors") );
            destroyQureg(mat, QUEST_ENV);
        }
    }
    destroyQureg(vec, QUEST_ENV);
}
References createDensityQureg(), createQureg(), destroyQureg(), getRealAmp(), initDebugState(), NUM_QUBITS, QUEST_ENV, and toQVector().
TEST_CASE() [76/136]
TEST_CASE ("getStaticComplexMatrixN" , "" [data_structures])
See also
getStaticComplexMatrixN
Author
Tyson Jones
Definition at line 32 of file test_data_structures.cpp.
{
    /* use of this function is illegal in C++ */
    SUCCEED( );
}
TEST_CASE() [77/136]
TEST_CASE ("hadamard" , "" [unitaries])
See also
hadamard
Author
Tyson Jones
Definition at line 937 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    qreal a = 1/sqrt(2);
    QMatrix op{{a,a},{a,-a}};
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        SECTION( "state-vector ") {
            hadamard(quregVec, target);
            applyReferenceOp(refVec, target, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            hadamard(quregMatr, target);
            applyReferenceOp(refMatr, target, op);
            REQUIRE( areEqual(quregMatr, refMatr, 10*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qubit indices" ) {
            int target = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( hadamard(quregVec, target), Contains("Invalid target") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, hadamard(), NUM_QUBITS, PREPARE_TEST, and qreal.
TEST_CASE() [78/136]
TEST_CASE ("initBlankState" , "" [state_initialisations])
See also
initBlankState
Author
Tyson Jones
Definition at line 90 of file test_state_initialisations.cpp.
{
    Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        SECTION( "state-vector" ) {
            initBlankState(vec);
            REQUIRE( areEqual(vec, QVector(1<<NUM_QUBITS)) );
        }
        SECTION( "density-matrix" ) {
            initBlankState(mat);
            REQUIRE( areEqual(mat, getZeroMatrix(1<<NUM_QUBITS)) );
        }
    }
    SECTION( "input validation" ) {
        // no user validation
        SUCCEED( );
    }
    destroyQureg(vec, QUEST_ENV);
    destroyQureg(mat, QUEST_ENV);
}
References areEqual(), createDensityQureg(), createQureg(), destroyQureg(), getZeroMatrix(), initBlankState(), NUM_QUBITS, and QUEST_ENV.
TEST_CASE() [79/136]
TEST_CASE ("initClassicalState" , "" [state_initialisations])
See also
initClassicalState
Author
Tyson Jones
Definition at line 123 of file test_state_initialisations.cpp.
{
    Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        int numInds = (1<<NUM_QUBITS);
        int ind = GENERATE_COPY( range(0,numInds) );
        SECTION( "state-vector" ) {
            initClassicalState(vec, ind);
            QVector vecRef = QVector(1<<NUM_QUBITS);
            vecRef[ind] = 1;
            REQUIRE( areEqual(vec, vecRef) );
        }
        SECTION( "density-matrix" ) {
            initClassicalState(mat, ind);
            QMatrix matRef = getZeroMatrix(1<<NUM_QUBITS);
            matRef[ind][ind] = 1;
            REQUIRE( areEqual(mat, matRef) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "state index" ) {
            int ind = GENERATE( -1, (1<<NUM_QUBITS) );
            REQUIRE_THROWS_WITH( initClassicalState(vec, ind), Contains("Invalid state index") );
        }
    }
    destroyQureg(vec, QUEST_ENV);
    destroyQureg(mat, QUEST_ENV);
}
References areEqual(), createDensityQureg(), createQureg(), destroyQureg(), getZeroMatrix(), initClassicalState(), NUM_QUBITS, and QUEST_ENV.
TEST_CASE() [80/136]
TEST_CASE ("initComplexMatrixN" , "" [data_structures])
See also
initComplexMatrixN
Author
Tyson Jones
Definition at line 822 of file test_data_structures.cpp.
{
    /* use of this function is illegal in C++ */
    SUCCEED( );
}
TEST_CASE() [81/136]
TEST_CASE ("initDiagonalOp" , "" [data_structures])
See also
initDiagonalOp
Author
Tyson Jones
Definition at line 834 of file test_data_structures.cpp.
{
    // must be at least one amplitude per node
    int minNumQb = calcLog2(QUEST_ENV.numRanks);
    if (minNumQb == 0)
        minNumQb = 1;
    SECTION( "correctness" ) {
        // try 10 valid number of qubits
        int numQb = GENERATE_COPY( range(minNumQb, minNumQb+10) );
        DiagonalOp op = createDiagonalOp(numQb, QUEST_ENV);
        long long int len = (1LL << numQb);
        VLA(qreal, reals, len);
        VLA(qreal, imags, len);
        long long int n;
        for (n=0; n<len; n++) {
            reals[n] = (qreal)    n;
            imags[n] = (qreal) -2*n; // (n - 2n i)
        }
        initDiagonalOp(op, reals, imags);
        // check that op.real and op.imag were modified...
        REQUIRE( areEqual(toQVector(op), reals, imags) );
        // and also that GPU real and imag were modified
        // via if it modifies an all-unity state-vec correctly
        Qureg qureg = createQureg(numQb, QUEST_ENV);
        for (long long int i=0; i<qureg.numAmpsPerChunk; i++) {
            qureg.stateVec.real[i] = 1;
            qureg.stateVec.imag[i] = 1;
        }
        copyStateToGPU(qureg);
        QVector prodRef = toQMatrix(op) * toQVector(qureg);
        // (n - 2n i) * (1 + 1i) = 3n - n*i
        applyDiagonalOp(qureg, op);
        copyStateFromGPU(qureg);
        QVector result = toQVector(qureg);
        REQUIRE( areEqual(prodRef, result) );
        destroyQureg(qureg, QUEST_ENV);
        destroyDiagonalOp(op, QUEST_ENV);
    }
}
References applyDiagonalOp(), areEqual(), calcLog2(), copyStateFromGPU(), copyStateToGPU(), createDiagonalOp(), createQureg(), destroyDiagonalOp(), destroyQureg(), initDiagonalOp(), Qureg::numAmpsPerChunk, QuESTEnv::numRanks, qreal, QUEST_ENV, Qureg::stateVec, toQMatrix(), toQVector(), and VLA.
TEST_CASE() [82/136]
TEST_CASE ("initDiagonalOpFromPauliHamil" , "" [data_structures])
See also
initDiagonalOpFromPauliHamil
Author
Tyson Jones
Definition at line 888 of file test_data_structures.cpp.
{
    // distributed diagonal op must contain at least one amplitude per node
    int minNumQb = calcLog2(QUEST_ENV.numRanks);
    if (minNumQb == 0)
        minNumQb = 1;
    SECTION( "correctness" ) {
        // try (at most) 10 valid number of qubits (even for validation)
        int numQb = GENERATE_COPY( range(minNumQb, min(10,minNumQb+10)) );
        DiagonalOp op = createDiagonalOp(numQb, QUEST_ENV);
        // try several sized random all-Z Hamiltonians
        int numTerms = GENERATE_COPY( 1, numQb, 5*numQb );
        PauliHamil hamil = createPauliHamil(numQb, numTerms);
        setRandomDiagPauliHamil(hamil);
        initDiagonalOpFromPauliHamil(op, hamil);
        REQUIRE( areEqual(toQMatrix(op), toQMatrix(hamil)) );
        destroyPauliHamil(hamil);
        destroyDiagonalOp(op, QUEST_ENV);
    }
    SECTION( "input validation" ) {
        SECTION( "hamiltonian parameters" ) {
            DiagonalOp op = createDiagonalOp(minNumQb, QUEST_ENV);
            PauliHamil hamil;
            hamil.numQubits = GENERATE( -1, 0 );
            hamil.numSumTerms = 1;
            REQUIRE_THROWS_WITH( initDiagonalOpFromPauliHamil(op, hamil), Contains("number of qubits") && Contains("strictly positive") );
            hamil.numQubits = minNumQb;
            hamil.numSumTerms = GENERATE( -1, 0 );
            REQUIRE_THROWS_WITH( initDiagonalOpFromPauliHamil(op, hamil), Contains("terms") && Contains("strictly positive") );
            destroyDiagonalOp(op, QUEST_ENV);
        }
        SECTION( "mismatching dimensions" ) {
            int numQbA = minNumQb+1;
            int numQbB = GENERATE_COPY( numQbA-1, numQbA+1 );
            DiagonalOp op = createDiagonalOp(numQbA, QUEST_ENV);
            PauliHamil hamil = createPauliHamil(numQbB, 1);
            REQUIRE_THROWS_WITH( initDiagonalOpFromPauliHamil(op, hamil), Contains("Pauli Hamiltonian and diagonal operator have different, incompatible dimensions") );
            destroyDiagonalOp(op, QUEST_ENV);
            destroyPauliHamil(hamil);
        }
        SECTION( "pauli codes" ) {
            DiagonalOp op = createDiagonalOp(minNumQb, QUEST_ENV);
            PauliHamil hamil = createPauliHamil(minNumQb, 5);  // all I
            // make only one code invalid
            int numCodes = minNumQb * hamil.numSumTerms;
            int ind = GENERATE_COPY( range(0,numCodes) );
            hamil.pauliCodes[ind] = GENERATE( PAULI_X, PAULI_Y );
            REQUIRE_THROWS_WITH( initDiagonalOpFromPauliHamil(op, hamil), Contains("contained operators other than PAULI_Z and PAULI_I") );
            destroyDiagonalOp(op, QUEST_ENV);
            destroyPauliHamil(hamil);
        }
    }
}
References areEqual(), calcLog2(), createDiagonalOp(), createPauliHamil(), destroyDiagonalOp(), destroyPauliHamil(), initDiagonalOpFromPauliHamil(), PauliHamil::numQubits, QuESTEnv::numRanks, PauliHamil::numSumTerms, PAULI_X, PAULI_Y, PauliHamil::pauliCodes, QUEST_ENV, setRandomDiagPauliHamil(), and toQMatrix().
TEST_CASE() [83/136]
TEST_CASE ("initPauliHamil" , "" [data_structures])
See also
initPauliHamil
Author
Tyson Jones
Definition at line 966 of file test_data_structures.cpp.
{
    SECTION( "correctness" ) {
        PauliHamil hamil = createPauliHamil(3, 2);
        qreal coeffs[] = {-5, 5};
        enum pauliOpType codes[] = {
            PAULI_X, PAULI_Y, PAULI_Z,
            PAULI_Z, PAULI_Y, PAULI_X};
        initPauliHamil(hamil, coeffs, codes);
        // check everything written correctly
        for (int t=0; t<2; t++) {
            REQUIRE( coeffs[t] == hamil.termCoeffs[t] );
            for (int q=0; q<3; q++) {
                int ind = 3*t+q;
                REQUIRE( codes[ind] == hamil.pauliCodes[ind] );
            }
        }
        destroyPauliHamil(hamil);
    }
    SECTION( "input validation" ) {
        SECTION( "parameters" ) {
            // parameters checked before codes, so safe to leave un-initialised
            qreal coeffs[1];
            enum pauliOpType codes[1];
            PauliHamil hamil;
            hamil.numQubits = GENERATE( -1, 0 );
            hamil.numSumTerms = 1;
            REQUIRE_THROWS_WITH( initPauliHamil(hamil, coeffs, codes), Contains("number of qubits") && Contains("strictly positive") );
            hamil.numQubits = 1;
            hamil.numSumTerms = GENERATE( -1, 0 );
            REQUIRE_THROWS_WITH( initPauliHamil(hamil, coeffs, codes), Contains("terms") && Contains("strictly positive") );
        }
        SECTION( "Pauli codes" ) {
            int numQb = 3;
            int numTerms = 2;
            int numCodes = numQb * numTerms;
            VLA(qreal, coeffs, numTerms);
            VLA(pauliOpType, codes, numCodes);
            // make only one code invalid
            for (int i=0; i<numCodes; i++)
                codes[i] = PAULI_I;
            codes[GENERATE_COPY( range(0,numCodes) )] = (pauliOpType) GENERATE( -1, 4 );
            PauliHamil hamil = createPauliHamil(numQb, numTerms);
            REQUIRE_THROWS_WITH( initPauliHamil(hamil, coeffs, codes), Contains("Invalid Pauli code") );
            destroyPauliHamil(hamil);
        }
    }
}
References createPauliHamil(), destroyPauliHamil(), initPauliHamil(), PauliHamil::numQubits, PauliHamil::numSumTerms, PAULI_I, PAULI_X, PAULI_Y, PAULI_Z, PauliHamil::pauliCodes, qreal, PauliHamil::termCoeffs, and VLA.
TEST_CASE() [84/136]
TEST_CASE ("initPlusState" , "" [state_initialisations])
See also
initPlusState
Author
Tyson Jones
Definition at line 166 of file test_state_initialisations.cpp.
{
    Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        SECTION( "state-vector" ) {
            // |+> = 1/sqrt(N^2) sum_i |i>
            //     = 1/sqrt(N^2) {1, ..., 1}
            initPlusState(vec);
            QVector vecRef = QVector(1<<NUM_QUBITS);
            for (size_t i=0; i<vecRef.size(); i++)
                vecRef[i] = 1./sqrt(pow(2,NUM_QUBITS));
            REQUIRE( areEqual(vec, vecRef) );
        }
        SECTION( "density-matrix" ) {
            // |+><+| = 1/sqrt(N^2) sum_i |i> 1/sqrt(N^2) sum_j <j|
            //        = 1/(N^2) sum_{ij} |i><j|
            //        = 1/(N^2) {{1, ..., 1}, ...}
            initPlusState(mat);
            QMatrix matRef = getZeroMatrix(1<<NUM_QUBITS);
            for (size_t i=0; i<matRef.size(); i++)
                for (size_t j=0; j<matRef.size(); j++)
                    matRef[i][j] = 1./pow(2, NUM_QUBITS);
            REQUIRE( areEqual(mat, matRef) );
        }
    }
    SECTION( "input validation" ) {
        // no user validation
        SUCCEED( );
    }
    destroyQureg(vec, QUEST_ENV);
    destroyQureg(mat, QUEST_ENV);
}
References areEqual(), createDensityQureg(), createQureg(), destroyQureg(), getZeroMatrix(), initPlusState(), NUM_QUBITS, and QUEST_ENV.
TEST_CASE() [85/136]
TEST_CASE ("initPureState" , "" [state_initialisations])
See also
initPureState
Author
Tyson Jones
Definition at line 211 of file test_state_initialisations.cpp.
{
    Qureg vec1 = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg mat1 = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        SECTION( "state-vector" ) {
            /* state-vector version just performs cloneQureg */
            Qureg vec2 = createQureg(NUM_QUBITS, QUEST_ENV);
            // make sure states start differently
            initDebugState(vec1);
            initBlankState(vec2);
            REQUIRE( !areEqual(vec1, vec2) );
            // make sure vec2 is overwritten with vec1
            QVector copy1 = toQVector(vec1);
            initPureState(vec2, vec1);
            REQUIRE( areEqual(vec1, vec2) );
            // make sure vec1 was not modified
            REQUIRE( areEqual(vec1, copy1) );
            destroyQureg(vec2, QUEST_ENV);
        }
        SECTION( "density-matrix" ) {
            /* density matrix version initialises matrix in |pure><pure| */
            initDebugState(vec1); // |vec1> = sum_i a_i |i>
            QVector copy1 = toQVector(vec1);
            // make sure mat1 is modified correctly
            initBlankState(mat1);
            initPureState(mat1, vec1); // mat1 = |vec1><vec1| = sum_{ij} a_i a_j* |i><j|
            QMatrix matRef = getZeroMatrix(1<<NUM_QUBITS);
            for (size_t i=0; i<matRef.size(); i++)
                for (size_t j=0; j<matRef.size(); j++)
                    matRef[i][j] = copy1[i] * conj(copy1[j]);
            REQUIRE( areEqual(mat1, matRef) );
            // make sure vec1 was not modified
            REQUIRE( areEqual(vec1, copy1) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qureg types" ) {
            // density matrix as second arg is illegal (regardless of first arg)
            REQUIRE_THROWS_WITH( initPureState(vec1, mat1), Contains("Second argument must be a state-vector") );
            REQUIRE_THROWS_WITH( initPureState(mat1, mat1), Contains("Second argument must be a state-vector") );
        }
        SECTION( "qureg dimensions" ) {
            Qureg vec2 = createQureg(NUM_QUBITS + 1, QUEST_ENV);
            REQUIRE_THROWS_WITH( initPureState(vec1, vec2), Contains("Dimensions") && Contains("don't match") );
            REQUIRE_THROWS_WITH( initPureState(mat1, vec2), Contains("Dimensions") && Contains("don't match") );
            destroyQureg(vec2, QUEST_ENV);
        }
    }
    destroyQureg(vec1, QUEST_ENV);
    destroyQureg(mat1, QUEST_ENV);
}
References areEqual(), createDensityQureg(), createQureg(), destroyQureg(), getZeroMatrix(), initBlankState(), initDebugState(), initPureState(), NUM_QUBITS, QUEST_ENV, and toQVector().
TEST_CASE() [86/136]
TEST_CASE ("initStateFromAmps" , "" [state_initialisations])
See also
initStateFromAmps
Author
Tyson Jones
Definition at line 286 of file test_state_initialisations.cpp.
{
    Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        SECTION( "state-vector" ) {
            // create random (unnormalised) vector
            QVector vecRef = getRandomQVector(1<<NUM_QUBITS);
            VLA(qreal, ampsRe, vec.numAmpsTotal);
            VLA(qreal, ampsIm, vec.numAmpsTotal);
            for (size_t i=0; i<vecRef.size(); i++) {
                ampsRe[i] = real(vecRef[i]);
                ampsIm[i] = imag(vecRef[i]);
            }
            initStateFromAmps(vec, ampsRe, ampsIm);
            REQUIRE( areEqual(vec, vecRef) );
        }
        SECTION( "density-matrix" ) {
            // create random (unnormalised) matrix
            QMatrix matRef = getRandomQMatrix(1<<NUM_QUBITS);
            VLA(qreal, ampsRe, mat.numAmpsTotal);
            VLA(qreal, ampsIm, mat.numAmpsTotal);
            // populate column-wise
            long long int i=0;
            for (size_t c=0; c<matRef.size(); c++) {
                for (size_t r=0; r<matRef.size(); r++) {
                    ampsRe[i] = real(matRef[r][c]);
                    ampsIm[i] = imag(matRef[r][c]);
                    i++;
                }
            }
            initStateFromAmps(mat, ampsRe, ampsIm);
            REQUIRE( areEqual(mat, matRef) );
        }
    }
    destroyQureg(vec, QUEST_ENV);
    destroyQureg(mat, QUEST_ENV);
}
References areEqual(), createDensityQureg(), createQureg(), destroyQureg(), getRandomQMatrix(), getRandomQVector(), initStateFromAmps(), NUM_QUBITS, Qureg::numAmpsTotal, qreal, QUEST_ENV, and VLA.
TEST_CASE() [87/136]
TEST_CASE ("initZeroState" , "" [state_initialisations])
See also
initZeroState
Author
Tyson Jones
Definition at line 340 of file test_state_initialisations.cpp.
{
    Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        SECTION( "state-vector" ) {
            initBlankState(vec);
            initZeroState(vec);
            QVector refVec = QVector(vec.numAmpsTotal);
            refVec[0] = 1;
            REQUIRE( areEqual(vec, refVec) );
        }
        SECTION( "density-matrix" ) {
            initBlankState(mat);
            initZeroState(mat);
            QMatrix refMat = getZeroMatrix(1<<mat.numQubitsRepresented);
            refMat[0][0] = 1;
            REQUIRE( areEqual(mat, refMat) );
        }
    }
    SECTION( "input validation" ) {
        // no input validation
        SUCCEED( );
    }
    destroyQureg(vec, QUEST_ENV);
    destroyQureg(mat, QUEST_ENV);
}
References areEqual(), createDensityQureg(), createQureg(), destroyQureg(), getZeroMatrix(), initBlankState(), initZeroState(), NUM_QUBITS, Qureg::numAmpsTotal, Qureg::numQubitsRepresented, and QUEST_ENV.
TEST_CASE() [88/136]
TEST_CASE ("measure" , "" [gates])
See also
measure
Author
Tyson Jones
Definition at line 121 of file test_gates.cpp.
{
    Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        int qubit = GENERATE( range(0,NUM_QUBITS) );
        // repeat these random tests 10 times on every qubit
        GENERATE( range(0,10) );
        SECTION( "state-vector" ) {
            QVector vecRef = getRandomStateVector(NUM_QUBITS);
            toQureg(vec, vecRef);
            int outcome = measure(vec, qubit);
            REQUIRE( (outcome == 0 || outcome == 1) );
            // calculate prob of this outcome
            qreal prob = 0;
            for (size_t ind=0; ind<vecRef.size(); ind++) {
                int bit = (ind >> qubit) & 1; // target-th bit
                if (bit == outcome)
                    prob += pow(abs(vecRef[ind]), 2);
            }
            REQUIRE( prob > REAL_EPS );
            // renormalise by the outcome prob
            for (size_t ind=0; ind<vecRef.size(); ind++) {
                int bit = (ind >> qubit) & 1; // target-th bit
                if (bit == outcome)
                    vecRef[ind] /= sqrt(prob);
                else
                    vecRef[ind] = 0;
            }
            REQUIRE( areEqual(vec, vecRef) );
        }
        SECTION( "density-matrix" ) {
            QMatrix matRef = getRandomDensityMatrix(NUM_QUBITS);
            toQureg(mat, matRef);
            int outcome = measure(mat, qubit);
            REQUIRE( (outcome == 0 || outcome == 1) );
            // compute prob of this outcome
            qreal prob = 0;
            for (size_t ind=0; ind<matRef.size(); ind++) {
                int bit = (ind >> qubit) & 1; // qubit-th bit
                if (bit == outcome)
                    prob += real(matRef[ind][ind]);
            }
            REQUIRE( prob > REAL_EPS );
            // renorm (/prob) every |*outcome*><*outcome*| state, zeroing all others
            for (size_t r=0; r<matRef.size(); r++) {
                for (size_t c=0; c<matRef.size(); c++) {
                    int ketBit = (c >> qubit) & 1;
                    int braBit = (r >> qubit) & 1;
                    if (ketBit == outcome && braBit == outcome)
                        matRef[r][c] /= prob;
                    else
                        matRef[r][c] = 0;
                }
            }
            REQUIRE( areEqual(mat, matRef) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qubit index" ) {
            int qubit = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( measure(vec, qubit), Contains("Invalid target qubit") );
        }
    }
    destroyQureg(vec, QUEST_ENV);
    destroyQureg(mat, QUEST_ENV);
}
References areEqual(), createDensityQureg(), createQureg(), destroyQureg(), getRandomDensityMatrix(), getRandomStateVector(), measure(), NUM_QUBITS, qreal, QUEST_ENV, and toQureg().
TEST_CASE() [89/136]
TEST_CASE ("measureWithStats" , "" [gates])
See also
measureWithStats
Author
Tyson Jones
Definition at line 213 of file test_gates.cpp.
{
    Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
    Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        int qubit = GENERATE( range(0,NUM_QUBITS) );
        // repeat these random tests 10 times on every qubit
        GENERATE( range(0,10) );
        SECTION( "state-vector" ) {
            QVector vecRef = getRandomStateVector(NUM_QUBITS);
            toQureg(vec, vecRef);
            qreal res;
            int outcome = measureWithStats(vec, qubit, &res);
            REQUIRE( (outcome == 0 || outcome == 1) );
            // calculate prob of this outcome
            qreal prob = 0;
            for (size_t ind=0; ind<vecRef.size(); ind++) {
                int bit = (ind >> qubit) & 1; // target-th bit
                if (bit == outcome)
                    prob += pow(abs(vecRef[ind]), 2);
            }
            REQUIRE( prob == Approx(res) );
            // renormalise by the outcome prob
            for (size_t ind=0; ind<vecRef.size(); ind++) {
                int bit = (ind >> qubit) & 1; // target-th bit
                if (bit == outcome)
                    vecRef[ind] /= sqrt(prob);
                else
                    vecRef[ind] = 0;
            }
            REQUIRE( areEqual(vec, vecRef) );
        }
        SECTION( "density-matrix" ) {
            QMatrix matRef = getRandomDensityMatrix(NUM_QUBITS);
            toQureg(mat, matRef);
            qreal res;
            int outcome = measureWithStats(mat, qubit, &res);
            REQUIRE( (outcome == 0 || outcome == 1) );
            // compute prob of this outcome
            qreal prob = 0;
            for (size_t ind=0; ind<matRef.size(); ind++) {
                int bit = (ind >> qubit) & 1; // qubit-th bit
                if (bit == outcome)
                    prob += real(matRef[ind][ind]);
            }
            REQUIRE( prob == Approx(res) );
            // renorm (/prob) every |*outcome*><*outcome*| state, zeroing all others
            for (size_t r=0; r<matRef.size(); r++) {
                for (size_t c=0; c<matRef.size(); c++) {
                    int ketBit = (c >> qubit) & 1;
                    int braBit = (r >> qubit) & 1;
                    if (ketBit == outcome && braBit == outcome)
                        matRef[r][c] /= prob;
                    else
                        matRef[r][c] = 0;
                }
            }
            REQUIRE( areEqual(mat, matRef) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qubit index" ) {
            int qubit = GENERATE( -1, NUM_QUBITS );
            qreal res;
            REQUIRE_THROWS_WITH( measureWithStats(vec, qubit, &res), Contains("Invalid target qubit") );
        }
    }
    destroyQureg(vec, QUEST_ENV);
    destroyQureg(mat, QUEST_ENV);
}
References areEqual(), createDensityQureg(), createQureg(), destroyQureg(), getRandomDensityMatrix(), getRandomStateVector(), measureWithStats(), NUM_QUBITS, qreal, QUEST_ENV, and toQureg().
TEST_CASE() [90/136]
TEST_CASE ("mixDamping" , "" [decoherence])
See also
mixDamping
Author
Tyson Jones
Definition at line 23 of file test_decoherence.cpp.
{
    PREPARE_TEST(qureg, ref);
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        qreal prob = getRandomReal(0, 1);
        mixDamping(qureg, target, prob);
        // ref -> kraus0 ref kraus0^dagger + kraus1 ref kraus1^dagger
        QMatrix kraus0{{1,0},{0,sqrt(1-prob)}};
        QMatrix rho0 = ref;
        applyReferenceOp(rho0, target, kraus0);
        QMatrix kraus1{{0,sqrt(prob)},{0,0}};
        QMatrix rho1 = ref;
        applyReferenceOp(rho1, target, kraus1);
        ref = rho0 + rho1;
        REQUIRE( areEqual(qureg, ref) );
    }
    SECTION( "validation ") {
        SECTION( "qubit index" ) {
            int target = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( mixDamping(qureg, target, 0), Contains("Invalid target") );
        }
        SECTION( "probability" ) {
            REQUIRE_THROWS_WITH( mixDamping(qureg, 0, -.1), Contains("Probabilities") );
            REQUIRE_THROWS_WITH( mixDamping(qureg, 0, 1.1), Contains("Probabilities") );
        }
        SECTION( "density-matrix" ) {
            Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
            REQUIRE_THROWS_WITH( mixDamping(vec, 0, 0), Contains("density matrices") );
            destroyQureg(vec, QUEST_ENV);
        }
    }
    destroyQureg(qureg, QUEST_ENV);
}
References applyReferenceOp(), areEqual(), createQureg(), destroyQureg(), getRandomReal(), mixDamping(), NUM_QUBITS, PREPARE_TEST, qreal, and QUEST_ENV.
TEST_CASE() [91/136]
TEST_CASE ("mixDensityMatrix" , "" [decoherence])
See also
mixDensityMatrix
Author
Tyson Jones
Definition at line 73 of file test_decoherence.cpp.
{
    Qureg qureg1 = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    Qureg qureg2 = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    initDebugState(qureg1);
    initDebugState(qureg2);
    QMatrix ref1 = toQMatrix(qureg1);
    QMatrix ref2 = toQMatrix(qureg2);
    SECTION( "correctness" ) {
        // test p in {0, 1} and 10 random values in (0,1)
        qreal prob = GENERATE( 0., 1., take(10, random(0.,1.)) );
        mixDensityMatrix(qureg1, prob, qureg2);
        // ensure target qureg modified correctly
        ref1 = (1-prob)*ref1 + (prob)*ref2;
        REQUIRE( areEqual(qureg1, ref1) );
        // enure other qureg was not modified
        REQUIRE( areEqual(qureg2, ref2) );
    }
    SECTION( "input validation" ) {
        SECTION( "probabilities") {
            qreal prob = GENERATE( -0.1, 1.1 );
            REQUIRE_THROWS_WITH( mixDensityMatrix(qureg1, prob, qureg2), Contains("Probabilities") );
        }
        SECTION( "density matrices" ) {
            // one is statevec
            Qureg state1 = createQureg(qureg1.numQubitsRepresented, QUEST_ENV);
            REQUIRE_THROWS_WITH( mixDensityMatrix(qureg1, 0, state1), Contains("density matrices") );
            REQUIRE_THROWS_WITH( mixDensityMatrix(state1, 0, qureg1), Contains("density matrices") );
            // both are statevec
            Qureg state2 = createQureg(qureg1.numQubitsRepresented, QUEST_ENV);
            REQUIRE_THROWS_WITH( mixDensityMatrix(state1, 0, state2), Contains("density matrices") );
            destroyQureg(state1, QUEST_ENV);
            destroyQureg(state2, QUEST_ENV);
        }
        SECTION( "matching dimensions" ) {
            Qureg qureg3 = createDensityQureg(1 + qureg1.numQubitsRepresented, QUEST_ENV);
            REQUIRE_THROWS_WITH( mixDensityMatrix(qureg1, 0, qureg3), Contains("Dimensions") );
            REQUIRE_THROWS_WITH( mixDensityMatrix(qureg3, 0, qureg1), Contains("Dimensions") );
            destroyQureg(qureg3, QUEST_ENV);
        }
    }
    destroyQureg(qureg1, QUEST_ENV);
    destroyQureg(qureg2, QUEST_ENV);
}
References areEqual(), createDensityQureg(), createQureg(), destroyQureg(), initDebugState(), mixDensityMatrix(), NUM_QUBITS, Qureg::numQubitsRepresented, qreal, QUEST_ENV, and toQMatrix().
TEST_CASE() [92/136]
TEST_CASE ("mixDephasing" , "" [decoherence])
See also
mixDephasing
Author
Tyson Jones
Definition at line 134 of file test_decoherence.cpp.
{
    PREPARE_TEST(qureg, ref);
    SECTION( "correctness " ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        qreal prob = getRandomReal(0, 1/2.);
        mixDephasing(qureg, target, prob);
        // ref -> (1 - prob) ref + prob Z ref Z
        QMatrix phaseRef = ref;
        applyReferenceOp(phaseRef, target, QMatrix{{1,0},{0,-1}}); // Z ref Z
        ref = ((1 - prob) * ref) + (prob * phaseRef);
        REQUIRE( areEqual(qureg, ref) );
    }
    SECTION( "validation ") {
        SECTION( "qubit index" ) {
            int target = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( mixDephasing(qureg, target, 0), Contains("Invalid target") );
        }
        SECTION( "probability" ) {
            REQUIRE_THROWS_WITH( mixDephasing(qureg, 0, -.1), Contains("Probabilities") );
            REQUIRE_THROWS_WITH( mixDephasing(qureg, 0, .6), Contains("probability") && Contains("cannot exceed 1/2") );
        }
        SECTION( "density-matrix" ) {
            Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
            REQUIRE_THROWS_WITH( mixDephasing(vec, 0, 0), Contains("density matrices") );
            destroyQureg(vec, QUEST_ENV);
        }
    }
    destroyQureg(qureg, QUEST_ENV);
}
References applyReferenceOp(), areEqual(), createQureg(), destroyQureg(), getRandomReal(), mixDephasing(), NUM_QUBITS, PREPARE_TEST, qreal, and QUEST_ENV.
TEST_CASE() [93/136]
TEST_CASE ("mixDepolarising" , "" [decoherence])
See also
mixDepolarising
Author
Tyson Jones
Definition at line 180 of file test_decoherence.cpp.
{
    PREPARE_TEST(qureg, ref);
    SECTION( "correctness " ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        qreal prob = getRandomReal(0, 3/4.);
        mixDepolarising(qureg, target, prob);
        QMatrix xRef = ref;
        applyReferenceOp(xRef, target, QMatrix{{0,1},{1,0}}); // X ref X
        QMatrix yRef = ref;
        applyReferenceOp(yRef, target, QMatrix{{0,-qcomp(0,1)},{qcomp(0,1),0}}); // Y ref Y
        QMatrix zRef = ref;
        applyReferenceOp(zRef, target, QMatrix{{1,0},{0,-1}}); // Z ref Z
        ref = ((1 - prob) * ref) + ((prob/3.) * ( xRef + yRef + zRef));
        REQUIRE( areEqual(qureg, ref) );
    }
    SECTION( "validation ") {
        SECTION( "qubit index" ) {
            int target = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( mixDepolarising(qureg, target, 0), Contains("Invalid target") );
        }
        SECTION( "probability" ) {
            REQUIRE_THROWS_WITH( mixDepolarising(qureg, 0, -.1), Contains("Probabilities") );
            REQUIRE_THROWS_WITH( mixDepolarising(qureg, 0, .76), Contains("probability") && Contains("cannot exceed 3/4") );
        }
        SECTION( "density-matrix" ) {
            Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
            REQUIRE_THROWS_WITH( mixDepolarising(vec, 0, 0), Contains("density matrices") );
            destroyQureg(vec, QUEST_ENV);
        }
    }
    destroyQureg(qureg, QUEST_ENV);
}
References applyReferenceOp(), areEqual(), createQureg(), destroyQureg(), getRandomReal(), mixDepolarising(), NUM_QUBITS, PREPARE_TEST, qcomp, qreal, and QUEST_ENV.
TEST_CASE() [94/136]
TEST_CASE ("mixKrausMap" , "" [decoherence])
See also
mixKrausMap
Author
Tyson Jones
Definition at line 525 of file test_decoherence.cpp.
{
    PREPARE_TEST(qureg, ref);
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        int numOps = GENERATE( range(1,5) ); // max 4 inclusive
        std::vector<QMatrix> matrs = getRandomKrausMap(1, numOps);
        VLA(ComplexMatrix2, ops, numOps);
        for (int i=0; i<numOps; i++)
            ops[i] = toComplexMatrix2(matrs[i]);
        mixKrausMap(qureg, target, ops, numOps);
        // set ref -> K_i ref K_i^dagger
        VLA(QMatrix, matrRefs, numOps);
        for (int i=0; i<numOps; i++) {
            matrRefs[i] = ref;
            applyReferenceOp(matrRefs[i], target, matrs[i]);
        }
        ref = getZeroMatrix(ref.size());
        for (int i=0; i<numOps; i++)
            ref += matrRefs[i];
        REQUIRE( areEqual(qureg, ref, 10*REAL_EPS) );
    }
    SECTION( "input validation" ) {
        SECTION( "number of operators" ) {
            int numOps = GENERATE( 0, 5 );
            REQUIRE_THROWS_WITH( mixKrausMap(qureg, 0, NULL, numOps), Contains("operators") );
        }
        SECTION( "trace preserving" ) {
            // valid Kraus map
            int numOps = GENERATE( range(1,5) ); // max 4 inclusive
            std::vector<QMatrix> matrs = getRandomKrausMap(1, numOps);
            VLA(ComplexMatrix2, ops, numOps);
            for (int i=0; i<numOps; i++)
                ops[i] = toComplexMatrix2(matrs[i]);
            // make invalid
            ops[GENERATE_REF( range(0,numOps) )].real[0][0] = 0;
            REQUIRE_THROWS_WITH( mixKrausMap(qureg, 0, ops, numOps), Contains("trace preserving") );
        }
        SECTION( "qubit index" ) {
            int target = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( mixKrausMap(qureg, target, NULL, 1), Contains("Invalid target qubit") );
        }
        SECTION( "density-matrix" ) {
            Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
            REQUIRE_THROWS_WITH( mixKrausMap(vec, 0, NULL, 1), Contains("density matrices") );
            destroyQureg(vec, QUEST_ENV);
        }
        SECTION( "operators fit in node" ) {
            qureg.numAmpsPerChunk = 3; // min 4
            REQUIRE_THROWS_WITH( mixKrausMap(qureg, 0, NULL, 1), Contains("targets too many qubits") );
        }
    }
    destroyQureg(qureg, QUEST_ENV);
}
References applyReferenceOp(), areEqual(), createQureg(), destroyQureg(), getRandomKrausMap(), getZeroMatrix(), mixKrausMap(), NUM_QUBITS, PREPARE_TEST, QUEST_ENV, ComplexMatrix2::real, toComplexMatrix2(), and VLA.
TEST_CASE() [95/136]
TEST_CASE ("mixMultiQubitKrausMap" , "" [decoherence])
See also
mixMultiQubitKrausMap
Author
Tyson Jones
Definition at line 229 of file test_decoherence.cpp.
{
    PREPARE_TEST(qureg, ref);
    // figure out max-num (inclusive) targs allowed by hardware backend
    // (each node must contain as 2^(2*numTargs) amps)
    int maxNumTargs = calcLog2(qureg.numAmpsPerChunk) / 2;
    SECTION( "correctness" ) {
        /* note that this function incurs a stack overhead when numTargs < 4,
         * and a heap overhead when numTargs >= 4
         */
        // try every size (qubit wise) map
        int numTargs = GENERATE_COPY( range(1,maxNumTargs+1) ); // inclusive upper bound
        // previously, we tried every unique set of targets, via:
        //      int* targs = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numTargs) );
        // alas, this is too slow for CI, so we instead try a fixed number of random sets:
        GENERATE( range(0, 10) );
        VLA(int, targs, numTargs);
        setRandomTargets(targs, numTargs, NUM_QUBITS);
        // try the min and max number of operators, and 2 random numbers
        // (there are way too many to try all!)
        int maxNumOps = (2*numTargs)*(2*numTargs);
        int numOps = GENERATE_COPY( 1, maxNumOps, take(2,random(1,maxNumOps)) );
        // use a new random map
        std::vector<QMatrix> matrs = getRandomKrausMap(numTargs, numOps);
        // create map in QuEST datatypes
        VLA(ComplexMatrixN, ops, numOps);
        for (int i=0; i<numOps; i++) {
            ops[i] = createComplexMatrixN(numTargs);
            toComplexMatrixN(matrs[i], ops[i]);
        }
        mixMultiQubitKrausMap(qureg, targs, numTargs, ops, numOps);
        // set ref -> K_i ref K_i^dagger
        VLA(QMatrix, matrRefs, numOps);
        for (int i=0; i<numOps; i++) {
            matrRefs[i] = ref;
            applyReferenceOp(matrRefs[i], targs, numTargs, matrs[i]);
        }
        ref = getZeroMatrix(ref.size());
        for (int i=0; i<numOps; i++)
            ref += matrRefs[i];
        REQUIRE( areEqual(qureg, ref, 1E2*REAL_EPS) );
        // cleanup QuEST datatypes
        for (int i=0; i<numOps; i++)
            destroyComplexMatrixN(ops[i]);
    }
    SECTION( "input validation" ) {
        SECTION( "repetition of target" ) {
            // make valid targets
            int targs[NUM_QUBITS];
            for (int i=0; i<NUM_QUBITS; i++)
                targs[i] = i;
            // duplicate one
            int badInd = GENERATE( range(0,NUM_QUBITS) );
            int copyInd = GENERATE_COPY( filter([=](int i){ return i!=badInd; }, range(0,NUM_QUBITS)) );
            targs[badInd] = targs[copyInd];
            REQUIRE_THROWS_WITH( mixMultiQubitKrausMap(qureg, targs, NUM_QUBITS, NULL, 1), Contains("target qubits") && Contains("unique") );
        }
        SECTION( "qubit indices" ) {
            // make valid targets
            int targs[NUM_QUBITS];
            for (int i=0; i<NUM_QUBITS; i++)
                targs[i] = i;
            // make one invalid
            targs[GENERATE( range(0,NUM_QUBITS) )] = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( mixMultiQubitKrausMap(qureg, targs, NUM_QUBITS, NULL, 1), Contains("Invalid target qubit") );
        }
        SECTION( "number of operators" ) {
            int numTargs = GENERATE_COPY( range(1,maxNumTargs+1) );
            int maxNumOps = (2*numTargs)*(2*numTargs);
            int numOps = GENERATE_REF( -1, 0, maxNumOps + 1 );
            // make valid targets to avoid triggering target validation
            VLA(int, targs, numTargs);
            for (int i=0; i<numTargs; i++)
                targs[i] = i;
            REQUIRE_THROWS_WITH( mixMultiQubitKrausMap(qureg, targs, numTargs, NULL, numOps), Contains("operators may be specified") );
        }
        SECTION( "initialisation of operators" ) {
            /* compilers don't auto-initialise to NULL; the below circumstance
             * only really occurs when 'malloc' returns NULL in createComplexMatrixN,
             * which actually triggers its own validation. Hence this test is useless
             * currently.
             */
            int numTargs = NUM_QUBITS;
            int numOps = (2*numTargs)*(2*numTargs);
            // no need to initialise ops, but set their attribs correct to avoid triggering other validation
            VLA(ComplexMatrixN, ops, numOps);
            for (int i=0; i<numOps; i++)
                ops[i].numQubits = numTargs;
            // make one of the max-ops explicitly NULL
            ops[GENERATE_COPY( range(0,numTargs) )].real = NULL;
            // make valid targets to avoid triggering target validation
            VLA(int, targs, numTargs);
            for (int i=0; i<numTargs; i++)
                targs[i] = i;
            REQUIRE_THROWS_WITH( mixMultiQubitKrausMap(qureg, targs, numTargs, ops, numOps), Contains("ComplexMatrixN") && Contains("created") );
        }
        SECTION( "dimension of operators" ) {
            // make valid (dimension-wise) max-qubits Kraus map
            int numTargs = NUM_QUBITS;
            int numOps = (2*numTargs)*(2*numTargs);
            VLA(ComplexMatrixN, ops, numOps);
            for (int i=0; i<numOps; i++)
                ops[i] = createComplexMatrixN(numTargs);
            // make one have wrong-dimensions
            int badInd = GENERATE_COPY( range(0,numTargs) );
            destroyComplexMatrixN(ops[badInd]);
            ops[badInd] = createComplexMatrixN(numTargs - 1);
            // make valid targets to avoid triggering target validation
            VLA(int, targs, numTargs);
            for (int i=0; i<numTargs; i++)
                targs[i] = i;
            REQUIRE_THROWS_WITH( mixMultiQubitKrausMap(qureg, targs, numTargs, ops, numOps), Contains("same number of qubits") );
            for (int i=0; i<numOps; i++)
                destroyComplexMatrixN(ops[i]);
        }
        SECTION( "trace preserving" ) {
            int numTargs = GENERATE_COPY( range(1,maxNumTargs+1) );
            int maxNumOps = (2*numTargs) * (2*numTargs);
            int numOps = GENERATE_COPY( 1, 2, maxNumOps );
            // generate a valid map
            std::vector<QMatrix> matrs = getRandomKrausMap(numTargs, numOps);
            VLA(ComplexMatrixN, ops, numOps);
            for (int i=0; i<numOps; i++) {
                ops[i] = createComplexMatrixN(numTargs);
                toComplexMatrixN(matrs[i], ops[i]);
            }
            // make only one invalid
            ops[GENERATE_REF( range(0,numOps) )].real[0][0] = 0;
            // make valid targets to avoid triggering target validation
            VLA(int, targs, numTargs);
            for (int i=0; i<numTargs; i++)
                targs[i] = i;
            REQUIRE_THROWS_WITH( mixMultiQubitKrausMap(qureg, targs, numTargs, ops, numOps), Contains("trace preserving") );
            for (int i=0; i<numOps; i++)
                destroyComplexMatrixN(ops[i]);
        }
        SECTION( "density-matrix" ) {
            Qureg statevec = createQureg(NUM_QUBITS, QUEST_ENV);
            // make valid targets to avoid triggering target validation
            int targs[NUM_QUBITS];
            for (int i=0; i<NUM_QUBITS; i++)
                targs[i] = i;
            REQUIRE_THROWS_WITH( mixMultiQubitKrausMap(statevec, targs, NUM_QUBITS, NULL, 1), Contains("valid only for density matrices") );
            destroyQureg(statevec, QUEST_ENV);
        }
        SECTION( "operator fits in node" ) {
            // each node requires (2 numTargs)^2 amplitudes
            int minAmps = (2*NUM_QUBITS) * (2*NUM_QUBITS);
            // make valid targets to avoid triggering target validation
            int targs[NUM_QUBITS];
            for (int i=0; i<NUM_QUBITS; i++)
                targs[i] = i;
            // make a simple Identity map
            ComplexMatrixN ops[] = {createComplexMatrixN(NUM_QUBITS)};
            for (int i=0; i<(1<<NUM_QUBITS); i++)
                ops[0].real[i][i] = 1;
            // fake a smaller qureg
            qureg.numAmpsPerChunk = minAmps - 1;
            REQUIRE_THROWS_WITH( mixMultiQubitKrausMap(qureg, targs, NUM_QUBITS, ops, 1), Contains("targets too many qubits") && Contains("cannot all fit") );
            destroyComplexMatrixN(ops[0]);
        }
    }
    destroyQureg(qureg, QUEST_ENV);
}
References applyReferenceOp(), areEqual(), calcLog2(), createComplexMatrixN(), createQureg(), destroyComplexMatrixN(), destroyQureg(), getRandomKrausMap(), getZeroMatrix(), mixMultiQubitKrausMap(), NUM_QUBITS, PREPARE_TEST, QUEST_ENV, setRandomTargets(), toComplexMatrixN(), and VLA.
TEST_CASE() [96/136]
TEST_CASE ("mixNonTPKrausMap" , "" [decoherence])
See also
mixNonTPKrausMap
Author
Tyson Jones
Definition at line 599 of file test_decoherence.cpp.
{
    PREPARE_TEST(qureg, ref);
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        int numOps = GENERATE( range(1,5) ); // max 4 inclusive
        // map consists of unconstrained 2x2 random matrices
        std::vector<QMatrix> matrs;
        for (int i=0; i<numOps; i++)
            matrs.push_back(getRandomQMatrix(2));
        VLA(ComplexMatrix2, ops, numOps);
        for (int i=0; i<numOps; i++)
            ops[i] = toComplexMatrix2(matrs[i]);
        mixNonTPKrausMap(qureg, target, ops, numOps);
        // set ref -> K_i ref K_i^dagger
        VLA(QMatrix, matrRefs, numOps);
        for (int i=0; i<numOps; i++) {
            matrRefs[i] = ref;
            applyReferenceOp(matrRefs[i], target, matrs[i]);
        }
        ref = getZeroMatrix(ref.size());
        for (int i=0; i<numOps; i++)
            ref += matrRefs[i];
        REQUIRE( areEqual(qureg, ref, 1E2*REAL_EPS) );
    }
    SECTION( "input validation" ) {
        SECTION( "number of operators" ) {
            int numOps = GENERATE( 0, 5 );
            REQUIRE_THROWS_WITH( mixNonTPKrausMap(qureg, 0, NULL, numOps), Contains("operators") );
        }
        SECTION( "qubit index" ) {
            int target = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( mixNonTPKrausMap(qureg, target, NULL, 1), Contains("Invalid target qubit") );
        }
        SECTION( "density-matrix" ) {
            Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
            REQUIRE_THROWS_WITH( mixNonTPKrausMap(vec, 0, NULL, 1), Contains("density matrices") );
            destroyQureg(vec, QUEST_ENV);
        }
        SECTION( "operators fit in node" ) {
            qureg.numAmpsPerChunk = 3; // min 4
            REQUIRE_THROWS_WITH( mixNonTPKrausMap(qureg, 0, NULL, 1), Contains("targets too many qubits") );
        }
    }
    destroyQureg(qureg, QUEST_ENV);
}
References applyReferenceOp(), areEqual(), createQureg(), destroyQureg(), getRandomQMatrix(), getZeroMatrix(), mixNonTPKrausMap(), NUM_QUBITS, PREPARE_TEST, QUEST_ENV, toComplexMatrix2(), and VLA.
TEST_CASE() [97/136]
TEST_CASE ("mixNonTPMultiQubitKrausMap" , "" [decoherence])
See also
mixNonTPMultiQubitKrausMap
Author
Tyson Jones
Definition at line 663 of file test_decoherence.cpp.
{
    PREPARE_TEST(qureg, ref);
    // figure out max-num (inclusive) targs allowed by hardware backend
    // (each node must contain as 2^(2*numTargs) amps)
    int maxNumTargs = calcLog2(qureg.numAmpsPerChunk) / 2;
    SECTION( "correctness" ) {
        /* note that this function incurs a stack overhead when numTargs < 4,
         * and a heap overhead when numTargs >= 4
         */
        int numTargs = GENERATE_COPY( range(1,maxNumTargs+1) ); // inclusive upper bound
        // previously, we tried every unique set of targets, via:
        //      int* targs = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numTargs) );
        // alas, this is too slow for CI, so we instead try a fixed number of random sets:
        GENERATE( range(0, 10) );
        VLA(int, targs, numTargs);
        setRandomTargets(targs, numTargs, NUM_QUBITS);
        // try the min and max number of operators, and 2 random numbers
        // (there are way too many to try all!)
        int maxNumOps = (2*numTargs)*(2*numTargs);
        int numOps = GENERATE_COPY( 1, maxNumOps, take(2,random(1,maxNumOps)) );
        // use a new random map, of unconstrained random (2^numTargs x 2^numTargs) matrices
        std::vector<QMatrix> matrs;
        for (int i=0; i<numOps; i++)
            matrs.push_back(getRandomQMatrix(1 << numTargs));
        // create map in QuEST datatypes
        VLA(ComplexMatrixN, ops, numOps);
        for (int i=0; i<numOps; i++) {
            ops[i] = createComplexMatrixN(numTargs);
            toComplexMatrixN(matrs[i], ops[i]);
        }
        mixNonTPMultiQubitKrausMap(qureg, targs, numTargs, ops, numOps);
        // set ref -> K_i ref K_i^dagger
        VLA(QMatrix, matrRefs, numOps);
        for (int i=0; i<numOps; i++) {
            matrRefs[i] = ref;
            applyReferenceOp(matrRefs[i], targs, numTargs, matrs[i]);
        }
        ref = getZeroMatrix(ref.size());
        for (int i=0; i<numOps; i++)
            ref += matrRefs[i];
        REQUIRE( areEqual(qureg, ref, 1E5*REAL_EPS) );
        // cleanup QuEST datatypes
        for (int i=0; i<numOps; i++)
            destroyComplexMatrixN(ops[i]);
    }
    SECTION( "input validation" ) {
        SECTION( "repetition of target" ) {
            // make valid targets
            int targs[NUM_QUBITS];
            for (int i=0; i<NUM_QUBITS; i++)
                targs[i] = i;
            // duplicate one
            int badInd = GENERATE( range(0,NUM_QUBITS) );
            int copyInd = GENERATE_COPY( filter([=](int i){ return i!=badInd; }, range(0,NUM_QUBITS)) );
            targs[badInd] = targs[copyInd];
            REQUIRE_THROWS_WITH( mixNonTPMultiQubitKrausMap(qureg, targs, NUM_QUBITS, NULL, 1), Contains("target qubits") && Contains("unique") );
        }
        SECTION( "qubit indices" ) {
            // make valid targets
            int targs[NUM_QUBITS];
            for (int i=0; i<NUM_QUBITS; i++)
                targs[i] = i;
            // make one invalid
            targs[GENERATE( range(0,NUM_QUBITS) )] = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( mixNonTPMultiQubitKrausMap(qureg, targs, NUM_QUBITS, NULL, 1), Contains("Invalid target qubit") );
        }
        SECTION( "number of operators" ) {
            int numTargs = GENERATE_COPY( range(1,maxNumTargs+1) );
            int maxNumOps = (2*numTargs)*(2*numTargs);
            int numOps = GENERATE_REF( -1, 0, maxNumOps + 1 );
            // make valid targets to avoid triggering target validation
            VLA(int, targs, numTargs);
            for (int i=0; i<numTargs; i++)
                targs[i] = i;
            REQUIRE_THROWS_WITH( mixNonTPMultiQubitKrausMap(qureg, targs, numTargs, NULL, numOps), Contains("operators may be specified") );
        }
        SECTION( "initialisation of operators" ) {
            /* compilers don't auto-initialise to NULL; the below circumstance
             * only really occurs when 'malloc' returns NULL in createComplexMatrixN,
             * which actually triggers its own validation. Hence this test is useless
             * currently.
             */
            int numTargs = NUM_QUBITS;
            int numOps = (2*numTargs)*(2*numTargs);
            // no need to initialise ops, but set their attribs correct to avoid triggering other validation
            VLA(ComplexMatrixN, ops, numOps);
            for (int i=0; i<numOps; i++)
                ops[i].numQubits = numTargs;
            // make one of the max-ops explicitly NULL
            ops[GENERATE_COPY( range(0,numTargs) )].real = NULL;
            // make valid targets to avoid triggering target validation
            VLA(int, targs, numTargs);
            for (int i=0; i<numTargs; i++)
                targs[i] = i;
            REQUIRE_THROWS_WITH( mixNonTPMultiQubitKrausMap(qureg, targs, numTargs, ops, numOps), Contains("ComplexMatrixN") && Contains("created") );
        }
        SECTION( "dimension of operators" ) {
            // make valid (dimension-wise) max-qubits Kraus map
            int numTargs = NUM_QUBITS;
            int numOps = (2*numTargs)*(2*numTargs);
            VLA(ComplexMatrixN, ops, numOps);
            for (int i=0; i<numOps; i++)
                ops[i] = createComplexMatrixN(numTargs);
            // make one have wrong-dimensions
            int badInd = GENERATE_COPY( range(0,numTargs) );
            destroyComplexMatrixN(ops[badInd]);
            ops[badInd] = createComplexMatrixN(numTargs - 1);
            // make valid targets to avoid triggering target validation
            VLA(int, targs, numTargs);
            for (int i=0; i<numTargs; i++)
                targs[i] = i;
            REQUIRE_THROWS_WITH( mixNonTPMultiQubitKrausMap(qureg, targs, numTargs, ops, numOps), Contains("same number of qubits") );
            for (int i=0; i<numOps; i++)
                destroyComplexMatrixN(ops[i]);
        }
        SECTION( "density-matrix" ) {
            Qureg statevec = createQureg(NUM_QUBITS, QUEST_ENV);
            // make valid targets to avoid triggering target validation
            int targs[NUM_QUBITS];
            for (int i=0; i<NUM_QUBITS; i++)
                targs[i] = i;
            REQUIRE_THROWS_WITH( mixNonTPMultiQubitKrausMap(statevec, targs, NUM_QUBITS, NULL, 1), Contains("valid only for density matrices") );
            destroyQureg(statevec, QUEST_ENV);
        }
        SECTION( "operator fits in node" ) {
            // each node requires (2 numTargs)^2 amplitudes
            int minAmps = (2*NUM_QUBITS) * (2*NUM_QUBITS);
            // make valid targets to avoid triggering target validation
            int targs[NUM_QUBITS];
            for (int i=0; i<NUM_QUBITS; i++)
                targs[i] = i;
            // make a simple Identity map
            ComplexMatrixN ops[] = {createComplexMatrixN(NUM_QUBITS)};
            for (int i=0; i<(1<<NUM_QUBITS); i++)
                ops[0].real[i][i] = 1;
            // fake a smaller qureg
            qureg.numAmpsPerChunk = minAmps - 1;
            REQUIRE_THROWS_WITH( mixNonTPMultiQubitKrausMap(qureg, targs, NUM_QUBITS, ops, 1), Contains("targets too many qubits") && Contains("cannot all fit") );
            destroyComplexMatrixN(ops[0]);
        }
    }
    destroyQureg(qureg, QUEST_ENV);
}
References applyReferenceOp(), areEqual(), calcLog2(), createComplexMatrixN(), createQureg(), destroyComplexMatrixN(), destroyQureg(), getRandomQMatrix(), getZeroMatrix(), mixNonTPMultiQubitKrausMap(), NUM_QUBITS, PREPARE_TEST, QUEST_ENV, setRandomTargets(), toComplexMatrixN(), and VLA.
TEST_CASE() [98/136]
TEST_CASE ("mixNonTPTwoQubitKrausMap" , "" [decoherence])
See also
mixNonTPTwoQubitKrausMap
Author
Tyson Jones
Definition at line 855 of file test_decoherence.cpp.
{
    PREPARE_TEST(qureg, ref);
    SECTION( "correctness" ) {
        int targ1 = GENERATE( range(0,NUM_QUBITS) );
        int targ2 = GENERATE_COPY( filter([=](int t){ return t!=targ1; }, range(0,NUM_QUBITS)) );
        int numOps = GENERATE( range(1,17) ); // max 16 inclusive
        // map consists of unconstrained 4x4 random matrices
        std::vector<QMatrix> matrs;
        for (int i=0; i<numOps; i++)
            matrs.push_back(getRandomQMatrix(4));
        VLA(ComplexMatrix4, ops, numOps);
        for (int i=0; i<numOps; i++)
            ops[i] = toComplexMatrix4(matrs[i]);
        mixNonTPTwoQubitKrausMap(qureg, targ1, targ2, ops, numOps);
        // set ref -> K_i ref K_i^dagger
        int targs[2] = {targ1, targ2};
        VLA(QMatrix, matrRefs, numOps);
        for (int i=0; i<numOps; i++) {
            matrRefs[i] = ref;
            applyReferenceOp(matrRefs[i], targs, 2, matrs[i]);
        }
        ref = getZeroMatrix(ref.size());
        for (int i=0; i<numOps; i++)
            ref += matrRefs[i];
        REQUIRE( areEqual(qureg, ref, 1E4*REAL_EPS) );
    }
    SECTION( "input validation" ) {
        SECTION( "number of operators" ) {
            int numOps = GENERATE( 0, 17 );
            REQUIRE_THROWS_WITH( mixNonTPTwoQubitKrausMap(qureg, 0,1, NULL, numOps), Contains("operators") );
        }
        SECTION( "target collision" ) {
            int target = GENERATE( range(0,NUM_QUBITS) );
            REQUIRE_THROWS_WITH( mixNonTPTwoQubitKrausMap(qureg, target, target, NULL, 1), Contains("target qubits") && Contains("unique") );
        }
        SECTION( "qubit index" ) {
            int target = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( mixNonTPTwoQubitKrausMap(qureg, 0,target, NULL, 1), Contains("Invalid target qubit") );
            REQUIRE_THROWS_WITH( mixNonTPTwoQubitKrausMap(qureg, target,0, NULL, 1), Contains("Invalid target qubit") );
        }
        SECTION( "density-matrix" ) {
            Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
            REQUIRE_THROWS_WITH( mixNonTPTwoQubitKrausMap(vec, 0,1, NULL, 1), Contains("density matrices") );
            destroyQureg(vec, QUEST_ENV);
        }
        SECTION( "operators fit in node" ) {
            qureg.numAmpsPerChunk = 15; // min 16
            REQUIRE_THROWS_WITH( mixNonTPTwoQubitKrausMap(qureg, 0,1, NULL, 1), Contains("targets too many qubits") );
        }
    }
    destroyQureg(qureg, QUEST_ENV);
}
References applyReferenceOp(), areEqual(), createQureg(), destroyQureg(), getRandomQMatrix(), getZeroMatrix(), mixNonTPTwoQubitKrausMap(), NUM_QUBITS, PREPARE_TEST, QUEST_ENV, toComplexMatrix4(), and VLA.
TEST_CASE() [99/136]
TEST_CASE ("mixPauli" , "" [decoherence])
See also
mixPauli
Author
Tyson Jones
Definition at line 447 of file test_decoherence.cpp.
{
    PREPARE_TEST(qureg, ref);
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        // randomly generate valid pauli-error probabilities
        qreal probs[3];
        qreal max0 = 1/2.;                 // satisfies p1 < 1 - py
        probs[0] = getRandomReal(0, max0);
        qreal max1 = (max0 - probs[0])/2.; // p2 can use half of p1's "unused space"
        probs[1] = getRandomReal(0, max1);
        qreal max2 = (max1 - probs[1])/2.; // p3 can use half of p2's "unused space"
        probs[2] = getRandomReal(0, max2);
        // uniformly randomly assign probs (bound to target)
        int inds[3] = {0,1,2};
        std::shuffle(inds,inds+3, std::default_random_engine(1E5 * target));
        qreal probX = probs[inds[0]];           // seed:target shows no variation
        qreal probY = probs[inds[1]];
        qreal probZ = probs[inds[2]];
        mixPauli(qureg, target, probX, probY, probZ);
        QMatrix xRef = ref;
        applyReferenceOp(xRef, target, QMatrix{{0,1},{1,0}}); // X ref X
        QMatrix yRef = ref;
        applyReferenceOp(yRef, target, QMatrix{{0,-qcomp(0,1)},{qcomp(0,1),0}}); // Y ref Y
        QMatrix zRef = ref;
        applyReferenceOp(zRef, target, QMatrix{{1,0},{0,-1}}); // Z ref Z
        ref = ((1 - probX - probY - probZ) * ref) +
              (probX * xRef) + (probY * yRef) + (probZ * zRef);
        REQUIRE( areEqual(qureg, ref) );
    }
    SECTION( "input validation" ) {
        SECTION( "qubit index" ) {
            int target = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( mixPauli(qureg, target, 0, 0, 0), Contains("Invalid target") );
        }
        SECTION( "probability" ) {
            int target = 0;
            // probs clearly must be in [0, 1]
            REQUIRE_THROWS_WITH( mixPauli(qureg, target, -.1,   0,   0), Contains("Probabilities") );
            REQUIRE_THROWS_WITH( mixPauli(qureg, target,   0, -.1,   0), Contains("Probabilities") );
            REQUIRE_THROWS_WITH( mixPauli(qureg, target,   0,   0, -.1), Contains("Probabilities") );
            // max single-non-zero-prob is 0.5
            REQUIRE_THROWS_WITH( mixPauli(qureg, target, .6,  0,  0), Contains("cannot exceed the probability") );
            REQUIRE_THROWS_WITH( mixPauli(qureg, target,  0, .6,  0), Contains("cannot exceed the probability") );
            REQUIRE_THROWS_WITH( mixPauli(qureg, target,  0,  0, .6), Contains("cannot exceed the probability") );
            // must satisfy px, py, pz < 1 - px - py - pz
            REQUIRE_THROWS_WITH( mixPauli(qureg, target,  .3,  .3, .3), Contains("cannot exceed the probability") );
        }
        SECTION( "density-matrix" ) {
            Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
            REQUIRE_THROWS_WITH( mixPauli(vec, 0, 0, 0, 0), Contains("density matrices") );
            destroyQureg(vec, QUEST_ENV);
        }
    }
    destroyQureg(qureg, QUEST_ENV);
}
References applyReferenceOp(), areEqual(), createQureg(), destroyQureg(), getRandomReal(), mixPauli(), NUM_QUBITS, PREPARE_TEST, qcomp, qreal, and QUEST_ENV.
TEST_CASE() [100/136]
TEST_CASE ("mixTwoQubitDephasing" , "" [decoherence])
See also
mixTwoQubitDephasing
Author
Tyson Jones
Definition at line 927 of file test_decoherence.cpp.
{
    PREPARE_TEST(qureg, ref);
    SECTION( "correctness" ) {
        int targ1 = GENERATE( range(0,NUM_QUBITS) );
        int targ2 = GENERATE_COPY( filter([=](int t){ return t!=targ1; }, range(0,NUM_QUBITS)) );
        qreal prob = getRandomReal(0, 3/4.);
        mixTwoQubitDephasing(qureg, targ1, targ2, prob);
        // ref -> (1 - prob) ref + prob/3 (Z1 ref Z1 + Z2 ref Z2 + Z1 Z2 ref Z1 Z2)
        QMatrix zMatr{{1,0},{0,-1}};
        QMatrix z1Ref = ref;
        applyReferenceOp(z1Ref, targ1, zMatr); // Z1 ref Z1
        QMatrix z2Ref = ref;
        applyReferenceOp(z2Ref, targ2, zMatr); // Z2 ref Z2
        QMatrix z1z2Ref = ref;
        applyReferenceOp(z1z2Ref, targ1, zMatr);
        applyReferenceOp(z1z2Ref, targ2, zMatr); // Z1 Z2 ref Z1 Z2
        ref = ((1 - prob) * ref) + (prob/3.) * (z1Ref + z2Ref + z1z2Ref);
        REQUIRE( areEqual(qureg, ref) );
    }
    SECTION( "input validation" ) {
        SECTION( "qubit indices" ) {
            int targ = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( mixTwoQubitDephasing(qureg, 0, targ, 0), Contains("Invalid target") );
            REQUIRE_THROWS_WITH( mixTwoQubitDephasing(qureg, targ, 0, 0), Contains("Invalid target") );
        }
        SECTION( "target collision" ) {
            int targ = GENERATE( range(0,NUM_QUBITS) );
            REQUIRE_THROWS_WITH( mixTwoQubitDephasing(qureg, targ, targ, 0), Contains("target") && Contains("unique") );
        }
        SECTION( "probability" ) {
            REQUIRE_THROWS_WITH( mixTwoQubitDephasing(qureg, 0, 1, -.1), Contains("Probabilities") );
            REQUIRE_THROWS_WITH( mixTwoQubitDephasing(qureg, 0, 1, 3/4. + .01), Contains("probability") && Contains("cannot exceed 3/4") );
        }
        SECTION( "density-matrix" ) {
            Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
            REQUIRE_THROWS_WITH( mixTwoQubitDephasing(vec, 0, 1, 0), Contains("density matrices") );
            destroyQureg(vec, QUEST_ENV);
        }
    }
    destroyQureg(qureg, QUEST_ENV);
}
References applyReferenceOp(), areEqual(), createQureg(), destroyQureg(), getRandomReal(), mixTwoQubitDephasing(), NUM_QUBITS, PREPARE_TEST, qreal, and QUEST_ENV.
TEST_CASE() [101/136]
TEST_CASE ("mixTwoQubitDepolarising" , "" [decoherence])
See also
mixTwoQubitDepolarising
Author
Tyson Jones
Definition at line 986 of file test_decoherence.cpp.
{
    PREPARE_TEST(qureg, ref);
    SECTION( "correctness" ) {
        int targ1 = GENERATE( range(0,NUM_QUBITS) );
        int targ2 = GENERATE_COPY( filter([=](int t){ return t!=targ1; }, range(0,NUM_QUBITS)) );
        qreal prob = getRandomReal(0, 15/16.);
        mixTwoQubitDepolarising(qureg, targ1, targ2, prob);
        QMatrix paulis[4] = {
            QMatrix{{1,0},{0,1}},       // I
            QMatrix{{0,1},{1,0}},       // X
            QMatrix{{0,-qcomp(0,1)},{qcomp(0,1),0}},    // Y
            QMatrix{{1,0},{0,-1}}       // Z
        };
        int targs[2] = {targ1, targ2};
        QMatrix refInit = ref;
        ref = (1 - (16/15.)*prob) * ref;
        for (int i=0; i<4; i++) {
            for (int j=0; j<4; j++) {
                QMatrix term = refInit;
                applyReferenceOp(term, targs, 2,
                    getKroneckerProduct(paulis[i], paulis[j]));
                ref += (prob/15.) * term;
            }
        }
        REQUIRE( areEqual(qureg, ref, 1E4*REAL_EPS) );
    }
    SECTION( "input validation" ) {
        SECTION( "qubit indices" ) {
            int targ = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( mixTwoQubitDepolarising(qureg, 0, targ, 0), Contains("Invalid target") );
            REQUIRE_THROWS_WITH( mixTwoQubitDepolarising(qureg, targ, 0, 0), Contains("Invalid target") );
        }
        SECTION( "target collision" ) {
            int targ = GENERATE( range(0,NUM_QUBITS) );
            REQUIRE_THROWS_WITH( mixTwoQubitDepolarising(qureg, targ, targ, 0), Contains("target") && Contains("unique") );
        }
        SECTION( "probability" ) {
            REQUIRE_THROWS_WITH( mixTwoQubitDepolarising(qureg, 0, 1, -.1), Contains("Probabilities") );
            REQUIRE_THROWS_WITH( mixTwoQubitDepolarising(qureg, 0, 1, 15/16. + .01), Contains("probability") && Contains("cannot exceed 15/16") );
        }
        SECTION( "density-matrix" ) {
            Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
            REQUIRE_THROWS_WITH( mixTwoQubitDepolarising(vec, 0, 1, 0), Contains("density matrices") );
            destroyQureg(vec, QUEST_ENV);
        }
    }
    destroyQureg(qureg, QUEST_ENV);
}
References applyReferenceOp(), areEqual(), createQureg(), destroyQureg(), getKroneckerProduct(), getRandomReal(), mixTwoQubitDepolarising(), NUM_QUBITS, PREPARE_TEST, qcomp, qreal, and QUEST_ENV.
TEST_CASE() [102/136]
TEST_CASE ("mixTwoQubitKrausMap" , "" [decoherence])
See also
mixTwoQubitKrausMap
Author
Tyson Jones
Definition at line 1053 of file test_decoherence.cpp.
{
    PREPARE_TEST(qureg, ref);
    SECTION( "correctness" ) {
        int targ1 = GENERATE( range(0,NUM_QUBITS) );
        int targ2 = GENERATE_COPY( filter([=](int t){ return t!=targ1; }, range(0,NUM_QUBITS)) );
        int numOps = GENERATE( range(1,17) ); // max 16 inclusive
        std::vector<QMatrix> matrs = getRandomKrausMap(2, numOps);
        VLA(ComplexMatrix4, ops, numOps);
        for (int i=0; i<numOps; i++)
            ops[i] = toComplexMatrix4(matrs[i]);
        mixTwoQubitKrausMap(qureg, targ1, targ2, ops, numOps);
        // set ref -> K_i ref K_i^dagger
        int targs[2] = {targ1, targ2};
        VLA(QMatrix, matrRefs, numOps);
        for (int i=0; i<numOps; i++) {
            matrRefs[i] = ref;
            applyReferenceOp(matrRefs[i], targs, 2, matrs[i]);
        }
        ref = getZeroMatrix(ref.size());
        for (int i=0; i<numOps; i++)
            ref += matrRefs[i];
        REQUIRE( areEqual(qureg, ref, 10*REAL_EPS) );
    }
    SECTION( "input validation" ) {
        SECTION( "number of operators" ) {
            int numOps = GENERATE( 0, 17 );
            REQUIRE_THROWS_WITH( mixTwoQubitKrausMap(qureg, 0,1, NULL, numOps), Contains("operators") );
        }
        SECTION( "trace preserving" ) {
            // valid Kraus map
            int numOps = GENERATE( range(1,16) );
            std::vector<QMatrix> matrs = getRandomKrausMap(2, numOps);
            VLA(ComplexMatrix4, ops, numOps);
            for (int i=0; i<numOps; i++)
                ops[i] = toComplexMatrix4(matrs[i]);
            // make only one of the ops at a time invalid
            ops[GENERATE_REF( range(0,numOps) )].real[0][0] = 0;
            REQUIRE_THROWS_WITH( mixTwoQubitKrausMap(qureg, 0,1, ops, numOps), Contains("trace preserving") );
        }
        SECTION( "target collision" ) {
            int target = GENERATE( range(0,NUM_QUBITS) );
            REQUIRE_THROWS_WITH( mixTwoQubitKrausMap(qureg, target, target, NULL, 1), Contains("target qubits") && Contains("unique") );
        }
        SECTION( "qubit index" ) {
            int target = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( mixTwoQubitKrausMap(qureg, 0,target, NULL, 1), Contains("Invalid target qubit") );
            REQUIRE_THROWS_WITH( mixTwoQubitKrausMap(qureg, target,0, NULL, 1), Contains("Invalid target qubit") );
        }
        SECTION( "density-matrix" ) {
            Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
            REQUIRE_THROWS_WITH( mixTwoQubitKrausMap(vec, 0,1, NULL, 1), Contains("density matrices") );
            destroyQureg(vec, QUEST_ENV);
        }
        SECTION( "operators fit in node" ) {
            qureg.numAmpsPerChunk = 15; // min 16
            REQUIRE_THROWS_WITH( mixTwoQubitKrausMap(qureg, 0,1, NULL, 1), Contains("targets too many qubits") );
        }
    }
    destroyQureg(qureg, QUEST_ENV);
}
References applyReferenceOp(), areEqual(), createQureg(), destroyQureg(), getRandomKrausMap(), getZeroMatrix(), mixTwoQubitKrausMap(), NUM_QUBITS, PREPARE_TEST, QUEST_ENV, ComplexMatrix4::real, toComplexMatrix4(), and VLA.
TEST_CASE() [103/136]
TEST_CASE ("multiControlledMultiQubitNot" , "" [unitaries])
See also
multiControlledMultiQubitNot
Author
Tyson Jones
Definition at line 977 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    SECTION( "correctness" ) {
        // try all possible numbers of targets and controls
        int numTargs = GENERATE_COPY( range(1,NUM_QUBITS) ); // leave space for 1 ctrl
        int maxNumCtrls = NUM_QUBITS - numTargs;
        int numCtrls = GENERATE_COPY( range(1,maxNumCtrls+1) );
        // generate all possible valid qubit arrangements
        int* targs = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numTargs) );
        int* ctrls = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numCtrls, targs, numTargs) );
        // for each qubit arrangement, use a new random unitary
        QMatrix notOp{{0, 1},{1,0}};
        SECTION( "state-vector" ) {
            multiControlledMultiQubitNot(quregVec, ctrls, numCtrls, targs, numTargs);
            for (int t=0; t<numTargs; t++)
                applyReferenceOp(refVec, ctrls, numCtrls, targs[t], notOp);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            multiControlledMultiQubitNot(quregMatr, ctrls, numCtrls, targs, numTargs);
            for (int t=0; t<numTargs; t++)
                applyReferenceOp(refMatr, ctrls, numCtrls, targs[t], notOp);
            REQUIRE( areEqual(quregMatr, refMatr) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "number of targets" ) {
            // there cannot be more targets than qubits in register
            // (numTargs=NUM_QUBITS is caught elsewhere, because that implies ctrls are invalid)
            int numTargs = GENERATE( -1, 0, NUM_QUBITS+1 );
            int targs[NUM_QUBITS+1]; // prevents seg-fault if validation doesn't trigger
            int ctrls[] = {0};
            REQUIRE_THROWS_WITH( multiControlledMultiQubitNot(quregVec, ctrls, 1, targs, numTargs), Contains("Invalid number of target"));
        }
        SECTION( "repetition in targets" ) {
            int ctrls[] = {0};
            int numTargs = 3;
            int targs[] = {1,2,2};
            REQUIRE_THROWS_WITH( multiControlledMultiQubitNot(quregVec, ctrls, 1, targs, numTargs), Contains("target") && Contains("unique"));
        }
        SECTION( "number of controls" ) {
            int numCtrls = GENERATE( -1, 0, NUM_QUBITS, NUM_QUBITS+1 );
            int ctrls[NUM_QUBITS+1]; // avoids seg-fault if validation not triggered
            int targs[1] = {0};
            REQUIRE_THROWS_WITH( multiControlledMultiQubitNot(quregVec, ctrls, numCtrls, targs, 1), Contains("Invalid number of control"));
        }
        SECTION( "repetition in controls" ) {
            int ctrls[] = {0,1,1};
            int targs[] = {3};
            REQUIRE_THROWS_WITH( multiControlledMultiQubitNot(quregVec, ctrls, 3, targs, 1), Contains("control") && Contains("unique"));
        }
        SECTION( "control and target collision" ) {
            int ctrls[] = {0,1,2};
            int targs[] = {3,1,4};
            REQUIRE_THROWS_WITH( multiControlledMultiQubitNot(quregVec, ctrls, 3, targs, 3), Contains("Control") && Contains("target") && Contains("disjoint"));
        }
        SECTION( "qubit indices" ) {
            // valid inds
            int numQb = 2;
            int qb1[2] = {0,1};
            int qb2[2] = {2,3};
            // make qb1 invalid
            int inv = GENERATE( -1, NUM_QUBITS );
            qb1[GENERATE_COPY(range(0,numQb))] = inv;
            REQUIRE_THROWS_WITH( multiControlledMultiQubitNot(quregVec, qb1, numQb, qb2, numQb), Contains("Invalid control") );
            REQUIRE_THROWS_WITH( multiControlledMultiQubitNot(quregVec, qb2, numQb, qb1, numQb), Contains("Invalid target") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, multiControlledMultiQubitNot(), NUM_QUBITS, PREPARE_TEST, and sublists().
TEST_CASE() [104/136]
TEST_CASE ("multiControlledMultiQubitUnitary" , "" [unitaries])
See also
multiControlledMultiQubitUnitary
Author
Tyson Jones
Definition at line 1073 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    // figure out max-num targs (inclusive) allowed by hardware backend
    int maxNumTargs = calcLog2(quregVec.numAmpsPerChunk);
    if (maxNumTargs >= NUM_QUBITS)
        maxNumTargs = NUM_QUBITS - 1; // leave room for min-number of control qubits
    SECTION( "correctness" ) {
        // try all possible numbers of targets and controls
        int numTargs = GENERATE_COPY( range(1,maxNumTargs+1) );
        int maxNumCtrls = NUM_QUBITS - numTargs;
        int numCtrls = GENERATE_COPY( range(1,maxNumCtrls+1) );
        // generate all possible valid qubit arrangements
        int* targs = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numTargs) );
        int* ctrls = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numCtrls, targs, numTargs) );
        // for each qubit arrangement, use a new random unitary
        QMatrix op = getRandomUnitary(numTargs);
        ComplexMatrixN matr = createComplexMatrixN(numTargs);
        toComplexMatrixN(op, matr);
        SECTION( "state-vector" ) {
            multiControlledMultiQubitUnitary(quregVec, ctrls, numCtrls, targs, numTargs, matr);
            applyReferenceOp(refVec, ctrls, numCtrls, targs, numTargs, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            multiControlledMultiQubitUnitary(quregMatr, ctrls, numCtrls, targs, numTargs, matr);
            applyReferenceOp(refMatr, ctrls, numCtrls, targs, numTargs, op);
            REQUIRE( areEqual(quregMatr, refMatr, 10*REAL_EPS) );
        }
        destroyComplexMatrixN(matr);
    }
    SECTION( "input validation" ) {
        SECTION( "number of targets" ) {
            // there cannot be more targets than qubits in register
            // (numTargs=NUM_QUBITS is caught elsewhere, because that implies ctrls are invalid)
            int numTargs = GENERATE( -1, 0, NUM_QUBITS+1 );
            int targs[NUM_QUBITS+1]; // prevents seg-fault if validation doesn't trigger
            int ctrls[] = {0};
            ComplexMatrixN matr = createComplexMatrixN(NUM_QUBITS+1); // prevent seg-fault
            toComplexMatrixN(getRandomUnitary(NUM_QUBITS+1), matr); // ensure unitary
            REQUIRE_THROWS_WITH( multiControlledMultiQubitUnitary(quregVec, ctrls, 1, targs, numTargs, matr), Contains("Invalid number of target"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "repetition in targets" ) {
            int ctrls[] = {0};
            int numTargs = 3;
            int targs[] = {1,2,2};
            ComplexMatrixN matr = createComplexMatrixN(numTargs); // prevents seg-fault if validation doesn't trigger
            toComplexMatrixN(getRandomUnitary(numTargs), matr); // ensure unitary
            REQUIRE_THROWS_WITH( multiControlledMultiQubitUnitary(quregVec, ctrls, 1, targs, numTargs, matr), Contains("target") && Contains("unique"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "number of controls" ) {
            int numCtrls = GENERATE( -1, 0, NUM_QUBITS, NUM_QUBITS+1 );
            int ctrls[NUM_QUBITS+1]; // avoids seg-fault if validation not triggered
            int targs[1] = {0};
            ComplexMatrixN matr = createComplexMatrixN(1);
            toComplexMatrixN(getRandomUnitary(1), matr); // ensure unitary
            REQUIRE_THROWS_WITH( multiControlledMultiQubitUnitary(quregVec, ctrls, numCtrls, targs, 1, matr), Contains("Invalid number of control"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "repetition in controls" ) {
            int ctrls[] = {0,1,1};
            int targs[] = {3};
            ComplexMatrixN matr = createComplexMatrixN(1);
            toComplexMatrixN(getRandomUnitary(1), matr); // ensure unitary
            REQUIRE_THROWS_WITH( multiControlledMultiQubitUnitary(quregVec, ctrls, 3, targs, 1, matr), Contains("control") && Contains("unique"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "control and target collision" ) {
            int ctrls[] = {0,1,2};
            int targs[] = {3,1,4};
            ComplexMatrixN matr = createComplexMatrixN(3);
            toComplexMatrixN(getRandomUnitary(3), matr); // ensure unitary
            REQUIRE_THROWS_WITH( multiControlledMultiQubitUnitary(quregVec, ctrls, 3, targs, 3, matr), Contains("Control") && Contains("target") && Contains("disjoint"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "qubit indices" ) {
            // valid inds
            int numQb = 2;
            int qb1[2] = {0,1};
            int qb2[2] = {2,3};
            ComplexMatrixN matr = createComplexMatrixN(numQb);
            toComplexMatrixN(getRandomUnitary(numQb), matr); // ensure unitary
            // make qb1 invalid
            int inv = GENERATE( -1, NUM_QUBITS );
            qb1[GENERATE_COPY(range(0,numQb))] = inv;
            REQUIRE_THROWS_WITH( multiControlledMultiQubitUnitary(quregVec, qb1, numQb, qb2, numQb, matr), Contains("Invalid control") );
            REQUIRE_THROWS_WITH( multiControlledMultiQubitUnitary(quregVec, qb2, numQb, qb1, numQb, matr), Contains("Invalid target") );
            destroyComplexMatrixN(matr);
        }
        SECTION( "unitarity" ) {
            int ctrls[1] = {0};
            int numTargs = GENERATE_COPY( range(1,maxNumTargs+1) );
            VLA(int, targs, numTargs);
            for (int i=0; i<numTargs; i++)
                targs[i] = i+1;
            ComplexMatrixN matr = createComplexMatrixN(numTargs); // initially zero, hence not-unitary
            REQUIRE_THROWS_WITH( multiControlledMultiQubitUnitary(quregVec, ctrls, 1, targs, numTargs, matr), Contains("unitary") );
            destroyComplexMatrixN(matr);
        }
        SECTION( "unitary creation" ) {
            int ctrls[1] = {0};
            int targs[3] = {1,2,3};
            /* compilers don't auto-initialise to NULL; the below circumstance
             * only really occurs when 'malloc' returns NULL in createComplexMatrixN,
             * which actually triggers its own validation. Hence this test is useless
             * currently.
             */
            ComplexMatrixN matr;
            matr.real = NULL;
            matr.imag = NULL;
            REQUIRE_THROWS_WITH( multiControlledMultiQubitUnitary(quregVec, ctrls, 1, targs, 3, matr), Contains("created") );
        }
        SECTION( "unitary dimensions" ) {
            int ctrls[1] = {0};
            int targs[2] = {1,2};
            ComplexMatrixN matr = createComplexMatrixN(3); // intentionally wrong size
            toComplexMatrixN(getRandomUnitary(3), matr); // ensure unitary
            REQUIRE_THROWS_WITH( multiControlledMultiQubitUnitary(quregVec, ctrls, 1, targs, 2, matr), Contains("matrix size"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "unitary fits in node" ) {
            // pretend we have a very limited distributed memory (judged by matr size)
            quregVec.numAmpsPerChunk = 1;
            int ctrls[1] = {0};
            int targs[2] = {1,2};
            ComplexMatrixN matr = createComplexMatrixN(2);
            toComplexMatrixN(getRandomUnitary(2), matr); // ensure unitary
            REQUIRE_THROWS_WITH( multiControlledMultiQubitUnitary(quregVec, ctrls, 1, targs, 2, matr), Contains("targets too many qubits"));
            destroyComplexMatrixN(matr);
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), calcLog2(), CLEANUP_TEST, createComplexMatrixN(), destroyComplexMatrixN(), getRandomUnitary(), ComplexMatrixN::imag, multiControlledMultiQubitUnitary(), NUM_QUBITS, PREPARE_TEST, ComplexMatrixN::real, sublists(), toComplexMatrixN(), and VLA.
TEST_CASE() [105/136]
TEST_CASE ("multiControlledMultiRotatePauli" , "" [unitaries])
See also
multiControlledMultiRotatePauli
Author
Tyson Jones
Definition at line 1245 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    qreal param = getRandomReal(-4*M_PI, 4*M_PI);
    SECTION( "correctness" ) {
        // try all possible numbers of targets and controls
        int numTargs = GENERATE_COPY( range(1,NUM_QUBITS) ); // leave space for min 1 control qubit
        int maxNumCtrls = NUM_QUBITS - numTargs;
        int numCtrls = GENERATE_COPY( range(1,maxNumCtrls+1) );
        // generate all possible valid qubit arrangements
        int* targs = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numTargs) );
        int* ctrls = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numCtrls, targs, numTargs) );
        /* it's too expensive to try ALL Pauli sequences, via
         *      pauliOpType* paulis = GENERATE_COPY( pauliseqs(numTargs) );.
         * Furthermore, take(10, pauliseqs(numTargs)) will try the same pauli codes.
         * Hence, we instead opt to randomly generate pauliseqs
         */
        VLA(pauliOpType, paulis, numTargs);
        for (int i=0; i<numTargs; i++)
            paulis[i] = (pauliOpType) getRandomInt(0,4);
        // exclude identities from reference matrix exp (they apply unwanted global phase)
        VLA(int, refTargs, numTargs);
        int numRefTargs = 0;
        QMatrix xMatr{{0,1},{1,0}};
        QMatrix yMatr{{0,-qcomp(0,1)},{qcomp(0,1),0}};
        QMatrix zMatr{{1,0},{0,-1}};
        // build correct reference matrix by pauli-matrix exponentiation...
        QMatrix pauliProd{{1}};
        for (int i=0; i<numTargs; i++) {
            QMatrix fac;
            if (paulis[i] == PAULI_I) continue; // exclude I-targets from ref list
            if (paulis[i] == PAULI_X) fac = xMatr;
            if (paulis[i] == PAULI_Y) fac = yMatr;
            if (paulis[i] == PAULI_Z) fac = zMatr;
            pauliProd = getKroneckerProduct(fac, pauliProd);
            // include this target in ref list
            refTargs[numRefTargs++] = targs[i];
        }
        // produces exp(-i param/2 pauliProd), unless pauliProd = I
        QMatrix op;
        if (numRefTargs > 0)
            op = getExponentialOfPauliMatrix(param, pauliProd);
        SECTION( "state-vector" ) {
            multiControlledMultiRotatePauli(quregVec, ctrls, numCtrls, targs, paulis, numTargs, param);
            if (numRefTargs > 0)
                applyReferenceOp(refVec, ctrls, numCtrls, refTargs, numRefTargs, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            multiControlledMultiRotatePauli(quregMatr, ctrls, numCtrls, targs, paulis, numTargs, param);
            if (numRefTargs > 0)
                applyReferenceOp(refMatr, ctrls, numCtrls, refTargs, numRefTargs, op);
            REQUIRE( areEqual(quregMatr, refMatr, 10*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        // test all validation on both state-vector and density-matrix.
        // want GENERATE_COPY( quregVec, quregMatr ), but too lazy to patch
        // using github.com/catchorg/Catch2/issues/1809
        Qureg regs[] = {quregVec, quregMatr};
        Qureg qureg = regs[GENERATE(0,1)];
        // over-sized array to prevent seg-fault in case of validation fail below
        pauliOpType paulis[NUM_QUBITS+1];
        for (int q=0; q<NUM_QUBITS+1; q++)
            paulis[q] = PAULI_I;
        SECTION( "pauli codes" ) {
            int numCtrls = 1;
            int ctrls[] = {3};
            int numTargs = 3;
            int targs[3] = {0, 1, 2};
            // make a single Pauli invalid
            paulis[GENERATE_COPY(range(0,numTargs))] = (pauliOpType) GENERATE( -1, 4 );
            REQUIRE_THROWS_WITH( multiControlledMultiRotatePauli(qureg, ctrls, numCtrls, targs, paulis, numTargs, param), Contains("Invalid Pauli code"));
        }
        SECTION( "number of targets" ) {
            // there cannot be more targets than qubits in register
            // (numTargs=NUM_QUBITS is caught elsewhere, because that implies ctrls are invalid)
            int numTargs = GENERATE( -1, 0, NUM_QUBITS+1 );
            int numCtrls = 1;
            int targs[NUM_QUBITS+1]; // prevents seg-fault if validation doesn't trigger
            int ctrls[] = {0};
            REQUIRE_THROWS_WITH( multiControlledMultiRotatePauli(qureg, ctrls, numCtrls, targs, paulis, numTargs, param), Contains("Invalid number of target") );
        }
        SECTION( "repetition in targets" ) {
            int numCtrls = 1;
            int numTargs = 3;
            int ctrls[] = {0};
            int targs[] = {1,2,2};
            REQUIRE_THROWS_WITH( multiControlledMultiRotatePauli(qureg, ctrls, numCtrls, targs, paulis, numTargs, param), Contains("target") && Contains("unique"));
        }
        SECTION( "number of controls" ) {
            int numCtrls = GENERATE( -1, 0, NUM_QUBITS, NUM_QUBITS+1 );
            int numTargs = 1;
            int ctrls[NUM_QUBITS+1]; // avoids seg-fault if validation not triggered
            int targs[1] = {0};
            REQUIRE_THROWS_WITH( multiControlledMultiRotatePauli(qureg, ctrls, numCtrls, targs, paulis, numTargs, param), Contains("Invalid number of control"));
        }
        SECTION( "repetition in controls" ) {
            int numCtrls = 3;
            int numTargs = 1;
            int ctrls[] = {0,1,1};
            int targs[] = {3};
            REQUIRE_THROWS_WITH( multiControlledMultiRotatePauli(qureg, ctrls, numCtrls, targs, paulis, numTargs, param), Contains("control") && Contains("unique"));
        }
        SECTION( "control and target collision" ) {
            int numCtrls = 3;
            int numTargs = 3;
            int ctrls[] = {0,1,2};
            int targs[] = {3,1,4};
            REQUIRE_THROWS_WITH( multiControlledMultiRotatePauli(qureg, ctrls, numCtrls, targs, paulis, numTargs, param), Contains("Control") && Contains("target") && Contains("disjoint"));
        }
        SECTION( "qubit indices" ) {
            // valid inds
            int numQb = 2;
            int qb1[2] = {0,1};
            int qb2[2] = {2,3};
            // make qb1 invalid
            int inv = GENERATE( -1, NUM_QUBITS );
            qb1[GENERATE_COPY(range(0,numQb))] = inv;
            REQUIRE_THROWS_WITH( multiControlledMultiRotatePauli(qureg, qb1, numQb, qb2, paulis, numQb, param), Contains("Invalid control") );
            REQUIRE_THROWS_WITH( multiControlledMultiRotatePauli(qureg, qb2, numQb, qb1, paulis, numQb, param),  Contains("Invalid target") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, getExponentialOfPauliMatrix(), getKroneckerProduct(), getRandomInt(), getRandomReal(), M_PI, multiControlledMultiRotatePauli(), NUM_QUBITS, PAULI_I, PAULI_X, PAULI_Y, PAULI_Z, PREPARE_TEST, qcomp, qreal, sublists(), and VLA.
TEST_CASE() [106/136]
TEST_CASE ("multiControlledMultiRotateZ" , "" [unitaries])
See also
multiControlledMultiRotateZ
Author
Tyson Jones
Definition at line 1408 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    qreal param = getRandomReal(-4*M_PI, 4*M_PI);
    SECTION( "correctness" ) {
        // try all possible numbers of targets and controls
        int numTargs = GENERATE_COPY( range(1,NUM_QUBITS) ); // leave space for min 1 control qubit
        int maxNumCtrls = NUM_QUBITS - numTargs;
        int numCtrls = GENERATE_COPY( range(1,maxNumCtrls+1) );
        // generate all possible valid qubit arrangements
        int* targs = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numTargs) );
        int* ctrls = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numCtrls, targs, numTargs) );
        // build correct reference matrix by diagonal-matrix exponentiation...
        QMatrix zMatr{{1,0},{0,-1}};
        QMatrix zProd = zMatr;
        for (int t=0; t<numTargs-1; t++)
            zProd = getKroneckerProduct(zMatr, zProd); // Z . Z ... Z
        // exp( -i param/2 Z . Z ... Z)
        QMatrix op = getExponentialOfDiagonalMatrix(qcomp(0, -param/2) * zProd);
        SECTION( "state-vector" ) {
            multiControlledMultiRotateZ(quregVec, ctrls, numCtrls, targs, numTargs, param);
            applyReferenceOp(refVec, ctrls, numCtrls, targs, numTargs, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            multiControlledMultiRotateZ(quregMatr, ctrls, numCtrls, targs, numTargs, param);
            applyReferenceOp(refMatr, ctrls, numCtrls, targs, numTargs, op);
            REQUIRE( areEqual(quregMatr, refMatr, 2*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        // test all validation on both state-vector and density-matrix.
        // want GENERATE_COPY( quregVec, quregMatr ), but too lazy to patch
        // using github.com/catchorg/Catch2/issues/1809
        Qureg regs[] = {quregVec, quregMatr};
        Qureg qureg = regs[GENERATE(0,1)];
        SECTION( "number of targets" ) {
            // there cannot be more targets than qubits in register
            // (numTargs=NUM_QUBITS is caught elsewhere, because that implies ctrls are invalid)
            int numTargs = GENERATE( -1, 0, NUM_QUBITS+1 );
            int numCtrls = 1;
            int targs[NUM_QUBITS+1]; // prevents seg-fault if validation doesn't trigger
            int ctrls[] = {0};
            REQUIRE_THROWS_WITH( multiControlledMultiRotateZ(qureg, ctrls, numCtrls, targs, numTargs, param), Contains("Invalid number of target") );
        }
        SECTION( "repetition in targets" ) {
            int numCtrls = 1;
            int numTargs = 3;
            int ctrls[] = {0};
            int targs[] = {1,2,2};
            REQUIRE_THROWS_WITH( multiControlledMultiRotateZ(qureg, ctrls, numCtrls, targs, numTargs, param), Contains("target") && Contains("unique"));
        }
        SECTION( "number of controls" ) {
            int numCtrls = GENERATE( -1, 0, NUM_QUBITS, NUM_QUBITS+1 );
            int numTargs = 1;
            int ctrls[NUM_QUBITS+1]; // avoids seg-fault if validation not triggered
            int targs[1] = {0};
            REQUIRE_THROWS_WITH( multiControlledMultiRotateZ(qureg, ctrls, numCtrls, targs, numTargs, param), Contains("Invalid number of control"));
        }
        SECTION( "repetition in controls" ) {
            int numCtrls = 3;
            int numTargs = 1;
            int ctrls[] = {0,1,1};
            int targs[] = {3};
            REQUIRE_THROWS_WITH( multiControlledMultiRotateZ(qureg, ctrls, numCtrls, targs, numTargs, param), Contains("control") && Contains("unique"));
        }
        SECTION( "control and target collision" ) {
            int numCtrls = 3;
            int numTargs = 3;
            int ctrls[] = {0,1,2};
            int targs[] = {3,1,4};
            REQUIRE_THROWS_WITH( multiControlledMultiRotateZ(qureg, ctrls, numCtrls, targs, numTargs, param), Contains("Control") && Contains("target") && Contains("disjoint"));
        }
        SECTION( "qubit indices" ) {
            // valid inds
            int numQb = 2;
            int qb1[2] = {0,1};
            int qb2[2] = {2,3};
            // make qb1 invalid
            int inv = GENERATE( -1, NUM_QUBITS );
            qb1[GENERATE_COPY(range(0,numQb))] = inv;
            REQUIRE_THROWS_WITH( multiControlledMultiRotateZ(qureg, qb1, numQb, qb2, numQb, param), Contains("Invalid control") );
            REQUIRE_THROWS_WITH( multiControlledMultiRotateZ(qureg, qb2, numQb, qb1, numQb, param), Contains("Invalid target") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, getExponentialOfDiagonalMatrix(), getKroneckerProduct(), getRandomReal(), M_PI, multiControlledMultiRotateZ(), NUM_QUBITS, PREPARE_TEST, qcomp, qreal, and sublists().
TEST_CASE() [107/136]
TEST_CASE ("multiControlledPhaseFlip" , "" [unitaries])
See also
multiControlledPhaseFlip
Author
Tyson Jones
Definition at line 1525 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    // acts on the final control qubit
    QMatrix op{{1,0},{0,-1}};
    SECTION( "correctness" ) {
        // generate ALL valid qubit arrangements
        int numCtrls = GENERATE( range(1,NUM_QUBITS) ); // numCtrls=NUM_QUBITS stopped by overzealous validation
        int* ctrls = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numCtrls) );
        SECTION( "state-vector" ) {
            multiControlledPhaseFlip(quregVec, ctrls, numCtrls);
            applyReferenceOp(refVec, ctrls, numCtrls-1, ctrls[numCtrls-1], op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            multiControlledPhaseFlip(quregMatr, ctrls, numCtrls);
            applyReferenceOp(refMatr, ctrls, numCtrls-1, ctrls[numCtrls-1], op);
            REQUIRE( areEqual(quregMatr, refMatr) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "number of controls" ) {
            int numCtrls = GENERATE( -1, 0, NUM_QUBITS+1 );
            int ctrls[NUM_QUBITS+1]; // avoids seg-fault if validation not triggered
            REQUIRE_THROWS_WITH( multiControlledPhaseFlip(quregVec, ctrls, numCtrls), Contains("Invalid number of qubits"));
        }
        SECTION( "repetition of controls" ) {
            int numCtrls = 3;
            int ctrls[] = {0,1,1};
            REQUIRE_THROWS_WITH( multiControlledPhaseFlip(quregVec, ctrls, numCtrls), Contains("qubits must be unique"));
        }
        SECTION( "qubit indices" ) {
            int numCtrls = 3;
            int ctrls[] = { 1, 2, GENERATE( -1, NUM_QUBITS ) };
            REQUIRE_THROWS_WITH( multiControlledPhaseFlip(quregVec, ctrls, numCtrls), Contains("Invalid qubit") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, multiControlledPhaseFlip(), NUM_QUBITS, PREPARE_TEST, and sublists().
TEST_CASE() [108/136]
TEST_CASE ("multiControlledPhaseShift" , "" [unitaries])
See also
multiControlledPhaseShift
Author
Tyson Jones
Definition at line 1581 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    qreal param = getRandomReal(-2*M_PI, 2*M_PI);
    QMatrix op{{1,0},{0,expI(param)}};
    SECTION( "correctness" ) {
        // generate ALL valid qubit arrangements
        int numCtrls = GENERATE( range(1,NUM_QUBITS) ); // numCtrls=NUM_QUBITS stopped by overzealous validation
        int* ctrls = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numCtrls) );
        SECTION( "state-vector" ) {
            multiControlledPhaseShift(quregVec, ctrls, numCtrls, param);
            applyReferenceOp(refVec, ctrls, numCtrls-1, ctrls[numCtrls-1], op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            multiControlledPhaseShift(quregMatr, ctrls, numCtrls, param);
            applyReferenceOp(refMatr, ctrls, numCtrls-1, ctrls[numCtrls-1], op);
            REQUIRE( areEqual(quregMatr, refMatr, 2*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "number of controls" ) {
            int numCtrls = GENERATE( -1, 0, NUM_QUBITS+1 );
            int ctrls[NUM_QUBITS+1]; // avoids seg-fault if validation not triggered
            REQUIRE_THROWS_WITH( multiControlledPhaseShift(quregVec, ctrls, numCtrls, param), Contains("Invalid number of qubits"));
        }
        SECTION( "repetition of controls" ) {
            int numCtrls = 3;
            int ctrls[] = {0,1,1};
            REQUIRE_THROWS_WITH( multiControlledPhaseShift(quregVec, ctrls, numCtrls, param), Contains("qubits must be unique"));
        }
        SECTION( "qubit indices" ) {
            int numCtrls = 3;
            int ctrls[] = { 1, 2, GENERATE( -1, NUM_QUBITS ) };
            REQUIRE_THROWS_WITH( multiControlledPhaseShift(quregVec, ctrls, numCtrls, param), Contains("Invalid qubit") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, expI(), getRandomReal(), M_PI, multiControlledPhaseShift(), NUM_QUBITS, PREPARE_TEST, qreal, and sublists().
TEST_CASE() [109/136]
TEST_CASE ("multiControlledTwoQubitUnitary" , "" [unitaries])
See also
multiControlledTwoQubitUnitary
Author
Tyson Jones
Definition at line 1636 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    // in distributed mode, each node must be able to fit all amps modified by unitary
    REQUIRE( quregVec.numAmpsPerChunk >= 4 );
    // every test will use a unique random matrix
    QMatrix op = getRandomUnitary(2);
    ComplexMatrix4 matr = toComplexMatrix4(op);
    SECTION( "correctness" ) {
        // generate ALL valid qubit arrangements
        int targ1 = GENERATE( range(0,NUM_QUBITS) );
        int targ2 = GENERATE_COPY( filter([=](int t){ return t!=targ1; }, range(0,NUM_QUBITS)) );
        int targs[] = {targ1, targ2};
        int numCtrls = GENERATE( range(1,NUM_QUBITS-1) ); // leave room for 2 targets (upper bound is exclusive)
        int* ctrls = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numCtrls, targs, 2) );
        SECTION( "state-vector" ) {
            multiControlledTwoQubitUnitary(quregVec, ctrls, numCtrls, targ1, targ2, matr);
            applyReferenceOp(refVec, ctrls, numCtrls, targ1, targ2, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            multiControlledTwoQubitUnitary(quregMatr, ctrls, numCtrls, targ1, targ2, matr);
            applyReferenceOp(refMatr, ctrls, numCtrls, targ1, targ2, op);
            REQUIRE( areEqual(quregMatr, refMatr, 10*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "number of controls" ) {
            // numCtrls=(NUM_QUBITS-1) is ok since requires ctrl qubit inds are invalid
            int numCtrls = GENERATE( -1, 0, NUM_QUBITS, NUM_QUBITS+1 );
            int ctrls[NUM_QUBITS+1]; // avoids seg-fault if validation not triggered
            REQUIRE_THROWS_WITH( multiControlledTwoQubitUnitary(quregVec, ctrls, numCtrls, 0, 1, matr), Contains("Invalid number of control"));
        }
        SECTION( "repetition of controls" ) {
            int numCtrls = 3;
            int ctrls[] = {0,1,1};
            int targ1 = 2;
            int targ2 = 3;
            REQUIRE_THROWS_WITH( multiControlledTwoQubitUnitary(quregVec, ctrls, numCtrls, targ1, targ2, matr), Contains("control") && Contains("unique"));;
        }
        SECTION( "repetition of targets" ) {
            int numCtrls = 3;
            int ctrls[] = {0,1,2};
            int targ1 = 3;
            int targ2 = targ1;
            REQUIRE_THROWS_WITH( multiControlledTwoQubitUnitary(quregVec, ctrls, numCtrls, targ1, targ2, matr), Contains("target") && Contains("unique"));
        }
        SECTION( "control and target collision" ) {
            int numCtrls = 3;
            int ctrls[] = {0,1,2};
            int targ1 = 3;
            int targ2 = ctrls[GENERATE_COPY( range(0,numCtrls) )];
            REQUIRE_THROWS_WITH( multiControlledTwoQubitUnitary(quregVec, ctrls, numCtrls, targ1, targ2, matr), Contains("Control") && Contains("target") );
        }
        SECTION( "qubit indices" ) {
            // valid indices
            int targ1 = 0;
            int targ2 = 1;
            int numCtrls = 3;
            int ctrls[] = { 2, 3, 4 };
            int inv = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( multiControlledTwoQubitUnitary(quregVec, ctrls, numCtrls, inv, targ2, matr), Contains("Invalid target") );
            REQUIRE_THROWS_WITH( multiControlledTwoQubitUnitary(quregVec, ctrls, numCtrls, targ1, inv, matr), Contains("Invalid target") );
            ctrls[numCtrls-1] = inv; // make ctrls invalid
            REQUIRE_THROWS_WITH( multiControlledTwoQubitUnitary(quregVec, ctrls, numCtrls, targ1, targ2, matr), Contains("Invalid control") );
        }
        SECTION( "unitarity " ) {
            int ctrls[1] = {0};
            matr.real[0][0] = 0; // break unitarity
            REQUIRE_THROWS_WITH( multiControlledTwoQubitUnitary(quregVec, ctrls, 1, 1, 2, matr), Contains("unitary") );
        }
        SECTION( "unitary fits in node" ) {
            // pretend we have a very limited distributed memory
            quregVec.numAmpsPerChunk = 1;
            int ctrls[1] = {0};
            REQUIRE_THROWS_WITH( multiControlledTwoQubitUnitary(quregVec, ctrls, 1, 1, 2, matr), Contains("targets too many qubits"));
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, getRandomUnitary(), multiControlledTwoQubitUnitary(), NUM_QUBITS, PREPARE_TEST, ComplexMatrix4::real, sublists(), and toComplexMatrix4().
TEST_CASE() [110/136]
TEST_CASE ("multiControlledUnitary" , "" [unitaries])
See also
multiControlledUnitary
Author
Tyson Jones
Definition at line 1740 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    // every test will use a unique random matrix
    QMatrix op = getRandomUnitary(1);
    ComplexMatrix2 matr = toComplexMatrix2(op);
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        int numCtrls = GENERATE( range(1,NUM_QUBITS) ); // leave space for one target (exclusive upper bound)
        int* ctrls = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numCtrls, target) );
        SECTION( "state-vector" ) {
            multiControlledUnitary(quregVec, ctrls, numCtrls, target, matr);
            applyReferenceOp(refVec, ctrls, numCtrls, target, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            multiControlledUnitary(quregMatr, ctrls, numCtrls, target, matr);
            applyReferenceOp(refMatr, ctrls, numCtrls, target, op);
            REQUIRE( areEqual(quregMatr, refMatr, 10*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "number of controls" ) {
            int numCtrls = GENERATE( -1, 0, NUM_QUBITS, NUM_QUBITS+1 );
            int ctrls[NUM_QUBITS+1]; // avoids seg-fault if validation not triggered
            REQUIRE_THROWS_WITH( multiControlledUnitary(quregVec, ctrls, numCtrls, 0, matr), Contains("Invalid number of control"));
        }
        SECTION( "repetition of controls" ) {
            int ctrls[] = {0,1,1};
            REQUIRE_THROWS_WITH( multiControlledUnitary(quregVec, ctrls, 3, 2, matr), Contains("control") && Contains("unique"));
        }
        SECTION( "control and target collision" ) {
            int ctrls[] = {0,1,2};
            int targ = ctrls[GENERATE( range(0,3) )];
            REQUIRE_THROWS_WITH( multiControlledUnitary(quregVec, ctrls, 3, targ, matr), Contains("Control") && Contains("target") );
        }
        SECTION( "qubit indices" ) {
            int ctrls[] = { 1, 2, GENERATE( -1, NUM_QUBITS ) };
            REQUIRE_THROWS_WITH( multiControlledUnitary(quregVec, ctrls, 3, 0, matr), Contains("Invalid control") );
            ctrls[2] = 3; // make ctrls valid
            int targ = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( multiControlledUnitary(quregVec, ctrls, 3, targ, matr), Contains("Invalid target") );
        }
        SECTION( "unitarity" ) {
            matr.real[0][0] = 0; // break matr unitarity
            int ctrls[] = {0};
            REQUIRE_THROWS_WITH( multiControlledUnitary(quregVec, ctrls, 1, 1, matr), Contains("unitary") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, getRandomUnitary(), multiControlledUnitary(), NUM_QUBITS, PREPARE_TEST, ComplexMatrix2::real, sublists(), and toComplexMatrix2().
TEST_CASE() [111/136]
TEST_CASE ("multiQubitNot" , "" [unitaries])
See also
multiQubitNot
Author
Tyson Jones
Definition at line 1811 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    SECTION( "correctness" ) {
        // try all possible numbers of targets and controls
        int numTargs = GENERATE_COPY( range(1,NUM_QUBITS+1) ); // leave space for 1 ctrl
        // generate all possible valid qubit arrangements
        int* targs = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numTargs) );
        // for each qubit arrangement, use a new random unitary
        QMatrix notOp{{0, 1},{1,0}};
        SECTION( "state-vector" ) {
            multiQubitNot(quregVec, targs, numTargs);
            for (int t=0; t<numTargs; t++)
                applyReferenceOp(refVec, targs[t], notOp);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            multiQubitNot(quregMatr, targs, numTargs);
            for (int t=0; t<numTargs; t++)
                applyReferenceOp(refMatr, targs[t], notOp);
            REQUIRE( areEqual(quregMatr, refMatr) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "number of targets" ) {
            // there cannot be more targets than qubits in register
            int numTargs = GENERATE( -1, 0, NUM_QUBITS+1 );
            int targs[NUM_QUBITS+1];
            REQUIRE_THROWS_WITH( multiQubitNot(quregVec, targs, numTargs), Contains("Invalid number of target"));
        }
        SECTION( "repetition in targets" ) {
            int numTargs = 3;
            int targs[] = {1,2,2};
            REQUIRE_THROWS_WITH( multiQubitNot(quregVec, targs, numTargs), Contains("target") && Contains("unique"));
        }
        SECTION( "target indices" ) {
            // valid inds
            int numQb = 5;
            int qubits[] = {0,1,2,3,4};
            // make one index invalid
            qubits[GENERATE_COPY(range(0,numQb))] = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( multiQubitNot(quregVec, qubits, numQb), Contains("Invalid target") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, multiQubitNot(), NUM_QUBITS, PREPARE_TEST, and sublists().
TEST_CASE() [112/136]
TEST_CASE ("multiQubitUnitary" , "" [unitaries])
See also
multiQubitUnitary
Author
Tyson Jones
Definition at line 1878 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    // figure out max-num (inclusive) targs allowed by hardware backend
    int maxNumTargs = calcLog2(quregVec.numAmpsPerChunk);
    SECTION( "correctness" ) {
        // generate all possible qubit arrangements
        int numTargs = GENERATE_COPY( range(1,maxNumTargs+1) ); // inclusive upper bound
        int* targs = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numTargs) );
        // for each qubit arrangement, use a new random unitary
        QMatrix op = getRandomUnitary(numTargs);
        ComplexMatrixN matr = createComplexMatrixN(numTargs);
        toComplexMatrixN(op, matr);
        SECTION( "state-vector" ) {
            multiQubitUnitary(quregVec, targs, numTargs, matr);
            applyReferenceOp(refVec, targs, numTargs, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            multiQubitUnitary(quregMatr, targs, numTargs, matr);
            applyReferenceOp(refMatr, targs, numTargs, op);
            REQUIRE( areEqual(quregMatr, refMatr, 10*REAL_EPS) );
        }
        destroyComplexMatrixN(matr);
    }
    SECTION( "input validation" ) {
        SECTION( "number of targets" ) {
            // there cannot be more targets than qubits in register
            int numTargs = GENERATE( -1, 0, NUM_QUBITS+1 );
            int targs[NUM_QUBITS+1]; // prevents seg-fault if validation doesn't trigger
            ComplexMatrixN matr = createComplexMatrixN(NUM_QUBITS+1); // prevent seg-fault
            REQUIRE_THROWS_WITH( multiQubitUnitary(quregVec, targs, numTargs, matr), Contains("Invalid number of target"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "repetition in targets" ) {
            int numTargs = 3;
            int targs[] = {1,2,2};
            ComplexMatrixN matr = createComplexMatrixN(numTargs); // prevents seg-fault if validation doesn't trigger
            REQUIRE_THROWS_WITH( multiQubitUnitary(quregVec, targs, numTargs, matr), Contains("target") && Contains("unique"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "qubit indices" ) {
            int numTargs = 3;
            int targs[] = {1,2,3};
            ComplexMatrixN matr = createComplexMatrixN(numTargs); // prevents seg-fault if validation doesn't trigger
            int inv = GENERATE( -1, NUM_QUBITS );
            targs[GENERATE_COPY( range(0,numTargs) )] = inv; // make invalid target
            REQUIRE_THROWS_WITH( multiQubitUnitary(quregVec, targs, numTargs, matr), Contains("Invalid target") );
            destroyComplexMatrixN(matr);
        }
        SECTION( "unitarity" ) {
            int numTargs = GENERATE_COPY( range(1,maxNumTargs) );
            VLA(int, targs, numTargs);
            for (int i=0; i<numTargs; i++)
                targs[i] = i+1;
            ComplexMatrixN matr = createComplexMatrixN(numTargs); // initially zero, hence not-unitary
            REQUIRE_THROWS_WITH( multiQubitUnitary(quregVec, targs, numTargs, matr), Contains("unitary") );
            destroyComplexMatrixN(matr);
        }
        SECTION( "unitary creation" ) {
            int numTargs = 3;
            int targs[] = {1,2,3};
            /* compilers don't auto-initialise to NULL; the below circumstance
             * only really occurs when 'malloc' returns NULL in createComplexMatrixN,
             * which actually triggers its own validation. Hence this test is useless
             * currently.
             */
            ComplexMatrixN matr;
            matr.real = NULL;
            matr.imag = NULL;
            REQUIRE_THROWS_WITH( multiQubitUnitary(quregVec, targs, numTargs, matr), Contains("created") );
        }
        SECTION( "unitary dimensions" ) {
            int targs[2] = {1,2};
            ComplexMatrixN matr = createComplexMatrixN(3); // intentionally wrong size
            REQUIRE_THROWS_WITH( multiQubitUnitary(quregVec, targs, 2, matr), Contains("matrix size"));
            destroyComplexMatrixN(matr);
        }
        SECTION( "unitary fits in node" ) {
            // pretend we have a very limited distributed memory (judged by matr size)
            quregVec.numAmpsPerChunk = 1;
            int qb[] = {1,2};
            ComplexMatrixN matr = createComplexMatrixN(2); // prevents seg-fault if validation doesn't trigger
            REQUIRE_THROWS_WITH( multiQubitUnitary(quregVec, qb, 2, matr), Contains("targets too many qubits"));
            destroyComplexMatrixN(matr);
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), calcLog2(), CLEANUP_TEST, createComplexMatrixN(), destroyComplexMatrixN(), getRandomUnitary(), ComplexMatrixN::imag, multiQubitUnitary(), NUM_QUBITS, PREPARE_TEST, ComplexMatrixN::real, sublists(), toComplexMatrixN(), and VLA.
TEST_CASE() [113/136]
TEST_CASE ("multiRotatePauli" , "" [unitaries])
See also
multiRotatePauli
Author
Tyson Jones
Definition at line 1997 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    qreal param = getRandomReal(-4*M_PI, 4*M_PI);
    SECTION( "correctness" ) {
        int numTargs = GENERATE( range(1,NUM_QUBITS+1) );
        int* targs = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numTargs) );
        /* it's too expensive to try ALL Pauli sequences, via
         *      pauliOpType* paulis = GENERATE_COPY( pauliseqs(numTargs) );.
         * Furthermore, take(10, pauliseqs(numTargs)) will try the same pauli codes.
         * Hence, we instead opt to repeatedlyrandomly generate pauliseqs
         */
        GENERATE( range(0,10) ); // gen 10 random pauli-codes for every targs
        VLA(pauliOpType, paulis, numTargs);
        for (int i=0; i<numTargs; i++)
            paulis[i] = (pauliOpType) getRandomInt(0,4);
        // exclude identities from reference matrix exp (they apply unwanted global phase)
        VLA(int, refTargs, numTargs);
        int numRefTargs = 0;
        QMatrix xMatr{{0,1},{1,0}};
        QMatrix yMatr{{0,-qcomp(0,1)},{qcomp(0,1),0}};
        QMatrix zMatr{{1,0},{0,-1}};
        // build correct reference matrix by pauli-matrix exponentiation...
        QMatrix pauliProd{{1}};
        for (int i=0; i<numTargs; i++) {
            QMatrix fac;
            if (paulis[i] == PAULI_I) continue; // exclude I-targets from ref list
            if (paulis[i] == PAULI_X) fac = xMatr;
            if (paulis[i] == PAULI_Y) fac = yMatr;
            if (paulis[i] == PAULI_Z) fac = zMatr;
            pauliProd = getKroneckerProduct(fac, pauliProd);
            // include this target in ref list
            refTargs[numRefTargs++] = targs[i];
        }
        // produces exp(-i param/2 pauliProd), unless pauliProd = I
        QMatrix op;
        if (numRefTargs > 0)
            op = getExponentialOfPauliMatrix(param, pauliProd);
        SECTION( "state-vector" ) {
            multiRotatePauli(quregVec, targs, paulis, numTargs, param);
            if (numRefTargs > 0)
                applyReferenceOp(refVec, refTargs, numRefTargs, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            multiRotatePauli(quregMatr, targs, paulis, numTargs, param);
            if (numRefTargs > 0)
                applyReferenceOp(refMatr, refTargs, numRefTargs, op);
            REQUIRE( areEqual(quregMatr, refMatr, 10*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "number of targets" ) {
            int numTargs = GENERATE( -1, 0, NUM_QUBITS+1 );
            int targs[NUM_QUBITS+1]; // prevent seg-fault if validation isn't triggered
            pauliOpType paulis[NUM_QUBITS+1] = {PAULI_I};
            REQUIRE_THROWS_WITH( multiRotatePauli(quregVec, targs, paulis, numTargs, param), Contains("Invalid number of target"));
        }
        SECTION( "repetition of targets" ) {
            int numTargs = 3;
            int targs[3] = {0, 1, 1};
            pauliOpType paulis[3] = {PAULI_I};
            REQUIRE_THROWS_WITH( multiRotatePauli(quregVec, targs, paulis, numTargs, param), Contains("target") && Contains("unique"));
        }
        SECTION( "qubit indices" ) {
            int numTargs = 3;
            int targs[3] = {0, 1, 2};
            targs[GENERATE_COPY(range(0,numTargs))] = GENERATE( -1, NUM_QUBITS );
            pauliOpType paulis[3] = {PAULI_I};
            REQUIRE_THROWS_WITH( multiRotatePauli(quregVec, targs, paulis, numTargs, param), Contains("Invalid target"));
        }
        SECTION( "pauli codes" ) {
            int numTargs = 3;
            int targs[3] = {0, 1, 2};
            pauliOpType paulis[3] = {PAULI_I, PAULI_I, PAULI_I};
            paulis[GENERATE_COPY(range(0,numTargs))] = (pauliOpType) GENERATE( -1, 4 );
            REQUIRE_THROWS_WITH( multiRotatePauli(quregVec, targs, paulis, numTargs, param), Contains("Invalid Pauli code"));
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, getExponentialOfPauliMatrix(), getKroneckerProduct(), getRandomInt(), getRandomReal(), M_PI, multiRotatePauli(), NUM_QUBITS, PAULI_I, PAULI_X, PAULI_Y, PAULI_Z, PREPARE_TEST, qcomp, qreal, sublists(), and VLA.
TEST_CASE() [114/136]
TEST_CASE ("multiRotateZ" , "" [unitaries])
See also
multiRotateZ
Author
Tyson Jones
Definition at line 2100 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    qreal param = getRandomReal(-4*M_PI, 4*M_PI);
    SECTION( "correctness" ) {
        int numTargs = GENERATE( range(1,NUM_QUBITS+1) );
        int* targs = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numTargs) );
        // build correct reference matrix by diagonal-matrix exponentiation...
        QMatrix zMatr{{1,0},{0,-1}};
        QMatrix zProd = zMatr;
        for (int t=0; t<numTargs-1; t++)
            zProd = getKroneckerProduct(zMatr, zProd); // Z . Z ... Z
        // (-i param/2) Z . I . Z ...
        QMatrix expArg = qcomp(0, -param/2) *
            getFullOperatorMatrix(NULL, 0, targs, numTargs, zProd, NUM_QUBITS);
        // exp( -i param/2 Z . I . Z ...)
        QMatrix op = getExponentialOfDiagonalMatrix(expArg);
        // all qubits to specify full operator matrix on reference structures
        int allQubits[NUM_QUBITS];
        for (int i=0; i<NUM_QUBITS; i++)
            allQubits[i] = i;
        SECTION( "state-vector" ) {
            multiRotateZ(quregVec, targs, numTargs, param);
            applyReferenceOp(refVec, allQubits, NUM_QUBITS, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            multiRotateZ(quregMatr, targs, numTargs, param);
            applyReferenceOp(refMatr, allQubits, NUM_QUBITS, op);
            REQUIRE( areEqual(quregMatr, refMatr, 2*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "number of targets" ) {
            int numTargs = GENERATE( -1, 0, NUM_QUBITS+1 );
            int targs[NUM_QUBITS+1]; // prevent seg-fault if validation isn't triggered
            REQUIRE_THROWS_WITH( multiRotateZ(quregVec, targs, numTargs, param), Contains("Invalid number of target"));
        }
        SECTION( "repetition of targets" ) {
            int numTargs = 3;
            int targs[3] = {0, 1, 1};
            REQUIRE_THROWS_WITH( multiRotateZ(quregVec, targs, numTargs, param), Contains("target") && Contains("unique"));
        }
        SECTION( "qubit indices" ) {
            int numTargs = 3;
            int targs[3] = {0, 1, 2};
            targs[GENERATE_COPY(range(0,numTargs))] = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( multiRotateZ(quregVec, targs, numTargs, param), Contains("Invalid target"));
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, getExponentialOfDiagonalMatrix(), getFullOperatorMatrix(), getKroneckerProduct(), getRandomReal(), M_PI, multiRotateZ(), NUM_QUBITS, PREPARE_TEST, qcomp, qreal, and sublists().
TEST_CASE() [115/136]
TEST_CASE ("multiStateControlledUnitary" , "" [unitaries])
See also
multiStateControlledUnitary
Author
Tyson Jones
Definition at line 2173 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    // every test will use a unique random matrix
    QMatrix op = getRandomUnitary(1);
    ComplexMatrix2 matr = toComplexMatrix2(op);
    // the zero-conditioned control qubits can be effected by notting before/after ctrls
    QMatrix notOp{{0,1},{1,0}};
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        int numCtrls = GENERATE( range(1,NUM_QUBITS) ); // leave space for one target (exclusive upper bound)
        int* ctrls = GENERATE_COPY( sublists(range(0,NUM_QUBITS), numCtrls, target) );
        int* ctrlState = GENERATE_COPY( bitsets(numCtrls) );
        SECTION( "state-vector" ) {
            multiStateControlledUnitary(quregVec, ctrls, ctrlState, numCtrls, target, matr);
            // simulate controlled-state by notting before & after controls
            for (int i=0; i<numCtrls; i++)
                if (ctrlState[i] == 0)
                    applyReferenceOp(refVec, ctrls[i], notOp);
            applyReferenceOp(refVec, ctrls, numCtrls, target, op);
            for (int i=0; i<numCtrls; i++)
                if (ctrlState[i] == 0)
                    applyReferenceOp(refVec, ctrls[i], notOp);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            multiStateControlledUnitary(quregMatr, ctrls, ctrlState, numCtrls, target, matr);
            // simulate controlled-state by notting before & after controls
            for (int i=0; i<numCtrls; i++)
                if (ctrlState[i] == 0)
                    applyReferenceOp(refMatr, ctrls[i], notOp);
            applyReferenceOp(refMatr, ctrls, numCtrls, target, op);
            for (int i=0; i<numCtrls; i++)
                if (ctrlState[i] == 0)
                    applyReferenceOp(refMatr, ctrls[i], notOp);
            REQUIRE( areEqual(quregMatr, refMatr, 10*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "number of controls" ) {
            int numCtrls = GENERATE( -1, 0, NUM_QUBITS, NUM_QUBITS+1 );
            int ctrls[NUM_QUBITS+1];
            int ctrlState[NUM_QUBITS+1] = {0};
            REQUIRE_THROWS_WITH( multiStateControlledUnitary(quregVec, ctrls, ctrlState, numCtrls, 0, matr), Contains("Invalid number of control"));
        }
        SECTION( "repetition of controls" ) {
            int ctrls[] = {0,1,1};
            int ctrlState[] = {0, 1, 0};
            REQUIRE_THROWS_WITH( multiStateControlledUnitary(quregVec, ctrls, ctrlState, 3, 2, matr), Contains("control") && Contains("unique"));
        }
        SECTION( "control and target collision" ) {
            int ctrls[] = {0,1,2};
            int ctrlState[] = {0, 1, 0};
            int targ = ctrls[GENERATE( range(0,3) )];
            REQUIRE_THROWS_WITH( multiStateControlledUnitary(quregVec, ctrls, ctrlState, 3, targ, matr), Contains("Control") && Contains("target") );
        }
        SECTION( "qubit indices" ) {
            int ctrls[] = { 1, 2, GENERATE( -1, NUM_QUBITS ) };
            int ctrlState[] = {0, 1, 0};
            REQUIRE_THROWS_WITH( multiStateControlledUnitary(quregVec, ctrls, ctrlState, 3, 0, matr), Contains("Invalid control") );
            ctrls[2] = 3; // make ctrls valid
            int targ = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( multiStateControlledUnitary(quregVec, ctrls, ctrlState, 3, targ, matr), Contains("Invalid target") );
        }
        SECTION( "unitarity" ) {
            matr.real[0][0] = 0; // break matr unitarity
            int ctrls[] = {0};
            int ctrlState[1] = {0};
            REQUIRE_THROWS_WITH( multiStateControlledUnitary(quregVec, ctrls, ctrlState, 1, 1, matr), Contains("unitary") );
        }
        SECTION( "control state bits" ) {
            // valid qubits
            int ctrls[] = {0, 1, 2};
            int ctrlState[] = {0, 0, 0};
            int targ = 3;
            // make invalid
            ctrlState[2] = GENERATE(-1, 2);
            REQUIRE_THROWS_WITH( multiStateControlledUnitary(quregVec, ctrls, ctrlState, 3, targ, matr), Contains("state") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), bitsets(), CLEANUP_TEST, getRandomUnitary(), multiStateControlledUnitary(), NUM_QUBITS, PREPARE_TEST, ComplexMatrix2::real, sublists(), and toComplexMatrix2().
TEST_CASE() [116/136]
TEST_CASE ("pauliX" , "" [unitaries])
See also
pauliX
Author
Tyson Jones
Definition at line 2282 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    QMatrix op{{0,1},{1,0}};
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        SECTION( "state-vector" ) {
            pauliX(quregVec, target);
            applyReferenceOp(refVec, target, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix correctness" ) {
            pauliX(quregMatr, target);
            applyReferenceOp(refMatr, target, op);
            REQUIRE( areEqual(quregMatr, refMatr) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qubit indices" ) {
            int target = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( pauliX(quregVec, target), Contains("Invalid target") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, NUM_QUBITS, pauliX(), and PREPARE_TEST.
TEST_CASE() [117/136]
TEST_CASE ("pauliY" , "" [unitaries])
See also
pauliY
Author
Tyson Jones
Definition at line 2321 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    QMatrix op{{0,-qcomp(0,1)},{qcomp(0,1),0}};
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        SECTION( "state-vector" ) {
            pauliY(quregVec, target);
            applyReferenceOp(refVec, target, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix correctness" ) {
            pauliY(quregMatr, target);
            applyReferenceOp(refMatr, target, op);
            REQUIRE( areEqual(quregMatr, refMatr) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qubit indices" ) {
            int target = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( pauliY(quregVec, target), Contains("Invalid target") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, NUM_QUBITS, pauliY(), PREPARE_TEST, and qcomp.
TEST_CASE() [118/136]
TEST_CASE ("pauliZ" , "" [unitaries])
See also
pauliZ
Author
Tyson Jones
Definition at line 2360 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    QMatrix op{{1,0},{0,-1}};
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        SECTION( "state-vector" ) {
            pauliZ(quregVec, target);
            applyReferenceOp(refVec, target, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix correctness" ) {
            pauliZ(quregMatr, target);
            applyReferenceOp(refMatr, target, op);
            REQUIRE( areEqual(quregMatr, refMatr) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qubit indices" ) {
            int target = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( pauliZ(quregVec, target), Contains("Invalid target") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, NUM_QUBITS, pauliZ(), and PREPARE_TEST.
TEST_CASE() [119/136]
TEST_CASE ("phaseShift" , "" [unitaries])
See also
phaseShift
Author
Tyson Jones
Definition at line 2399 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    qreal param = getRandomReal(-2*M_PI, 2*M_PI);
    QMatrix op{{1,0},{0,expI(param)}};
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        SECTION( "state-vector ") {
            phaseShift(quregVec, target, param);
            applyReferenceOp(refVec, target, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            phaseShift(quregMatr, target, param);
            applyReferenceOp(refMatr, target, op);
            REQUIRE( areEqual(quregMatr, refMatr) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qubit indices" ) {
            int target = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( phaseShift(quregVec, target, param), Contains("Invalid target") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, expI(), getRandomReal(), M_PI, NUM_QUBITS, phaseShift(), PREPARE_TEST, and qreal.
TEST_CASE() [120/136]
TEST_CASE ("rotateAroundAxis" , "" [unitaries])
See also
rotateAroundAxis
Author
Tyson Jones
Definition at line 2439 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    // each test will use a random parameter and axis vector
    qreal param = getRandomReal(-4*M_PI, 4*M_PI);
    Vector vec;
    vec.x=getRandomReal(-1,1);
    vec.y=getRandomReal(-1,1);
    vec.z=getRandomReal(-1,1);
    // Rn(a) = cos(a/2)I - i sin(a/2) n . paulivector
    // (pg 24 of vcpc.univie.ac.at/~ian/hotlist/qc/talks/bloch-sphere-rotations.pdf)
    qreal c = cos(param/2);
    qreal s = sin(param/2);
    qreal m = sqrt(vec.x*vec.x + vec.y*vec.y + vec.z*vec.z);
    QMatrix op{{c - qcomp(0,1)*vec.z*s/m, -(vec.y + qcomp(0,1)*vec.x)*s/m},
               {(vec.y - qcomp(0,1)*vec.x)*s/m, c + qcomp(0,1)*vec.z*s/m}};
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        SECTION( "state-vector ") {
            rotateAroundAxis(quregVec, target, param, vec);
            applyReferenceOp(refVec, target, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            rotateAroundAxis(quregMatr, target, param, vec);
            applyReferenceOp(refMatr, target, op);
            REQUIRE( areEqual(quregMatr, refMatr, 10*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qubit indices" ) {
            int target = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( rotateAroundAxis(quregVec, target, param, vec), Contains("Invalid target") );
        }
        SECTION( "zero rotation axis" ) {
            int target = 0;
            vec.x=0; vec.y=0; vec.z=0;
            REQUIRE_THROWS_WITH( rotateAroundAxis(quregVec, target, param, vec), Contains("Invalid axis") && Contains("zero") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, getRandomReal(), M_PI, NUM_QUBITS, PREPARE_TEST, qcomp, qreal, rotateAroundAxis(), Vector::x, Vector::y, and Vector::z.
TEST_CASE() [121/136]
TEST_CASE ("rotateX" , "" [unitaries])
See also
rotateX
Author
Tyson Jones
Definition at line 2498 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    qreal param = getRandomReal(-4*M_PI, 4*M_PI);
    QMatrix op{
        {cos(param/2), - sin(param/2)*qcomp(0,1)},
        {- sin(param/2)*qcomp(0,1), cos(param/2)}};
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        SECTION( "state-vector ") {
            rotateX(quregVec, target, param);
            applyReferenceOp(refVec, target, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            rotateX(quregMatr, target, param);
            applyReferenceOp(refMatr, target, op);
            REQUIRE( areEqual(quregMatr, refMatr, 2*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qubit indices" ) {
            int target = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( rotateX(quregVec, target, param), Contains("Invalid target") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, getRandomReal(), M_PI, NUM_QUBITS, PREPARE_TEST, qcomp, qreal, and rotateX().
TEST_CASE() [122/136]
TEST_CASE ("rotateY" , "" [unitaries])
See also
rotateY
Author
Tyson Jones
Definition at line 2540 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    qreal param = getRandomReal(-4*M_PI, 4*M_PI);
    QMatrix op{{cos(param/2), -sin(param/2)},{sin(param/2), cos(param/2)}};
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        SECTION( "state-vector ") {
            rotateY(quregVec, target, param);
            applyReferenceOp(refVec, target, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            rotateY(quregMatr, target, param);
            applyReferenceOp(refMatr, target, op);
            REQUIRE( areEqual(quregMatr, refMatr, 2*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qubit indices" ) {
            int target = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( rotateY(quregVec, target, param), Contains("Invalid target") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, getRandomReal(), M_PI, NUM_QUBITS, PREPARE_TEST, qreal, and rotateY().
TEST_CASE() [123/136]
TEST_CASE ("rotateZ" , "" [unitaries])
See also
rotateZ
Author
Tyson Jones
Definition at line 2580 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    qreal param = getRandomReal(-4*M_PI, 4*M_PI);
    QMatrix op{{expI(-param/2.),0},{0,expI(param/2.)}};
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        SECTION( "state-vector ") {
            rotateZ(quregVec, target, param);
            applyReferenceOp(refVec, target, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            rotateZ(quregMatr, target, param);
            applyReferenceOp(refMatr, target, op);
            REQUIRE( areEqual(quregMatr, refMatr, 2*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qubit indices" ) {
            int target = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( rotateZ(quregVec, target, param), Contains("Invalid target") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, expI(), getRandomReal(), M_PI, NUM_QUBITS, PREPARE_TEST, qreal, and rotateZ().
TEST_CASE() [124/136]
TEST_CASE ("setAmps" , "" [state_initialisations])
See also
setAmps
Author
Tyson Jones
Definition at line 381 of file test_state_initialisations.cpp.
{
    Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
    int maxInd = vec.numAmpsTotal;
    VLA(qreal, reals, maxInd);
    VLA(qreal, imags, maxInd);
    SECTION( "correctness" ) {
        SECTION( "state-vector" ) {
            // all valid number of amplitudes and offsets
            int startInd = GENERATE_COPY( range(0,maxInd) );
            int numAmps = GENERATE_COPY( range(0,1+maxInd-startInd) ); // upper-bound allows all amps specified
            // generate random amplitudes
            for (int i=0; i<numAmps; i++) {
                reals[i] = getRandomReal(-5,5);
                imags[i] = getRandomReal(-5,5);
            }
            // check both specified and un-specified amplitudes are correctly handled
            initDebugState(vec);
            QVector vecRef = toQVector(vec);
            setAmps(vec, startInd, reals, imags, numAmps);
            for (int i=0; i<numAmps; i++)
                vecRef[startInd+i] = reals[i] + imags[i] * (qcomp) 1i;
            REQUIRE( areEqual(vec, vecRef) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "start index" ) {
            int startInd = GENERATE_COPY( -1, maxInd );
            int numAmps = 0;
            REQUIRE_THROWS_WITH( setAmps(vec, startInd, reals, imags, numAmps), Contains("Invalid amplitude index") );
        }
        SECTION( "number of amplitudes" ) {
            // independent
            int startInd = 0;
            int numAmps = GENERATE_COPY( -1, maxInd+1 );
            REQUIRE_THROWS_WITH( setAmps(vec, startInd, reals, imags, numAmps), Contains("Invalid number of amplitudes") );
            // invalid considering start-index
            startInd = maxInd - 1;
            numAmps = 2;
            REQUIRE_THROWS_WITH( setAmps(vec, startInd, reals, imags, numAmps), Contains("More amplitudes given than exist") );
        }
        SECTION( "density-matrix" ) {
            Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
            REQUIRE_THROWS_WITH( setAmps(mat, 0, reals, imags, 0), Contains("valid only for state-vectors") );
            destroyQureg(mat, QUEST_ENV);
        }
    }
    destroyQureg(vec, QUEST_ENV);
}
References areEqual(), createDensityQureg(), createQureg(), destroyQureg(), getRandomReal(), initDebugState(), NUM_QUBITS, Qureg::numAmpsTotal, qcomp, qreal, QUEST_ENV, setAmps(), toQVector(), and VLA.
TEST_CASE() [125/136]
TEST_CASE ("setDensityAmps" , "" [state_initialisations])
See also
setDensityAmps
Author
Tyson Jones
Definition at line 451 of file test_state_initialisations.cpp.
{
    Qureg matr = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    VLA(qreal, reals, matr.numAmpsTotal);
    VLA(qreal, imags, matr.numAmpsTotal);
    int maxInd = (1 << NUM_QUBITS);
    SECTION( "correctness" ) {
        SECTION( "density-matrix" ) {
            // try all valid number of amplitudes and offsets
            int startRow = GENERATE_COPY( range(0,maxInd) );
            int startCol = GENERATE_COPY( range(0,maxInd) );
            // determine the max number of amps that can be passed from the given start indices
            int numPriorAmps = startRow + startCol*(1 << matr.numQubitsRepresented);
            int maxNumAmps = matr.numAmpsTotal - numPriorAmps;
            // previously, we tried all possible number of amps, like so:
            //      int numAmps = GENERATE_COPY( range(0,maxNumAmps) ); // upper-bound allows all amps specified
            // but this is too many and causes a timeout on Ubuntu.
            // So we instead randomly choose the number of amps, and repeat 10 times.
            int numAmps = getRandomInt(0, maxNumAmps);
            GENERATE_COPY( range(0,10) );
            // generate random amplitudes
            for (int i=0; i<numAmps; i++) {
                reals[i] = getRandomReal(-5,5);
                imags[i] = getRandomReal(-5,5);
            }
            // check both specified and un-specified amplitudes are correctly handled
            initDebugState(matr);
            QMatrix matrRef = toQMatrix(matr);
            setDensityAmps(matr, startRow, startCol, reals, imags, numAmps);
            int r=startRow;
            int c=startCol;
            for (int i=0; i<numAmps; i++) {
                qcomp amp = reals[i] + imags[i] * (qcomp) 1i;
                matrRef[r][c] = amp;
                r++;
                if (r >= maxInd ) {
                    r=0;
                    c++;
                }
            }
            REQUIRE( areEqual(matr, matrRef) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "start index" ) {
            int badInd = GENERATE_COPY( -1, maxInd );
            int numAmps = 0;
            REQUIRE_THROWS_WITH( setDensityAmps(matr, badInd, 0, reals, imags, numAmps), Contains("Invalid amplitude index") );
            REQUIRE_THROWS_WITH( setDensityAmps(matr, 0, badInd, reals, imags, numAmps), Contains("Invalid amplitude index") );
        }
        SECTION( "number of amplitudes" ) {
            // independent
            int numAmps = GENERATE_COPY( -1, matr.numAmpsTotal+1 );
            REQUIRE_THROWS_WITH( setDensityAmps(matr, 0, 0, reals, imags, numAmps), Contains("Invalid number of amplitudes") );
            // invalid considering start-index
            REQUIRE_THROWS_WITH( setDensityAmps(matr, maxInd-1, maxInd-1, reals, imags, 2), Contains("More amplitudes given than exist") );
            REQUIRE_THROWS_WITH( setDensityAmps(matr, maxInd-1, maxInd-2, reals, imags, maxInd+2), Contains("More amplitudes given than exist") );
        }
        SECTION( "state-vector" ) {
            Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
            REQUIRE_THROWS_WITH( setDensityAmps(vec, 0, 0, reals, imags, 0), Contains("valid only for density matrices") );
            destroyQureg(vec, QUEST_ENV);
        }
    }
    destroyQureg(matr, QUEST_ENV);
}
References areEqual(), createDensityQureg(), createQureg(), destroyQureg(), getRandomInt(), getRandomReal(), initDebugState(), NUM_QUBITS, Qureg::numAmpsTotal, Qureg::numQubitsRepresented, qcomp, qreal, QUEST_ENV, setDensityAmps(), toQMatrix(), and VLA.
TEST_CASE() [126/136]
TEST_CASE ("setDiagonalOpElems" , "" [data_structures])
See also
setDiagonalOpElems
Author
Tyson Jones
Definition at line 1032 of file test_data_structures.cpp.
{
    // must be at least one amplitude per node
    int minNumQb = calcLog2(QUEST_ENV.numRanks);
    if (minNumQb == 0)
        minNumQb = 1;
    // try 10 valid number of qubits (even for validation)
    int numQb = GENERATE_COPY( range(minNumQb, minNumQb+10) );
    DiagonalOp op = createDiagonalOp(numQb, QUEST_ENV);
    SECTION( "correctness" ) {
        // make entire array on every node
        long long int len = (1LL << numQb);
        VLA(qreal, reals, len);
        VLA(qreal, imags, len);
        long long int n;
        for (n=0; n<len; n++) {
            reals[n] = (qreal)    n;
            imags[n] = (qreal) -2*n; // (n - 2n i)
        }
        // set one value at a time (only relevant nodes will update)
        for (n=0; n<len; n++)
            setDiagonalOpElems(op, n, &reals[n], &imags[n], 1);
        // check op.real and op.imag updated correctly
        REQUIRE( areEqual(toQVector(op), reals, imags) );
        // no check that GPU values updated (occurs in initDiagonalOp)
    }
    SECTION( "input validation" ) {
        long long int maxInd = (1LL << numQb);
        qreal *reals = NULL;
        qreal *imags = NULL;
        SECTION( "start index" ) {
            int startInd = GENERATE_COPY( -1, maxInd );
            int numAmps = 1;
            REQUIRE_THROWS_WITH( setDiagonalOpElems(op, startInd, reals, imags, numAmps), Contains("Invalid element index") );
        }
        SECTION( "number of elements" ) {
            // independent
            int startInd = 0;
            int numAmps = GENERATE_COPY( -1, maxInd+1 );
            REQUIRE_THROWS_WITH( setDiagonalOpElems(op, startInd, reals, imags, numAmps), Contains("Invalid number of elements") );
            // invalid considering start-index
            startInd = maxInd - 1;
            numAmps = 2;
            REQUIRE_THROWS_WITH( setDiagonalOpElems(op, startInd, reals, imags, numAmps), Contains("More elements given than exist") );
        }
    }
    destroyDiagonalOp(op, QUEST_ENV);
}
References areEqual(), calcLog2(), createDiagonalOp(), destroyDiagonalOp(), QuESTEnv::numRanks, qreal, QUEST_ENV, setDiagonalOpElems(), toQVector(), and VLA.
TEST_CASE() [127/136]
TEST_CASE ("setQuregToPauliHamil" , "" [state_initialisations])
See also
setQuregToPauliHamil
Author
Tyson Jones
Definition at line 540 of file test_state_initialisations.cpp.
{
    Qureg rho = createDensityQureg(NUM_QUBITS, QUEST_ENV);
    SECTION( "correctness" ) {
        // too expensive to enumerate all paulis, so try 10x with random ones
        GENERATE( range(0,10) );
        int numTerms = GENERATE( 1, 2, 10, 15, 100, 1000 );
        PauliHamil hamil = createPauliHamil(NUM_QUBITS, numTerms);
        setRandomPauliSum(hamil);
        setQuregToPauliHamil(rho, hamil);
        REQUIRE( areEqual(rho, toQMatrix(hamil)) );
        destroyPauliHamil(hamil);
    }
    SECTION( "input validation" ) {
        SECTION( "density-matrix" ) {
            PauliHamil hamil = createPauliHamil(NUM_QUBITS, 5);
            Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
            REQUIRE_THROWS_WITH( setQuregToPauliHamil(vec, hamil), Contains("density matrices") );
            destroyQureg(vec, QUEST_ENV);
            destroyPauliHamil(hamil);
        }
        SECTION( "pauli codes" ) {
            int numTerms = 3;
            PauliHamil hamil = createPauliHamil(NUM_QUBITS, numTerms);
            // make one pauli code wrong
            hamil.pauliCodes[GENERATE_COPY( range(0,numTerms*NUM_QUBITS) )] = (pauliOpType) GENERATE( -1, 4 );
            REQUIRE_THROWS_WITH( setQuregToPauliHamil(rho, hamil), Contains("Invalid Pauli code") );
            destroyPauliHamil(hamil);
        }
        SECTION( "matching hamiltonian qubits" ) {
            int numTerms = 1;
            PauliHamil hamil = createPauliHamil(NUM_QUBITS + 1, numTerms);
            REQUIRE_THROWS_WITH( setQuregToPauliHamil(rho, hamil), Contains("same number of qubits") );
            destroyPauliHamil(hamil);
        }
    }
    destroyQureg(rho, QUEST_ENV);
}
References areEqual(), createDensityQureg(), createPauliHamil(), createQureg(), destroyPauliHamil(), destroyQureg(), NUM_QUBITS, PauliHamil::pauliCodes, QUEST_ENV, setQuregToPauliHamil(), setRandomPauliSum(), and toQMatrix().
TEST_CASE() [128/136]
TEST_CASE ("setWeightedQureg" , "" [state_initialisations])
See also
setWeightedQureg
Author
Tyson Jones
Definition at line 600 of file test_state_initialisations.cpp.
{
    SECTION( "correctness" ) {
        // repeat each test below 10 times
        GENERATE( range(0,10) );
        /* note tolerance in areEqual increases with tests, since
         * small differences propogate in vecC which is not re-initialised
         */
        SECTION( "state-vector" ) {
            // make three random vectors
            Qureg vecA = createQureg(NUM_QUBITS, QUEST_ENV);
            Qureg vecB = createQureg(NUM_QUBITS, QUEST_ENV);
            Qureg vecC = createQureg(NUM_QUBITS, QUEST_ENV);
            for (int j=0; j<vecA.numAmpsPerChunk; j++) {
                vecA.stateVec.real[j] = getRandomReal(-5,5); vecA.stateVec.imag[j] = getRandomReal(-5,5);
                vecB.stateVec.real[j] = getRandomReal(-5,5); vecB.stateVec.imag[j] = getRandomReal(-5,5);
                vecC.stateVec.real[j] = getRandomReal(-5,5); vecC.stateVec.imag[j] = getRandomReal(-5,5);
            }
            copyStateToGPU(vecA); copyStateToGPU(vecB); copyStateToGPU(vecC);
            QVector refA = toQVector(vecA);
            QVector refB = toQVector(vecB);
            QVector refC = toQVector(vecC);
            QVector refOut;
            // get three random factors
            qcomp numA = getRandomReal(-5,5) + getRandomReal(-5,5) * (qcomp) 1i;
            qcomp numB = getRandomReal(-5,5) + getRandomReal(-5,5) * (qcomp) 1i;
            qcomp numC = getRandomReal(-5,5) + getRandomReal(-5,5) * (qcomp) 1i;
            Complex facA; facA.real = real(numA); facA.imag = imag(numA);
            Complex facB; facB.real = real(numB); facB.imag = imag(numB);
            Complex facC; facC.real = real(numC); facC.imag = imag(numC);
            // check out-qureg is correct, when all quregs are unique...
            setWeightedQureg(facA, vecA, facB, vecB, facC, vecC);
            refOut = numA*refA + numB*refB + numC*refC;
            REQUIRE( areEqual(vecC, refOut) );
            // ... and that other qureg's aren't modified
            REQUIRE( areEqual(vecA, refA) );
            REQUIRE( areEqual(vecB, refB) );
            // check quregOut correct, when it's also qureg2
            refC = toQVector(vecC);
            setWeightedQureg(facB, vecB, facC, vecC, facA, vecC);
            refOut = numB*refB + numC*refC + numA*refC;
            REQUIRE( areEqual(vecC, refOut, 10*REAL_EPS) );
            // ... and that the remaining qureg is not modified
            REQUIRE( areEqual(vecB, refB) );
            // check quregOut correct, when it's also qureg1
            refC = toQVector(vecC);
            setWeightedQureg(facC, vecC, facB, vecB, facA, vecC);
            refOut = numC*refC + numB*refB + numA*refC;
            REQUIRE( areEqual(vecC, refOut, 10*REAL_EPS) );
            // ... and that the remaining qureg is not modified
            REQUIRE( areEqual(vecB, refB) );
            // check quregOut is correct when it's both input quregs
            refC = toQVector(vecC);
            setWeightedQureg(facA, vecC, facB, vecC, facC, vecC);
            refOut = numA*refC + numB*refC + numC*refC;
            REQUIRE( areEqual(vecC, refOut, 1E3*REAL_EPS) );
            // cleanup
            destroyQureg(vecA, QUEST_ENV);
            destroyQureg(vecB, QUEST_ENV);
            destroyQureg(vecC, QUEST_ENV);
        }
        SECTION( "density-matrix" ) {
            // make three random matrices
            Qureg matA = createDensityQureg(NUM_QUBITS, QUEST_ENV);
            Qureg matB = createDensityQureg(NUM_QUBITS, QUEST_ENV);
            Qureg matC = createDensityQureg(NUM_QUBITS, QUEST_ENV);
            for (int j=0; j<matA.numAmpsPerChunk; j++) {
                matA.stateVec.real[j] = getRandomReal(-5,5); matA.stateVec.imag[j] = getRandomReal(-5,5);
                matB.stateVec.real[j] = getRandomReal(-5,5); matB.stateVec.imag[j] = getRandomReal(-5,5);
                matC.stateVec.real[j] = getRandomReal(-5,5); matC.stateVec.imag[j] = getRandomReal(-5,5);
            }
            copyStateToGPU(matA); copyStateToGPU(matB); copyStateToGPU(matC);
            QMatrix refA = toQMatrix(matA);
            QMatrix refB = toQMatrix(matB);
            QMatrix refC = toQMatrix(matC);
            QMatrix refOut;
            // get three random factors
            qcomp numA = getRandomReal(-5,5) + getRandomReal(-5,5) * (qcomp) 1i;
            qcomp numB = getRandomReal(-5,5) + getRandomReal(-5,5) * (qcomp) 1i;
            qcomp numC = getRandomReal(-5,5) + getRandomReal(-5,5) * (qcomp) 1i;
            Complex facA; facA.real = real(numA); facA.imag = imag(numA);
            Complex facB; facB.real = real(numB); facB.imag = imag(numB);
            Complex facC; facC.real = real(numC); facC.imag = imag(numC);
            // check out-qureg is correct, when all quregs are unique...
            setWeightedQureg(facA, matA, facB, matB, facC, matC);
            refOut = numA*refA + numB*refB + numC*refC;
            REQUIRE( areEqual(matC, refOut) );
            // ... and that other qureg's aren't modified
            REQUIRE( areEqual(matA, refA) );
            REQUIRE( areEqual(matB, refB) );
            // check quregOut correct, when it's also qureg2
            refC = toQMatrix(matC);
            setWeightedQureg(facB, matB, facC, matC, facA, matC);
            refOut = numB*refB + numC*refC + numA*refC;
            REQUIRE( areEqual(matC, refOut, 10*REAL_EPS) );
            // ... and that the remaining qureg is not modified
            REQUIRE( areEqual(matB, refB) );
            // check quregOut correct, when it's also qureg1
            refC = toQMatrix(matC);
            setWeightedQureg(facC, matC, facB, matB, facA, matC);
            refOut = numC*refC + numB*refB + numA*refC;
            REQUIRE( areEqual(matC, refOut, 1E2*REAL_EPS) );
            // ... and that the remaining qureg is not modified
            REQUIRE( areEqual(matB, refB) );
            // check quregOut is correct when it's both input quregs
            refC = toQMatrix(matC);
            setWeightedQureg(facA, matC, facB, matC, facC, matC);
            refOut = numA*refC + numB*refC + numC*refC;
            REQUIRE( areEqual(matC, refOut, 1E3*REAL_EPS) );
            // cleanup
            destroyQureg(matA, QUEST_ENV);
            destroyQureg(matB, QUEST_ENV);
            destroyQureg(matC, QUEST_ENV);
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qureg types" ) {
            Qureg vec = createQureg(NUM_QUBITS, QUEST_ENV);
            Qureg mat = createDensityQureg(NUM_QUBITS, QUEST_ENV);
            Complex f; f.real = 0; f.imag = 0;
            // two state-vecs, one density-matrix
            REQUIRE_THROWS_WITH( setWeightedQureg(f, mat, f, vec, f, vec), Contains("state-vectors or") && Contains("density matrices") );
            REQUIRE_THROWS_WITH( setWeightedQureg(f, vec, f, mat, f, vec), Contains("state-vectors or") && Contains("density matrices") );
            REQUIRE_THROWS_WITH( setWeightedQureg(f, vec, f, vec, f, mat), Contains("state-vectors or") && Contains("density matrices") );
            // one state-vec, two density-matrices
            REQUIRE_THROWS_WITH( setWeightedQureg(f, vec, f, mat, f, mat), Contains("state-vectors or") && Contains("density matrices") );
            REQUIRE_THROWS_WITH( setWeightedQureg(f, mat, f, vec, f, mat), Contains("state-vectors or") && Contains("density matrices") );
            REQUIRE_THROWS_WITH( setWeightedQureg(f, mat, f, mat, f, vec), Contains("state-vectors or") && Contains("density matrices") );
            destroyQureg(vec, QUEST_ENV);
            destroyQureg(mat, QUEST_ENV);
        }
        SECTION( "qureg dimensions" ) {
            Qureg vecA = createQureg(NUM_QUBITS, QUEST_ENV);
            Qureg vecB = createQureg(NUM_QUBITS + 1, QUEST_ENV);
            Qureg matA = createDensityQureg(NUM_QUBITS, QUEST_ENV);
            Qureg matB = createDensityQureg(NUM_QUBITS + 1, QUEST_ENV);
            Complex f; f.real = 0; f.imag = 0;
            // state-vecs
            REQUIRE_THROWS_WITH( setWeightedQureg(f, vecA, f, vecB, f, vecB), Contains("Dimensions") );
            REQUIRE_THROWS_WITH( setWeightedQureg(f, vecB, f, vecA, f, vecB), Contains("Dimensions") );
            REQUIRE_THROWS_WITH( setWeightedQureg(f, vecB, f, vecB, f, vecA), Contains("Dimensions") );
            // density-matrices
            REQUIRE_THROWS_WITH( setWeightedQureg(f, matA, f, matB, f, matB), Contains("Dimensions") );
            REQUIRE_THROWS_WITH( setWeightedQureg(f, matB, f, matA, f, matB), Contains("Dimensions") );
            REQUIRE_THROWS_WITH( setWeightedQureg(f, matB, f, matB, f, matA), Contains("Dimensions") );
            destroyQureg(vecA, QUEST_ENV);
            destroyQureg(vecB, QUEST_ENV);
            destroyQureg(matA, QUEST_ENV);
            destroyQureg(matB, QUEST_ENV);
        }
    }
}
References areEqual(), copyStateToGPU(), createDensityQureg(), createQureg(), destroyQureg(), getRandomReal(), Complex::imag, NUM_QUBITS, Qureg::numAmpsPerChunk, qcomp, QUEST_ENV, Complex::real, setWeightedQureg(), Qureg::stateVec, toQMatrix(), and toQVector().
TEST_CASE() [129/136]
TEST_CASE ("sGate" , "" [unitaries])
See also
sGate
Author
Tyson Jones
Definition at line 2620 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    QMatrix op{{1,0},{0,qcomp(0,1)}};
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        SECTION( "state-vector ") {
            sGate(quregVec, target);
            applyReferenceOp(refVec, target, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            sGate(quregMatr, target);
            applyReferenceOp(refMatr, target, op);
            REQUIRE( areEqual(quregMatr, refMatr) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qubit indices" ) {
            int target = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( sGate(quregVec, target), Contains("Invalid target") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, NUM_QUBITS, PREPARE_TEST, qcomp, and sGate().
TEST_CASE() [130/136]
TEST_CASE ("sqrtSwapGate" , "" [unitaries])
See also
sqrtSwapGate
Author
Tyson Jones
Definition at line 2659 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    qcomp a = qcomp(.5, .5);
    qcomp b = qcomp(.5, -.5);
    QMatrix op{{1,0,0,0},{0,a,b,0},{0,b,a,0},{0,0,0,1}};
    SECTION( "correctness" ) {
        int targ1 = GENERATE( range(0,NUM_QUBITS) );
        int targ2 = GENERATE_COPY( filter([=](int t){ return t!=targ1; }, range(0,NUM_QUBITS)) );
        int targs[] = {targ1, targ2};
        SECTION( "state-vector" ) {
            sqrtSwapGate(quregVec, targ1, targ2);
            applyReferenceOp(refVec, targs, 2, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            sqrtSwapGate(quregMatr, targ1, targ2);
            applyReferenceOp(refMatr, targs, 2, op);
            REQUIRE( areEqual(quregMatr, refMatr) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qubit indices" ) {
            int targ1 = GENERATE( -1, NUM_QUBITS );
            int targ2 = 0;
            REQUIRE_THROWS_WITH( sqrtSwapGate(quregVec, targ1, targ2), Contains("Invalid target") );
            REQUIRE_THROWS_WITH( sqrtSwapGate(quregVec, targ2, targ1), Contains("Invalid target") );
        }
        SECTION( "repetition of targets" ) {
            int qb = 0;
            REQUIRE_THROWS_WITH( sqrtSwapGate(quregVec, qb, qb), Contains("target") && Contains("unique") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, NUM_QUBITS, PREPARE_TEST, qcomp, and sqrtSwapGate().
TEST_CASE() [131/136]
TEST_CASE ("swapGate" , "" [unitaries])
See also
swapGate
Author
Tyson Jones
Definition at line 2709 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    QMatrix op{{1,0,0,0},{0,0,1,0},{0,1,0,0},{0,0,0,1}};
    SECTION( "correctness" ) {
        int targ1 = GENERATE( range(0,NUM_QUBITS) );
        int targ2 = GENERATE_COPY( filter([=](int t){ return t!=targ1; }, range(0,NUM_QUBITS)) );
        int targs[] = {targ1, targ2};
        SECTION( "state-vector" ) {
            swapGate(quregVec, targ1, targ2);
            applyReferenceOp(refVec, targs, 2, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            swapGate(quregMatr, targ1, targ2);
            applyReferenceOp(refMatr, targs, 2, op);
            REQUIRE( areEqual(quregMatr, refMatr) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qubit indices" ) {
            int targ1 = GENERATE( -1, NUM_QUBITS );
            int targ2 = 0;
            REQUIRE_THROWS_WITH( swapGate(quregVec, targ1, targ2), Contains("Invalid target") );
            REQUIRE_THROWS_WITH( swapGate(quregVec, targ2, targ1), Contains("Invalid target") );
        }
        SECTION( "repetition of targets" ) {
            int qb = 0;
            REQUIRE_THROWS_WITH( swapGate(quregVec, qb, qb), Contains("target") && Contains("unique") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, NUM_QUBITS, PREPARE_TEST, and swapGate().
TEST_CASE() [132/136]
TEST_CASE ("syncDiagonalOp" , "" [data_structures])
See also
syncDiagonalOp
Author
Tyson Jones
Definition at line 1100 of file test_data_structures.cpp.
{
    // must be at least one amplitude per node
    int minNumQb = calcLog2(QUEST_ENV.numRanks);
    if (minNumQb == 0)
        minNumQb = 1;
    SECTION( "correctness" ) {
        // try 10 valid number of qubits
        int numQb = GENERATE_COPY( range(minNumQb, minNumQb+10) );
        DiagonalOp op = createDiagonalOp(numQb, QUEST_ENV);
        // check that changes get sync'd to the GPU...
        long long int n;
        for (n=0; n<op.numElemsPerChunk; n++) {
            op.real[n] = (qreal)    n;
            op.imag[n] = (qreal) -2*n; // (n - 2n i)
        }
        syncDiagonalOp(op);
        // via if it modifies an all-unity state-vec correctly
        Qureg qureg = createQureg(numQb, QUEST_ENV);
        for (long long int i=0; i<qureg.numAmpsPerChunk; i++) {
            qureg.stateVec.real[i] = 1;
            qureg.stateVec.imag[i] = 1;
        }
        copyStateToGPU(qureg);
        // (n - 2n i) * (1 + 1i) = 3n - n*i
        applyDiagonalOp(qureg, op);
        copyStateFromGPU(qureg);
        for (n=0; n<qureg.numAmpsPerChunk; n++) {
            REQUIRE( qureg.stateVec.real[n] == 3*n );
            REQUIRE( qureg.stateVec.imag[n] == -n );
        }
        destroyQureg(qureg, QUEST_ENV);
        destroyDiagonalOp(op, QUEST_ENV);
    }
}
References applyDiagonalOp(), calcLog2(), copyStateFromGPU(), copyStateToGPU(), createDiagonalOp(), createQureg(), destroyDiagonalOp(), destroyQureg(), DiagonalOp::imag, Qureg::numAmpsPerChunk, DiagonalOp::numElemsPerChunk, QuESTEnv::numRanks, qreal, QUEST_ENV, DiagonalOp::real, Qureg::stateVec, and syncDiagonalOp().
TEST_CASE() [133/136]
TEST_CASE ("tGate" , "" [unitaries])
See also
tGate
Author
Tyson Jones
Definition at line 2757 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    QMatrix op{{1,0},{0,expI(M_PI/4.)}};
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        SECTION( "state-vector ") {
            tGate(quregVec, target);
            applyReferenceOp(refVec, target, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            tGate(quregMatr, target);
            applyReferenceOp(refMatr, target, op);
            REQUIRE( areEqual(quregMatr, refMatr, 1E2*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qubit indices" ) {
            int target = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( tGate(quregVec, target), Contains("Invalid target") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, expI(), M_PI, NUM_QUBITS, PREPARE_TEST, and tGate().
TEST_CASE() [134/136]
TEST_CASE ("toComplex" , "" [data_structures])
See also
toComplex
Author
Tyson Jones
Definition at line 44 of file test_data_structures.cpp.
{
    qcomp a = qcomp(.5,-.2);
    #if (!defined(_WIN32)) && (!defined(_WIN64))
    Complex b = toComplex(a);
    #else
    // MSVC profanely forbids in-line struct initialisation
    Complex b; b.real = real(a); b.imag = imag(a);
    #endif
    REQUIRE( real(a) == b.real );
    REQUIRE( imag(a) == b.imag );
}
References Complex::imag, qcomp, Complex::real, and toComplex.
TEST_CASE() [135/136]
TEST_CASE ("twoQubitUnitary" , "" [unitaries])
See also
twoQubitUnitary
Author
Tyson Jones
Definition at line 2796 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    // in distributed mode, each node must be able to fit all amps modified by unitary
    REQUIRE( quregVec.numAmpsPerChunk >= 4 );
    // every test will use a unique random matrix
    QMatrix op = getRandomUnitary(2);
    ComplexMatrix4 matr = toComplexMatrix4(op);
    SECTION( "correctness" ) {
        int targ1 = GENERATE( range(0,NUM_QUBITS) );
        int targ2 = GENERATE_COPY( filter([=](int t){ return t!=targ1; }, range(0,NUM_QUBITS)) );
        int targs[] = {targ1, targ2};
        SECTION( "state-vector" ) {
            twoQubitUnitary(quregVec, targ1, targ2, matr);
            applyReferenceOp(refVec, targs, 2, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            twoQubitUnitary(quregMatr, targ1, targ2, matr);
            applyReferenceOp(refMatr, targs, 2, op);
            REQUIRE( areEqual(quregMatr, refMatr, 10*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qubit indices" ) {
            int targ1 = GENERATE( -1, NUM_QUBITS );
            int targ2 = 0;
            REQUIRE_THROWS_WITH( twoQubitUnitary(quregVec, targ1, targ2, matr), Contains("Invalid target") );
            REQUIRE_THROWS_WITH( twoQubitUnitary(quregVec, targ2, targ1, matr), Contains("Invalid target") );
        }
        SECTION( "repetition of targets" ) {
            int qb = 0;
            REQUIRE_THROWS_WITH( twoQubitUnitary(quregVec, qb, qb, matr), Contains("target") && Contains("unique") );
        }
        SECTION( "unitarity" ) {
            matr.real[0][0] = 0; // break matr unitarity
            REQUIRE_THROWS_WITH( twoQubitUnitary(quregVec, 0, 1, matr), Contains("unitary") );
        }
        SECTION( "unitary fits in node" ) {
            // pretend we have a very limited distributed memory
            quregVec.numAmpsPerChunk = 1;
            REQUIRE_THROWS_WITH( twoQubitUnitary(quregVec, 0, 1, matr), Contains("targets too many qubits"));
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, getRandomUnitary(), NUM_QUBITS, PREPARE_TEST, ComplexMatrix4::real, toComplexMatrix4(), and twoQubitUnitary().
TEST_CASE() [136/136]
TEST_CASE ("unitary" , "" [unitaries])
See also
unitary
Author
Tyson Jones
Definition at line 2861 of file test_unitaries.cpp.
{
    PREPARE_TEST( quregVec, quregMatr, refVec, refMatr );
    // every test will use a unique random matrix
    QMatrix op = getRandomUnitary(1);
    ComplexMatrix2 matr = toComplexMatrix2(op);
    SECTION( "correctness" ) {
        int target = GENERATE( range(0,NUM_QUBITS) );
        SECTION( "state-vector" ) {
            unitary(quregVec, target, matr);
            applyReferenceOp(refVec, target, op);
            REQUIRE( areEqual(quregVec, refVec) );
        }
        SECTION( "density-matrix" ) {
            unitary(quregMatr, target, matr);
            applyReferenceOp(refMatr, target, op);
            REQUIRE( areEqual(quregMatr, refMatr, 10*REAL_EPS) );
        }
    }
    SECTION( "input validation" ) {
        SECTION( "qubit indices" ) {
            int target = GENERATE( -1, NUM_QUBITS );
            REQUIRE_THROWS_WITH( unitary(quregVec, target, matr), Contains("Invalid target") );
        }
        SECTION( "unitarity" ) {
            matr.real[0][0] = 0; // break matr unitarity
            REQUIRE_THROWS_WITH( unitary(quregVec, 0, matr), Contains("unitary") );
        }
    }
    CLEANUP_TEST( quregVec, quregMatr );
}
References applyReferenceOp(), areEqual(), CLEANUP_TEST, getRandomUnitary(), NUM_QUBITS, PREPARE_TEST, ComplexMatrix2::real, toComplexMatrix2(), and unitary().