QuEST: Unit test utilities
Unit test utilities
Functions used in the unit testing.
Typedefs
typedef std::vector< std::vector< qcomp > > QMatrix
A complex square matrix.
typedef std::vector< qcomp > QVector
A complex vector, which can be zero-initialised with QVector(numAmps).
Functions
void applyReferenceMatrix (QMatrix &state, int *ctrls, int numCtrls, int *targs, int numTargs, QMatrix op)
Modifies the density matrix state to be the result of left-multiplying the multi-target operator matrix op, with the specified control and target qubits (in ctrls and targs respectively).
void applyReferenceMatrix (QMatrix &state, int *targs, int numTargs, QMatrix op)
Modifies the density matrix state to be the result of left-multiplying the multi-target operator matrix op, with the target qubits (assuming no control qubits).
void applyReferenceMatrix (QVector &state, int *ctrls, int numCtrls, int *targs, int numTargs, QMatrix op)
Modifies the state-vector state to be the result of left-multiplying the multi-target operator matrix op, with the specified control and target qubits (in ctrls and targs respectively).
void applyReferenceMatrix (QVector &state, int *targs, int numTargs, QMatrix op)
Modifies the state-vector state to be the result of left-multiplying the multi-target operator matrix op, with the specified target qubits (assuming no control qubits).
void applyReferenceOp (QMatrix &state, int *ctrls, int numCtrls, int *targs, int numTargs, QMatrix op)
Modifies the density matrix state to be the result of applying the multi-target operator matrix op, with the specified control and target qubits (in ctrls and targs respectively).
void applyReferenceOp (QMatrix &state, int *ctrls, int numCtrls, int targ1, int targ2, QMatrix op)
Modifies the density matrix state to be the result of applying the two-target operator matrix op, with the specified control qubits (in ctrls).
void applyReferenceOp (QMatrix &state, int *ctrls, int numCtrls, int target, QMatrix op)
Modifies the density matrix state to be the result of applying the single-target operator matrix op, with the specified control qubits (in ctrls).
void applyReferenceOp (QMatrix &state, int *targs, int numTargs, QMatrix op)
Modifies the density matrix state to be the result of applying the multi-target operator matrix op, with no control qubits.
void applyReferenceOp (QMatrix &state, int ctrl, int *targs, int numTargs, QMatrix op)
Modifies the density matrix state to be the result of applying the multi-target operator matrix op, with a single control qubit ctrl.
void applyReferenceOp (QMatrix &state, int ctrl, int targ, QMatrix op)
Modifies the density matrix state to be the result of applying the single-control single-target operator matrix op.
void applyReferenceOp (QMatrix &state, int ctrl, int targ1, int targ2, QMatrix op)
Modifies the density matrix state to be the result of applying the two-target operator matrix op, with a single control qubit ctrl.
void applyReferenceOp (QMatrix &state, int targ, QMatrix op)
Modifies the density matrix state to be the result of applying the single-target operator matrix op, with no control qubit.
void applyReferenceOp (QVector &state, int *ctrls, int numCtrls, int *targs, int numTargs, QMatrix op)
Modifies the state-vector state to be the result of applying the multi-target operator matrix op, with the specified control and target qubits (in ctrls and targs respectively).
void applyReferenceOp (QVector &state, int *ctrls, int numCtrls, int targ1, int targ2, QMatrix op)
Modifies the state-vector state to be the result of applying the two-target operator matrix op, with the specified control qubits (in ctrls).
void applyReferenceOp (QVector &state, int *ctrls, int numCtrls, int target, QMatrix op)
Modifies the state-vector state to be the result of applying the single-target operator matrix op, with the specified control qubits (in ctrls).
void applyReferenceOp (QVector &state, int *targs, int numTargs, QMatrix op)
Modifies the state-vector state to be the result of applying the multi-target operator matrix op, with no contorl qubits.
void applyReferenceOp (QVector &state, int ctrl, int *targs, int numTargs, QMatrix op)
Modifies the state-vector state to be the result of applying the multi-target operator matrix op, with a single control qubit (ctrl) This updates state under.
void applyReferenceOp (QVector &state, int ctrl, int targ, QMatrix op)
Modifies the state-vector state to be the result of applying the single-target operator matrix op, with a single control qubit (ctrl).
void applyReferenceOp (QVector &state, int ctrl, int targ1, int targ2, QMatrix op)
Modifies the state-vector state to be the result of applying the two-target operator matrix op, with a single control qubit (ctrl).
void applyReferenceOp (QVector &state, int targ, QMatrix op)
Modifies the state-vector state to be the result of applying the single-target operator matrix op, with no contorl qubits.
bool areEqual (QMatrix a, QMatrix b)
Returns true if the absolute value of the difference between every amplitude in matrices a and b is less than REAL_EPS.
bool areEqual (Qureg qureg, QMatrix matr)
Performs a hardware-agnostic comparison of density-matrix qureg to matr, checking whether the difference between the real and imaginary components of every amplitude is smaller than the QuEST_PREC-specific REAL_EPS (defined in QuEST_precision) precision.
bool areEqual (Qureg qureg, QMatrix matr, qreal precision)
Performs a hardware-agnostic comparison of density-matrix qureg to matr, checking whether the difference between the real and imaginary components of every amplitude is smaller than precision.
bool areEqual (Qureg qureg, QVector vec)
Performs a hardware-agnostic comparison of state-vector qureg to vec, checking whether the difference between the real and imaginary components of every amplitude is smaller than the QuEST_PREC-specific REAL_EPS (defined in QuEST_precision) precision.
bool areEqual (Qureg qureg, QVector vec, qreal precision)
Performs a hardware-agnostic comparison of state-vector qureg to vec, checking whether the difference between the real and imaginary components of every amplitude is smaller than precision.
bool areEqual (Qureg qureg1, Qureg qureg2)
Performs a hardware-agnostic comparison of the given quregs, checking whether the difference between the real and imaginary components of every amplitude is smaller than the QuEST_PREC-specific REAL_EPS (defined in QuEST_precision) precision.
bool areEqual (Qureg qureg1, Qureg qureg2, qreal precision)
Performs a hardware-agnostic comparison of the given quregs, checking whether the difference between the real and imaginary components of every amplitude is smaller than precision.
bool areEqual (QVector a, QVector b)
Returns true if the absolute value of the difference between every amplitude in vectors a and b is less than REAL_EPS.
bool areEqual (QVector vec, qreal *reals)
Returns true if the absolute value of the difference between every element in vec (which must be strictly real) and those implied by reals, is less than REAL_EPS.
bool areEqual (QVector vec, qreal *reals, qreal *imags)
Returns true if the absolute value of the difference between every element in vec and those implied by reals and imags, is less than REAL_EPS.
CatchGen< int * > bitsets (int numBits)
Returns a Catch2 generator of every numBits-length bit-set, in increasing lexographic order, where left-most (zero index) bit is treated as LEAST significant (opposite typical convention).
unsigned int calcLog2 (long unsigned int res)
Returns log2 of numbers which must be gauranteed to be 2^n.
void deleteFilesWithPrefixSynch (char *prefix)
Deletes all files with filename starting with prefix.
QMatrix getConjugateTranspose (QMatrix a)
Returns the conjugate transpose of the complex square matrix a.
QVector getDFT (QVector in)
Returns the discrete fourier transform of vector in.
QVector getDFT (QVector in, int *targs, int numTargs)
Returns the discrete fourier transform of a sub-partition of the vector in.
QMatrix getExponentialOfDiagonalMatrix (QMatrix a)
Returns the matrix exponential of a diagonal, square, complex matrix.
QMatrix getExponentialOfPauliMatrix (qreal angle, QMatrix a)
Returns the matrix exponential of a kronecker product of pauli matrices (or of any involutory matrices), with exponent factor (-i angle / 2).
QMatrix getFullOperatorMatrix (int *ctrls, int numCtrls, int *targs, int numTargs, QMatrix op, int numQubits)
Takes a 2^numTargs-by-2^numTargs matrix op and a returns a 2^numQubits-by-2^numQubits matrix where op is controlled on the given ctrls qubits.
QMatrix getIdentityMatrix (size_t dim)
Returns a dim-by-dim identity matrix.
QMatrix getKetBra (QVector ket, QVector bra)
Returns the matrix |ket><bra|, with ith-jth element ket(i) conj(bra(j)), since |ket><bra| = sum_i a_i|i> sum_j b_j* <j| = sum_{ij} a_i b_j* |i><j|.
QMatrix getKroneckerProduct (QMatrix a, QMatrix b)
Returns the kronecker product of a and b, where a and b are square but possibly differently-sized complex matrices.
QVector getKroneckerProduct (QVector b, QVector a)
Returns b (otimes) a.
QVector getMatrixDiagonal (QMatrix matr)
Returns the diagonal vector of the given matrix.
QMatrix getMixedDensityMatrix (std::vector< qreal > probs, std::vector< QVector > states)
Returns a mixed density matrix formed from mixing the given pure states, which are assumed normalised, but not necessarily orthogonal.
QVector getNormalised (QVector vec)
Returns an L2-normalised copy of vec, using Kahan summation for improved accuracy.
QMatrix getPureDensityMatrix (QVector state)
Returns a density matrix initialised into the given pure state.
qcomp getRandomComplex ()
Returns a random complex number within the square closing (-1-i) and (1+i), from a distribution uniformly randomising the individual real and imaginary components in their domains.
QMatrix getRandomDensityMatrix (int numQb)
Returns a random numQb-by-numQb density matrix, from an undisclosed distribution, in a very mixed state.
int getRandomInt (int min, int max)
Returns a random integer between min (inclusive) and max (exclusive), from the uniform distribution.
std::vector< QMatrix > getRandomKrausMap (int numQb, int numOps)
Returns a random Kraus map of #numOps 2^numQb-by-2^numQb operators, from an undisclosed distribution.
std::vector< QVector > getRandomOrthonormalVectors (int numQb, int numStates)
Returns a list of random orthonormal complex vectors, from an undisclosed distribution.
std::vector< qreal > getRandomProbabilities (int numProbs)
Returns a list of random real scalars, each in [0, 1], which sum to unity.
QMatrix getRandomPureDensityMatrix (int numQb)
Returns a random numQb-by-numQb density matrix, from an undisclosed distribution, which is pure (corresponds to a random state-vector)
QMatrix getRandomQMatrix (int dim)
Returns a dim-by-dim complex matrix, where the real and imaginary value of each element are independently random, under the standard normal distribution (mean 0, standard deviation 1).
QVector getRandomQVector (int dim)
Returns a dim-length vector with random complex amplitudes in the square joining {-1-i, 1+i}, of an undisclosed distribution.
qreal getRandomReal (qreal min, qreal max)
Returns a random real between min (inclusive) and max (exclusive), from the uniform distribution.
QVector getRandomStateVector (int numQb)
Returns a random numQb-length L2-normalised state-vector from an undisclosed distribution.
QMatrix getRandomUnitary (int numQb)
Returns a uniformly random (under Haar) 2^numQb-by-2^numQb unitary matrix.
QMatrix getSwapMatrix (int qb1, int qb2, int numQb)
Returns the 2^numQb-by-2^numQb unitary matrix which swaps qubits qb1 and qb2; the SWAP gate of not-necessarily-adjacent qubits.
long long int getTwosComplement (long long int decimal, int numBits)
Returns the two's complement signed encoding of the unsigned number decimal, which must be a number between 0 and 2^numBits (exclusive).
long long int getUnsigned (long long int twosComp, int numBits)
Return the unsigned value of a number, made of #numBits bits, which under two's complement, encodes the signed number twosComp.
long long int getValueOfTargets (long long int ind, int *targs, int numTargs)
Returns the integer value of the targeted sub-register for the given full state index ind.
QMatrix getZeroMatrix (size_t dim)
Returns a dim-by-dim square complex matrix, initialised to all zeroes.
CatchGen< pauliOpType * > pauliseqs (int numPaulis)
Returns a Catch2 generator of every numPaulis-length set of Pauli-matrix types (or base-4 integers).
CatchGen< int * > sequences (int base, int numDigits)
Returns a Catch2 generator of every numDigits-length sequence in the given base, in increasing lexographic order, where left-most (zero index) bit is treated as LEAST significant (opposite typical convention).
void setDiagMatrixOverrides (QMatrix &matr, int *numQubitsPerReg, int numRegs, enum bitEncoding encoding, long long int *overrideInds, qreal *overridePhases, int numOverrides)
Modifies the given diagonal matrix such that the diagonal elements which correspond to the coordinates in overrideInds are replaced with exp(i phase), as prescribed by overridePhases.
void setRandomDiagPauliHamil (PauliHamil hamil)
Populates hamil with random coefficients and a random amount number of PAULI_I and PAULI_Z operators.
void setRandomPauliSum (PauliHamil hamil)
Populates hamil with random coefficients and pauli codes.
void setRandomPauliSum (qreal *coeffs, pauliOpType *codes, int numQubits, int numTerms)
Populates the coeffs array with random qreals in (-5, 5), and populates codes with random Pauli codes.
void setRandomTargets (int *targs, int numTargs, int numQb)
Populates targs with a random selection of numTargs elements from [0,numQb-1].
void setSubMatrix (QMatrix &dest, QMatrix sub, size_t r, size_t c)
Modifies dest by overwriting its submatrix (from top-left corner (r, c) to bottom-right corner (r + dest.size(), c + dest.size()) with the complete elements of sub.
void setUniqueFilename (char *outFn, char *prefix)
Modifies outFn to be a filename of format prefix_NUM.txt where NUM is a new unique integer so far.
CatchGen< int * > sublists (CatchGen< int > &&gen, int numSamps, const int *exclude, int numExclude)
Returns a Catch2 generator of every length-sublen sublist of the elements generated by gen, which exclude all elements in exclude, in increasing lexographic order.
CatchGen< int * > sublists (CatchGen< int > &&gen, int numSamps, int excluded)
Returns a Catch2 generator of every length-sublen sublist of the elements generated by gen which exclude element excluded, in increasing lexographic order.
CatchGen< int * > sublists (CatchGen< int > &&gen, int sublen)
Returns a Catch2 generator of every length-sublen sublist of the elements generated by gen, in increasing lexographic order.
CatchGen< int * > sublists (int *list, int len, int sublen)
Returns a Catch2 generator of every length-sublen sublist of length-len list, in increasing lexographic order.
ComplexMatrix2 toComplexMatrix2 (QMatrix qm)
Returns a ComplexMatrix2 copy of QMatix qm.
ComplexMatrix4 toComplexMatrix4 (QMatrix qm)
Returns a ComplexMatrix4 copy of QMatix qm.
void toComplexMatrixN (QMatrix qm, ComplexMatrixN cm)
Initialises cm with the values of qm.
QMatrix toDiagonalQMatrix (QVector vec)
Returns a diagonal complex matrix formed by the given vector.
QMatrix toQMatrix (Complex alpha, Complex beta)
Returns the matrix (where a=alpha, b=beta) {{a, -conj(b)}, {b, conj(a)}} using the qcomp complex type.
QMatrix toQMatrix (ComplexMatrix2 src)
Returns a copy of the given 2-by-2 matrix.
QMatrix toQMatrix (ComplexMatrix4 src)
Returns a copy of the given 4-by-4 matrix.
QMatrix toQMatrix (ComplexMatrixN src)
Returns a copy of the given 2^N-by-2^N matrix.
QMatrix toQMatrix (DiagonalOp op)
Returns a 2^N-by-2^N complex diagonal matrix form of the DiagonalOp.
QMatrix toQMatrix (PauliHamil hamil)
Returns a 2^N-by-2^N Hermitian matrix form of the PauliHamil.
QMatrix toQMatrix (qreal *coeffs, pauliOpType *paulis, int numQubits, int numTerms)
Returns a 2^N-by-2^N Hermitian matrix form of the specified weighted sum of Pauli products.
QMatrix toQMatrix (Qureg qureg)
Returns an equal-size copy of the given density matrix qureg.
QMatrix toQMatrix (SubDiagonalOp op)
Returns a 2^n-by-2^n complex diagonal matrix form of the SubDiagonalOp, where n = op.numQubits.
void toQureg (Qureg qureg, QMatrix mat)
Initialises the density matrix qureg to have the same amplitudes as mat.
void toQureg (Qureg qureg, QVector vec)
Initialises the state-vector qureg to have the same amplitudes as vec.
QVector toQVector (DiagonalOp op)
Returns a vector with the same of the full diagonal operator, populated with op's elements.
QVector toQVector (Qureg qureg)
Returns an equal-size copy of the given state-vector qureg.
void writeToFileSynch (char *fn, const string &contents)
Writes contents to the file with filename fn, which is created and/or overwritten.
Detailed Description
Functions used in the unit testing.
These are mostly unoptimised, analytic implementations of the complex linear algebra that QuEST ultimately effects on quantum states. These are not part of the QuEST API, and require C++14.
Author
Tyson Jones
Typedef Documentation
QMatrix
typedef std::vector<std::vector<qcomp> > QMatrix
A complex square matrix.
Should be initialised with getZeroMatrix(). These have all the natural linear-algebra operator overloads, including left-multiplication onto a vector.
This data-structure is not partitioned between nodes in distributed mode. That is, every node has a complete copy, allowing for safe comparisons.
Author
Tyson Jones
Definition at line 66 of file utilities.hpp.
QVector
typedef std::vector<qcomp> QVector
A complex vector, which can be zero-initialised with QVector(numAmps).
These have all the natural linear-algebra operator overloads.
This data-structure is not partitioned between nodes in distributed mode. That is, every node has a complete copy, allowing for safe comparisons.
Author
Tyson Jones
Definition at line 77 of file utilities.hpp.
Function Documentation
applyReferenceMatrix() [1/4]
void applyReferenceMatrix (QMatrix & state, int * ctrls, int numCtrls, int * targs, int numTargs, QMatrix op)
Modifies the density matrix state to be the result of left-multiplying the multi-target operator matrix op, with the specified control and target qubits (in ctrls and targs respectively).
Here, op is treated like a simple matrix and is hence left-multiplied onto the state once.
Author
Tyson Jones
Definition at line 855 of file utilities.cpp.
  {
    // for density matrices, op is left-multiplied only
    int numQubits = calcLog2(state.size());
    QMatrix leftOp = getFullOperatorMatrix(ctrls, numCtrls, targs, numTargs, op, numQubits);
    state = leftOp * state;
}
References calcLog2(), and getFullOperatorMatrix().
applyReferenceMatrix() [2/4]
void applyReferenceMatrix (QMatrix & state, int * targs, int numTargs, QMatrix op)
Modifies the density matrix state to be the result of left-multiplying the multi-target operator matrix op, with the target qubits (assuming no control qubits).
Here, op is treated like a simple matrix and is hence left-multiplied onto the state once.
Author
Tyson Jones
Definition at line 863 of file utilities.cpp.
  {
    applyReferenceMatrix(state, NULL, 0, targs, numTargs, op);
}
References applyReferenceMatrix().
applyReferenceMatrix() [3/4]
void applyReferenceMatrix (QVector & state, int * ctrls, int numCtrls, int * targs, int numTargs, QMatrix op)
Modifies the state-vector state to be the result of left-multiplying the multi-target operator matrix op, with the specified control and target qubits (in ctrls and targs respectively).
This is an alias of applyReferenceOp(), since operators are always left-multiplied as matrices onto state-vectors.
Author
Tyson Jones
Definition at line 843 of file utilities.cpp.
  {
    // for state-vectors, the op is always just left-multiplied
    applyReferenceOp(state, ctrls, numCtrls, targs, numTargs, op);
}
References applyReferenceOp().
Referenced by applyReferenceMatrix(), and TEST_CASE().
applyReferenceMatrix() [4/4]
void applyReferenceMatrix (QVector & state, int * targs, int numTargs, QMatrix op)
Modifies the state-vector state to be the result of left-multiplying the multi-target operator matrix op, with the specified target qubits (assuming no control qubits).
T
Author
Tyson Jones
Definition at line 849 of file utilities.cpp.
  {
    // for state-vectors, the op is always just left-multiplied
    applyReferenceOp(state, targs, numTargs, op);
}
References applyReferenceOp().
applyReferenceOp() [1/16]
void applyReferenceOp (QMatrix & state, int * ctrls, int numCtrls, int * targs, int numTargs, QMatrix op)
Modifies the density matrix state to be the result of applying the multi-target operator matrix op, with the specified control and target qubits (in ctrls and targs respectively).
This updates state under
even if op is not unitary (which is useful for applying Kraus operators).
op must be a 2^numTargs-by-2^numTargs matrix. Furthermore, every element of targs must not appear in ctrls (and vice-versa), though this is not explicitly checked. Elements of targs and ctrls should be unique.
This function works by computing getFullOperatorMatrix() from the given arguments, and left-multipling it to state, then right-multiplying its conjugate transpose onto the result.
Author
Tyson Jones
Definition at line 786 of file utilities.cpp.
  {
    int numQubits = calcLog2(state.size());
    QMatrix leftOp = getFullOperatorMatrix(ctrls, numCtrls, targs, numTargs, op, numQubits);
    QMatrix rightOp = getConjugateTranspose(leftOp);
    state = leftOp * state * rightOp;
}
References calcLog2(), getConjugateTranspose(), and getFullOperatorMatrix().
applyReferenceOp() [2/16]
void applyReferenceOp (QMatrix & state, int * ctrls, int numCtrls, int targ1, int targ2, QMatrix op)
Modifies the density matrix state to be the result of applying the two-target operator matrix op, with the specified control qubits (in ctrls).
This updates state under
even if op is not unitary (which is useful for applying Kraus operators).
op must be a 4-by-4 matrix. Both targ1 and targ2 must not appear in ctrls, though this is not explicitly checked. Elements of ctrls, and targ1 and targ2, should be unique.
This function works by computing getFullOperatorMatrix() from the given arguments, and left-multipling it to state, then right-multiplying its conjugate transpose onto the result.
Author
Tyson Jones
Definition at line 794 of file utilities.cpp.
  {
    int targs[2] = {targ1, targ2};
    applyReferenceOp(state, ctrls, numCtrls, targs, 2, op);
}
References applyReferenceOp().
applyReferenceOp() [3/16]
void applyReferenceOp (QMatrix & state, int * ctrls, int numCtrls, int target, QMatrix op)
Modifies the density matrix state to be the result of applying the single-target operator matrix op, with the specified control qubits (in ctrls).
This updates state under
even if op is not unitary (which is useful for applying Kraus operators).
op must be a 2-by-2 matrix. target must not appear in ctrls, though this is not explicitly checked.
This function works by computing getFullOperatorMatrix() from the given arguments, and left-multipling it to state, then right-multiplying its conjugate transpose onto the result.
Author
Tyson Jones
Definition at line 800 of file utilities.cpp.
  {
    int targs[1] = {target};
    applyReferenceOp(state, ctrls, numCtrls, targs, 1, op);
}
References applyReferenceOp().
applyReferenceOp() [4/16]
void applyReferenceOp (QMatrix & state, int * targs, int numTargs, QMatrix op)
Modifies the density matrix state to be the result of applying the multi-target operator matrix op, with no control qubits.
This updates state under
even if op is not unitary (which is useful for applying Kraus operators).
op must be a 2^numTargs-by-2^numTargs matrix. Every element in targs should be unique, though this is not explicitly checked.
This function works by computing getFullOperatorMatrix() from the given arguments, and left-multipling it to state, then right-multiplying its conjugate transpose onto the result.
Author
Tyson Jones
Definition at line 806 of file utilities.cpp.
  {
    applyReferenceOp(state, NULL, 0, targs, numTargs, op);
}
References applyReferenceOp().
applyReferenceOp() [5/16]
void applyReferenceOp (QMatrix & state, int ctrl, int * targs, int numTargs, QMatrix op)
Modifies the density matrix state to be the result of applying the multi-target operator matrix op, with a single control qubit ctrl.
This updates state under
even if op is not unitary (which is useful for applying Kraus operators).
op must be a 2^numTargs-by-2^numTargs matrix, and ctrl must not appear in targs (though this is not explicitly checked).
This function works by computing getFullOperatorMatrix() from the given arguments, and left-multipling it to state, then right-multiplying its conjugate transpose onto the result.
Author
Tyson Jones
Definition at line 818 of file utilities.cpp.
  {
    int ctrls[1] = {ctrl};
    applyReferenceOp(state, ctrls, 1, targs, numTargs, op);
}
References applyReferenceOp().
applyReferenceOp() [6/16]
void applyReferenceOp (QMatrix & state, int ctrl, int targ, QMatrix op)
Modifies the density matrix state to be the result of applying the single-control single-target operator matrix op.
This updates state under
even if op is not unitary (which is useful for applying Kraus operators).
op must be a 2-by-2 matrix, and ctrl and targ should be different.
This function works by computing getFullOperatorMatrix() from the given arguments, and left-multipling it to state, then right-multiplying its conjugate transpose onto the result.
Author
Tyson Jones
Definition at line 811 of file utilities.cpp.
  {
    int ctrls[1] = {ctrl};
    int targs[1] = {targ};
    applyReferenceOp(state, ctrls, 1, targs, 1, op);
}
References applyReferenceOp().
applyReferenceOp() [7/16]
void applyReferenceOp (QMatrix & state, int ctrl, int targ1, int targ2, QMatrix op)
Modifies the density matrix state to be the result of applying the two-target operator matrix op, with a single control qubit ctrl.
This updates state under
even if op is not unitary (which is useful for applying Kraus operators).
op must be a 4-by-4 matrix, and ctrl, targ1 and targ2 must be unique.
This function works by computing getFullOperatorMatrix() from the given arguments, and left-multipling it to state, then right-multiplying its conjugate transpose onto the result.
Author
Tyson Jones
Definition at line 824 of file utilities.cpp.
  {
    int ctrls[1] = {ctrl};
    int targs[2] = {targ1, targ2};
    applyReferenceOp(state, ctrls, 1, targs, 2, op);
}
References applyReferenceOp().
applyReferenceOp() [8/16]
void applyReferenceOp (QMatrix & state, int targ, QMatrix op)
Modifies the density matrix state to be the result of applying the single-target operator matrix op, with no control qubit.
This updates state under
even if op is not unitary (which is useful for applying Kraus operators).
op must be a 2-by-2 matrix.
This function works by computing getFullOperatorMatrix() from the given arguments, and left-multipling it to state, then right-multiplying its conjugate transpose onto the result.
Author
Tyson Jones
Definition at line 831 of file utilities.cpp.
  {
    int targs[1] = {targ};
    applyReferenceOp(state, NULL, 0, targs, 1, op);
}
References applyReferenceOp().
applyReferenceOp() [9/16]
void applyReferenceOp (QVector & state, int * ctrls, int numCtrls, int * targs, int numTargs, QMatrix op)
Modifies the state-vector state to be the result of applying the multi-target operator matrix op, with the specified control and target qubits (in ctrls and targs respectively).
This updates state under
even if op is not unitary.
op must be a 2^numTargs-by-2^numTargs matrix. Furthermore, every element of targs must not appear in ctrls (and vice-versa), though this is not explicitly checked. Elements of targs and ctrls should be unique.
This function works by computing getFullOperatorMatrix() from the given arguments, and left-multiplying it onto state.
Author
Tyson Jones
Definition at line 730 of file utilities.cpp.
  {
    int numQubits = calcLog2(state.size());
    QMatrix fullOp = getFullOperatorMatrix(ctrls, numCtrls, targs, numTargs, op, numQubits);
    state = fullOp * state;
}
References calcLog2(), and getFullOperatorMatrix().
Referenced by applyReferenceMatrix(), applyReferenceOp(), and TEST_CASE().
applyReferenceOp() [10/16]
void applyReferenceOp (QVector & state, int * ctrls, int numCtrls, int targ1, int targ2, QMatrix op)
Modifies the state-vector state to be the result of applying the two-target operator matrix op, with the specified control qubits (in ctrls).
This updates state under
even if op is not unitary.
op must be a 4-by-4 matrix. Furthermore, ctrls, targ1 and targ2 should all be unique.
This function works by computing getFullOperatorMatrix() from the given arguments, and left-multiplying it onto state.
Author
Tyson Jones
Definition at line 737 of file utilities.cpp.
  {
    int targs[2] = {targ1, targ2};
    applyReferenceOp(state, ctrls, numCtrls, targs, 2, op);
}
References applyReferenceOp().
applyReferenceOp() [11/16]
void applyReferenceOp (QVector & state, int * ctrls, int numCtrls, int target, QMatrix op)
Modifies the state-vector state to be the result of applying the single-target operator matrix op, with the specified control qubits (in ctrls).
This updates state under
even if op is not unitary.
op must be a 2-by-2 matrix. Furthermore, elements in ctrls and target should all be unique.
This function works by computing getFullOperatorMatrix() from the given arguments, and left-multiplying it onto state.
Author
Tyson Jones
Definition at line 743 of file utilities.cpp.
  {
    int targs[1] = {target};
    applyReferenceOp(state, ctrls, numCtrls, targs, 1, op);
}
References applyReferenceOp().
applyReferenceOp() [12/16]
void applyReferenceOp (QVector & state, int * targs, int numTargs, QMatrix op)
Modifies the state-vector state to be the result of applying the multi-target operator matrix op, with no contorl qubits.
This updates state under
even if op is not unitary.
op must be a 2^numTargs-by-2^numTargs matrix. Furthermore, elements in targs should be unique.
This function works by computing getFullOperatorMatrix() from the given arguments, and left-multiplying it onto state.
Author
Tyson Jones
Definition at line 749 of file utilities.cpp.
  {
    applyReferenceOp(state, NULL, 0, targs, numTargs, op);
}
References applyReferenceOp().
applyReferenceOp() [13/16]
void applyReferenceOp (QVector & state, int ctrl, int * targs, int numTargs, QMatrix op)
Modifies the state-vector state to be the result of applying the multi-target operator matrix op, with a single control qubit (ctrl) This updates state under.
even if op is not unitary.
op must be a 2^numTargs-by-2^numTargs matrix. Furthermore, elements in targs and ctrl should be unique.
This function works by computing getFullOperatorMatrix() from the given arguments, and left-multiplying it onto state.
Author
Tyson Jones
Definition at line 761 of file utilities.cpp.
  {
    int ctrls[1] = {ctrl};
    applyReferenceOp(state, ctrls, 1, targs, numTargs, op);
}
References applyReferenceOp().
applyReferenceOp() [14/16]
void applyReferenceOp (QVector & state, int ctrl, int targ, QMatrix op)
Modifies the state-vector state to be the result of applying the single-target operator matrix op, with a single control qubit (ctrl).
This updates state under
even if op is not unitary.
op must be a 2-by-2 matrix. Furthermore, ctrl and targ must be different.
This function works by computing getFullOperatorMatrix() from the given arguments, and left-multiplying it onto state.
Author
Tyson Jones
Definition at line 754 of file utilities.cpp.
  {
    int ctrls[1] = {ctrl};
    int targs[1] = {targ};
    applyReferenceOp(state, ctrls, 1, targs, 1, op);
}
References applyReferenceOp().
applyReferenceOp() [15/16]
void applyReferenceOp (QVector & state, int ctrl, int targ1, int targ2, QMatrix op)
Modifies the state-vector state to be the result of applying the two-target operator matrix op, with a single control qubit (ctrl).
This updates state under
even if op is not unitary.
op must be a 4-by-4 matrix. Furthermore, ctrl, targ1 and targ2 should all be unique.
This function works by computing getFullOperatorMatrix() from the given arguments, and left-multiplying it onto state.
Author
Tyson Jones
Definition at line 767 of file utilities.cpp.
  {
    int ctrls[1] = {ctrl};
    int targs[2] = {targ1, targ2};
    applyReferenceOp(state, ctrls, 1, targs, 2, op);
}
References applyReferenceOp().
applyReferenceOp() [16/16]
void applyReferenceOp (QVector & state, int targ, QMatrix op)
Modifies the state-vector state to be the result of applying the single-target operator matrix op, with no contorl qubits.
This updates state under
even if op is not unitary.
op must be a 2-by-2 matrix.
This function works by computing getFullOperatorMatrix() from the given arguments, and left-multiplying it onto state.
Author
Tyson Jones
Definition at line 774 of file utilities.cpp.
  {
    int targs[1] = {targ};
    applyReferenceOp(state, NULL, 0, targs, 1, op);
}
References applyReferenceOp().
areEqual() [1/10]
bool areEqual (QMatrix a, QMatrix b)
Returns true if the absolute value of the difference between every amplitude in matrices a and b is less than REAL_EPS.
Author
Tyson Jones
Definition at line 408 of file utilities.cpp.
{
    DEMAND( a.size() == b.size() );
    for (size_t i=0; i<a.size(); i++)
        for (size_t j=0; j<b.size(); j++)
            if (abs(a[i][j] - b[i][j]) > REAL_EPS)
                return false;
    return true;
}
References DEMAND.
areEqual() [2/10]
bool areEqual (Qureg qureg, QMatrix matr)
Performs a hardware-agnostic comparison of density-matrix qureg to matr, checking whether the difference between the real and imaginary components of every amplitude is smaller than the QuEST_PREC-specific REAL_EPS (defined in QuEST_precision) precision.
This function demands qureg is a density matrix, and that qureg and matr have equal dimensions.
In GPU mode, this function involves a GPU to CPU memory copy overhead. In distributed mode, it involves a all-to-all single-int broadcast.
Author
Tyson Jones
Definition at line 999 of file utilities.cpp.
{
    return areEqual(qureg, matr, REAL_EPS);
}
References areEqual().
areEqual() [3/10]
bool areEqual (Qureg qureg, QMatrix matr, qreal precision)
Performs a hardware-agnostic comparison of density-matrix qureg to matr, checking whether the difference between the real and imaginary components of every amplitude is smaller than precision.
This function demands qureg is a density matrix, and that qureg and matr have equal dimensions.
In GPU mode, this function involves a GPU to CPU memory copy overhead. In distributed mode, it involves a all-to-all single-int broadcast.
Author
Tyson Jones
Definition at line 941 of file utilities.cpp.
{
    DEMAND( qureg.isDensityMatrix );
    DEMAND( (long long int) (matr.size()*matr.size()) == qureg.numAmpsTotal );
    // ensure local qureg.stateVec is up to date
    copyStateFromGPU(qureg);
    syncQuESTEnv(QUEST_ENV);
    // the starting index in vec of this node's qureg partition.
    long long int startInd = qureg.chunkId * qureg.numAmpsPerChunk;
    long long int globalInd, row, col, i;
    int ampsAgree;
    // compare each of this node's amplitude to the corresponding matr sub-matrix
    for (i=0; i<qureg.numAmpsPerChunk; i++) {
        globalInd = startInd + i;
        row = globalInd % matr.size();
        col = globalInd / matr.size();
        qreal realDif = absReal(qureg.stateVec.real[i] - real(matr[row][col]));
        qreal imagDif = absReal(qureg.stateVec.imag[i] - imag(matr[row][col]));
        ampsAgree = (realDif < precision && imagDif < precision);
        // DEBUG
        if (!ampsAgree) {
            char buff[200];
            sprintf(buff, "[msg from utilities.cpp] node %d has a disagreement at %lld of (%s) + i(%s):\n\t[qureg] %s + i(%s) VS [ref] %s + i(%s)\n",
                qureg.chunkId, startInd+i,
                REAL_STRING_FORMAT, REAL_STRING_FORMAT, REAL_STRING_FORMAT,
                REAL_STRING_FORMAT, REAL_STRING_FORMAT, REAL_STRING_FORMAT);
            printf(buff,
                realDif, imagDif,
                qureg.stateVec.real[i], qureg.stateVec.imag[i],
                real(matr[row][col]), imag(matr[row][col]));
        }
        // break loop as soon as amplitudes disagree
        if (!ampsAgree)
            break;
        /* TODO:
         * of the nodes which disagree, the lowest-rank should send its
         * disagreeing (i, row, col, stateVec[i]) to rank 0 which should
         * report it immediately (before the impending DEMAND failure)
         * using FAIL_CHECK, so users can determine nature of disagreement
         * (e.g. numerical precision).
         * Note FAIL_CHECK accepts << like cout, e.g.
         * FAIL_CHECK( "Amp at (" << row << ", " << col ") disagreed" );
         */
    }
    // if one node's partition wasn't equal, all-nodes must report not-equal
    int allAmpsAgree = ampsAgree;
#ifdef DISTRIBUTED_MODE
    MPI_Allreduce(&ampsAgree, &allAmpsAgree, 1, MPI_INT, MPI_LAND, MPI_COMM_WORLD);
#endif
    return allAmpsAgree;
}
References Qureg::chunkId, copyStateFromGPU(), DEMAND, Qureg::isDensityMatrix, Qureg::numAmpsPerChunk, Qureg::numAmpsTotal, qreal, QUEST_ENV, Qureg::stateVec, and syncQuESTEnv().
areEqual() [4/10]
bool areEqual (Qureg qureg, QVector vec)
Performs a hardware-agnostic comparison of state-vector qureg to vec, checking whether the difference between the real and imaginary components of every amplitude is smaller than the QuEST_PREC-specific REAL_EPS (defined in QuEST_precision) precision.
This function demands qureg is a state-vector, and that qureg and vec have the same number of amplitudes.
In GPU mode, this function involves a GPU to CPU memory copy overhead. In distributed mode, it involves a all-to-all single-int broadcast.
Author
Tyson Jones
Definition at line 937 of file utilities.cpp.
{
    return areEqual(qureg, vec, REAL_EPS);
}
References areEqual().
areEqual() [5/10]
bool areEqual (Qureg qureg, QVector vec, qreal precision)
Performs a hardware-agnostic comparison of state-vector qureg to vec, checking whether the difference between the real and imaginary components of every amplitude is smaller than precision.
This function demands qureg is a state-vector, and that qureg and vec have the same number of amplitudes.
In GPU mode, this function involves a GPU to CPU memory copy overhead. In distributed mode, it involves a all-to-all single-int broadcast.
Author
Tyson Jones
Definition at line 896 of file utilities.cpp.
{
    DEMAND( !qureg.isDensityMatrix );
    DEMAND( (int) vec.size() == qureg.numAmpsTotal );
    copyStateFromGPU(qureg);
    syncQuESTEnv(QUEST_ENV);
    // the starting index in vec of this node's qureg partition.
    long long int startInd = qureg.chunkId * qureg.numAmpsPerChunk;
    int ampsAgree = 1;
    for (long long int i=0; i<qureg.numAmpsPerChunk; i++) {
        qreal realDif = absReal(qureg.stateVec.real[i] - real(vec[startInd+i]));
        qreal imagDif = absReal(qureg.stateVec.imag[i] - imag(vec[startInd+i]));
        if (realDif > precision || imagDif > precision) {
            ampsAgree = 0;
            // debug
            char buff[200];
            sprintf(buff, "Disagreement at %lld of (%s) + i(%s):\n\t%s + i(%s) VS %s + i(%s)\n",
                startInd+i,
                REAL_STRING_FORMAT, REAL_STRING_FORMAT, REAL_STRING_FORMAT,
                REAL_STRING_FORMAT, REAL_STRING_FORMAT, REAL_STRING_FORMAT);
            printf(buff,
                realDif, imagDif,
                qureg.stateVec.real[i], qureg.stateVec.imag[i],
                real(vec[startInd+i]), imag(vec[startInd+i]));
            break;
        }
    }
    // if one node's partition wasn't equal, all-nodes must report not-equal
    int allAmpsAgree = ampsAgree;
#ifdef DISTRIBUTED_MODE
    MPI_Allreduce(&ampsAgree, &allAmpsAgree, 1, MPI_INT, MPI_LAND, MPI_COMM_WORLD);
#endif
    return allAmpsAgree;
}
References Qureg::chunkId, copyStateFromGPU(), DEMAND, Qureg::isDensityMatrix, Qureg::numAmpsPerChunk, Qureg::numAmpsTotal, qreal, QUEST_ENV, Qureg::stateVec, and syncQuESTEnv().
areEqual() [6/10]
bool areEqual (Qureg qureg1, Qureg qureg2)
Performs a hardware-agnostic comparison of the given quregs, checking whether the difference between the real and imaginary components of every amplitude is smaller than the QuEST_PREC-specific REAL_EPS (defined in QuEST_precision) precision.
This function demands that qureg1 and qureg2 are of the same type (i.e. both state-vectors or both density matrices), and of an equal number of qubits.
In GPU mode, this function involves a GPU to CPU memory copy overhead. In distributed mode, it involves a all-to-all single-int broadcast.
Author
Tyson Jones
Definition at line 892 of file utilities.cpp.
{
    return areEqual(qureg1, qureg2, REAL_EPS);
}
References areEqual().
areEqual() [7/10]
bool areEqual (Qureg qureg1, Qureg qureg2, qreal precision)
Performs a hardware-agnostic comparison of the given quregs, checking whether the difference between the real and imaginary components of every amplitude is smaller than precision.
This function demands that qureg1 and qureg2 are of the same type (i.e. both state-vectors or both density matrices), and of an equal number of qubits.
In GPU mode, this function involves a GPU to CPU memory copy overhead. In distributed mode, it involves a all-to-all single-int broadcast.
Author
Tyson Jones
Definition at line 869 of file utilities.cpp.
{
    DEMAND( qureg1.isDensityMatrix == qureg2.isDensityMatrix );
    DEMAND( qureg1.numAmpsTotal == qureg2.numAmpsTotal );
    copyStateFromGPU(qureg1);
    copyStateFromGPU(qureg2);
    syncQuESTEnv(QUEST_ENV);
    // loop terminates when areEqual = 0
    int ampsAgree = 1;
    for (long long int i=0; ampsAgree && i<qureg1.numAmpsPerChunk; i++)
        ampsAgree = (
               absReal(qureg1.stateVec.real[i] - qureg2.stateVec.real[i]) < precision
            && absReal(qureg1.stateVec.imag[i] - qureg2.stateVec.imag[i]) < precision);
    // if one node's partition wasn't equal, all-nodes must report not-equal
    int allAmpsAgree = ampsAgree;
#ifdef DISTRIBUTED_MODE
    MPI_Allreduce(&ampsAgree, &allAmpsAgree, 1, MPI_INT, MPI_LAND, MPI_COMM_WORLD);
#endif
    return allAmpsAgree;
}
References copyStateFromGPU(), DEMAND, Qureg::isDensityMatrix, Qureg::numAmpsPerChunk, Qureg::numAmpsTotal, QUEST_ENV, Qureg::stateVec, and syncQuESTEnv().
areEqual() [8/10]
bool areEqual (QVector a, QVector b)
Returns true if the absolute value of the difference between every amplitude in vectors a and b is less than REAL_EPS.
Author
Tyson Jones
Definition at line 399 of file utilities.cpp.
{
    DEMAND( a.size() == b.size() );
    for (size_t i=0; i<a.size(); i++)
        if (abs(a[i] - b[i]) > REAL_EPS)
            return false;
    return true;
}
References DEMAND.
Referenced by areEqual(), getRandomKrausMap(), getRandomUnitary(), and TEST_CASE().
areEqual() [9/10]
bool areEqual (QVector vec, qreal * reals)
Returns true if the absolute value of the difference between every element in vec (which must be strictly real) and those implied by reals, is less than REAL_EPS.
Author
Tyson Jones
Definition at line 1017 of file utilities.cpp.
{
    for (size_t i=0; i<vec.size(); i++) {
        DEMAND( imag(vec[i]) == 0. );
        qreal dif = abs(real(vec[i]) - reals[i]);
        if (dif > REAL_EPS)
            return false;
    }
    return true;
}
References DEMAND, and qreal.
areEqual() [10/10]
bool areEqual (QVector vec, qreal * reals, qreal * imags)
Returns true if the absolute value of the difference between every element in vec and those implied by reals and imags, is less than REAL_EPS.
Author
Tyson Jones
Definition at line 1003 of file utilities.cpp.
{
    qreal dif;
    for (size_t i=0; i<vec.size(); i++) {
        dif = absReal(real(vec[i]) - reals[i]);
        if (dif > REAL_EPS)
            return false;
        dif = absReal(imag(vec[i]) - imags[i]);
        if (dif > REAL_EPS)
            return false;
    }
    return true;
}
References qreal.
bitsets()
CatchGen< int * > bitsets (int numBits)
Returns a Catch2 generator of every numBits-length bit-set, in increasing lexographic order, where left-most (zero index) bit is treated as LEAST significant (opposite typical convention).
Note that the produced bitset must not be modified during generation.
This function can be used like
int* bits = GENERATE(bitsets(3));
to produce {0,0,0}, {1,0,0}, {0,1,0}, {1,1,0}, {0,0,1}, {1,0,1}, {0,1,1}, {1,1,1}.
Author
Tyson Jones
Definition at line 1598 of file utilities.cpp.
{
    return Catch::Generators::GeneratorWrapper<int*>(
        std::unique_ptr<Catch::Generators::IGenerator<int*>>(
            new SequenceGenerator<int>(1, numBits)));
}
Referenced by TEST_CASE().
calcLog2()
unsigned int calcLog2 (long unsigned int num)
Returns log2 of numbers which must be gauranteed to be 2^n.
Author
Tyson Jones
Returns log2 of numbers which must be gauranteed to be 2^n.
Definition at line 350 of file QuEST_validation.c.
{
    unsigned int l = 0;
    while (num >>= 1)
        l++;
    return l;
}
Referenced by applyReferenceMatrix(), applyReferenceOp(), TEST_CASE(), validateDiagPauliHamilFromFile(), validateNumQubitsInDiagOp(), validateNumQubitsInQureg(), and validateNumQubitsInSubDiagOp().
deleteFilesWithPrefixSynch()
void deleteFilesWithPrefixSynch (char * prefix)
Deletes all files with filename starting with prefix.
In distributed mode, the master node deletes while the other nodes wait until complete.
Author
Tyson Jones
Definition at line 1416 of file utilities.cpp.
{
    // master node deletes all files
    if (QUEST_ENV.rank == 0) {
        char cmd[200];
        sprintf(cmd, "exec rm %s*", prefix);
        system(cmd);
    }
    // other nodes wait
    syncQuESTEnv(QUEST_ENV);
}
References QUEST_ENV, QuESTEnv::rank, and syncQuESTEnv().
Referenced by TEST_CASE().
getConjugateTranspose()
QMatrix getConjugateTranspose (QMatrix a)
Returns the conjugate transpose of the complex square matrix a.
Author
Tyson Jones
Definition at line 189 of file utilities.cpp.
{
    QMatrix b = a;
    for (size_t r=0; r<a.size(); r++)
        for (size_t c=0; c<a.size(); c++)
            b[r][c] = conj(a[c][r]);
    return b;
}
Referenced by applyReferenceOp(), getRandomKrausMap(), and getRandomUnitary().
getDFT() [1/2]
QVector getDFT (QVector in)
Returns the discrete fourier transform of vector in.
Author
Tyson Jones
Definition at line 653 of file utilities.cpp.
{
    REQUIRE( in.size() > 0 );
    size_t dim = in.size();
    qreal ampFac = 1 / sqrt( dim );
    qreal phaseFac = 2 * M_PI / dim;
    QVector dftVec = QVector(dim);
    for (size_t x=0; x<dim; x++) {
        dftVec[x] = 0;
        for (size_t y=0; y<dim; y++)
            dftVec[x] += expI(phaseFac * x * y) * in[y];
        dftVec[x] *= ampFac;
    }
    return dftVec;
}
References expI(), M_PI, and qreal.
Referenced by TEST_CASE().
getDFT() [2/2]
QVector getDFT (QVector in, int * targs, int numTargs)
Returns the discrete fourier transform of a sub-partition of the vector in.
Author
Tyson Jones
Definition at line 701 of file utilities.cpp.
{
    QVector out = QVector(in.size());
    long long int inDim = (long long int) in.size();
    long long int targDim = (1LL << numTargs);
    for (long long int j=0; j<inDim; j++) {
        // |j> = |x> (x) |...>, but mixed (not separated)
        long long int x = getValueOfTargets(j, targs, numTargs);
        for (long long int y=0; y<targDim; y++) {
            // modifies sum_y |y> (x) ...
            long long int outInd = getIndexOfTargetValues(j, targs, numTargs, y);
            qcomp elem = (in[j] / sqrt(pow(2,numTargs))) * expI(2*M_PI * x * y / pow(2,numTargs));
            out[outInd] += elem;
        }
    }
    return out;
}
References expI(), getIndexOfTargetValues(), getValueOfTargets(), M_PI, and qcomp.
getExponentialOfDiagonalMatrix()
QMatrix getExponentialOfDiagonalMatrix (QMatrix a)
Returns the matrix exponential of a diagonal, square, complex matrix.
This method explicitly checks that the passed matrix a is diagonal.
Author
Tyson Jones
Definition at line 197 of file utilities.cpp.
{
    // ensure diagonal
    for (size_t r=0; r<a.size(); r++)
        for (size_t c=0; c<a.size(); c++) {
            if (r == c)
                continue;
            DEMAND( real(a[r][c]) == 0. );
            DEMAND( imag(a[r][c]) == 0. );
        }
    // exp(diagonal) = diagonal(exp)
    QMatrix diag = a;
    for (size_t i=0; i<a.size(); i++)
        diag[i][i] = exp(diag[i][i]);
    return diag;
}
References DEMAND.
Referenced by TEST_CASE().
getExponentialOfPauliMatrix()
QMatrix getExponentialOfPauliMatrix (qreal angle, QMatrix a)
Returns the matrix exponential of a kronecker product of pauli matrices (or of any involutory matrices), with exponent factor (-i angle / 2).
This method will not explicitly check that the passed matrix a is kronecker product of involutory matrices, but will otherwise return an incorrect exponential.
Author
Tyson Jones
Definition at line 216 of file utilities.cpp.
{
    QMatrix iden = getIdentityMatrix(a.size());
    QMatrix expo = (cos(angle/2) * iden) + ((qcomp) -1i * sin(angle/2) * a);
    return expo;
}
References getIdentityMatrix(), and qcomp.
Referenced by TEST_CASE().
getFullOperatorMatrix()
QMatrix getFullOperatorMatrix (int * ctrls, int numCtrls, int * targs, int numTargs, QMatrix op, int numQubits)
Takes a 2^numTargs-by-2^numTargs matrix op and a returns a 2^numQubits-by-2^numQubits matrix where op is controlled on the given ctrls qubits.
The union of {ctrls} and {targs} must be unique (though this is not explicitly checked), and every element must be >= 0 (not checked). The passed {ctrls} and {targs} arrays are unmodified.
This funciton works by first swapping {targs} and {ctrls} (via swap unitaries) to be strictly increasing {0,1,...}, building controlled(op), tensoring it to the full Hilbert space, and then 'unswapping'. The returned matrix has form: swap1 ... swapN . controlled(op) . swapN ... swap1
Author
Tyson Jones
Definition at line 304 of file utilities.cpp.
  {
    DEMAND( numCtrls >= 0 );
    DEMAND( numTargs >= 0 );
    DEMAND( numQubits >= (numCtrls+numTargs) );
    DEMAND( op.size() == (1u << numTargs) );
    // copy {ctrls} and {targs}to restore at end
    std::vector<int> ctrlsCopy(ctrls, ctrls+numCtrls);
    std::vector<int> targsCopy(targs, targs+numTargs);
    // full-state matrix of qubit swaps
    QMatrix swaps = getIdentityMatrix(1 << numQubits);
    QMatrix unswaps = getIdentityMatrix(1 << numQubits);
    QMatrix matr;
    // swap targs to {0, ..., numTargs-1}
    for (int i=0; i<numTargs; i++) {
        if (i != targs[i]) {
            matr = getSwapMatrix(i, targs[i], numQubits);
            swaps = matr * swaps;
            unswaps = unswaps * matr;
            // even if this is the last targ, ctrls might still need updating
            updateIndices(
                i, targs[i], (i < numTargs-1)? &targs[i+1] : NULL,
                numTargs-i-1, ctrls, numCtrls);
        }
    }
    // swap ctrls to {numTargs, ..., numTargs+numCtrls-1}
    for (int i=0; i<numCtrls; i++) {
        int newInd = numTargs+i;
        if (newInd != ctrls[i]) {
            matr = getSwapMatrix(newInd, ctrls[i], numQubits);
            swaps = matr * swaps;
            unswaps = unswaps * matr;
            // update remaining ctrls (if any exist)
            if (i < numCtrls-1)
                updateIndices(newInd, ctrls[i], NULL, 0, &ctrls[i+1], numCtrls-i-1);
        }
    }
    // construct controlled-op matrix for qubits {0, ..., numCtrls+numTargs-1}
    size_t dim = 1 << (numCtrls+numTargs);
    QMatrix fullOp = getIdentityMatrix(dim);
    setSubMatrix(fullOp, op, dim-op.size(), dim-op.size());
    // create full-state controlled-op matrix (left-pad identities)
    if (numQubits > numCtrls+numTargs) {
        size_t pad = 1 << (numQubits - numCtrls - numTargs);
        fullOp = getKroneckerProduct(getIdentityMatrix(pad), fullOp);
    }
    // apply swap to either side (to swap qubits back and forth)
    fullOp = unswaps * fullOp * swaps;
    // restore {ctrls and targs}
    for (int i=0; i<numCtrls; i++)
        ctrls[i] = ctrlsCopy[i];
    for (int i=0; i<numTargs; i++)
        targs[i] = targsCopy[i];
    return fullOp;
}
References DEMAND, getIdentityMatrix(), getKroneckerProduct(), getSwapMatrix(), setSubMatrix(), and updateIndices().
Referenced by applyReferenceMatrix(), applyReferenceOp(), and TEST_CASE().
getIdentityMatrix()
QMatrix getIdentityMatrix (size_t dim)
Returns a dim-by-dim identity matrix.
Author
Tyson Jones
Definition at line 161 of file utilities.cpp.
{
    DEMAND( dim > 1 );
    QMatrix matr = getZeroMatrix(dim);
    for (size_t i=0; i<dim; i++)
        matr[i][i] = 1;
    return matr;
}
References DEMAND, and getZeroMatrix().
Referenced by getExponentialOfPauliMatrix(), getFullOperatorMatrix(), getRandomKrausMap(), getRandomUnitary(), and getSwapMatrix().
getKetBra()
QMatrix getKetBra (QVector ket, QVector bra)
Returns the matrix |ket><bra|, with ith-jth element ket(i) conj(bra(j)), since |ket><bra| = sum_i a_i|i> sum_j b_j* <j| = sum_{ij} a_i b_j* |i><j|.
The dimensions of bra and ket must agree, and the returned square complex matrix has dimensions size(bra) x size(bra).
Author
Tyson Jones
Definition at line 169 of file utilities.cpp.
{
    DEMAND( ket.size() == bra.size() );
    QMatrix mat = getZeroMatrix(ket.size());
    for (size_t r=0; r<ket.size(); r++)
        for (size_t c=0; c<ket.size(); c++)
            mat[r][c] = ket[r] * conj(bra[c]);
    return mat;
}
References DEMAND, and getZeroMatrix().
Referenced by getPureDensityMatrix(), getRandomDensityMatrix(), and TEST_CASE().
getKroneckerProduct() [1/2]
QMatrix getKroneckerProduct (QMatrix a, QMatrix b)
Returns the kronecker product of a and b, where a and b are square but possibly differently-sized complex matrices.
Author
Tyson Jones
Definition at line 179 of file utilities.cpp.
{
    QMatrix prod = getZeroMatrix(a.size() * b.size());
    for (size_t r=0; r<b.size(); r++)
        for (size_t c=0; c<b.size(); c++)
            for (size_t i=0; i<a.size(); i++)
                for (size_t j=0; j<a.size(); j++)
                    prod[r+b.size()*i][c+b.size()*j] = a[i][j] * b[r][c];
    return prod;
}
References getZeroMatrix().
getKroneckerProduct() [2/2]
QVector getKroneckerProduct (QVector b, QVector a)
Returns b (otimes) a.
If b and a are state-vectors, the resulting kronecker product is the seperable state formed by joining the qubits in the state-vectors, producing |b>|a> (a is least significant)
Author
Tyson Jones
Definition at line 143 of file utilities.cpp.
{
    QVector prod = QVector(a.size() * b.size());
    for (size_t i=0; i<prod.size(); i++)
        prod[i] = b[i / a.size()] * a[i % a.size()];
    return prod;
}
Referenced by getFullOperatorMatrix(), getSwapMatrix(), TEST_CASE(), and toQMatrix().
getMatrixDiagonal()
QVector getMatrixDiagonal (QMatrix matr)
Returns the diagonal vector of the given matrix.
Author
Tyson Jones
Definition at line 518 of file utilities.cpp.
{
    QVector vec = QVector(matr.size());
    for (size_t i=0; i<vec.size(); i++)
        vec[i] = matr[i][i];
    return vec;
}
getMixedDensityMatrix()
QMatrix getMixedDensityMatrix (std::vector< qreal > probs, std::vector< QVector > states)
Returns a mixed density matrix formed from mixing the given pure states, which are assumed normalised, but not necessarily orthogonal.
Author
Tyson Jones
Definition at line 641 of file utilities.cpp.
{
    DEMAND( probs.size() == states.size() );
    DEMAND( probs.size() >= 1 );
    QMatrix matr = getZeroMatrix(states[0].size());
    for (size_t i=0; i<probs.size(); i++)
        matr += probs[i] * getPureDensityMatrix(states[i]);
    return matr;
}
References DEMAND, getPureDensityMatrix(), and getZeroMatrix().
Referenced by TEST_CASE().
getNormalised()
QVector getNormalised (QVector vec)
Returns an L2-normalised copy of vec, using Kahan summation for improved accuracy.
Author
Tyson Jones
Definition at line 447 of file utilities.cpp.
{
    qreal norm = 0;
    qreal y, t, c;
    c = 0;
    for (size_t i=0; i<vec.size(); i++) {
        y = real(vec[i])*real(vec[i]) - c;
        t = norm + y;
        c = ( t - norm ) - y;
        norm = t;
        y = imag(vec[i])*imag(vec[i]) - c;
        t = norm + y;
        c = ( t - norm ) - y;
        norm = t;
    }
    for (size_t i=0; i<vec.size(); i++)
        vec[i] /= sqrt(norm);
    return vec;
}
References qreal.
Referenced by getRandomOrthonormalVectors(), and getRandomStateVector().
getPureDensityMatrix()
QMatrix getPureDensityMatrix (QVector state)
Returns a density matrix initialised into the given pure state.
Author
Tyson Jones
Definition at line 508 of file utilities.cpp.
{
    return getKetBra(state, state);
}
References getKetBra().
Referenced by getMixedDensityMatrix(), getRandomPureDensityMatrix(), and TEST_CASE().
getRandomComplex()
qcomp getRandomComplex ()
Returns a random complex number within the square closing (-1-i) and (1+i), from a distribution uniformly randomising the individual real and imaginary components in their domains.
Author
Tyson Jones
Definition at line 432 of file utilities.cpp.
{
    return getRandomReal(-1,1) + getRandomReal(-1,1) * (qcomp) 1i;
}
References getRandomReal(), and qcomp.
Referenced by getRandomQVector(), and TEST_CASE().
getRandomDensityMatrix()
QMatrix getRandomDensityMatrix (int numQb)
Returns a random numQb-by-numQb density matrix, from an undisclosed distribution, in a very mixed state.
This function works by generating 2^numQb random pure states, and mixing them with random probabilities.
Author
Tyson Jones
Definition at line 491 of file utilities.cpp.
{
    DEMAND( numQb > 0 );
    // generate random probabilities to weight random pure states
    int dim = 1<<numQb;
    std::vector<qreal> probs = getRandomProbabilities(dim);
    // add random pure states
    QMatrix dens = getZeroMatrix(dim);
    for (int i=0; i<dim; i++) {
        QVector pure = getRandomStateVector(numQb);
        dens += probs[i] * getKetBra(pure, pure);
    }
    return dens;
}
References DEMAND, getKetBra(), getRandomProbabilities(), getRandomStateVector(), and getZeroMatrix().
Referenced by TEST_CASE().
getRandomInt()
int getRandomInt (int min, int max)
Returns a random integer between min (inclusive) and max (exclusive), from the uniform distribution.
Demands that max > min.
Author
Tyson Jones
Definition at line 527 of file utilities.cpp.
{
    return (int) round(getRandomReal(min, max-1));
}
References getRandomReal().
Referenced by setRandomPauliSum(), and TEST_CASE().
getRandomKrausMap()
std::vector< QMatrix > getRandomKrausMap (int numQb, int numOps)
Returns a random Kraus map of #numOps 2^numQb-by-2^numQb operators, from an undisclosed distribution.
Note this method is very simple and cannot generate all possible Kraus maps. It works by generating numOps random unitary matrices, and randomly re-normalising them, such that the sum of ops[j]^dagger ops[j] = 1
Author
Tyson Jones
Definition at line 579 of file utilities.cpp.
{
    DEMAND( numOps >= 1 );
    DEMAND( numOps <= 4*numQb*numQb );
    // generate random unitaries
    std::vector<QMatrix> ops;
    for (int i=0; i<numOps; i++)
        ops.push_back(getRandomUnitary(numQb));
    // generate random weights
    std::vector<qreal> weights(numOps);
    for (int i=0; i<numOps; i++)
        weights[i] = getRandomReal(0, 1);
    // normalise random weights
    qreal weightSum = 0;
    for (int i=0; i<numOps; i++)
        weightSum += weights[i];
    for (int i=0; i<numOps; i++)
        weights[i] = sqrt((qreal) weights[i]/weightSum);
    // normalise ops
    for (int i=0; i<numOps; i++)
        ops[i] *= weights[i];
    // check what we produced was a valid Kraus map
    QMatrix iden = getIdentityMatrix(1 << numQb);
    QMatrix prodSum = getZeroMatrix(1 << numQb);
    for (int i=0; i<numOps; i++)
        prodSum += getConjugateTranspose(ops[i]) * ops[i];
    DEMAND( areEqual(prodSum, iden) );
    return ops;
}
References areEqual(), DEMAND, getConjugateTranspose(), getIdentityMatrix(), getRandomReal(), getRandomUnitary(), getZeroMatrix(), and qreal.
Referenced by TEST_CASE().
getRandomOrthonormalVectors()
std::vector< QVector > getRandomOrthonormalVectors (int numQb, int numStates)
Returns a list of random orthonormal complex vectors, from an undisclosed distribution.
Author
Tyson Jones
Definition at line 614 of file utilities.cpp.
{
    DEMAND( numQb >= 1 );
    DEMAND( numStates >= 1);
    // set of orthonormal vectors
    std::vector<QVector> vecs;
    for (int n=0; n<numStates; n++) {
        QVector vec = getRandomStateVector(numQb);
        // orthogonalise by substracting projections of existing vectors
        for (int m=0; m<n; m++) {
            qcomp prod = vec * vecs[m];
            vec -= (prod * vecs[m]);
        }
        // renormalise
        vec = getNormalised(vec);
        // add to orthonormal set
        vecs.push_back(vec);
    }
    return vecs;
}
References DEMAND, getNormalised(), getRandomStateVector(), and qcomp.
Referenced by TEST_CASE().
getRandomProbabilities()
std::vector< qreal > getRandomProbabilities (int numProbs)
Returns a list of random real scalars, each in [0, 1], which sum to unity.
Author
Tyson Jones
Definition at line 473 of file utilities.cpp.
{
    // generate random unnormalised scalars
    std::vector<qreal> probs;
    qreal total = 0;
    for (int i=0; i<numProbs; i++) {
        qreal prob = getRandomReal(0, 1);
        probs.push_back(prob);
        total += prob;
    }
    // normalise
    for (int i=0; i<numProbs; i++)
        probs[i] /= total;
    return probs;
}
References getRandomReal(), and qreal.
Referenced by getRandomDensityMatrix(), and TEST_CASE().
getRandomPureDensityMatrix()
QMatrix getRandomPureDensityMatrix (int numQb)
Returns a random numQb-by-numQb density matrix, from an undisclosed distribution, which is pure (corresponds to a random state-vector)
Author
Tyson Jones
Definition at line 512 of file utilities.cpp.
{
    QVector vec = getRandomStateVector(numQb);
    QMatrix mat = getPureDensityMatrix(vec);
    return mat;
}
References getPureDensityMatrix(), and getRandomStateVector().
getRandomQMatrix()
QMatrix getRandomQMatrix (int dim)
Returns a dim-by-dim complex matrix, where the real and imaginary value of each element are independently random, under the standard normal distribution (mean 0, standard deviation 1).
Author
Tyson Jones
Definition at line 379 of file utilities.cpp.
{
    DEMAND( dim > 1 );
    QMatrix matr = getZeroMatrix(dim);
    for (int i=0; i<dim; i++) {
        for (int j=0; j<dim; j++) {
            // generate 2 normally-distributed random numbers via Box-Muller
            qreal a = rand()/(qreal) RAND_MAX;
            qreal b = rand()/(qreal) RAND_MAX;
            if (a == 0) a = REAL_EPS; // prevent rand()=0 creation of NaN
            qreal r1 = sqrt(-2 * log(a)) * cos(2 * 3.14159265 * b);
            qreal r2 = sqrt(-2 * log(a)) * sin(2 * 3.14159265 * b);
            matr[i][j] = r1 + r2 * (qcomp) 1i;
        }
    }
    return matr;
}
References DEMAND, getZeroMatrix(), qcomp, and qreal.
Referenced by getRandomUnitary(), and TEST_CASE().
getRandomQVector()
QVector getRandomQVector (int dim)
Returns a dim-length vector with random complex amplitudes in the square joining {-1-i, 1+i}, of an undisclosed distribution.
The resulting vector is NOT L2-normalised.
Author
Tyson Jones
Definition at line 436 of file utilities.cpp.
{
    QVector vec = QVector(dim);
    for (int i=0; i<dim; i++)
        vec[i] = getRandomComplex();
    // check we didn't get the impossibly-unlikely zero-amplitude outcome
    DEMAND( real(vec[0]) != 0 );
    return vec;
}
References DEMAND, and getRandomComplex().
Referenced by getRandomStateVector(), and TEST_CASE().
getRandomReal()
qreal getRandomReal (qreal min, qreal max)
Returns a random real between min (inclusive) and max (exclusive), from the uniform distribution.
Demands that max > min.
Author
Tyson Jones
Definition at line 422 of file utilities.cpp.
{
    DEMAND( min <= max );
    qreal r = min + (max - min) * (rand() / (qreal) RAND_MAX);
    // check bounds satisfied
    DEMAND( r >= min );
    DEMAND( r <= max );
    return r;
}
References DEMAND, and qreal.
Referenced by getRandomComplex(), getRandomInt(), getRandomKrausMap(), getRandomProbabilities(), setRandomDiagPauliHamil(), setRandomPauliSum(), and TEST_CASE().
getRandomStateVector()
QVector getRandomStateVector (int numQb)
Returns a random numQb-length L2-normalised state-vector from an undisclosed distribution.
This function works by randomly generating each complex amplitude, then L2-normalising.
Author
Tyson Jones
Definition at line 469 of file utilities.cpp.
{
    return getNormalised(getRandomQVector(1<<numQb));
}
References getNormalised(), and getRandomQVector().
Referenced by getRandomDensityMatrix(), getRandomOrthonormalVectors(), getRandomPureDensityMatrix(), and TEST_CASE().
getRandomUnitary()
QMatrix getRandomUnitary (int numQb)
Returns a uniformly random (under Haar) 2^numQb-by-2^numQb unitary matrix.
This function works by first generating a complex matrix where each element is independently random; the real and imaginary component thereof are independent standard normally-distributed (mean 0, standard-dev 1). Then, the matrix is orthonormalised via the Gram Schmidt algorithm. The resulting unitary matrix MAY be uniformly distributed under the Haar measure, but we make no assurance. This routine may return an identity matrix if it was unable to sufficiently precisely produce a unitary of the given size.
Author
Tyson Jones
Definition at line 531 of file utilities.cpp.
{
    DEMAND( numQb >= 1 );
    QMatrix matr = getRandomQMatrix(1 << numQb);
    for (size_t i=0; i<matr.size(); i++) {
        QVector row = matr[i];
        // compute new orthogonal row by subtracting proj row onto prevs
        for (int k=i-1; k>=0; k--) {
            // compute row . prev = sum_n row_n conj(prev_n)
            qcomp prod = 0;
            for (size_t n=0; n<row.size(); n++)
                prod += row[n] * conj(matr[k][n]);
            // subtract (proj row onto prev) = (prod * prev) from final row
            for (size_t n=0; n<row.size(); n++)
                matr[i][n] -= prod * matr[k][n];
        }
        // compute row magnitude
        qreal mag = 0;
        for (size_t j=0; j<row.size(); j++)
            mag += pow(abs(matr[i][j]), 2);
        mag = sqrt(mag);
        // normalise row
        for (size_t j=0; j<row.size(); j++)
            matr[i][j] /= mag;
    }
    // ensure matrix is indeed unitary
    QMatrix conjprod = matr * getConjugateTranspose(matr);
    QMatrix iden = getIdentityMatrix(1 << numQb);
    // generating big unitary matrices is hard; if we fail, default to identity
    if ( numQb >= 3 && !areEqual(conjprod, iden) ) {
        matr = getIdentityMatrix(1 << numQb);
        conjprod = matr;
    }
    DEMAND( areEqual(conjprod, iden) );
    // return the new orthonormal matrix
    return matr;
}
References areEqual(), DEMAND, getConjugateTranspose(), getIdentityMatrix(), getRandomQMatrix(), qcomp, and qreal.
Referenced by getRandomKrausMap(), and TEST_CASE().
getSwapMatrix()
QMatrix getSwapMatrix (int qb1, int qb2, int numQb)
Returns the 2^numQb-by-2^numQb unitary matrix which swaps qubits qb1 and qb2; the SWAP gate of not-necessarily-adjacent qubits.
If qb1 == qb2, returns the identity matrix.
Author
Tyson Jones
Definition at line 230 of file utilities.cpp.
{
    DEMAND( numQb > 1 );
    DEMAND( (qb1 >= 0 && qb1 < numQb) );
    DEMAND( (qb2 >= 0 && qb2 < numQb) );
    if (qb1 > qb2)
        std::swap(qb1, qb2);
    if (qb1 == qb2)
        return getIdentityMatrix(1 << numQb);
    QMatrix swap;
    if (qb2 == qb1 + 1) {
        // qubits are adjacent
        swap = QMatrix{{1,0,0,0},{0,0,1,0},{0,1,0,0},{0,0,0,1}};
    } else {
        // qubits are distant
        int block = 1 << (qb2 - qb1);
        swap = getZeroMatrix(block*2);
        QMatrix iden = getIdentityMatrix(block/2);
        // Lemma 3.1 of arxiv.org/pdf/1711.09765.pdf
        QMatrix p0{{1,0},{0,0}};
        QMatrix l0{{0,1},{0,0}};
        QMatrix l1{{0,0},{1,0}};
        QMatrix p1{{0,0},{0,1}};
        /* notating a^(n+1) = identity(1<<n) (otimes) a, we construct the matrix
         * [ p0^(N) l1^N ]
         * [ l0^(N) p1^N ]
         * where N = qb2 - qb1 */
        setSubMatrix(swap, getKroneckerProduct(iden, p0), 0, 0);
        setSubMatrix(swap, getKroneckerProduct(iden, l0), block, 0);
        setSubMatrix(swap, getKroneckerProduct(iden, l1), 0, block);
        setSubMatrix(swap, getKroneckerProduct(iden, p1), block, block);
    }
    // pad swap with outer identities
    if (qb1 > 0)
        swap = getKroneckerProduct(swap, getIdentityMatrix(1<<qb1));
    if (qb2 < numQb-1)
        swap = getKroneckerProduct(getIdentityMatrix(1<<(numQb-qb2-1)), swap);
    return swap;
}
References DEMAND, getIdentityMatrix(), getKroneckerProduct(), getZeroMatrix(), and setSubMatrix().
Referenced by getFullOperatorMatrix().
getTwosComplement()
long long int getTwosComplement (long long int decimal, int numBits)
Returns the two's complement signed encoding of the unsigned number decimal, which must be a number between 0 and 2^numBits (exclusive).
The returned number lies in [-2^(numBits-1), 2^(numBits-1)-1]
Author
Tyson Jones
Definition at line 1327 of file utilities.cpp.
{
    DEMAND( decimal >= 0 );
    DEMAND( numBits >= 2 );
    DEMAND( decimal < (1LL << numBits) );
    long long int maxMag = 1LL << (numBits-1);
    if (decimal >= maxMag)
        return -maxMag + (decimal - maxMag);
    else
        return decimal;
}
References DEMAND.
Referenced by TEST_CASE().
getUnsigned()
long long int getUnsigned (long long int twosComp, int numBits)
Return the unsigned value of a number, made of #numBits bits, which under two's complement, encodes the signed number twosComp.
The returned number lies in [0, 2^(numBits)-1]
Author
Tyson Jones
Definition at line 1339 of file utilities.cpp.
{
    DEMAND( numBits >= 2 );
    DEMAND( twosComp < (1LL << (numBits-1)) );
    DEMAND( twosComp >= - (1LL << (numBits-1)) );
    if (twosComp >= 0)
        return twosComp;
    else
        return (1<<numBits) + twosComp;
}
References DEMAND.
Referenced by setDiagMatrixOverrides().
getValueOfTargets()
long long int getValueOfTargets (long long int ind, int * targs, int numTargs)
Returns the integer value of the targeted sub-register for the given full state index ind.
Author
Tyson Jones
Definition at line 671 of file utilities.cpp.
{
    DEMAND( ind >= 0 );
    long long int val = 0;
    for (int t=0; t<numTargs; t++)
        val += ((ind >> targs[t]) & 1) * (1LL << t);
    return val;
}
References DEMAND.
Referenced by getDFT().
getZeroMatrix()
QMatrix getZeroMatrix (size_t dim)
Returns a dim-by-dim square complex matrix, initialised to all zeroes.
Author
Tyson Jones
Definition at line 153 of file utilities.cpp.
{
    DEMAND( dim > 1 );
    QMatrix matr = QMatrix(dim);
    for (size_t i=0; i<dim; i++)
        matr[i].resize(dim);
    return matr;
}
References DEMAND.
Referenced by getIdentityMatrix(), getKetBra(), getKroneckerProduct(), getMixedDensityMatrix(), getRandomDensityMatrix(), getRandomKrausMap(), getRandomQMatrix(), getSwapMatrix(), TEST_CASE(), toDiagonalQMatrix(), and toQMatrix().
pauliseqs()
CatchGen< pauliOpType * > pauliseqs (int numPaulis)
Returns a Catch2 generator of every numPaulis-length set of Pauli-matrix types (or base-4 integers).
Generates in increasing lexographic order, where the left-most (zero index) pauli is treated as LEAST significant. Note that the sequence must not be modified during generation.
This function can be used like
pauliOpType* set = GENERATE(pauliseqs(2));
to produce {I,I}, {X,I}, {Y,I}, {Z,I}, {I,X}, {X,X}, {Y,X}, {Z,X}, {I,Y}, {X,Y}, {Y,Y}, {Z,Y}, {I,Z}, {X,Z}, {Y,Z}, {Z,Z}/
Author
Tyson Jones
Definition at line 1608 of file utilities.cpp.
{
    return Catch::Generators::GeneratorWrapper<pauliOpType*>(
        std::unique_ptr<Catch::Generators::IGenerator<pauliOpType*>>(
            new SequenceGenerator<pauliOpType>(PAULI_Z, numPaulis)));
}
References PAULI_Z.
sequences()
CatchGen< int * > sequences (int base, int numDigits)
Returns a Catch2 generator of every numDigits-length sequence in the given base, in increasing lexographic order, where left-most (zero index) bit is treated as LEAST significant (opposite typical convention).
Note that the sequence must not be modified during generation.
This function can be used like
int base = 3;
int numDigits = 2;
int* seq = GENERATE_COPY(sequences(base, numDigits));
to produce {0,0}, {1,0}, {2,0}, {0,1}, {1,1}, {2,1}, {0,2}, {1,2}, {2,2}.
Author
Tyson Jones
Definition at line 1603 of file utilities.cpp.
{
    return Catch::Generators::GeneratorWrapper<int*>(
        std::unique_ptr<Catch::Generators::IGenerator<int*>>(
            new SequenceGenerator<int>(base-1, numDigits)));
}
setDiagMatrixOverrides()
void setDiagMatrixOverrides (QMatrix & matr, int * numQubitsPerReg, int numRegs, enum bitEncoding encoding, long long int * overrideInds, qreal * overridePhases, int numOverrides)
Modifies the given diagonal matrix such that the diagonal elements which correspond to the coordinates in overrideInds are replaced with exp(i phase), as prescribed by overridePhases.
This function assumes that the given registers are contiguous, are in order of increasing significance, and that the matrix is proportionately sized and structured to act on the space of all registers combined. Overrides can be repeated, and only the first encountered for a given index will be effected (much like applyMultiVarPhaseFuncOverrides()).
Author
Tyson Jones
Definition at line 1357 of file utilities.cpp.
{
    DEMAND( (encoding == UNSIGNED || encoding == TWOS_COMPLEMENT) );
    DEMAND( numRegs > 0 );
    DEMAND( numOverrides >= 0 );
    int totalQb = 0;
    for (int r=0; r<numRegs; r++) {
        DEMAND( numQubitsPerReg[r] > 0 );
        totalQb += numQubitsPerReg[r];
    }
    DEMAND( matr.size() == (1 << totalQb) );
    // record whether a diagonal index has been already overriden
    std::vector<int> hasBeenOverriden(1 << totalQb);
    for (int i=0; i<(1 << totalQb); i++)
        hasBeenOverriden[i] = 0;
    int flatInd = 0;
    for (int v=0; v<numOverrides; v++) {
        int matrInd = 0;
        int numQubitsLeft = 0;
        for (int r=0; r<numRegs; r++) {
            if (encoding == UNSIGNED)
                matrInd += overrideInds[flatInd] * (1 << numQubitsLeft);
            else if (encoding == TWOS_COMPLEMENT)
                matrInd += getUnsigned(overrideInds[flatInd], numQubitsPerReg[r]) * (1 << numQubitsLeft);
            numQubitsLeft += numQubitsPerReg[r];
            flatInd += 1;
        }
        if (!hasBeenOverriden[matrInd]) {
            matr[matrInd][matrInd] = expI(overridePhases[v]);
            hasBeenOverriden[matrInd] = 1;
        }
    }
}
References DEMAND, expI(), getUnsigned(), TWOS_COMPLEMENT, and UNSIGNED.
Referenced by TEST_CASE().
setRandomDiagPauliHamil()
void setRandomDiagPauliHamil (PauliHamil hamil)
Populates hamil with random coefficients and a random amount number of PAULI_I and PAULI_Z operators.
Author
Tyson Jones
Definition at line 1264 of file utilities.cpp.
{
    int i=0;
    for (int n=0; n<hamil.numSumTerms; n++) {
        hamil.termCoeffs[n] = getRandomReal(-5, 5);
        for (int q=0; q<hamil.numQubits; q++)
            if (getRandomReal(-1,1) > 0)
                hamil.pauliCodes[i++] = PAULI_Z;
            else
                hamil.pauliCodes[i++] = PAULI_I;
    }
}
References getRandomReal(), PauliHamil::numQubits, PauliHamil::numSumTerms, PAULI_I, PAULI_Z, PauliHamil::pauliCodes, and PauliHamil::termCoeffs.
Referenced by TEST_CASE().
setRandomPauliSum() [1/2]
void setRandomPauliSum (PauliHamil hamil)
Populates hamil with random coefficients and pauli codes.
Author
Tyson Jones
Definition at line 1260 of file utilities.cpp.
{
    setRandomPauliSum(hamil.termCoeffs, hamil.pauliCodes, hamil.numQubits, hamil.numSumTerms);
}
References PauliHamil::numQubits, PauliHamil::numSumTerms, PauliHamil::pauliCodes, setRandomPauliSum(), and PauliHamil::termCoeffs.
setRandomPauliSum() [2/2]
void setRandomPauliSum (qreal * coeffs, pauliOpType * codes, int numQubits, int numTerms)
Populates the coeffs array with random qreals in (-5, 5), and populates codes with random Pauli codes.
Author
Tyson Jones
Definition at line 1252 of file utilities.cpp.
{
    int i=0;
    for (int n=0; n<numTerms; n++) {
        coeffs[n] = getRandomReal(-5, 5);
        for (int q=0; q<numQubits; q++)
            codes[i++] = (pauliOpType) getRandomInt(0,4);
    }
}
References getRandomInt(), and getRandomReal().
Referenced by setRandomPauliSum(), and TEST_CASE().
setRandomTargets()
void setRandomTargets (int * targs, int numTargs, int numQb)
Populates targs with a random selection of numTargs elements from [0,numQb-1].
List targs does not need to be initialised and its elements are overwritten.
Author
Tyson Jones
Definition at line 1276 of file utilities.cpp.
{
    DEMAND( numQb >= 1 );
    DEMAND( numTargs >= 1);
    DEMAND( numTargs <= numQb );
    // create an ordered list of all possible qubits
    VLA(int, allQb, numQb);
    for (int q=0; q<numQb; q++)
        allQb[q] = q;
    // shuffle all qubits
    std::random_shuffle(&allQb[0], &allQb[numQb]);
    // select numTargs of all qubits
    for (int i=0; i<numTargs; i++)
        targs[i] = allQb[i];
}
References DEMAND, and VLA.
Referenced by TEST_CASE().
setSubMatrix()
void setSubMatrix (QMatrix & dest, QMatrix sub, size_t r, size_t c)
Modifies dest by overwriting its submatrix (from top-left corner (r, c) to bottom-right corner (r + dest.size(), c + dest.size()) with the complete elements of sub.
This demands that dest.size() >= sub.size() + max(r,c).
Author
Tyson Jones
Definition at line 222 of file utilities.cpp.
{
    DEMAND( sub.size() + r <= dest.size() );
    DEMAND( sub.size() + c <= dest.size() );
    for (size_t i=0; i<sub.size(); i++)
        for (size_t j=0; j<sub.size(); j++)
            dest[r+i][c+j] = sub[i][j];
}
References DEMAND.
Referenced by getFullOperatorMatrix(), and getSwapMatrix().
setUniqueFilename()
void setUniqueFilename (char * outFn, char * prefix)
Modifies outFn to be a filename of format prefix_NUM.txt where NUM is a new unique integer so far.
This is useful for getting unique filenames for independent test cases of functions requiring reading/writing to file, to avoid IO locks (especially common in distributed mode).
Author
Tyson Jones
Definition at line 1399 of file utilities.cpp.
{
    sprintf(outFn, "%s_%d.txt", prefix, fn_unique_suffix_id++);
}
References fn_unique_suffix_id.
Referenced by TEST_CASE().
sublists() [1/4]
CatchGen< int * > sublists (CatchGen< int > && gen, int numSamps, const int * exclude, int numExclude)
Returns a Catch2 generator of every length-sublen sublist of the elements generated by gen, which exclude all elements in exclude, in increasing lexographic order.
This generates every fixed-length combination of gen's elements the nominated exclusions, and every permutation of each.
There is on need for the elements of exclude to actually appear in those of gen. sublen must less than or equal to the number of elements in gen, after the nominated exclusions.
Note that the sublist must not be modified, else further generation may break (QuEST's internal functions will indeed modify but restore the qubit index lists given to them, which is ok). Assumes list contains no duplicates, otherwise the generated sublists may be duplicated.
This function can be used like
int sublen = 2;
int exclude[2] = {3,4};
int* sublist = GENERATE_COPY(sublists(range(1,6), sublen, exclude, 2));
to generate {1,2}, {1,5}, {2,1}, {2,5}, {5,1}, {5,2}
Author
Tyson Jones
sublists() [2/4]
CatchGen< int * > sublists (CatchGen< int > && gen, int numSamps, int excluded)
Returns a Catch2 generator of every length-sublen sublist of the elements generated by gen which exclude element excluded, in increasing lexographic order.
This generates every fixed-length combination of gen's elements the nominated exclusions, and every permutation of each.
sublen must less than or equal to the number of elements in gen, after the nominated exclusion. There is no need for excluded to actually appear in the elements of gen.
Note that the sublist must not be modified, else further generation may break (QuEST's internal functions will indeed modify but restore the qubit index lists given to them, which is ok). Assumes list contains no duplicates, otherwise the generated sublists may be duplicated.
This function can be used like
int sublen = 2;
int excluded = 1;
int* sublist = GENERATE_COPY(sublists(range(1,4), sublen, excluded));
to generate {2,3}, {3,2}.
Author
Tyson Jones
sublists() [3/4]
CatchGen< int * > sublists (CatchGen< int > && gen, int sublen)
Returns a Catch2 generator of every length-sublen sublist of the elements generated by gen, in increasing lexographic order.
This generates every fixed-length combination of gen's elements, and every permutation of each. Note that the produced sublist must not be modified, else further generation may break (QuEST's internal functions will indeed modify but restore the qubit index lists given to them, which is ok). Assumes list contains no duplicates, otherwise the generated sublists may be duplicated.
This function can be used like
int sublen = 2;
int* sublist = GENERATE_COPY(sublists(list, 4, sublen));
to generate {1,2}, {1,3}, {1,4}, {2,1}, {2,3}, {2,4}, {3,1}, {3,2}, {3, 4}, {4,1}, {4,2}, {4, 3}.
Author
Tyson Jones
sublists() [4/4]
CatchGen< int * > sublists (int * list, int len, int sublen)
Returns a Catch2 generator of every length-sublen sublist of length-len list, in increasing lexographic order.
This generates every fixed-length combination of the given list and every permutation of each. & If the sublist length is the full list length, this generator produces every permutation correctly. Note that the sublist must not be modified, else further & generation may break (QuEST's internal functions will indeed modify but restore the qubit index lists given to them, which is ok). Assumes list contains no duplicates, otherwise the generated sublists may be duplicated.
This function can be used like
int list[4] = {1,2,3,4};
int sublen = 2;
int* sublist = GENERATE_COPY(sublists(list, 4, sublen));
to generate {1,2}, {1,3}, {1,4}, {2,1}, {2,3}, {2,4}, {3,1}, {3,2}, {3, 4}, {4,1}, {4,2}, {4, 3}.
Author
Tyson Jones
Definition at line 1529 of file utilities.cpp.
  {
    return Catch::Generators::GeneratorWrapper<int*>(
        std::unique_ptr<Catch::Generators::IGenerator<int*>>(
            new SubListGenerator(list, len, sublen)));
}
Referenced by TEST_CASE().
toComplexMatrix2()
ComplexMatrix2 toComplexMatrix2 (QMatrix qm)
Returns a ComplexMatrix2 copy of QMatix qm.
Demands that qm is a 2-by-2 matrix.
Author
Tyson Jones
Definition at line 1037 of file utilities.cpp.
{
    DEMAND( qm.size() == 2 );
    ComplexMatrix2 cm;
    macro_copyQMatrix(cm, qm);
    return cm;
}
References DEMAND, and macro_copyQMatrix.
Referenced by TEST_CASE().
toComplexMatrix4()
ComplexMatrix4 toComplexMatrix4 (QMatrix qm)
Returns a ComplexMatrix4 copy of QMatix qm.
Demands that qm is a 4-by-4 matrix.
Author
Tyson Jones
Definition at line 1043 of file utilities.cpp.
{
    DEMAND( qm.size() == 4 );
    ComplexMatrix4 cm;
    macro_copyQMatrix(cm, qm);
    return cm;
}
References DEMAND, and macro_copyQMatrix.
Referenced by TEST_CASE().
toComplexMatrixN()
void toComplexMatrixN (QMatrix qm, ComplexMatrixN cm)
Initialises cm with the values of qm.
Demands that cm is a previously created ComplexMatrixN instance, with the same dimensions as qm.
Author
Tyson Jones
Definition at line 1049 of file utilities.cpp.
{
    DEMAND( qm.size() == (1u<<cm.numQubits) );
    macro_copyQMatrix(cm, qm);
}
References DEMAND, macro_copyQMatrix, and ComplexMatrixN::numQubits.
Referenced by TEST_CASE().
toDiagonalQMatrix()
QMatrix toDiagonalQMatrix (QVector vec)
Returns a diagonal complex matrix formed by the given vector.
Author
Tyson Jones
Definition at line 1350 of file utilities.cpp.
{
    QMatrix mat = getZeroMatrix(vec.size());
    for (size_t i=0; i<vec.size(); i++)
        mat[i][i] = vec[i];
    return mat;
}
References getZeroMatrix().
toQMatrix() [1/9]
QMatrix toQMatrix (Complex alpha, Complex beta)
Returns the matrix (where a=alpha, b=beta) {{a, -conj(b)}, {b, conj(a)}} using the qcomp complex type.
Author
Tyson Jones
Definition at line 1078 of file utilities.cpp.
{
    qcomp a = qcomp(alpha.real, alpha.imag);
    qcomp b = qcomp(beta.real, beta.imag);
    QMatrix matr{
        {a, -conj(b)},
        {b,  conj(a)}};
    return matr;
}
References Complex::imag, qcomp, and Complex::real.
toQMatrix() [2/9]
QMatrix toQMatrix (ComplexMatrix2 src)
Returns a copy of the given 2-by-2 matrix.
Author
Tyson Jones
Definition at line 1060 of file utilities.cpp.
{
    QMatrix dest = getZeroMatrix(2);
    macro_copyComplexMatrix(dest, src);
    return dest;
}
References getZeroMatrix(), and macro_copyComplexMatrix.
Referenced by TEST_CASE(), and toQMatrix().
toQMatrix() [3/9]
QMatrix toQMatrix (ComplexMatrix4 src)
Returns a copy of the given 4-by-4 matrix.
Author
Tyson Jones
Definition at line 1065 of file utilities.cpp.
{
    QMatrix dest = getZeroMatrix(4);
    macro_copyComplexMatrix(dest, src);
    return dest;
}
References getZeroMatrix(), and macro_copyComplexMatrix.
toQMatrix() [4/9]
QMatrix toQMatrix (ComplexMatrixN src)
Returns a copy of the given 2^N-by-2^N matrix.
Author
Tyson Jones
Definition at line 1070 of file utilities.cpp.
{
    DEMAND( src.real != NULL );
    DEMAND( src.imag != NULL );
    QMatrix dest = getZeroMatrix(1 << src.numQubits);
    macro_copyComplexMatrix(dest, src);
    return dest;
}
References DEMAND, getZeroMatrix(), ComplexMatrixN::imag, macro_copyComplexMatrix, ComplexMatrixN::numQubits, and ComplexMatrixN::real.
toQMatrix() [5/9]
QMatrix toQMatrix (DiagonalOp op)
Returns a 2^N-by-2^N complex diagonal matrix form of the DiagonalOp.
Author
Tyson Jones
Definition at line 1209 of file utilities.cpp.
{
    QVector vec = toQVector(op);
    QMatrix mat = getZeroMatrix(1LL << op.numQubits);
    for (size_t i=0; i<mat.size(); i++)
        mat[i][i] = vec[i];
    return mat;
}
References getZeroMatrix(), DiagonalOp::numQubits, and toQVector().
toQMatrix() [6/9]
QMatrix toQMatrix (PauliHamil hamil)
Returns a 2^N-by-2^N Hermitian matrix form of the PauliHamil.
Author
Tyson Jones
Definition at line 1323 of file utilities.cpp.
{
    return toQMatrix(hamil.termCoeffs, hamil.pauliCodes, hamil.numQubits, hamil.numSumTerms);
}
References PauliHamil::numQubits, PauliHamil::numSumTerms, PauliHamil::pauliCodes, PauliHamil::termCoeffs, and toQMatrix().
toQMatrix() [7/9]
QMatrix toQMatrix (qreal * coeffs, pauliOpType * paulis, int numQubits, int numTerms)
Returns a 2^N-by-2^N Hermitian matrix form of the specified weighted sum of Pauli products.
Author
Tyson Jones
Definition at line 1294 of file utilities.cpp.
{
    // produce a numTargs-big matrix 'pauliSum' by pauli-matrix tensoring and summing
    QMatrix iMatr{{1,0},{0,1}};
    QMatrix xMatr{{0,1},{1,0}};
    QMatrix yMatr{{0,-qcomp(0,1)},{qcomp(0,1),0}};
    QMatrix zMatr{{1,0},{0,-1}};
    QMatrix pauliSum = getZeroMatrix(1<<numQubits);
    for (int t=0; t<numTerms; t++) {
        QMatrix pauliProd = QMatrix{{1}};
        for (int q=0; q<numQubits; q++) {
            int i = q + t*numQubits;
            QMatrix fac;
            pauliOpType code = paulis[i];
            if (code == PAULI_I) fac = iMatr;
            if (code == PAULI_X) fac = xMatr;
            if (code == PAULI_Y) fac = yMatr;
            if (code == PAULI_Z) fac = zMatr;
            pauliProd = getKroneckerProduct(fac, pauliProd);
        }
        pauliSum += coeffs[t] * pauliProd;
    }
    // a now 2^numQubits by 2^numQubits Hermitian matrix
    return pauliSum;
}
References getKroneckerProduct(), getZeroMatrix(), PAULI_I, PAULI_X, PAULI_Y, PAULI_Z, and qcomp.
toQMatrix() [8/9]
QMatrix toQMatrix (Qureg qureg)
Returns an equal-size copy of the given density matrix qureg.
In GPU mode, this function involves a copy of qureg from GPU memory to RAM. In distributed mode, this involves an all-to-all broadcast of qureg.
Author
Tyson Jones
Definition at line 1087 of file utilities.cpp.
{
    DEMAND( qureg.isDensityMatrix );
#ifdef DISTRIBUTED_MODE
    DEMAND( qureg.numAmpsTotal < MPI_MAX_AMPS_IN_MSG );
#endif
    // ensure local qureg.stateVec is up to date
    copyStateFromGPU(qureg);
    syncQuESTEnv(QUEST_ENV);
    qreal* fullRe;
    qreal* fullIm;
    // in distributed mode, give every node the full state vector
#ifdef DISTRIBUTED_MODE
    fullRe = (qreal*) malloc(qureg.numAmpsTotal * sizeof *fullRe);
    fullIm = (qreal*) malloc(qureg.numAmpsTotal * sizeof *fullIm);
    MPI_Allgather(
        qureg.stateVec.real, qureg.numAmpsPerChunk, MPI_QuEST_REAL,
        fullRe, qureg.numAmpsPerChunk, MPI_QuEST_REAL, MPI_COMM_WORLD);
    MPI_Allgather(
        qureg.stateVec.imag, qureg.numAmpsPerChunk, MPI_QuEST_REAL,
        fullIm, qureg.numAmpsPerChunk, MPI_QuEST_REAL, MPI_COMM_WORLD);
#else
    fullRe = qureg.stateVec.real;
    fullIm = qureg.stateVec.imag;
#endif
    // copy full state vector into a QVector
    long long int dim = (1LL << qureg.numQubitsRepresented);
    QMatrix matr = getZeroMatrix(dim);
    for (long long int n=0; n<qureg.numAmpsTotal; n++)
        matr[n%dim][n/dim] = qcomp(fullRe[n], fullIm[n]);
    // clean up if we malloc'd the distributed array
#ifdef DISTRIBUTED_MODE
    free(fullRe);
    free(fullIm);
#endif
    return matr;
}
References copyStateFromGPU(), DEMAND, getZeroMatrix(), Qureg::isDensityMatrix, Qureg::numAmpsPerChunk, Qureg::numAmpsTotal, Qureg::numQubitsRepresented, qcomp, qreal, QUEST_ENV, Qureg::stateVec, and syncQuESTEnv().
toQMatrix() [9/9]
QMatrix toQMatrix (SubDiagonalOp op)
Returns a 2^n-by-2^n complex diagonal matrix form of the SubDiagonalOp, where n = op.numQubits.
Author
Tyson Jones
Definition at line 1217 of file utilities.cpp.
{
    QMatrix mat = getZeroMatrix(1LL << op.numQubits);
    for (size_t i=0; i<mat.size(); i++)
        mat[i][i] = qcomp(op.real[i], op.imag[i]);
    return mat;
}
References getZeroMatrix(), SubDiagonalOp::imag, SubDiagonalOp::numQubits, qcomp, and SubDiagonalOp::real.
toQureg() [1/2]
void toQureg (Qureg qureg, QMatrix mat)
Initialises the density matrix qureg to have the same amplitudes as mat.
Demands qureg is a density matrix of equal dimensions to mat. In GPU mode, this function involves a copy from RAM to GPU memory. This function has no communication cost in distributed mode.
Author
Tyson Jones
Definition at line 1237 of file utilities.cpp.
{
    DEMAND( qureg.isDensityMatrix );
    DEMAND( (1LL << qureg.numQubitsRepresented) == (long long int) mat.size() );
    syncQuESTEnv(QUEST_ENV);
    int len = (1 << qureg.numQubitsRepresented);
    for (int i=0; i<qureg.numAmpsPerChunk; i++) {
        int ind = qureg.chunkId*qureg.numAmpsPerChunk + i;
        qureg.stateVec.real[i] = real(mat[ind%len][ind/len]);
        qureg.stateVec.imag[i] = imag(mat[ind%len][ind/len]);
    }
    copyStateToGPU(qureg);
}
References Qureg::chunkId, copyStateToGPU(), DEMAND, Qureg::isDensityMatrix, Qureg::numAmpsPerChunk, Qureg::numQubitsRepresented, QUEST_ENV, Qureg::stateVec, and syncQuESTEnv().
toQureg() [2/2]
void toQureg (Qureg qureg, QVector vec)
Initialises the state-vector qureg to have the same amplitudes as vec.
Demands qureg is a state-vector of an equal size to vec. In GPU mode, this function involves a copy from RAM to GPU memory. This function has no communication cost in distributed mode.
Author
Tyson Jones
Definition at line 1224 of file utilities.cpp.
{
    DEMAND( !qureg.isDensityMatrix );
    DEMAND( qureg.numAmpsTotal == (long long int) vec.size() );
    syncQuESTEnv(QUEST_ENV);
    for (int i=0; i<qureg.numAmpsPerChunk; i++) {
        int ind = qureg.chunkId*qureg.numAmpsPerChunk + i;
        qureg.stateVec.real[i] = real(vec[ind]);
        qureg.stateVec.imag[i] = imag(vec[ind]);
    }
    copyStateToGPU(qureg);
}
References Qureg::chunkId, copyStateToGPU(), DEMAND, Qureg::isDensityMatrix, Qureg::numAmpsPerChunk, Qureg::numAmpsTotal, QUEST_ENV, Qureg::stateVec, and syncQuESTEnv().
Referenced by TEST_CASE().
toQVector() [1/2]
QVector toQVector (DiagonalOp op)
Returns a vector with the same of the full diagonal operator, populated with op's elements.
In distributed mode, this involves an all-to-all broadcast of op.
Author
Tyson Jones
Definition at line 1171 of file utilities.cpp.
{
    long long int totalElems = (1LL << op.numQubits);
#ifdef DISTRIBUTED_MODE
    DEMAND( totalElems < MPI_MAX_AMPS_IN_MSG );
#endif
    qreal* fullRe;
    qreal* fullIm;
    // in distributed mode, give every node the full diagonal operator
#ifdef DISTRIBUTED_MODE
    fullRe = (qreal*) malloc(totalElems * sizeof *fullRe);
    fullIm = (qreal*) malloc(totalElems * sizeof *fullIm);
    MPI_Allgather(
        op.real, op.numElemsPerChunk, MPI_QuEST_REAL,
        fullRe, op.numElemsPerChunk, MPI_QuEST_REAL, MPI_COMM_WORLD);
    MPI_Allgather(
        op.imag, op.numElemsPerChunk, MPI_QuEST_REAL,
        fullIm, op.numElemsPerChunk, MPI_QuEST_REAL, MPI_COMM_WORLD);
#else
    fullRe = op.real;
    fullIm = op.imag;
#endif
    // copy full state vector into a QVector
    QVector vec = QVector(totalElems);
    for (long long int i=0; i<totalElems; i++)
        vec[i] = qcomp(fullRe[i], fullIm[i]);
    // clean up if we malloc'd distrib array
#ifdef DISTRIBUTED_MODE
    free(fullRe);
    free(fullIm);
#endif
    return vec;
}
References DEMAND, DiagonalOp::imag, DiagonalOp::numElemsPerChunk, DiagonalOp::numQubits, qcomp, qreal, and DiagonalOp::real.
toQVector() [2/2]
QVector toQVector (Qureg qureg)
Returns an equal-size copy of the given state-vector qureg.
In GPU mode, this function involves a copy of qureg from GPU memory to RAM. In distributed mode, this involves an all-to-all broadcast of qureg.
Author
Tyson Jones
Definition at line 1129 of file utilities.cpp.
{
    DEMAND( !qureg.isDensityMatrix );
#ifdef DISTRIBUTED_MODE
    DEMAND( qureg.numAmpsTotal < MPI_MAX_AMPS_IN_MSG );
#endif
    // ensure local qureg.stateVec is up to date
    copyStateFromGPU(qureg);
    syncQuESTEnv(QUEST_ENV);
    qreal* fullRe;
    qreal* fullIm;
    // in distributed mode, give every node the full state vector
#ifdef DISTRIBUTED_MODE
    fullRe = (qreal*) malloc(qureg.numAmpsTotal * sizeof *fullRe);
    fullIm = (qreal*) malloc(qureg.numAmpsTotal * sizeof *fullIm);
    MPI_Allgather(
        qureg.stateVec.real, qureg.numAmpsPerChunk, MPI_QuEST_REAL,
        fullRe, qureg.numAmpsPerChunk, MPI_QuEST_REAL, MPI_COMM_WORLD);
    MPI_Allgather(
        qureg.stateVec.imag, qureg.numAmpsPerChunk, MPI_QuEST_REAL,
        fullIm, qureg.numAmpsPerChunk, MPI_QuEST_REAL, MPI_COMM_WORLD);
#else
    fullRe = qureg.stateVec.real;
    fullIm = qureg.stateVec.imag;
#endif
    // copy full state vector into a QVector
    QVector vec = QVector(qureg.numAmpsTotal);
    for (long long int i=0; i<qureg.numAmpsTotal; i++)
        vec[i] = qcomp(fullRe[i], fullIm[i]);
    // clean up if we malloc'd distrib array
#ifdef DISTRIBUTED_MODE
    free(fullRe);
    free(fullIm);
#endif
    return vec;
}
References copyStateFromGPU(), DEMAND, Qureg::isDensityMatrix, Qureg::numAmpsPerChunk, Qureg::numAmpsTotal, qcomp, qreal, QUEST_ENV, Qureg::stateVec, and syncQuESTEnv().
Referenced by TEST_CASE(), and toQMatrix().
writeToFileSynch()
void writeToFileSynch (char * fn, const string & contents)
Writes contents to the file with filename fn, which is created and/or overwritten.
In distributed mode, the master node writes while the other nodes wait until complete.
Author
Tyson Jones
Definition at line 1403 of file utilities.cpp.
{
    // master node writes
    if (QUEST_ENV.rank == 0) {
        FILE* file = fopen(fn, "w");
        fputs(contents.c_str(), file);
        fclose(file);
    }
    // other nodes wait
    syncQuESTEnv(QUEST_ENV);
}
References file, QUEST_ENV, QuESTEnv::rank, and syncQuESTEnv().
Referenced by TEST_CASE().