QuEST: QuEST_internal.h File Reference
QuEST_internal.h File Reference
General functions used internally, supplied by QuEST_common or by hardware-specific backends.
#include "QuEST.h"
#include "QuEST_precision.h"
Functions
void agnostic_applyQFT (Qureg qureg, int *qubits, int numQubits)
void agnostic_applyTrotterCircuit (Qureg qureg, PauliHamil hamil, qreal time, int order, int reps)
DiagonalOp agnostic_createDiagonalOp (int numQubits, QuESTEnv env)
void agnostic_destroyDiagonalOp (DiagonalOp op)
void agnostic_initDiagonalOpFromPauliHamil (DiagonalOp op, PauliHamil hamil)
void agnostic_setDiagonalOpElems (DiagonalOp op, long long int startInd, qreal *real, qreal *imag, long long int numElems)
void agnostic_syncDiagonalOp (DiagonalOp op)
void conjugateMatrixN (ComplexMatrixN u)
void densmatr_applyDiagonalOp (Qureg qureg, DiagonalOp op)
void densmatr_applyMultiQubitKrausSuperoperator (Qureg qureg, int *targets, int numTargets, ComplexMatrixN superOp)
Complex densmatr_calcExpecDiagonalOp (Qureg qureg, DiagonalOp op)
qreal densmatr_calcFidelity (Qureg qureg, Qureg pureState)
qreal densmatr_calcHilbertSchmidtDistance (Qureg a, Qureg b)
qreal densmatr_calcInnerProduct (Qureg a, Qureg b)
void densmatr_calcProbOfAllOutcomes (qreal *retProbs, Qureg qureg, int *qubits, int numQubits)
qreal densmatr_calcProbOfOutcome (Qureg qureg, int measureQubit, int outcome)
qreal densmatr_calcPurity (Qureg qureg)
Computes the trace of the density matrix squared.
qreal densmatr_calcTotalProb (Qureg qureg)
void densmatr_collapseToKnownProbOutcome (Qureg qureg, int measureQubit, int outcome, qreal outcomeProb)
Renorms (/prob) every | * outcome * >< * outcome * | state, setting all others to zero.
void densmatr_initClassicalState (Qureg qureg, long long int stateInd)
void densmatr_initPlusState (Qureg targetQureg)
void densmatr_initPureState (Qureg targetQureg, Qureg copyQureg)
int densmatr_measureWithStats (Qureg qureg, int measureQubit, qreal *outcomeProb)
void densmatr_mixDamping (Qureg qureg, int targetQubit, qreal damping)
void densmatr_mixDensityMatrix (Qureg combineQureg, qreal otherProb, Qureg otherQureg)
void densmatr_mixDephasing (Qureg qureg, int targetQubit, qreal dephase)
void densmatr_mixDepolarising (Qureg qureg, int targetQubit, qreal depolLevel)
void densmatr_mixKrausMap (Qureg qureg, int target, ComplexMatrix2 *ops, int numOps)
void densmatr_mixMultiQubitKrausMap (Qureg qureg, int *targets, int numTargets, ComplexMatrixN *ops, int numOps)
void densmatr_mixPauli (Qureg qureg, int qubit, qreal pX, qreal pY, qreal pZ)
void densmatr_mixTwoQubitDephasing (Qureg qureg, int qubit1, int qubit2, qreal dephase)
void densmatr_mixTwoQubitDepolarising (Qureg qureg, int qubit1, int qubit2, qreal depolLevel)
void densmatr_mixTwoQubitKrausMap (Qureg qureg, int target1, int target2, ComplexMatrix4 *ops, int numOps)
void densmatr_setQuregToPauliHamil (Qureg qureg, PauliHamil hamil)
void ensureIndsIncrease (int *ind1, int *ind2)
void getComplexPairAndPhaseFromUnitary (ComplexMatrix2 u, Complex *alpha, Complex *beta, qreal *globalPhase)
maps U(r0c0, r0c1, r1c0, r1c1) to exp(i globalPhase) U(alpha, beta)
void getComplexPairFromRotation (qreal angle, Vector axis, Complex *alpha, Complex *beta)
ComplexMatrix2 getConjugateMatrix2 (ComplexMatrix2 src)
ComplexMatrix4 getConjugateMatrix4 (ComplexMatrix4 src)
Complex getConjugateScalar (Complex scalar)
long long int getControlFlipMask (int *controlQubits, int *controlState, int numControlQubits)
long long int getQubitBitMask (int *controlQubits, int numControlQubits)
void getQuESTDefaultSeedKey (unsigned long int *key)
qreal getVectorMagnitude (Vector vec)
void getZYZRotAnglesFromComplexPair (Complex alpha, Complex beta, qreal *rz2, qreal *ry, qreal *rz1)
maps U(alpha, beta) to Rz(rz2) Ry(ry) Rz(rz1)
unsigned long int hashString (char *str)
void setConjugateMatrixN (ComplexMatrixN m)
void shiftIndices (int *indices, int numIndices, int shift)
void shiftSubregIndices (int *allInds, int *numIndsPerReg, int numRegs, int shift)
void statevec_applyDiagonalOp (Qureg qureg, DiagonalOp op)
void statevec_applyMultiVarPhaseFuncOverrides (Qureg qureg, int *qubits, int *numQubitsPerReg, int numRegs, enum bitEncoding encoding, qreal *coeffs, qreal *exponents, int *numTermsPerReg, long long int *overrideInds, qreal *overridePhases, int numOverrides, int conj)
void statevec_applyParamNamedPhaseFuncOverrides (Qureg qureg, int *qubits, int *numQubitsPerReg, int numRegs, enum bitEncoding encoding, enum phaseFunc functionNameCode, qreal *params, int numParams, long long int *overrideInds, qreal *overridePhases, int numOverrides, int conj)
void statevec_applyPauliSum (Qureg inQureg, enum pauliOpType *allCodes, qreal *termCoeffs, int numSumTerms, Qureg outQureg)
void statevec_applyPhaseFuncOverrides (Qureg qureg, int *qubits, int numQubits, enum bitEncoding encoding, qreal *coeffs, qreal *exponents, int numTerms, long long int *overrideInds, qreal *overridePhases, int numOverrides, int conj)
void statevec_applySubDiagonalOp (Qureg qureg, int *targets, SubDiagonalOp op, int conj)
Complex statevec_calcExpecDiagonalOp (Qureg qureg, DiagonalOp op)
qreal statevec_calcExpecPauliProd (Qureg qureg, int *targetQubits, enum pauliOpType *pauliCodes, int numTargets, Qureg workspace)
qreal statevec_calcExpecPauliSum (Qureg qureg, enum pauliOpType *allCodes, qreal *termCoeffs, int numSumTerms, Qureg workspace)
qreal statevec_calcFidelity (Qureg qureg, Qureg pureState)
Complex statevec_calcInnerProduct (Qureg bra, Qureg ket)
Terrible code which unnecessarily individually computes and sums the real and imaginary components of the inner product, so as to not have to worry about keeping the sums separated during reduction.
void statevec_calcProbOfAllOutcomes (qreal *retProbs, Qureg qureg, int *qubits, int numQubits)
qreal statevec_calcProbOfOutcome (Qureg qureg, int measureQubit, int outcome)
qreal statevec_calcTotalProb (Qureg qureg)
void statevec_cloneQureg (Qureg targetQureg, Qureg copyQureg)
works for both statevectors and density matrices
void statevec_collapseToKnownProbOutcome (Qureg qureg, int measureQubit, int outcome, qreal outcomeProb)
void statevec_compactUnitary (Qureg qureg, int targetQubit, Complex alpha, Complex beta)
int statevec_compareStates (Qureg mq1, Qureg mq2, qreal precision)
void statevec_controlledCompactUnitary (Qureg qureg, int controlQubit, int targetQubit, Complex alpha, Complex beta)
void statevec_controlledMultiQubitUnitary (Qureg qureg, int ctrl, int *targets, int numTargets, ComplexMatrixN u)
void statevec_controlledNot (Qureg qureg, int controlQubit, int targetQubit)
void statevec_controlledPauliY (Qureg qureg, int controlQubit, int targetQubit)
void statevec_controlledPauliYConj (Qureg qureg, int controlQubit, int targetQubit)
void statevec_controlledPhaseFlip (Qureg qureg, int idQubit1, int idQubit2)
void statevec_controlledPhaseShift (Qureg qureg, int idQubit1, int idQubit2, qreal angle)
void statevec_controlledRotateAroundAxis (Qureg qureg, int controlQubit, int targetQubit, qreal angle, Vector axis)
void statevec_controlledRotateAroundAxisConj (Qureg qureg, int controlQubit, int targetQubit, qreal angle, Vector axis)
void statevec_controlledRotateX (Qureg qureg, int controlQubit, int targetQubit, qreal angle)
void statevec_controlledRotateY (Qureg qureg, int controlQubit, int targetQubit, qreal angle)
void statevec_controlledRotateZ (Qureg qureg, int controlQubit, int targetQubit, qreal angle)
void statevec_controlledTwoQubitUnitary (Qureg qureg, int controlQubit, int targetQubit1, int targetQubit2, ComplexMatrix4 u)
void statevec_controlledUnitary (Qureg qureg, int controlQubit, int targetQubit, ComplexMatrix2 u)
void statevec_copySubstateFromGPU (Qureg qureg, long long int startInd, long long int numAmps)
void statevec_copySubstateToGPU (Qureg qureg, long long int startInd, long long int numAmps)
void statevec_createQureg (Qureg *qureg, int numQubits, QuESTEnv env)
void statevec_destroyQureg (Qureg qureg, QuESTEnv env)
qreal statevec_getImagAmp (Qureg qureg, long long int index)
qreal statevec_getProbAmp (Qureg qureg, long long int index)
qreal statevec_getRealAmp (Qureg qureg, long long int index)
void statevec_hadamard (Qureg qureg, int targetQubit)
void statevec_initBlankState (Qureg qureg)
void statevec_initClassicalState (Qureg qureg, long long int stateInd)
void statevec_initDebugState (Qureg qureg)
Initialise the state vector of probability amplitudes to an (unphysical) state with each component of each probability amplitude a unique floating point value.
void statevec_initPlusState (Qureg qureg)
int statevec_initStateFromSingleFile (Qureg *qureg, char filename[200], QuESTEnv env)
void statevec_initStateOfSingleQubit (Qureg *qureg, int qubitId, int outcome)
Initialise the state vector of probability amplitudes such that one qubit is set to 'outcome' and all other qubits are in an equal superposition of zero and one.
void statevec_initZeroState (Qureg qureg)
int statevec_measureWithStats (Qureg qureg, int measureQubit, qreal *outcomeProb)
void statevec_multiControlledMultiQubitNot (Qureg qureg, int ctrlMask, int targMask)
void statevec_multiControlledMultiQubitUnitary (Qureg qureg, long long int ctrlMask, int *targs, int numTargs, ComplexMatrixN u)
This calls swapQubitAmps only when it would involve a distributed communication; if the qubit chunks already fit in the node, it operates the unitary direct.
void statevec_multiControlledMultiRotatePauli (Qureg qureg, long long int ctrlMask, int *targetQubits, enum pauliOpType *targetPaulis, int numTargets, qreal angle, int applyConj)
void statevec_multiControlledMultiRotateZ (Qureg qureg, long long int ctrlMask, long long int targMask, qreal angle)
void statevec_multiControlledPhaseFlip (Qureg qureg, int *controlQubits, int numControlQubits)
void statevec_multiControlledPhaseShift (Qureg qureg, int *controlQubits, int numControlQubits, qreal angle)
void statevec_multiControlledTwoQubitUnitary (Qureg qureg, long long int ctrlMask, int targetQubit1, int targetQubit2, ComplexMatrix4 u)
This calls swapQubitAmps only when it would involve a distributed communication; if the qubit chunks already fit in the node, it operates the unitary direct.
void statevec_multiControlledUnitary (Qureg qureg, long long int ctrlQubitsMask, long long int ctrlFlipMask, int targetQubit, ComplexMatrix2 u)
void statevec_multiQubitUnitary (Qureg qureg, int *targets, int numTargets, ComplexMatrixN u)
void statevec_multiRotatePauli (Qureg qureg, int *targetQubits, enum pauliOpType *targetPaulis, int numTargets, qreal angle, int applyConj)
applyConj=1 will apply conjugate operation, else applyConj=0
void statevec_multiRotateZ (Qureg qureg, long long int mask, qreal angle)
void statevec_pauliX (Qureg qureg, int targetQubit)
void statevec_pauliY (Qureg qureg, int targetQubit)
void statevec_pauliYConj (Qureg qureg, int targetQubit)
void statevec_pauliZ (Qureg qureg, int targetQubit)
void statevec_phaseShift (Qureg qureg, int targetQubit, qreal angle)
void statevec_phaseShiftByTerm (Qureg qureg, int targetQubit, Complex term)
void statevec_reportStateToScreen (Qureg qureg, QuESTEnv env, int reportRank)
Print the current state vector of probability amplitudes for a set of qubits to standard out.
void statevec_rotateAroundAxis (Qureg qureg, int rotQubit, qreal angle, Vector axis)
void statevec_rotateAroundAxisConj (Qureg qureg, int rotQubit, qreal angle, Vector axis)
void statevec_rotateX (Qureg qureg, int rotQubit, qreal angle)
void statevec_rotateY (Qureg qureg, int rotQubit, qreal angle)
void statevec_rotateZ (Qureg qureg, int rotQubit, qreal angle)
void statevec_setAmps (Qureg qureg, long long int startInd, qreal *reals, qreal *imags, long long int numAmps)
void statevec_setWeightedQureg (Complex fac1, Qureg qureg1, Complex fac2, Qureg qureg2, Complex facOut, Qureg out)
void statevec_sGate (Qureg qureg, int targetQubit)
void statevec_sGateConj (Qureg qureg, int targetQubit)
void statevec_sqrtSwapGate (Qureg qureg, int qb1, int qb2)
void statevec_sqrtSwapGateConj (Qureg qureg, int qb1, int qb2)
void statevec_swapQubitAmps (Qureg qureg, int qb1, int qb2)
void statevec_tGate (Qureg qureg, int targetQubit)
void statevec_tGateConj (Qureg qureg, int targetQubit)
void statevec_twoQubitUnitary (Qureg qureg, int targetQubit1, int targetQubit2, ComplexMatrix4 u)
void statevec_unitary (Qureg qureg, int targetQubit, ComplexMatrix2 u)
Detailed Description
General functions used internally, supplied by QuEST_common or by hardware-specific backends.
Note that some bespoke functions used only internally exist in QuEST_qasm.h and QuEST_validation.h
Author
Ania Brown (statevecs, original architecture)
Tyson Jones (re-architecture, statevecs, density matrices)
Definition in file QuEST_internal.h.
Function Documentation
agnostic_applyQFT()
void agnostic_applyQFT (Qureg qureg, int * qubits, int numQubits)
Definition at line 846 of file QuEST_common.c.
{
    int densShift = qureg.numQubitsRepresented;
    // start with top/left-most qubit, work down
    for (int q=numQubits-1; q >= 0; q--) {
        // H
        statevec_hadamard(qureg, qubits[q]);
        if (qureg.isDensityMatrix)
            statevec_hadamard(qureg, qubits[q] + densShift);
        qasm_recordGate(qureg, GATE_HADAMARD, qubits[q]);
        if (q == 0)
            break;
        // succession of C-phases, control on qubits[q], targeting each of
        // qubits[q-1], qubits[q-1], ... qubits[0]. This can be expressed by
        // a single invocation of applyNamedPhaseFunc product
        int numRegs = 2;
        int numQubitsPerReg[2] = {q, 1};
        int regs[100]; // [q+1];
        for (int i=0; i<q+1; i++)
            regs[i] = qubits[i]; // qubits[q] is in own register
        int numParams = 1;
        qreal params[1] = { M_PI / (1 << q) };
        int conj = 0;
        statevec_applyParamNamedPhaseFuncOverrides(
            qureg, regs, numQubitsPerReg, numRegs,
            UNSIGNED, SCALED_PRODUCT, params, numParams,
            NULL, NULL, 0,
            conj);
        if (qureg.isDensityMatrix) {
            conj = 1;
            shiftSubregIndices(regs, numQubitsPerReg, numRegs, densShift);
            statevec_applyParamNamedPhaseFuncOverrides(
                qureg, regs, numQubitsPerReg, numRegs,
                UNSIGNED, SCALED_PRODUCT, params, numParams,
                NULL, NULL, 0,
                conj);
            shiftSubregIndices(regs, numQubitsPerReg, numRegs, - densShift);
        }
        qasm_recordNamedPhaseFunc(
            qureg, regs, numQubitsPerReg, numRegs,
            UNSIGNED, SCALED_PRODUCT, params, numParams,
            NULL, NULL, 0);
    }
    // final swaps
    for (int i=0; i<(numQubits/2); i++) {
        int qb1 = qubits[i];
        int qb2 = qubits[numQubits-i-1];
        statevec_swapQubitAmps(qureg, qb1, qb2);
        if (qureg.isDensityMatrix)
            statevec_swapQubitAmps(qureg, qb1 + densShift, qb2 + densShift);
        qasm_recordControlledGate(qureg, GATE_SWAP, qb1, qb2);
    }
}
References GATE_HADAMARD, GATE_SWAP, Qureg::isDensityMatrix, M_PI, Qureg::numQubitsRepresented, qasm_recordControlledGate(), qasm_recordGate(), qasm_recordNamedPhaseFunc(), qreal, SCALED_PRODUCT, shiftSubregIndices(), statevec_applyParamNamedPhaseFuncOverrides(), statevec_hadamard(), statevec_swapQubitAmps(), and UNSIGNED.
Referenced by applyFullQFT(), and applyQFT().
agnostic_applyTrotterCircuit()
void agnostic_applyTrotterCircuit (Qureg qureg, PauliHamil hamil, qreal time, int order, int reps)
Definition at line 837 of file QuEST_common.c.
{
    if (time == 0)
        return;
    for (int r=0; r<reps; r++)
        applySymmetrizedTrotterCircuit(qureg, hamil, time/reps, order);
}
References applySymmetrizedTrotterCircuit().
Referenced by applyTrotterCircuit().
agnostic_createDiagonalOp()
DiagonalOp agnostic_createDiagonalOp (int numQubits, QuESTEnv env)
Definition at line 1388 of file QuEST_cpu.c.
{
    // the 2^numQubits values will be evenly split between the env.numRanks nodes
    DiagonalOp op;
    op.numQubits = numQubits;
    op.numElemsPerChunk = (1LL << numQubits) / env.numRanks;
    op.chunkId = env.rank;
    op.numChunks = env.numRanks;
    // allocate CPU memory (initialised to zero)
    op.real = (qreal*) calloc(op.numElemsPerChunk, sizeof(qreal));
    op.imag = (qreal*) calloc(op.numElemsPerChunk, sizeof(qreal));
    // check cpu memory allocation was successful
    validateDiagonalOpAllocation(&op, env, __func__);
    return op;
}
References DiagonalOp::chunkId, cudaMalloc, cudaMemset, DiagonalOp::deviceOperator, DiagonalOp::imag, DiagonalOp::numChunks, DiagonalOp::numElemsPerChunk, DiagonalOp::numQubits, QuESTEnv::numRanks, qreal, QuESTEnv::rank, DiagonalOp::real, validateDiagonalOpAllocation(), and validateDiagonalOpGPUAllocation().
Referenced by createDiagonalOp(), and createDiagonalOpFromPauliHamilFile().
agnostic_destroyDiagonalOp()
void agnostic_destroyDiagonalOp (DiagonalOp op)
Definition at line 1407 of file QuEST_cpu.c.
{
    free(op.real);
    free(op.imag);
}
References cudaFree, DiagonalOp::deviceOperator, DiagonalOp::imag, and DiagonalOp::real.
Referenced by destroyDiagonalOp().
agnostic_initDiagonalOpFromPauliHamil()
void agnostic_initDiagonalOpFromPauliHamil (DiagonalOp op, PauliHamil hamil)
Definition at line 1416 of file QuEST_cpu.c.
{
    /* each node modifies its op sub-partition, evaluating the full hamil
     * for every element in the sub-partition
     */
    // unpack op
    long long int offset = op.chunkId * op.numElemsPerChunk;
    long long int numElems = op.numElemsPerChunk;
    qreal* opRe = op.real;
    qreal* opIm = op.imag;
    // unpack hamil
    int numTerms = hamil.numSumTerms;
    int numQubits = hamil.numQubits;
    qreal* coeffs = hamil.termCoeffs;
    enum pauliOpType* codes = hamil.pauliCodes;
    // private OpenMP vars
    long long int i, globalInd;
    qreal elem;
    int t, q, isOddNumOnes, sign;
# ifdef _OPENMP
# pragma omp parallel \
    default  (none) \
    shared   (offset,numElems, opRe,opIm, numTerms,numQubits,coeffs,codes) \
    private  (i,globalInd, elem, isOddNumOnes,t,q,sign)
# endif
    {
# ifdef _OPENMP
# pragma omp for schedule (static)
# endif
        for (i=0; i<numElems; i++) {
            globalInd = i + offset;
            elem = 0;
            // add every Hamiltonian coefficient to this element, either + or -
            for (t=0; t<numTerms; t++) {
                // determine parity of ones (in globalInd basis state) of the current term's targets
                isOddNumOnes = 0;
                for (q=0; q<numQubits; q++)
                    if (codes[q + t*numQubits] == PAULI_Z)
                        if (extractBit(q, globalInd))
                            isOddNumOnes = !isOddNumOnes;
                // add +- term coeff (avoiding thread divergence)
                sign = 1 - 2*isOddNumOnes; // (-1 if isOddNumOnes, else +1)
                elem += coeffs[t] * sign;
            }
            opRe[i] = elem;
            opIm[i] = 0;
        }
    }
    // we don't synch to GPU, because in GPU mode, the GPU populates and synchs to RAM
    // agnostic_syncDiagonalOp(op);
}
References DiagonalOp::chunkId, cudaDeviceSynchronize, cudaFree, cudaMalloc, cudaMemcpy, cudaMemcpyDeviceToHost, cudaMemcpyHostToDevice, DiagonalOp::deviceOperator, extractBit(), DiagonalOp::imag, DiagonalOp::numElemsPerChunk, PauliHamil::numQubits, DiagonalOp::numQubits, PauliHamil::numSumTerms, PAULI_Z, PauliHamil::pauliCodes, qreal, DiagonalOp::real, and PauliHamil::termCoeffs.
Referenced by createDiagonalOpFromPauliHamilFile(), and initDiagonalOpFromPauliHamil().
agnostic_setDiagonalOpElems()
void agnostic_setDiagonalOpElems (DiagonalOp op, long long int startInd, qreal * real, qreal * imag, long long int numElems)
Definition at line 4259 of file QuEST_cpu.c.
{
    // local start/end indices of the given amplitudes, assuming they fit in this chunk
    // these may be negative or above qureg.numAmpsPerChunk
    long long int localStartInd = startInd - op.chunkId*op.numElemsPerChunk;
    long long int localEndInd = localStartInd + numElems; // exclusive
    // add this to a local index to get corresponding elem in reals & imags
    long long int offset = op.chunkId*op.numElemsPerChunk - startInd;
    // restrict these indices to fit into this chunk
    if (localStartInd < 0)
        localStartInd = 0;
    if (localEndInd > op.numElemsPerChunk)
        localEndInd = op.numElemsPerChunk;
    // they may now be out of order = no iterations
    // unpacking OpenMP vars
    long long int index;
    qreal* vecRe = op.real;
    qreal* vecIm = op.imag;
# ifdef _OPENMP
# pragma omp parallel \
    default  (none) \
    shared   (localStartInd,localEndInd, vecRe,vecIm, real,imag, offset) \
    private  (index)
# endif
    {
# ifdef _OPENMP
# pragma omp for schedule (static)
# endif
        // iterate these local inds - this might involve no iterations
        for (index=localStartInd; index < localEndInd; index++) {
            vecRe[index] = real[index + offset];
            vecIm[index] = imag[index + offset];
        }
    }
}
References DiagonalOp::chunkId, cudaDeviceSynchronize, cudaMemcpy, cudaMemcpyHostToDevice, DiagonalOp::deviceOperator, DiagonalOp::imag, DiagonalOp::numElemsPerChunk, qreal, and DiagonalOp::real.
Referenced by initDiagonalOp(), and setDiagonalOpElems().
agnostic_syncDiagonalOp()
void agnostic_syncDiagonalOp (DiagonalOp op)
Definition at line 1412 of file QuEST_cpu.c.
{
    // nothing to do on CPU
}
References cudaDeviceSynchronize, cudaMemcpy, cudaMemcpyHostToDevice, DiagonalOp::deviceOperator, DiagonalOp::imag, DiagonalOp::numElemsPerChunk, and DiagonalOp::real.
Referenced by syncDiagonalOp().
conjugateMatrixN()
void conjugateMatrixN (ComplexMatrixN u)
densmatr_applyDiagonalOp()
void densmatr_applyDiagonalOp (Qureg qureg, DiagonalOp op)
Definition at line 1596 of file QuEST_cpu_distributed.c.
{
    copyDiagOpIntoMatrixPairState(qureg, op);
    densmatr_applyDiagonalOpLocal(qureg, op);
}
References copyDiagOpIntoMatrixPairState(), densmatr_applyDiagonalOpLocal(), DiagonalOp::imag, Qureg::numAmpsPerChunk, Qureg::pairStateVec, qreal, and DiagonalOp::real.
Referenced by applyDiagonalOp().
densmatr_applyMultiQubitKrausSuperoperator()
void densmatr_applyMultiQubitKrausSuperoperator (Qureg qureg, int * targets, int numTargets, ComplexMatrixN superOp)
Definition at line 630 of file QuEST_common.c.
{
    long long int ctrlMask = 0;
    int allTargets[200]; // [2*numTargets];
    for (int t=0; t < numTargets; t++) {
        allTargets[t] = targets[t];
        allTargets[t+numTargets] = targets[t] + qureg.numQubitsRepresented;
    }
    statevec_multiControlledMultiQubitUnitary(qureg, ctrlMask, allTargets, 2*numTargets, superOp);
}
References Qureg::numQubitsRepresented, and statevec_multiControlledMultiQubitUnitary().
Referenced by densmatr_mixMultiQubitKrausMap().
densmatr_calcExpecDiagonalOp()
Complex densmatr_calcExpecDiagonalOp (Qureg qureg, DiagonalOp op)
Definition at line 1620 of file QuEST_cpu_distributed.c.
{
    Complex localVal = densmatr_calcExpecDiagonalOpLocal(qureg, op);
    if (qureg.numChunks == 1)
        return localVal;
    qreal localRe = localVal.real;
    qreal localIm = localVal.imag;
    qreal globalRe, globalIm;
    MPI_Allreduce(&localRe, &globalRe, 1, MPI_QuEST_REAL, MPI_SUM, MPI_COMM_WORLD);
    MPI_Allreduce(&localIm, &globalIm, 1, MPI_QuEST_REAL, MPI_SUM, MPI_COMM_WORLD);
    Complex globalVal;
    globalVal.real = globalRe;
    globalVal.imag = globalIm;
    return globalVal;
}
References copySharedReduceBlock(), cudaDeviceSynchronize, cudaMemcpy, cudaMemcpyDeviceToHost, densmatr_calcExpecDiagonalOpLocal(), DiagonalOp::deviceOperator, Qureg::deviceStateVec, Qureg::firstLevelReduction, Complex::imag, Qureg::numAmpsPerChunk, Qureg::numChunks, DiagonalOp::numQubits, qreal, Complex::real, REDUCE_SHARED_SIZE, Qureg::secondLevelReduction, and swapDouble().
Referenced by calcExpecDiagonalOp().
densmatr_calcFidelity()
qreal densmatr_calcFidelity (Qureg qureg, Qureg pureState)
Definition at line 431 of file QuEST_cpu_distributed.c.
{
    // set qureg's pairState is to be the full pureState (on every node)
    copyVecIntoMatrixPairState(qureg, pureState);
    // collect calcFidelityLocal by every machine
    qreal localSum = densmatr_calcFidelityLocal(qureg, pureState);
    // sum each localSum
    qreal globalSum;
    MPI_Allreduce(&localSum, &globalSum, 1, MPI_QuEST_REAL, MPI_SUM, MPI_COMM_WORLD);
    return globalSum;
}
References copySharedReduceBlock(), copyVecIntoMatrixPairState(), cudaDeviceSynchronize, cudaMemcpy, cudaMemcpyDeviceToHost, densmatr_calcFidelityLocal(), Qureg::firstLevelReduction, Qureg::numQubitsRepresented, Qureg::pairStateVec, qreal, REDUCE_SHARED_SIZE, Qureg::secondLevelReduction, Qureg::stateVec, and swapDouble().
Referenced by calcFidelity().
densmatr_calcHilbertSchmidtDistance()
qreal densmatr_calcHilbertSchmidtDistance (Qureg a, Qureg b)
Definition at line 446 of file QuEST_cpu_distributed.c.
{
    qreal localSum = densmatr_calcHilbertSchmidtDistanceSquaredLocal(a, b);
    qreal globalSum;
    MPI_Allreduce(&localSum, &globalSum, 1, MPI_QuEST_REAL, MPI_SUM, MPI_COMM_WORLD);
    qreal dist = sqrt(globalSum);
    return dist;
}
References copySharedReduceBlock(), cudaDeviceSynchronize, cudaMemcpy, cudaMemcpyDeviceToHost, densmatr_calcHilbertSchmidtDistanceSquaredLocal(), Qureg::deviceStateVec, Qureg::firstLevelReduction, Qureg::numAmpsPerChunk, qreal, REDUCE_SHARED_SIZE, Qureg::secondLevelReduction, and swapDouble().
Referenced by calcHilbertSchmidtDistance().
densmatr_calcInnerProduct()
qreal densmatr_calcInnerProduct (Qureg a, Qureg b)
Definition at line 457 of file QuEST_cpu_distributed.c.
{
    qreal localSum = densmatr_calcInnerProductLocal(a, b);
    qreal globalSum;
    MPI_Allreduce(&localSum, &globalSum, 1, MPI_QuEST_REAL, MPI_SUM, MPI_COMM_WORLD);
    qreal dist = globalSum;
    return dist;
}
References copySharedReduceBlock(), cudaDeviceSynchronize, cudaMemcpy, cudaMemcpyDeviceToHost, densmatr_calcInnerProductLocal(), Qureg::firstLevelReduction, Qureg::numAmpsTotal, qreal, REDUCE_SHARED_SIZE, Qureg::secondLevelReduction, and swapDouble().
Referenced by calcDensityInnerProduct().
densmatr_calcProbOfAllOutcomes()
void densmatr_calcProbOfAllOutcomes (qreal * retProbs, Qureg qureg, int * qubits, int numQubits)
Definition at line 1351 of file QuEST_cpu_distributed.c.
{
    // each node populates retProbs with contributions from the subset of amps in each
    densmatr_calcProbOfAllOutcomesLocal(retProbs, qureg, qubits, numQubits);
    // then, retProbs are summed element-wise
    MPI_Allreduce(MPI_IN_PLACE, retProbs, 1LL<<numQubits, MPI_QuEST_REAL, MPI_SUM, MPI_COMM_WORLD);
}
References cudaFree, cudaMalloc, cudaMemcpy, cudaMemcpyDeviceToHost, cudaMemcpyHostToDevice, cudaMemset, densmatr_calcProbOfAllOutcomesLocal(), Qureg::numQubitsRepresented, and qreal.
Referenced by calcProbOfAllOutcomes().
densmatr_calcProbOfOutcome()
qreal densmatr_calcProbOfOutcome (Qureg qureg, int measureQubit, int outcome)
Definition at line 1330 of file QuEST_cpu_distributed.c.
{
        qreal zeroProb = densmatr_findProbabilityOfZeroLocal(qureg, measureQubit);
        qreal outcomeProb;
        MPI_Allreduce(&zeroProb, &outcomeProb, 1, MPI_QuEST_REAL, MPI_SUM, MPI_COMM_WORLD);
        if (outcome == 1)
                outcomeProb = 1.0 - outcomeProb;
        return outcomeProb;
}
References densmatr_findProbabilityOfZero(), densmatr_findProbabilityOfZeroLocal(), and qreal.
Referenced by calcProbOfOutcome(), collapseToOutcome(), and densmatr_measureWithStats().
densmatr_calcPurity()
qreal densmatr_calcPurity (Qureg qureg)
Computes the trace of the density matrix squared.
Definition at line 1360 of file QuEST_cpu_distributed.c.
{
    qreal localPurity = densmatr_calcPurityLocal(qureg);
    qreal globalPurity;
    MPI_Allreduce(&localPurity, &globalPurity, 1, MPI_QuEST_REAL, MPI_SUM, MPI_COMM_WORLD);
    return globalPurity;
}
References copySharedReduceBlock(), cudaDeviceSynchronize, cudaMemcpy, cudaMemcpyDeviceToHost, densmatr_calcPurityLocal(), Qureg::deviceStateVec, Qureg::firstLevelReduction, Qureg::numAmpsPerChunk, qreal, REDUCE_SHARED_SIZE, Qureg::secondLevelReduction, and swapDouble().
Referenced by calcPurity().
densmatr_calcTotalProb()
qreal densmatr_calcTotalProb (Qureg qureg)
Definition at line 53 of file QuEST_cpu_distributed.c.
{
        // computes the trace by summing every element ("diag") with global index (2^n + 1)i for i in [0, 2^n-1]
    long long int firstGlobalInd = qureg.chunkId * qureg.numAmpsPerChunk;
    long long int diagSpacing = 1LL + (1LL << qureg.numQubitsRepresented);
    long long int distFromPrevDiag = (firstGlobalInd % diagSpacing);
    long long int distToNextDiag = (distFromPrevDiag > 0)? diagSpacing - distFromPrevDiag : 0;
    // Kahan parameters
        qreal rankTotal = 0;
        qreal y, t, c;
        c = 0;
    long long int index = distToNextDiag;
    while (index < qureg.numAmpsPerChunk) {
        // Kahan summation - brackets are important
        y = qureg.stateVec.real[index] - c;
        t = rankTotal + y;
        c = ( t - rankTotal ) - y;
        rankTotal = t;
        index += diagSpacing;
    }
        // combine each node's sum of diagonals
        qreal globalTotal;
        if (qureg.numChunks > 1)
                MPI_Allreduce(&rankTotal, &globalTotal, 1, MPI_QuEST_REAL, MPI_SUM, MPI_COMM_WORLD);
        else
                globalTotal = rankTotal;
        return globalTotal;
}
References Qureg::chunkId, copyStateFromGPU(), Qureg::numAmpsPerChunk, Qureg::numChunks, Qureg::numQubitsRepresented, qreal, and Qureg::stateVec.
Referenced by calcTotalProb(), and statevec_calcExpecPauliProd().
densmatr_collapseToKnownProbOutcome()
void densmatr_collapseToKnownProbOutcome (Qureg qureg, int measureQubit, int outcome, qreal outcomeProb)
Renorms (/prob) every | * outcome * >< * outcome * | state, setting all others to zero.
Renorms (/prob) every | * outcome * >< * outcome * | state, setting all others to zero.
Definition at line 797 of file QuEST_cpu.c.
{
        // only (global) indices (as bit sequence): '* outcome *(n+q) outcome *q are spared
    // where n = measureQubit, q = qureg.numQubitsRepresented.
    // We can thus step in blocks of 2^q+n, killing every second, and inside the others,
    //  stepping in sub-blocks of 2^q, killing every second.
    // When outcome=1, we offset the start of these blocks by their size.
    long long int innerBlockSize = (1LL << measureQubit);
    long long int outerBlockSize = (1LL << (measureQubit + qureg.numQubitsRepresented));
    // Because there are 2^a number of nodes(/chunks), each node will contain 2^b number of blocks,
    // or each block will span 2^c number of nodes. Similarly for the innerblocks.
    long long int locNumAmps = qureg.numAmpsPerChunk;
    long long int globalStartInd = qureg.chunkId * locNumAmps;
    int innerBit = extractBit(measureQubit, globalStartInd);
    int outerBit = extractBit(measureQubit + qureg.numQubitsRepresented, globalStartInd);
    // If this chunk's amps are entirely inside an outer block
    if (locNumAmps <= outerBlockSize) {
        // if this is an undesired outer block, kill all elems
        if (outerBit != outcome) {
            zeroSomeAmps(qureg, 0, qureg.numAmpsPerChunk);
            return;
        }
        // othwerwise, if this is a desired outer block, and also entirely an inner block
        if (locNumAmps <= innerBlockSize) {
            // and that inner block is undesired, kill all elems
            if (innerBit != outcome)
                zeroSomeAmps(qureg, 0, qureg.numAmpsPerChunk);
            // otherwise normalise all elems
            else
                normaliseSomeAmps(qureg, totalStateProb, 0, qureg.numAmpsPerChunk);
            return;
        }
        // otherwise this is a desired outer block which contains 2^a inner blocks; kill/renorm every second inner block
        alternateNormZeroingSomeAmpBlocks(
            qureg, totalStateProb, innerBit==outcome, 0, qureg.numAmpsPerChunk, innerBlockSize);
        return;
    }
    // Otherwise, this chunk's amps contain multiple outer blocks (and hence multiple inner blocks)
    long long int numOuterDoubleBlocks = locNumAmps / (2*outerBlockSize);
    long long int firstBlockInd;
    // alternate norming* and zeroing the outer blocks (with order based on the desired outcome)
    // These loops aren't parallelised, since they could have 1 or 2 iterations and will prevent
    // inner parallelisation
    if (outerBit == outcome) {
        for (long long int outerDubBlockInd = 0; outerDubBlockInd < numOuterDoubleBlocks; outerDubBlockInd++) {
            firstBlockInd = outerDubBlockInd*2*outerBlockSize;
            // *norm only the desired inner blocks in the desired outer block
            alternateNormZeroingSomeAmpBlocks(
                qureg, totalStateProb, innerBit==outcome,
                firstBlockInd, outerBlockSize, innerBlockSize);
            // zero the undesired outer block
            zeroSomeAmps(qureg, firstBlockInd + outerBlockSize, outerBlockSize);
        }
    } else {
        for (long long int outerDubBlockInd = 0; outerDubBlockInd < numOuterDoubleBlocks; outerDubBlockInd++) {
            firstBlockInd = outerDubBlockInd*2*outerBlockSize;
            // same thing but undesired outer blocks come first
            zeroSomeAmps(qureg, firstBlockInd, outerBlockSize);
            alternateNormZeroingSomeAmpBlocks(
                qureg, totalStateProb, innerBit==outcome,
                firstBlockInd + outerBlockSize, outerBlockSize, innerBlockSize);
        }
    }
}
References alternateNormZeroingSomeAmpBlocks(), Qureg::chunkId, Qureg::deviceStateVec, extractBit(), normaliseSomeAmps(), Qureg::numAmpsPerChunk, Qureg::numQubitsRepresented, qreal, and zeroSomeAmps().
Referenced by applyProjector(), collapseToOutcome(), and densmatr_measureWithStats().
densmatr_initClassicalState()
void densmatr_initClassicalState (Qureg qureg, long long int stateInd)
Definition at line 1132 of file QuEST_cpu.c.
{
    // dimension of the state vector
    long long int densityNumElems = qureg.numAmpsPerChunk;
    // Can't use qureg->stateVec as a private OMP var
    qreal *densityReal = qureg.stateVec.real;
    qreal *densityImag = qureg.stateVec.imag;
    // initialise the state to all zeros
    long long int index;
# ifdef _OPENMP
# pragma omp parallel \
    default  (none) \
    shared   (densityNumElems, densityReal, densityImag) \
    private  (index)
# endif
    {
# ifdef _OPENMP
# pragma omp for schedule (static)
# endif
        for (index=0; index<densityNumElems; index++) {
            densityReal[index] = 0.0;
            densityImag[index] = 0.0;
        }
    }
    // index of the single density matrix elem to set non-zero
    long long int densityDim = 1LL << qureg.numQubitsRepresented;
    long long int densityInd = (densityDim + 1)*stateInd;
    // give the specified classical state prob 1
    if (qureg.chunkId == densityInd / densityNumElems){
        densityReal[densityInd % densityNumElems] = 1.0;
        densityImag[densityInd % densityNumElems] = 0.0;
    }
}
References Qureg::chunkId, Qureg::deviceStateVec, Qureg::numAmpsPerChunk, Qureg::numQubitsRepresented, qreal, and Qureg::stateVec.
Referenced by initClassicalState().
densmatr_initPlusState()
void densmatr_initPlusState (Qureg targetQureg)
Definition at line 1171 of file QuEST_cpu.c.
{
    // |+><+| = sum_i 1/sqrt(2^N) |i> 1/sqrt(2^N) <j| = sum_ij 1/2^N |i><j|
    long long int dim = (1LL << qureg.numQubitsRepresented);
    qreal probFactor = 1.0/((qreal) dim);
    // Can't use qureg->stateVec as a private OMP var
    qreal *densityReal = qureg.stateVec.real;
    qreal *densityImag = qureg.stateVec.imag;
    long long int index;
    long long int chunkSize = qureg.numAmpsPerChunk;
    // initialise the state to |+++..+++> = 1/normFactor {1, 1, 1, ...}
# ifdef _OPENMP
# pragma omp parallel \
    default  (none) \
    shared   (chunkSize, densityReal, densityImag, probFactor) \
    private  (index)
# endif
    {
# ifdef _OPENMP
# pragma omp for schedule (static)
# endif
        for (index=0; index<chunkSize; index++) {
            densityReal[index] = probFactor;
            densityImag[index] = 0.0;
        }
    }
}
References Qureg::deviceStateVec, Qureg::numAmpsPerChunk, Qureg::numQubitsRepresented, qreal, and Qureg::stateVec.
Referenced by initPlusState().
densmatr_initPureState()
void densmatr_initPureState (Qureg targetQureg, Qureg copyQureg)
Definition at line 468 of file QuEST_cpu_distributed.c.
{
    if (targetQureg.numChunks==1){
        // local version
        // save pointers to qureg's pair state
        qreal* quregPairRePtr = targetQureg.pairStateVec.real;
        qreal* quregPairImPtr = targetQureg.pairStateVec.imag;
        // populate qureg pair state with pure state (by repointing)
        targetQureg.pairStateVec.real = copyQureg.stateVec.real;
        targetQureg.pairStateVec.imag = copyQureg.stateVec.imag;
        // populate density matrix via it's pairState
        densmatr_initPureStateLocal(targetQureg, copyQureg);
        // restore pointers
        targetQureg.pairStateVec.real = quregPairRePtr;
        targetQureg.pairStateVec.imag = quregPairImPtr;
    } else {
        // set qureg's pairState is to be the full pure state (on every node)
        copyVecIntoMatrixPairState(targetQureg, copyQureg);
        // update every density matrix chunk using pairState
        densmatr_initPureStateLocal(targetQureg, copyQureg);
    }
}
References copyVecIntoMatrixPairState(), densmatr_initPureStateLocal(), Qureg::deviceStateVec, Qureg::numAmpsPerChunk, Qureg::numChunks, Qureg::pairStateVec, qreal, and Qureg::stateVec.
Referenced by initPureState().
densmatr_measureWithStats()
int densmatr_measureWithStats (Qureg qureg, int measureQubit, qreal * outcomeProb)
Definition at line 368 of file QuEST_common.c.
{
    qreal zeroProb = densmatr_calcProbOfOutcome(qureg, measureQubit, 0);
    int outcome = generateMeasurementOutcome(zeroProb, outcomeProb);
    densmatr_collapseToKnownProbOutcome(qureg, measureQubit, outcome, *outcomeProb);
    return outcome;
}
References densmatr_calcProbOfOutcome(), densmatr_collapseToKnownProbOutcome(), generateMeasurementOutcome(), and qreal.
Referenced by measure(), and measureWithStats().
densmatr_mixDamping()
void densmatr_mixDamping (Qureg qureg, int targetQubit, qreal damping)
Definition at line 741 of file QuEST_cpu_distributed.c.
{
    if (damping == 0)
        return;
    int rankIsUpper; // rank is in the upper half of an outer block
    int pairRank; // rank of corresponding chunk
    int useLocalDataOnly = densityMatrixBlockFitsInChunk(qureg.numAmpsPerChunk,
            qureg.numQubitsRepresented, targetQubit);
    if (useLocalDataOnly){
        densmatr_mixDampingLocal(qureg, targetQubit, damping);
    } else {
        // pack data to send to my pair process into the first half of pairStateVec
        compressPairVectorForSingleQubitDepolarise(qureg, targetQubit);
        rankIsUpper = chunkIsUpperInOuterBlock(qureg.chunkId, qureg.numAmpsPerChunk, targetQubit,
                qureg.numQubitsRepresented);
        pairRank = getChunkOuterBlockPairId(rankIsUpper, qureg.chunkId, qureg.numAmpsPerChunk,
                targetQubit, qureg.numQubitsRepresented);
        exchangePairStateVectorHalves(qureg, pairRank);
        densmatr_mixDampingDistributed(qureg, targetQubit, damping);
    }
}
References Qureg::chunkId, chunkIsUpperInOuterBlock(), compressPairVectorForSingleQubitDepolarise(), densityMatrixBlockFitsInChunk(), densmatr_mixDampingDistributed(), densmatr_mixDampingLocal(), densmatr_oneQubitDegradeOffDiagonal(), Qureg::deviceStateVec, exchangePairStateVectorHalves(), getChunkOuterBlockPairId(), Qureg::numAmpsPerChunk, Qureg::numQubitsRepresented, and qreal.
Referenced by mixDamping().
densmatr_mixDensityMatrix()
void densmatr_mixDensityMatrix (Qureg combineQureg, qreal otherProb, Qureg otherQureg)
Definition at line 907 of file QuEST_cpu.c.
{
    /* corresponding amplitudes live on the same node (same dimensions) */
    // unpack vars for OpenMP
    qreal* combineVecRe = combineQureg.stateVec.real;
    qreal* combineVecIm = combineQureg.stateVec.imag;
    qreal* otherVecRe = otherQureg.stateVec.real;
    qreal* otherVecIm = otherQureg.stateVec.imag;
    long long int numAmps = combineQureg.numAmpsPerChunk;
    long long int index;
# ifdef _OPENMP
# pragma omp parallel \
    default (none) \
    shared  (combineVecRe,combineVecIm,otherVecRe,otherVecIm, otherProb, numAmps) \
    private (index)
# endif
    {
# ifdef _OPENMP
# pragma omp for schedule  (static)
# endif
        for (index=0; index < numAmps; index++) {
            combineVecRe[index] *= 1-otherProb;
            combineVecIm[index] *= 1-otherProb;
            combineVecRe[index] += otherProb * otherVecRe[index];
            combineVecIm[index] += otherProb * otherVecIm[index];
        }
    }
}
References Qureg::numAmpsPerChunk, qreal, and Qureg::stateVec.
Referenced by mixDensityMatrix().
densmatr_mixDephasing()
void densmatr_mixDephasing (Qureg qureg, int targetQubit, qreal dephase)
Definition at line 91 of file QuEST_cpu.c.
{
    qreal retain=1-dephase;
    densmatr_oneQubitDegradeOffDiagonal(qureg, targetQubit, retain);
}
References densmatr_oneQubitDegradeOffDiagonal(), and qreal.
Referenced by densmatr_mixDepolarising(), densmatr_mixDepolarisingDistributed(), and mixDephasing().
densmatr_mixDepolarising()
void densmatr_mixDepolarising (Qureg qureg, int targetQubit, qreal depolLevel)
Definition at line 714 of file QuEST_cpu_distributed.c.
{
    if (depolLevel == 0)
        return;
    int rankIsUpper; // rank is in the upper half of an outer block
    int pairRank; // rank of corresponding chunk
    int useLocalDataOnly = densityMatrixBlockFitsInChunk(qureg.numAmpsPerChunk,
            qureg.numQubitsRepresented, targetQubit);
    if (useLocalDataOnly){
        densmatr_mixDepolarisingLocal(qureg, targetQubit, depolLevel);
    } else {
        // pack data to send to my pair process into the first half of pairStateVec
        compressPairVectorForSingleQubitDepolarise(qureg, targetQubit);
        rankIsUpper = chunkIsUpperInOuterBlock(qureg.chunkId, qureg.numAmpsPerChunk, targetQubit,
                qureg.numQubitsRepresented);
        pairRank = getChunkOuterBlockPairId(rankIsUpper, qureg.chunkId, qureg.numAmpsPerChunk,
                targetQubit, qureg.numQubitsRepresented);
        exchangePairStateVectorHalves(qureg, pairRank);
        densmatr_mixDepolarisingDistributed(qureg, targetQubit, depolLevel);
    }
}
References Qureg::chunkId, chunkIsUpperInOuterBlock(), compressPairVectorForSingleQubitDepolarise(), densityMatrixBlockFitsInChunk(), densmatr_mixDephasing(), densmatr_mixDepolarisingDistributed(), densmatr_mixDepolarisingLocal(), Qureg::deviceStateVec, exchangePairStateVectorHalves(), getChunkOuterBlockPairId(), Qureg::numAmpsPerChunk, Qureg::numQubitsRepresented, and qreal.
Referenced by mixDepolarising().
densmatr_mixKrausMap()
void densmatr_mixKrausMap (Qureg qureg, int target, ComplexMatrix2 * ops, int numOps)
Definition at line 640 of file QuEST_common.c.
{
    ComplexMatrix4 superOp;
    populateKrausSuperOperator2(&superOp, ops, numOps);
    densmatr_applyKrausSuperoperator(qureg, target, superOp);
}
References densmatr_applyKrausSuperoperator(), and populateKrausSuperOperator2().
Referenced by densmatr_mixPauli(), mixKrausMap(), and mixNonTPKrausMap().
densmatr_mixMultiQubitKrausMap()
void densmatr_mixMultiQubitKrausMap (Qureg qureg, int * targets, int numTargets, ComplexMatrixN * ops, int numOps)
Definition at line 698 of file QuEST_common.c.
{
    ComplexMatrixN superOp;
    /* superOp will contain 2^(4 numTargets) complex numbers.
     * At double precision, superOp will cost additional memory:
     * numTargs=1   ->   0.25 KiB
     * numTargs=2   ->   4 KiB
     * numTargs=3   ->   64 KiB
     * numTargs=4   ->   1 MiB
     * numTargs=5   ->   16 MiB.
     * At quad precision (usually 10 B per number, but possibly 16 B due to alignment),
     * this costs at most double.
     *
     * Hence, if superOp is kept in the stack, numTargs >= 4 would exceed Windows' 1 MB
     * maximum stack-space allocation (numTargs >= 5 exceeding Linux' 8 MB). Therefore,
     * for numTargets < 4, superOp will be kept in the stack, else in the heap
     */
     // if NOT on Windows, allocate ComplexN on stack depending on size
     #if (! defined(_WIN32)) && (! defined (_WIN64))
         if (numTargets < 4) {
             // everything must live in 'if' since this macro declares local vars
             macro_allocStackComplexMatrixN(superOp, 2*numTargets);
             populateKrausSuperOperatorN(&superOp, ops, numOps);
             densmatr_applyMultiQubitKrausSuperoperator(qureg, targets, numTargets, superOp);
         }
         else {
             superOp = createComplexMatrixN(2*numTargets);
             populateKrausSuperOperatorN(&superOp, ops, numOps);
             densmatr_applyMultiQubitKrausSuperoperator(qureg, targets, numTargets, superOp);
             destroyComplexMatrixN(superOp);
         }
     // on Windows, we must always create in heap
     #else
         superOp = createComplexMatrixN(2*numTargets);
         populateKrausSuperOperatorN(&superOp, ops, numOps);
         densmatr_applyMultiQubitKrausSuperoperator(qureg, targets, numTargets, superOp);
         destroyComplexMatrixN(superOp);
     #endif
}
References createComplexMatrixN(), densmatr_applyMultiQubitKrausSuperoperator(), destroyComplexMatrixN(), macro_allocStackComplexMatrixN, and populateKrausSuperOperatorN().
Referenced by mixMultiQubitKrausMap(), and mixNonTPMultiQubitKrausMap().
densmatr_mixPauli()
void densmatr_mixPauli (Qureg qureg, int qubit, qreal pX, qreal pY, qreal pZ)
Definition at line 740 of file QuEST_common.c.
{
    // convert pauli probabilities into Kraus map
    const int numOps = 4;
    ComplexMatrix2 ops[4]; // [numOps];
    for (int n=0; n < numOps; n++)
        ops[n] = (ComplexMatrix2) {.real={{0}}, .imag={{0}}};
    qreal facs[4] = { // literal numOps=4 for valid initialisation
                sqrt(1-(probX + probY + probZ)),
                sqrt(probX),
                sqrt(probY),
                sqrt(probZ)
        };
    ops[0].real[0][0] =  facs[0]; ops[0].real[1][1] =  facs[0];
    ops[1].real[0][1] =  facs[1]; ops[1].real[1][0] =  facs[1];
    ops[2].imag[0][1] = -facs[2]; ops[2].imag[1][0] =  facs[2];
    ops[3].real[0][0] =  facs[3]; ops[3].real[1][1] = -facs[3];
    densmatr_mixKrausMap(qureg, qubit, ops, numOps);
}
References densmatr_mixKrausMap(), ComplexMatrix2::imag, qreal, and ComplexMatrix2::real.
Referenced by mixPauli().
densmatr_mixTwoQubitDephasing()
void densmatr_mixTwoQubitDephasing (Qureg qureg, int qubit1, int qubit2, qreal dephase)
Definition at line 96 of file QuEST_cpu.c.
{
    qreal retain=1-dephase;
    long long int numTasks = qureg.numAmpsPerChunk;
    long long int innerMaskQubit1 = 1LL << qubit1;
    long long int outerMaskQubit1 = 1LL << (qubit1 + (qureg.numQubitsRepresented));
    long long int innerMaskQubit2 = 1LL << qubit2;
    long long int outerMaskQubit2 = 1LL << (qubit2 + (qureg.numQubitsRepresented));
    long long int totMaskQubit1 = innerMaskQubit1|outerMaskQubit1;
    long long int totMaskQubit2 = innerMaskQubit2|outerMaskQubit2;
    long long int thisTask;
    long long int thisPatternQubit1, thisPatternQubit2;
# ifdef _OPENMP
# pragma omp parallel \
    default  (none) \
    shared   (innerMaskQubit1,outerMaskQubit1,totMaskQubit1,innerMaskQubit2,outerMaskQubit2, \
                totMaskQubit2,qureg,retain,numTasks) \
    private  (thisTask,thisPatternQubit1,thisPatternQubit2)
# endif
    {
# ifdef _OPENMP
# pragma omp for schedule (static)
# endif
        for (thisTask=0; thisTask<numTasks; thisTask++){
            thisPatternQubit1 = (thisTask+qureg.numAmpsPerChunk*qureg.chunkId)&totMaskQubit1;
            thisPatternQubit2 = (thisTask+qureg.numAmpsPerChunk*qureg.chunkId)&totMaskQubit2;
            // any mismatch |...0...><...1...| etc
            if ( (thisPatternQubit1==innerMaskQubit1) || (thisPatternQubit1==outerMaskQubit1) ||
                    (thisPatternQubit2==innerMaskQubit2) || (thisPatternQubit2==outerMaskQubit2) ){
                // do dephase
                // the lines below will degrade the off-diagonal terms |..0..><..1..| and |..1..><..0..|
                qureg.stateVec.real[thisTask] = retain*qureg.stateVec.real[thisTask];
                qureg.stateVec.imag[thisTask] = retain*qureg.stateVec.imag[thisTask];
            }
        }
    }
}
References Qureg::chunkId, Qureg::deviceStateVec, Qureg::numAmpsPerChunk, Qureg::numQubitsRepresented, qreal, and Qureg::stateVec.
Referenced by densmatr_mixTwoQubitDepolarising(), and mixTwoQubitDephasing().
densmatr_mixTwoQubitDepolarising()
void densmatr_mixTwoQubitDepolarising (Qureg qureg, int qubit1, int qubit2, qreal depolLevel)
Definition at line 768 of file QuEST_cpu_distributed.c.
{
    if (depolLevel == 0)
        return;
    int rankIsUpperBiggerQubit, rankIsUpperSmallerQubit;
    int pairRank; // rank of corresponding chunk
    int biggerQubit, smallerQubit;
    densmatr_mixTwoQubitDephasing(qureg, qubit1, qubit2, depolLevel);
    qreal eta = 2/depolLevel;
    qreal delta = eta - 1 - sqrt( (eta-1)*(eta-1) - 1 );
    qreal gamma = 1+delta;
    gamma = 1/(gamma*gamma*gamma);
    qreal GAMMA_PARTS_1_OR_2 = 1.0;
    // TODO -- test delta too small
    /*
    if (fabs(4*delta*(1+delta)*gamma-depolLevel)>1e-5){
        printf("Numerical error in delta; for small error rates try Taylor expansion.\n");
        exit(1);
    }
    */
    biggerQubit = qubit1 > qubit2 ? qubit1 : qubit2;
    smallerQubit = qubit1 < qubit2 ? qubit1 : qubit2;
    int useLocalDataOnlyBigQubit, useLocalDataOnlySmallQubit;
    useLocalDataOnlyBigQubit = densityMatrixBlockFitsInChunk(qureg.numAmpsPerChunk,
        qureg.numQubitsRepresented, biggerQubit);
    if (useLocalDataOnlyBigQubit){
        // does parts 1, 2 and 3 locally in one go
        densmatr_mixTwoQubitDepolarisingLocal(qureg, qubit1, qubit2, delta, gamma);
    } else {
        useLocalDataOnlySmallQubit = densityMatrixBlockFitsInChunk(qureg.numAmpsPerChunk,
            qureg.numQubitsRepresented, smallerQubit);
        if (useLocalDataOnlySmallQubit){
            // do part 1 locally
            densmatr_mixTwoQubitDepolarisingLocalPart1(qureg, smallerQubit, biggerQubit, delta);
            // do parts 2 and 3 distributed (if part 2 is distributed part 3 is also distributed)
            // part 2 will be distributed and the value of the small qubit won't matter
            compressPairVectorForTwoQubitDepolarise(qureg, smallerQubit, biggerQubit);
            rankIsUpperBiggerQubit = chunkIsUpperInOuterBlock(qureg.chunkId, qureg.numAmpsPerChunk, biggerQubit,
                    qureg.numQubitsRepresented);
            pairRank = getChunkOuterBlockPairId(rankIsUpperBiggerQubit, qureg.chunkId, qureg.numAmpsPerChunk,
                    biggerQubit, qureg.numQubitsRepresented);
            exchangePairStateVectorHalves(qureg, pairRank);
            densmatr_mixTwoQubitDepolarisingDistributed(qureg, smallerQubit, biggerQubit, delta, GAMMA_PARTS_1_OR_2);
            // part 3 will be distributed but involve rearranging for the smaller qubit
            compressPairVectorForTwoQubitDepolarise(qureg, smallerQubit, biggerQubit);
            rankIsUpperBiggerQubit = chunkIsUpperInOuterBlock(qureg.chunkId, qureg.numAmpsPerChunk, biggerQubit,
                    qureg.numQubitsRepresented);
            pairRank = getChunkOuterBlockPairId(rankIsUpperBiggerQubit, qureg.chunkId, qureg.numAmpsPerChunk,
                    biggerQubit, qureg.numQubitsRepresented);
            exchangePairStateVectorHalves(qureg, pairRank);
            densmatr_mixTwoQubitDepolarisingQ1LocalQ2DistributedPart3(qureg, smallerQubit, biggerQubit, delta, gamma);
        } else {
            // do part 1, 2 and 3 distributed
            // part 1
            compressPairVectorForTwoQubitDepolarise(qureg, smallerQubit, biggerQubit);
            rankIsUpperSmallerQubit = chunkIsUpperInOuterBlock(qureg.chunkId, qureg.numAmpsPerChunk, smallerQubit,
                    qureg.numQubitsRepresented);
            pairRank = getChunkOuterBlockPairId(rankIsUpperSmallerQubit, qureg.chunkId, qureg.numAmpsPerChunk,
                    smallerQubit, qureg.numQubitsRepresented);
            exchangePairStateVectorHalves(qureg, pairRank);
            densmatr_mixTwoQubitDepolarisingDistributed(qureg, smallerQubit, biggerQubit, delta, GAMMA_PARTS_1_OR_2);
            // part 2
            compressPairVectorForTwoQubitDepolarise(qureg, smallerQubit, biggerQubit);
            rankIsUpperBiggerQubit = chunkIsUpperInOuterBlock(qureg.chunkId, qureg.numAmpsPerChunk, biggerQubit,
                    qureg.numQubitsRepresented);
            pairRank = getChunkOuterBlockPairId(rankIsUpperBiggerQubit, qureg.chunkId, qureg.numAmpsPerChunk,
                    biggerQubit, qureg.numQubitsRepresented);
            exchangePairStateVectorHalves(qureg, pairRank);
            densmatr_mixTwoQubitDepolarisingDistributed(qureg, smallerQubit, biggerQubit, delta, GAMMA_PARTS_1_OR_2);
            // part 3
            compressPairVectorForTwoQubitDepolarise(qureg, smallerQubit, biggerQubit);
            pairRank = getChunkOuterBlockPairIdForPart3(rankIsUpperSmallerQubit, rankIsUpperBiggerQubit,
                    qureg.chunkId, qureg.numAmpsPerChunk, smallerQubit, biggerQubit, qureg.numQubitsRepresented);
            exchangePairStateVectorHalves(qureg, pairRank);
            densmatr_mixTwoQubitDepolarisingDistributed(qureg, smallerQubit, biggerQubit, delta, gamma);
        }
    }
}
References Qureg::chunkId, chunkIsUpperInOuterBlock(), compressPairVectorForTwoQubitDepolarise(), densityMatrixBlockFitsInChunk(), densmatr_mixTwoQubitDephasing(), densmatr_mixTwoQubitDepolarisingDistributed(), densmatr_mixTwoQubitDepolarisingLocal(), densmatr_mixTwoQubitDepolarisingLocalPart1(), densmatr_mixTwoQubitDepolarisingQ1LocalQ2DistributedPart3(), Qureg::deviceStateVec, exchangePairStateVectorHalves(), getChunkOuterBlockPairId(), getChunkOuterBlockPairIdForPart3(), Qureg::numAmpsPerChunk, Qureg::numQubitsRepresented, and qreal.
Referenced by mixTwoQubitDepolarising().
densmatr_mixTwoQubitKrausMap()
void densmatr_mixTwoQubitKrausMap (Qureg qureg, int target1, int target2, ComplexMatrix4 * ops, int numOps)
Definition at line 680 of file QuEST_common.c.
{
  // On Windows, we must allocated superoperators dynamically
  #if defined(_WIN32) || defined(_WIN64)
      ComplexMatrixN superOp = createComplexMatrixN(4);
      populateKrausSuperOperator4(&superOp, ops, numOps);
      densmatr_applyTwoQubitKrausSuperoperator(qureg, target1, target2, superOp);
      destroyComplexMatrixN(superOp);
  // but otherwise, we can keep it on the stack
  #else
      ComplexMatrixN superOp;
      macro_allocStackComplexMatrixN(superOp, 4);
      populateKrausSuperOperator4(&superOp, ops, numOps);
      densmatr_applyTwoQubitKrausSuperoperator(qureg, target1, target2, superOp);
  #endif
}
References createComplexMatrixN(), densmatr_applyTwoQubitKrausSuperoperator(), destroyComplexMatrixN(), macro_allocStackComplexMatrixN, and populateKrausSuperOperator4().
Referenced by mixNonTPTwoQubitKrausMap(), and mixTwoQubitKrausMap().
densmatr_setQuregToPauliHamil()
void densmatr_setQuregToPauliHamil (Qureg qureg, PauliHamil hamil)
Definition at line 4646 of file QuEST_cpu.c.
{
    // flattened {I,X,Y,Z} matrix elements, where [k] = [p][i][j]
    int pauliRealElems[] = {   1,0, 0,1,   0,1, 1,0,   0,0, 0,0,   1,0, 0,-1  };
    int pauliImagElems[] = {   0,0, 0,0,   0,0, 0,0,   0,-1,1,0,   0,0, 0,0   };
    // constants (unpacked to prevent OpenMP struct tantrum)
    int numTerms = hamil.numSumTerms;
    int numQubits = hamil.numQubits;
    enum pauliOpType* paulis = hamil.pauliCodes;
    qreal* termCoeffs = hamil.termCoeffs;
    qreal* stateRe = qureg.stateVec.real;
    qreal* stateIm = qureg.stateVec.imag;
    long long int numLocAmps = qureg.numAmpsPerChunk;
    long long int nOffset = numLocAmps * qureg.chunkId;
    // private threading vars
    long long int n, nGlob, r, c, t, pInd;
    int q, i, j, p, k;
    qreal elemRe, elemIm;
    int kronRe, kronIm;
    int pauliRe, pauliIm, tmp;
    // use a private thread for every overwritten amplitude
# ifdef _OPENMP
# pragma omp parallel \
    default  (none) \
    shared   (pauliRealElems,pauliImagElems, numTerms,numQubits,numLocAmps,nOffset,  paulis,termCoeffs, stateRe,stateIm) \
    private  (q,i,j,p,k, r,c,n,nGlob,t,pInd, elemRe,elemIm, kronRe,kronIm, pauliRe,pauliIm, tmp)
# endif
    {
# ifdef _OPENMP
# pragma omp for schedule (static)
# endif
        for (n=0; n<numLocAmps; n++) {
            // |nGlob> = |rank>|n>
            nGlob = nOffset + n;
            // |nGlob> = |c>|r>
            r = nGlob & ((1LL << numQubits) - 1);
            c = nGlob >> numQubits;
            // new amplitude of |n>
            elemRe = 0;
            elemIm = 0;
            for (t=0; t<numTerms; t++) {
                // pauliKronecker[r][c] = prod_q Pauli[q][q-th bit of r and c]
                kronRe = 1;
                kronIm = 0;
                pInd = numQubits * t;
                for (q=0; q<numQubits; q++) {
                    // get element of Pauli matrix
                    i = (r >> q) & 1;
                    j = (c >> q) & 1;
                    p = (int) paulis[pInd++];
                    k = (p<<2) + (i<<1) + j;
                    pauliRe = pauliRealElems[k];
                    pauliIm = pauliImagElems[k];
                    // kron *= pauli
                    tmp = (pauliRe*kronRe) - (pauliIm*kronIm);
                    kronIm = (pauliRe*kronIm) + (pauliIm*kronRe);
                    kronRe = tmp;
                }
                // elem = sum_t coeffs[t] pauliKronecker[r][c]
                elemRe += termCoeffs[t] * kronRe;
                elemIm += termCoeffs[t] * kronIm;
            }
            // overwrite the density matrix entry
            stateRe[n] = elemRe;
            stateIm[n] = elemIm;
        }
    }
}
References Qureg::chunkId, cudaFree, cudaMalloc, cudaMemcpy, cudaMemcpyHostToDevice, Qureg::numAmpsPerChunk, PauliHamil::numQubits, PauliHamil::numSumTerms, PauliHamil::pauliCodes, qreal, Qureg::stateVec, and PauliHamil::termCoeffs.
Referenced by setQuregToPauliHamil().
ensureIndsIncrease()
void ensureIndsIncrease (int * ind1, int * ind2)
Definition at line 70 of file QuEST_common.c.
{
    if (*ind1 > *ind2) {
        int copy = *ind1;
        *ind1 = *ind2;
        *ind2 = copy;
    }
}
Referenced by mixTwoQubitDephasing(), and mixTwoQubitDepolarising().
getComplexPairAndPhaseFromUnitary()
void getComplexPairAndPhaseFromUnitary (ComplexMatrix2 u, Complex * alpha, Complex * beta, qreal * globalPhase)
maps U(r0c0, r0c1, r1c0, r1c1) to exp(i globalPhase) U(alpha, beta)
Definition at line 142 of file QuEST_common.c.
{
    qreal r0c0Phase = atan2(u.imag[0][0], u.real[0][0]);
    qreal r1c1Phase = atan2(u.imag[1][1], u.real[1][1]);
    *globalPhase = (r0c0Phase + r1c1Phase)/2.0;
    qreal cosPhase = cos(*globalPhase);
    qreal sinPhase = sin(*globalPhase);
    alpha->real = u.real[0][0]*cosPhase + u.imag[0][0]*sinPhase;
    alpha->imag = u.imag[0][0]*cosPhase - u.real[0][0]*sinPhase;
    beta->real  = u.real[1][0]*cosPhase + u.imag[1][0]*sinPhase;
    beta->imag  = u.imag[1][0]*cosPhase - u.real[1][0]*sinPhase;
}
References Complex::imag, ComplexMatrix2::imag, qreal, Complex::real, and ComplexMatrix2::real.
Referenced by qasm_recordControlledUnitary(), qasm_recordMultiControlledUnitary(), and qasm_recordUnitary().
getComplexPairFromRotation()
void getComplexPairFromRotation (qreal angle, Vector axis, Complex * alpha, Complex * beta)
Definition at line 120 of file QuEST_common.c.
{
    Vector unitAxis = getUnitVector(axis);
    alpha->real =   cos(angle/2.0);
    alpha->imag = - sin(angle/2.0)*unitAxis.z;
    beta->real  =   sin(angle/2.0)*unitAxis.y;
    beta->imag  = - sin(angle/2.0)*unitAxis.x;
}
References getUnitVector(), Complex::imag, Complex::real, Vector::x, Vector::y, and Vector::z.
Referenced by qasm_recordAxisRotation(), qasm_recordControlledAxisRotation(), statevec_controlledRotateAroundAxis(), statevec_controlledRotateAroundAxisConj(), statevec_rotateAroundAxis(), and statevec_rotateAroundAxisConj().
getConjugateMatrix2()
ComplexMatrix2 getConjugateMatrix2 (ComplexMatrix2 src)
Definition at line 105 of file QuEST_common.c.
{
    ComplexMatrix2 conj;
    macro_setConjugateMatrix(conj, src, 2);
    return conj;
}
References macro_setConjugateMatrix.
Referenced by controlledUnitary(), multiControlledUnitary(), multiStateControlledUnitary(), and unitary().
getConjugateMatrix4()
ComplexMatrix4 getConjugateMatrix4 (ComplexMatrix4 src)
Definition at line 110 of file QuEST_common.c.
{
    ComplexMatrix4 conj;
    macro_setConjugateMatrix(conj, src, 4);
    return conj;
}
References macro_setConjugateMatrix.
Referenced by controlledTwoQubitUnitary(), multiControlledTwoQubitUnitary(), and twoQubitUnitary().
getConjugateScalar()
Complex getConjugateScalar (Complex scalar)
Definition at line 91 of file QuEST_common.c.
{
    Complex conjScalar;
    conjScalar.real =   scalar.real;
    conjScalar.imag = - scalar.imag;
    return conjScalar;
}
References Complex::imag, and Complex::real.
Referenced by compactUnitary(), and controlledCompactUnitary().
getControlFlipMask()
long long int getControlFlipMask (int * controlQubits, int * controlState, int numControlQubits)
Definition at line 60 of file QuEST_common.c.
{
    long long int mask=0;
    for (int i=0; i<numControlQubits; i++)
        if (controlState[i] == 0)
            mask = mask | (1LL << controlQubits[i]);
    return mask;
}
Referenced by multiStateControlledUnitary().
getQubitBitMask()
long long int getQubitBitMask (int * controlQubits, int numControlQubits)
Definition at line 50 of file QuEST_common.c.
{
    long long int mask=0;
    for (int i=0; i<numQubits; i++)
        mask = mask | (1LL << qubits[i]);
    return mask;
}
Referenced by applyMultiControlledGateMatrixN(), applyMultiControlledMatrixN(), multiControlledMultiQubitNot(), multiControlledMultiQubitUnitary(), multiControlledMultiRotatePauli(), multiControlledMultiRotateZ(), multiControlledTwoQubitUnitary(), multiControlledUnitary(), multiQubitNot(), multiRotateZ(), multiStateControlledUnitary(), statevec_multiControlledMultiQubitUnitary(), statevec_multiControlledMultiRotatePauli(), statevec_multiControlledPhaseFlip(), statevec_multiControlledPhaseShift(), statevec_multiRotatePauli(), and validateMultiControlsMultiTargets().
getQuESTDefaultSeedKey()
void getQuESTDefaultSeedKey (unsigned long int * key)
Definition at line 195 of file QuEST_common.c.
{
    // init MT random number generator with two keys -- time and pid
    // for the MPI version, it is ok that all procs will get the same seed as random numbers will only be
    // used by the master process
#if (defined(_WIN32) || defined(_WIN64)) && ! defined(__MINGW32__)
    unsigned long int pid = (unsigned long int) _getpid();
    unsigned long int msecs = (unsigned long int) GetTickCount64();
    key[0] = msecs; key[1] = pid;
#else
    struct timeval  tv;
    gettimeofday(&tv, NULL);
    double time_in_mill =
        (tv.tv_sec) * 1000 + (tv.tv_usec) / 1000 ; // convert tv_sec & tv_usec to millisecond
    unsigned long int pid = getpid();
    unsigned long int msecs = (unsigned long int) time_in_mill;
    key[0] = msecs; key[1] = pid;
#endif
}
Referenced by seedQuESTDefault().
getVectorMagnitude()
qreal getVectorMagnitude (Vector vec)
Definition at line 79 of file QuEST_common.c.
{
    return sqrt(vec.x*vec.x + vec.y*vec.y + vec.z*vec.z);
}
References Vector::x, Vector::y, and Vector::z.
Referenced by getUnitVector(), and validateVector().
getZYZRotAnglesFromComplexPair()
void getZYZRotAnglesFromComplexPair (Complex alpha, Complex beta, qreal * rz2, qreal * ry, qreal * rz1)
maps U(alpha, beta) to Rz(rz2) Ry(ry) Rz(rz1)
Definition at line 130 of file QuEST_common.c.
{
    qreal alphaMag = sqrt(alpha.real*alpha.real + alpha.imag*alpha.imag);
    *ry = 2.0 * acos(alphaMag);
    qreal alphaPhase = atan2(alpha.imag, alpha.real);
    qreal betaPhase  = atan2(beta.imag,  beta.real);
    *rz2 = - alphaPhase + betaPhase;
    *rz1 = - alphaPhase - betaPhase;
}
References Complex::imag, qreal, and Complex::real.
Referenced by qasm_recordAxisRotation(), qasm_recordCompactUnitary(), qasm_recordControlledAxisRotation(), qasm_recordControlledCompactUnitary(), qasm_recordControlledUnitary(), qasm_recordMultiControlledUnitary(), and qasm_recordUnitary().
hashString()
unsigned long int hashString (char * str)
Definition at line 185 of file QuEST_common.c.
{
    unsigned long int hash = 5381;
    int c;
    while ((c = *str++))
        hash = ((hash << 5) + hash) + c; /* hash * 33 + c */
    return hash;
}
setConjugateMatrixN()
void setConjugateMatrixN (ComplexMatrixN m)
Definition at line 115 of file QuEST_common.c.
{
    int len = 1 << m.numQubits;
    macro_setConjugateMatrix(m, m, len);
}
References macro_setConjugateMatrix, and ComplexMatrixN::numQubits.
Referenced by applyGateMatrixN(), applyMultiControlledGateMatrixN(), controlledMultiQubitUnitary(), multiControlledMultiQubitUnitary(), and multiQubitUnitary().
shiftIndices()
void shiftIndices (int * indices, int numIndices, int shift)
Definition at line 156 of file QuEST_common.c.
{
    for (int j=0; j < numIndices; j++)
        indices[j] += shift;
}
Referenced by applyGateMatrixN(), applyGateSubDiagonalOp(), applyMultiControlledGateMatrixN(), applyPhaseFunc(), applyPhaseFuncOverrides(), controlledMultiQubitUnitary(), diagonalUnitary(), multiControlledMultiQubitUnitary(), multiControlledMultiRotatePauli(), multiControlledPhaseFlip(), multiControlledPhaseShift(), multiQubitUnitary(), and multiRotatePauli().
shiftSubregIndices()
void shiftSubregIndices (int * allInds, int * numIndsPerReg, int numRegs, int shift)
Definition at line 161 of file QuEST_common.c.
{
    int i=0;
    for (int r=0; r<numRegs; r++)
        for (int j=0; j<numIndsPerReg[r]; j++)
            allInds[i++] += shift;
}
Referenced by agnostic_applyQFT(), applyMultiVarPhaseFunc(), applyMultiVarPhaseFuncOverrides(), applyNamedPhaseFunc(), applyNamedPhaseFuncOverrides(), applyParamNamedPhaseFunc(), and applyParamNamedPhaseFuncOverrides().
statevec_applyDiagonalOp()
void statevec_applyDiagonalOp (Qureg qureg, DiagonalOp op)
Definition at line 4078 of file QuEST_cpu.c.
{
    // each node/chunk modifies only its values in an embarrassingly parallelisable way
    long long int numAmps = qureg.numAmpsPerChunk;
    qreal* stateRe = qureg.stateVec.real;
    qreal* stateIm = qureg.stateVec.imag;
    qreal* opRe = op.real;
    qreal* opIm = op.imag;
    qreal a,b,c,d;
    long long int index;
# ifdef _OPENMP
# pragma omp parallel \
    shared    (stateRe,stateIm, opRe,opIm, numAmps) \
    private   (index, a,b,c,d)
# endif
    {
# ifdef _OPENMP
# pragma omp for schedule  (static)
# endif
        for (index=0LL; index<numAmps; index++) {
            a = stateRe[index];
            b = stateIm[index];
            c = opRe[index];
            d = opIm[index];
            // (a + b i)(c + d i) = (a c - b d) + i (a d + b c)
            stateRe[index] = a*c - b*d;
            stateIm[index] = a*d + b*c;
        }
    }
}
References DiagonalOp::imag, Qureg::numAmpsPerChunk, qreal, DiagonalOp::real, and Qureg::stateVec.
Referenced by applyDiagonalOp().
statevec_applyMultiVarPhaseFuncOverrides()
void statevec_applyMultiVarPhaseFuncOverrides (Qureg qureg, int * qubits, int * numQubitsPerReg, int numRegs, enum bitEncoding encoding, qreal * coeffs, qreal * exponents, int * numTermsPerReg, long long int * overrideInds, qreal * overridePhases, int numOverrides, int conj)
Definition at line 4376 of file QuEST_cpu.c.
{
    // each node/chunk modifies only local values in an embarrassingly parallel way
    // note partitions of qubits, coeffs, exponents and overrideInds are stored flat
    // thread-shared vaes
    int chunkId = qureg.chunkId;
    long long int numAmps = qureg.numAmpsPerChunk;
    qreal* stateRe = qureg.stateVec.real;
    qreal* stateIm = qureg.stateVec.imag;
    // thread-private vars
    long long int index, globalAmpInd;
    int r, q, i, t, found, flatInd;
    qreal phase, c, s, re, im;
    // each thread has a private static array of length >= numRegs (private var-length is illegal)
    long long int phaseInds[MAX_NUM_REGS_APPLY_ARBITRARY_PHASE];
# ifdef _OPENMP
# pragma omp parallel \
    default  (none) \
    shared   (chunkId,numAmps, stateRe,stateIm, qubits,numQubitsPerReg,numRegs,encoding, coeffs,exponents,numTermsPerReg, overrideInds,overridePhases,numOverrides, conj) \
    private  (index,globalAmpInd, r,q,i,t,flatInd, found, phaseInds,phase, c,s,re,im)
# endif
    {
# ifdef _OPENMP
# pragma omp for schedule (static)
# endif
        for (index=0LL; index<numAmps; index++) {
            // determine global amplitude index
            globalAmpInd = chunkId * numAmps + index;
            // determine phase indices
            flatInd = 0;
            for (r=0; r<numRegs; r++) {
                phaseInds[r] = 0LL;
                if (encoding == UNSIGNED) {
                    for (q=0; q<numQubitsPerReg[r]; q++)
                        phaseInds[r] += (1LL << q) * extractBit(qubits[flatInd++], globalAmpInd);   // qubits[flatInd] ~ qubits[r][q]
                }
                else if (encoding == TWOS_COMPLEMENT) {
                    for (q=0; q<numQubitsPerReg[r]-1; q++)
                        phaseInds[r] += (1LL << q) * extractBit(qubits[flatInd++], globalAmpInd);
                    // use final qubit to indicate sign
                    if (extractBit(qubits[flatInd++], globalAmpInd) == 1)
                        phaseInds[r] -= (1LL << (numQubitsPerReg[r]-1));
                }
            }
            // determine if this phase index has an overriden value (i < numOverrides)
            for (i=0; i<numOverrides; i++) {
                found = 1;
                for (r=0; r<numRegs; r++) {
                    if (phaseInds[r] != overrideInds[i*numRegs+r]) {
                        found = 0;
                        break;
                    }
                }
                if (found)
                    break;
            }
            // compute the phase (unless overriden)
            phase = 0;
            if (i < numOverrides)
                phase = overridePhases[i];
            else {
                flatInd = 0;
                for (r=0; r<numRegs; r++) {
                    for (t=0; t<numTermsPerReg[r]; t++) {
                        phase += coeffs[flatInd] * pow(phaseInds[r], exponents[flatInd]);
                        flatInd++;
                    }
                }
            }
            // negate phase to conjugate operator
            if (conj)
                phase *= -1;
            // modify amp to amp * exp(i phase)
            c = cos(phase);
            s = sin(phase);
            re = stateRe[index];
            im = stateIm[index];
            // = {re[amp] cos(phase) - im[amp] sin(phase)} + i {re[amp] sin(phase) + im[amp] cos(phase)}
            stateRe[index] = re*c - im*s;
            stateIm[index] = re*s + im*c;
        }
    }
}
References Qureg::chunkId, cudaFree, cudaMalloc, cudaMemcpy, cudaMemcpyHostToDevice, extractBit(), MAX_NUM_REGS_APPLY_ARBITRARY_PHASE, Qureg::numAmpsPerChunk, qreal, Qureg::stateVec, TWOS_COMPLEMENT, and UNSIGNED.
Referenced by applyMultiVarPhaseFunc(), and applyMultiVarPhaseFuncOverrides().
statevec_applyParamNamedPhaseFuncOverrides()
void statevec_applyParamNamedPhaseFuncOverrides (Qureg qureg, int * qubits, int * numQubitsPerReg, int numRegs, enum bitEncoding encoding, enum phaseFunc functionNameCode, qreal * params, int numParams, long long int * overrideInds, qreal * overridePhases, int numOverrides, int conj)
Definition at line 4477 of file QuEST_cpu.c.
  {
    // each node/chunk modifies only local values in an embarrassingly parallel way
    // note partitions of qubits, overrideInds are stored flat
    // thread-shared vaes
    int chunkId = qureg.chunkId;
    long long int numAmps = qureg.numAmpsPerChunk;
    qreal* stateRe = qureg.stateVec.real;
    qreal* stateIm = qureg.stateVec.imag;
    // thread-private vars
    long long int index, globalAmpInd;
    int r, q, i, found, flatInd;
    qreal phase, norm, prod, dist, c, s, re, im;
    // each thread has a private static array of length >= numRegs (private var-length is illegal)
    long long int phaseInds[MAX_NUM_REGS_APPLY_ARBITRARY_PHASE];
# ifdef _OPENMP
# pragma omp parallel \
    default  (none) \
    shared   (chunkId,numAmps, stateRe,stateIm, qubits,numQubitsPerReg,numRegs,encoding, phaseFuncName,params,numParams, overrideInds,overridePhases,numOverrides, conj) \
    private  (index,globalAmpInd, r,q,i,flatInd, found, phaseInds,phase,norm,prod,dist, c,s,re,im)
# endif
    {
# ifdef _OPENMP
# pragma omp for schedule (static)
# endif
        for (index=0LL; index<numAmps; index++) {
            // determine global amplitude index
            globalAmpInd = chunkId * numAmps + index;
            // determine phase indices
            flatInd = 0;
            for (r=0; r<numRegs; r++) {
                phaseInds[r] = 0LL;
                if (encoding == UNSIGNED) {
                    for (q=0; q<numQubitsPerReg[r]; q++)
                        phaseInds[r] += (1LL << q) * extractBit(qubits[flatInd++], globalAmpInd);   // qubits[flatInd] ~ qubits[r][q]
                }
                else if (encoding == TWOS_COMPLEMENT) {
                    for (q=0; q<numQubitsPerReg[r]-1; q++)
                        phaseInds[r] += (1LL << q) * extractBit(qubits[flatInd++], globalAmpInd);
                    // use final qubit to indicate sign
                    if (extractBit(qubits[flatInd++], globalAmpInd) == 1)
                        phaseInds[r] -= (1LL << (numQubitsPerReg[r]-1));
                }
            }
            // determine if this phase index has an overriden value (i < numOverrides)
            for (i=0; i<numOverrides; i++) {
                found = 1;
                for (r=0; r<numRegs; r++) {
                    if (phaseInds[r] != overrideInds[i*numRegs+r]) {
                        found = 0;
                        break;
                    }
                }
                if (found)
                    break;
            }
            // compute the phase (unless overriden)
            phase = 0;
            if (i < numOverrides)
                phase = overridePhases[i];
            else {
                // compute norm related phases
                if (phaseFuncName == NORM || phaseFuncName == INVERSE_NORM ||
                    phaseFuncName == SCALED_NORM || phaseFuncName == SCALED_INVERSE_NORM ||
                    phaseFuncName == SCALED_INVERSE_SHIFTED_NORM) {
                    norm = 0;
                    if (phaseFuncName == SCALED_INVERSE_SHIFTED_NORM) {
                        for (r=0; r<numRegs; r++)
                            norm += (phaseInds[r] - params[2+r])*(phaseInds[r] - params[2+r]);
                    }
                    else
                        for (r=0; r<numRegs; r++)
                            norm += phaseInds[r]*phaseInds[r];
                    norm = sqrt(norm);
                    if (phaseFuncName == NORM)
                        phase = norm;
                    else if (phaseFuncName == INVERSE_NORM)
                        phase = (norm == 0.)? params[0] : 1/norm;  // smallest non-zero norm is 1
                    else if (phaseFuncName == SCALED_NORM)
                        phase = params[0] * norm;
                    else if (phaseFuncName == SCALED_INVERSE_NORM || phaseFuncName == SCALED_INVERSE_SHIFTED_NORM)
                        phase = (norm <= REAL_EPS)? params[1] : params[0] / norm; // unless shifted closer to zero
                }
                // compute product related phases
                else if (phaseFuncName == PRODUCT || phaseFuncName == INVERSE_PRODUCT ||
                         phaseFuncName == SCALED_PRODUCT || phaseFuncName == SCALED_INVERSE_PRODUCT) {
                    prod = 1;
                    for (r=0; r<numRegs; r++)
                        prod *= phaseInds[r];
                    if (phaseFuncName == PRODUCT)
                        phase = prod;
                    else if (phaseFuncName == INVERSE_PRODUCT)
                        phase = (prod == 0.)? params[0] : 1/prod;  // smallest non-zero product norm is +- 1
                    else if (phaseFuncName == SCALED_PRODUCT)
                        phase = params[0] * prod;
                    else if (phaseFuncName == SCALED_INVERSE_PRODUCT)
                        phase = (prod == 0.)? params[1] : params[0] / prod;
                }
                // compute Euclidean distance related phases
                else if (phaseFuncName == DISTANCE || phaseFuncName == INVERSE_DISTANCE ||
                         phaseFuncName == SCALED_DISTANCE || phaseFuncName == SCALED_INVERSE_DISTANCE ||
                         phaseFuncName == SCALED_INVERSE_SHIFTED_DISTANCE || phaseFuncName == SCALED_INVERSE_SHIFTED_WEIGHTED_DISTANCE) {
                    dist = 0;
                    if (phaseFuncName == SCALED_INVERSE_SHIFTED_DISTANCE) {
                        for (r=0; r<numRegs; r+=2)
                            dist += (phaseInds[r] - phaseInds[r+1] - params[2+r/2])*(phaseInds[r] - phaseInds[r+1] - params[2+r/2]);
                    }
                    else if (phaseFuncName == SCALED_INVERSE_SHIFTED_WEIGHTED_DISTANCE) {
                        for (r=0; r<numRegs; r+=2)
                            dist += params[2+r] * (phaseInds[r] - phaseInds[r+1] - params[2+r+1])*(phaseInds[r] - phaseInds[r+1] - params[2+r+1]);
                    }
                    else
                        for (r=0; r<numRegs; r+=2)
                            dist += (phaseInds[r+1] - phaseInds[r])*(phaseInds[r+1] - phaseInds[r]);
                    // if sqrt() arg would be negative, set it to divergence param
                    if (dist < 0)
                        dist = 0;
                    dist = sqrt(dist);
                    if (phaseFuncName == DISTANCE)
                        phase = dist;
                    else if (phaseFuncName == INVERSE_DISTANCE)
                        phase = (dist == 0.)? params[0] : 1/dist; // smallest non-zero dist is 1
                    else if (phaseFuncName == SCALED_DISTANCE)
                        phase = params[0] * dist;
                    else if (phaseFuncName == SCALED_INVERSE_DISTANCE || phaseFuncName == SCALED_INVERSE_SHIFTED_DISTANCE || phaseFuncName == SCALED_INVERSE_SHIFTED_WEIGHTED_DISTANCE)
                        phase = (dist <= REAL_EPS)? params[1] : params[0] / dist; // unless shifted closer to 0
                }
            }
            // negate phase to conjugate operator
            if (conj)
                phase *= -1;
            // modify amp to amp * exp(i phase)
            c = cos(phase);
            s = sin(phase);
            re = stateRe[index];
            im = stateIm[index];
            // = {re[amp] cos(phase) - im[amp] sin(phase)} + i {re[amp] sin(phase) + im[amp] cos(phase)}
            stateRe[index] = re*c - im*s;
            stateIm[index] = re*s + im*c;
        }
    }
}
References Qureg::chunkId, cudaFree, cudaMalloc, cudaMemcpy, cudaMemcpyHostToDevice, DISTANCE, extractBit(), INVERSE_DISTANCE, INVERSE_NORM, INVERSE_PRODUCT, MAX_NUM_REGS_APPLY_ARBITRARY_PHASE, NORM, Qureg::numAmpsPerChunk, PRODUCT, qreal, SCALED_DISTANCE, SCALED_INVERSE_DISTANCE, SCALED_INVERSE_NORM, SCALED_INVERSE_PRODUCT, SCALED_INVERSE_SHIFTED_DISTANCE, SCALED_INVERSE_SHIFTED_NORM, SCALED_INVERSE_SHIFTED_WEIGHTED_DISTANCE, SCALED_NORM, SCALED_PRODUCT, Qureg::stateVec, TWOS_COMPLEMENT, and UNSIGNED.
Referenced by agnostic_applyQFT(), applyNamedPhaseFunc(), applyNamedPhaseFuncOverrides(), applyParamNamedPhaseFunc(), and applyParamNamedPhaseFuncOverrides().
statevec_applyPauliSum()
void statevec_applyPauliSum (Qureg inQureg, enum pauliOpType * allCodes, qreal * termCoeffs, int numSumTerms, Qureg outQureg)
Definition at line 534 of file QuEST_common.c.
{
    int numQb = inQureg.numQubitsRepresented;
    int targs[100]; // [numQb];
    for (int q=0; q < numQb; q++)
        targs[q] = q;
    statevec_initBlankState(outQureg);
    for (int t=0; t < numSumTerms; t++) {
        Complex coef = (Complex) {.real=termCoeffs[t], .imag=0};
        Complex iden = (Complex) {.real=1, .imag=0};
        Complex zero = (Complex) {.real=0, .imag=0};
        // outQureg += coef paulis(inQureg)
        statevec_applyPauliProd(inQureg, targs, &allCodes[t*numQb], numQb);
        statevec_setWeightedQureg(coef, inQureg, iden, outQureg, zero, outQureg);
        // undero paulis(inQureg), exploiting XX=YY=ZZ=I
        statevec_applyPauliProd(inQureg, targs, &allCodes[t*numQb], numQb);
    }
}
References Qureg::numQubitsRepresented, Complex::real, statevec_applyPauliProd(), statevec_initBlankState(), and statevec_setWeightedQureg().
Referenced by applyPauliHamil(), and applyPauliSum().
statevec_applyPhaseFuncOverrides()
void statevec_applyPhaseFuncOverrides (Qureg qureg, int * qubits, int numQubits, enum bitEncoding encoding, qreal * coeffs, qreal * exponents, int numTerms, long long int * overrideInds, qreal * overridePhases, int numOverrides, int conj)
Definition at line 4299 of file QuEST_cpu.c.
{
    // each node/chunk modifies only local values in an embarrassingly parallel way
    // thread shared vars
    int chunkId = qureg.chunkId;
    long long int numAmps = qureg.numAmpsPerChunk;
    qreal* stateRe = qureg.stateVec.real;
    qreal* stateIm = qureg.stateVec.imag;
    // thread private vars
    long long int index, globalAmpInd, phaseInd;
    int i, t, q;
    qreal phase, c, s, re, im;
# ifdef _OPENMP
# pragma omp parallel \
    default  (none) \
    shared   (chunkId,numAmps, stateRe,stateIm, qubits,numQubits,encoding, coeffs,exponents,numTerms, overrideInds,overridePhases,numOverrides, conj) \
    private  (index, globalAmpInd, phaseInd, i,t,q, phase, c,s,re,im)
# endif
    {
# ifdef _OPENMP
# pragma omp for schedule (static)
# endif
        for (index=0LL; index<numAmps; index++) {
            // determine global amplitude index
            globalAmpInd = chunkId * numAmps + index;
            // determine phase index of {qubits}
            phaseInd = 0LL;
            if (encoding == UNSIGNED) {
                for (q=0; q<numQubits; q++) // use significance order specified by {qubits}
                    phaseInd += (1LL << q) * extractBit(qubits[q], globalAmpInd);
            }
            else if (encoding == TWOS_COMPLEMENT) {
                for (q=0; q<numQubits-1; q++) // use final qubit to indicate sign
                    phaseInd += (1LL << q) * extractBit(qubits[q], globalAmpInd);
                if (extractBit(qubits[numQubits-1], globalAmpInd) == 1)
                    phaseInd -= (1LL << (numQubits-1));
            }
            // determine if this phase index has an overriden value (i < numOverrides)
            for (i=0; i<numOverrides; i++)
                if (phaseInd == overrideInds[i])
                    break;
            // determine phase from {coeffs}, {exponents} (unless overriden)
            phase = 0;
            if (i < numOverrides)
                phase = overridePhases[i];
            else
                for (t=0; t<numTerms; t++)
                    phase += coeffs[t] * pow(phaseInd, exponents[t]);
            // negate phase to conjugate operator
            if (conj)
                phase *= -1;
            // modify amp to amp * exp(i phase)
            c = cos(phase);
            s = sin(phase);
            re = stateRe[index];
            im = stateIm[index];
            // = {re[amp] cos(phase) - im[amp] sin(phase)} + i {re[amp] sin(phase) + im[amp] cos(phase)}
            stateRe[index] = re*c - im*s;
            stateIm[index] = re*s + im*c;
        }
    }
}
References Qureg::chunkId, cudaFree, cudaMalloc, cudaMemcpy, cudaMemcpyHostToDevice, extractBit(), Qureg::numAmpsPerChunk, qreal, Qureg::stateVec, TWOS_COMPLEMENT, and UNSIGNED.
Referenced by applyPhaseFunc(), and applyPhaseFuncOverrides().
statevec_applySubDiagonalOp()
void statevec_applySubDiagonalOp (Qureg qureg, int * targets, SubDiagonalOp op, int conj)
Definition at line 1339 of file QuEST_cpu.c.
{
    // each node/chunk modifies only its values in an embarrassingly parallelisable way
    long long int numLocalAmps = qureg.numAmpsPerChunk;
    qreal* stateRe = qureg.stateVec.real;
    qreal* stateIm = qureg.stateVec.imag;
    qreal* opRe = op.real;
    qreal* opIm = op.imag;
    long long int indPref = qureg.chunkId * numLocalAmps;
    int numTargets = op.numQubits;
    int conjFac = 1;
    if (conj)
        conjFac = -1;
    int t;
    long long int i, j, v;
    qreal elemRe, elemIm, ampRe, ampIm;
# ifdef _OPENMP
# pragma omp parallel \
    shared    (numLocalAmps, indPref, numTargets, targets, stateRe,stateIm) \
    private   (j,i,v,t, elemRe,elemIm, ampRe,ampIm)
# endif
    {
# ifdef _OPENMP
# pragma omp for schedule  (static)
# endif
        for (j=0; j<numLocalAmps; j++) {
            i = indPref | j;
            v = 0;
            for (t=0; t<numTargets; t++)
                v |= extractBit(targets[t], i) << t;
            elemRe = opRe[v];
            elemIm = opIm[v] * conjFac;
            ampRe = stateRe[j];
            ampIm = stateIm[j];
            // (a + b i)(c + d i) = (a c - b d) + i (a d + b c)
            stateRe[j] = ampRe*elemRe - ampIm*elemIm;
            stateIm[j] = ampRe*elemIm + ampIm*elemRe;
        }
    }
}
References Qureg::chunkId, cudaFree, cudaMalloc, cudaMemcpy, cudaMemcpyHostToDevice, extractBit(), SubDiagonalOp::imag, Qureg::numAmpsPerChunk, SubDiagonalOp::numElems, SubDiagonalOp::numQubits, qreal, SubDiagonalOp::real, and Qureg::stateVec.
Referenced by applyGateSubDiagonalOp(), applySubDiagonalOp(), and diagonalUnitary().
statevec_calcExpecDiagonalOp()
Complex statevec_calcExpecDiagonalOp (Qureg qureg, DiagonalOp op)
Definition at line 1602 of file QuEST_cpu_distributed.c.
{
    Complex localExpec = statevec_calcExpecDiagonalOpLocal(qureg, op);
    if (qureg.numChunks == 1)
        return localExpec;
    qreal localReal = localExpec.real;
    qreal localImag = localExpec.imag;
    qreal globalReal, globalImag;
    MPI_Allreduce(&localReal, &globalReal, 1, MPI_QuEST_REAL, MPI_SUM, MPI_COMM_WORLD);
    MPI_Allreduce(&localImag, &globalImag, 1, MPI_QuEST_REAL, MPI_SUM, MPI_COMM_WORLD);
    Complex globalExpec;
    globalExpec.real = globalReal;
    globalExpec.imag = globalImag;
    return globalExpec;
}
References copySharedReduceBlock(), cudaDeviceSynchronize, cudaMemcpy, cudaMemcpyDeviceToHost, DiagonalOp::deviceOperator, Qureg::deviceStateVec, Qureg::firstLevelReduction, Complex::imag, Qureg::numAmpsPerChunk, Qureg::numChunks, qreal, Complex::real, REDUCE_SHARED_SIZE, Qureg::secondLevelReduction, statevec_calcExpecDiagonalOpLocal(), and swapDouble().
Referenced by calcExpecDiagonalOp().
statevec_calcExpecPauliProd()
qreal statevec_calcExpecPauliProd (Qureg qureg, int * targetQubits, enum pauliOpType * pauliCodes, int numTargets, Qureg workspace)
Definition at line 505 of file QuEST_common.c.
{
    statevec_cloneQureg(workspace, qureg);
    statevec_applyPauliProd(workspace, targetQubits, pauliCodes, numTargets);
    // compute the expected value
    qreal value;
    if (qureg.isDensityMatrix)
        value = densmatr_calcTotalProb(workspace); // Trace(ops qureg)
    else
        value = statevec_calcInnerProduct(workspace, qureg).real; // <qureg|ops|qureg>
    return value;
}
References densmatr_calcTotalProb(), Qureg::isDensityMatrix, qreal, Complex::real, statevec_applyPauliProd(), statevec_calcInnerProduct(), and statevec_cloneQureg().
Referenced by calcExpecPauliProd(), and statevec_calcExpecPauliSum().
statevec_calcExpecPauliSum()
qreal statevec_calcExpecPauliSum (Qureg qureg, enum pauliOpType * allCodes, qreal * termCoeffs, int numSumTerms, Qureg workspace)
Definition at line 520 of file QuEST_common.c.
{
    int numQb = qureg.numQubitsRepresented;
    int targs[100]; // [numQb];
    for (int q=0; q < numQb; q++)
        targs[q] = q;
    qreal value = 0;
    for (int t=0; t < numSumTerms; t++)
        value += termCoeffs[t] * statevec_calcExpecPauliProd(qureg, targs, &allCodes[t*numQb], numQb, workspace);
    return value;
}
References Qureg::numQubitsRepresented, qreal, and statevec_calcExpecPauliProd().
Referenced by calcExpecPauliHamil(), and calcExpecPauliSum().
statevec_calcFidelity()
qreal statevec_calcFidelity (Qureg qureg, Qureg pureState)
Definition at line 376 of file QuEST_common.c.
{
    Complex innerProd = statevec_calcInnerProduct(qureg, pureState);
    qreal innerProdMag = innerProd.real*innerProd.real + innerProd.imag*innerProd.imag;
    return innerProdMag;
}
References Complex::imag, qreal, Complex::real, and statevec_calcInnerProduct().
Referenced by calcFidelity().
statevec_calcInnerProduct()
Complex statevec_calcInnerProduct (Qureg bra, Qureg ket)
Terrible code which unnecessarily individually computes and sums the real and imaginary components of the inner product, so as to not have to worry about keeping the sums separated during reduction.
Truly disgusting, probably doubles runtime, please fix.
Todo:
could even do the kernel twice, storing real in bra.reduc and imag in ket.reduc?
Definition at line 35 of file QuEST_cpu_distributed.c.
{
    Complex localInnerProd = statevec_calcInnerProductLocal(bra, ket);
    if (bra.numChunks == 1)
        return localInnerProd;
    qreal localReal = localInnerProd.real;
    qreal localImag = localInnerProd.imag;
    qreal globalReal, globalImag;
    MPI_Allreduce(&localReal, &globalReal, 1, MPI_QuEST_REAL, MPI_SUM, MPI_COMM_WORLD);
    MPI_Allreduce(&localImag, &globalImag, 1, MPI_QuEST_REAL, MPI_SUM, MPI_COMM_WORLD);
    Complex globalInnerProd;
    globalInnerProd.real = globalReal;
    globalInnerProd.imag = globalImag;
    return globalInnerProd;
}
References copySharedReduceBlock(), cudaDeviceSynchronize, cudaMemcpy, cudaMemcpyDeviceToHost, Qureg::deviceStateVec, Qureg::firstLevelReduction, Complex::imag, Qureg::numAmpsPerChunk, Qureg::numChunks, qreal, Complex::real, REDUCE_SHARED_SIZE, Qureg::secondLevelReduction, statevec_calcInnerProductLocal(), and swapDouble().
Referenced by calcInnerProduct(), statevec_calcExpecPauliProd(), and statevec_calcFidelity().
statevec_calcProbOfAllOutcomes()
void statevec_calcProbOfAllOutcomes (qreal * retProbs, Qureg qureg, int * qubits, int numQubits)
Definition at line 1342 of file QuEST_cpu_distributed.c.
{
    // each node populates retProbs with contributions from the subset of amps in each
    statevec_calcProbOfAllOutcomesLocal(retProbs, qureg, qubits, numQubits);
    // then, retProbs are summed element-wise
    MPI_Allreduce(MPI_IN_PLACE, retProbs, 1LL<<numQubits, MPI_QuEST_REAL, MPI_SUM, MPI_COMM_WORLD);
}
References cudaFree, cudaMalloc, cudaMemcpy, cudaMemcpyDeviceToHost, cudaMemcpyHostToDevice, cudaMemset, Qureg::numAmpsPerChunk, qreal, and statevec_calcProbOfAllOutcomesLocal().
Referenced by calcProbOfAllOutcomes().
statevec_calcProbOfOutcome()
qreal statevec_calcProbOfOutcome (Qureg qureg, int measureQubit, int outcome)
Definition at line 1314 of file QuEST_cpu_distributed.c.
{
    qreal stateProb=0, totalStateProb=0;
    int skipValuesWithinRank = halfMatrixBlockFitsInChunk(qureg.numAmpsPerChunk, measureQubit);
    if (skipValuesWithinRank) {
        stateProb = statevec_findProbabilityOfZeroLocal(qureg, measureQubit);
    } else {
        if (!isChunkToSkipInFindPZero(qureg.chunkId, qureg.numAmpsPerChunk, measureQubit)){
            stateProb = statevec_findProbabilityOfZeroDistributed(qureg);
        } else stateProb = 0;
    }
    MPI_Allreduce(&stateProb, &totalStateProb, 1, MPI_QuEST_REAL, MPI_SUM, MPI_COMM_WORLD);
    if (outcome==1) totalStateProb = 1.0 - totalStateProb;
    return totalStateProb;
}
References Qureg::chunkId, halfMatrixBlockFitsInChunk(), isChunkToSkipInFindPZero(), Qureg::numAmpsPerChunk, qreal, statevec_findProbabilityOfZero(), statevec_findProbabilityOfZeroDistributed(), and statevec_findProbabilityOfZeroLocal().
Referenced by calcProbOfOutcome(), collapseToOutcome(), and statevec_measureWithStats().
statevec_calcTotalProb()
qreal statevec_calcTotalProb (Qureg qureg)
Definition at line 90 of file QuEST_cpu_distributed.c.
{
    // Implemented using Kahan summation for greater accuracy at a slight floating
    //   point operation overhead. For more details see https://en.wikipedia.org/wiki/Kahan_summation_algorithm
    qreal pTotal=0;
    qreal y, t, c;
    qreal allRankTotals=0;
    long long int index;
    long long int numAmpsPerRank = qureg.numAmpsPerChunk;
    c = 0.0;
    for (index=0; index<numAmpsPerRank; index++){
        // Perform pTotal+=qureg.stateVec.real[index]*qureg.stateVec.real[index]; by Kahan
        y = qureg.stateVec.real[index]*qureg.stateVec.real[index] - c;
        t = pTotal + y;
        // Don't change the bracketing on the following line
        c = ( t - pTotal ) - y;
        pTotal = t;
        // Perform pTotal+=qureg.stateVec.imag[index]*qureg.stateVec.imag[index]; by Kahan
        y = qureg.stateVec.imag[index]*qureg.stateVec.imag[index] - c;
        t = pTotal + y;
        // Don't change the bracketing on the following line
        c = ( t - pTotal ) - y;
        pTotal = t;
    }
    if (qureg.numChunks>1)
                MPI_Allreduce(&pTotal, &allRankTotals, 1, MPI_QuEST_REAL, MPI_SUM, MPI_COMM_WORLD);
    else
                allRankTotals=pTotal;
    return allRankTotals;
}
References copyStateFromGPU(), Qureg::numAmpsPerChunk, Qureg::numChunks, qreal, and Qureg::stateVec.
Referenced by calcTotalProb().
statevec_cloneQureg()
void statevec_cloneQureg (Qureg targetQureg, Qureg copyQureg)
works for both statevectors and density matrices
Definition at line 1611 of file QuEST_cpu.c.
{
    // registers are equal sized, so nodes hold the same state-vector partitions
    long long int stateVecSize;
    long long int index;
    // dimension of the state vector
    stateVecSize = targetQureg.numAmpsPerChunk;
    // Can't use qureg->stateVec as a private OMP var
    qreal *targetStateVecReal = targetQureg.stateVec.real;
    qreal *targetStateVecImag = targetQureg.stateVec.imag;
    qreal *copyStateVecReal = copyQureg.stateVec.real;
    qreal *copyStateVecImag = copyQureg.stateVec.imag;
    // initialise the state to |0000..0000>
# ifdef _OPENMP
# pragma omp parallel \
    default  (none) \
    shared   (stateVecSize, targetStateVecReal, targetStateVecImag, copyStateVecReal, copyStateVecImag) \
    private  (index)
# endif
    {
# ifdef _OPENMP
# pragma omp for schedule (static)
# endif
        for (index=0; index<stateVecSize; index++) {
            targetStateVecReal[index] = copyStateVecReal[index];
            targetStateVecImag[index] = copyStateVecImag[index];
        }
    }
}
References cudaDeviceSynchronize, cudaMemcpy, cudaMemcpyDeviceToDevice, Qureg::deviceStateVec, Qureg::numAmpsPerChunk, qreal, and Qureg::stateVec.
Referenced by cloneQureg(), createCloneQureg(), initPureState(), and statevec_calcExpecPauliProd().
statevec_collapseToKnownProbOutcome()
void statevec_collapseToKnownProbOutcome (Qureg qureg, int measureQubit, int outcome, qreal outcomeProb)
Definition at line 1370 of file QuEST_cpu_distributed.c.
{
    int skipValuesWithinRank = halfMatrixBlockFitsInChunk(qureg.numAmpsPerChunk, measureQubit);
    if (skipValuesWithinRank) {
        statevec_collapseToKnownProbOutcomeLocal(qureg, measureQubit, outcome, totalStateProb);
    } else {
        if (!isChunkToSkipInFindPZero(qureg.chunkId, qureg.numAmpsPerChunk, measureQubit)){
            // chunk has amps for q=0
            if (outcome==0) statevec_collapseToKnownProbOutcomeDistributedRenorm(qureg, measureQubit,
                    totalStateProb);
            else statevec_collapseToOutcomeDistributedSetZero(qureg);
        } else {
            // chunk has amps for q=1
            if (outcome==1) statevec_collapseToKnownProbOutcomeDistributedRenorm(qureg, measureQubit,
                    totalStateProb);
            else statevec_collapseToOutcomeDistributedSetZero(qureg);
        }
    }
}
References Qureg::chunkId, halfMatrixBlockFitsInChunk(), isChunkToSkipInFindPZero(), Qureg::numAmpsPerChunk, qreal, statevec_collapseToKnownProbOutcomeDistributedRenorm(), statevec_collapseToKnownProbOutcomeLocal(), and statevec_collapseToOutcomeDistributedSetZero().
Referenced by applyProjector(), collapseToOutcome(), and statevec_measureWithStats().
statevec_compactUnitary()
void statevec_compactUnitary (Qureg qureg, int targetQubit, Complex alpha, Complex beta)
Definition at line 860 of file QuEST_cpu_distributed.c.
{
    // flag to require memory exchange. 1: an entire block fits on one rank, 0: at most half a block fits on one rank
    int useLocalDataOnly = halfMatrixBlockFitsInChunk(qureg.numAmpsPerChunk, targetQubit);
    Complex rot1, rot2;
    // rank's chunk is in upper half of block
    int rankIsUpper;
    int pairRank; // rank of corresponding chunk
    if (useLocalDataOnly){
        // all values required to update state vector lie in this rank
        statevec_compactUnitaryLocal(qureg, targetQubit, alpha, beta);
    } else {
        // need to get corresponding chunk of state vector from other rank
        rankIsUpper = chunkIsUpper(qureg.chunkId, qureg.numAmpsPerChunk, targetQubit);
        getRotAngle(rankIsUpper, &rot1, &rot2, alpha, beta);
        pairRank = getChunkPairId(rankIsUpper, qureg.chunkId, qureg.numAmpsPerChunk, targetQubit);
        // get corresponding values from my pair
        exchangeStateVectors(qureg, pairRank);
        // this rank's values are either in the upper of lower half of the block.
        // send values to compactUnitaryDistributed in the correct order
        if (rankIsUpper){
            statevec_compactUnitaryDistributed(qureg,rot1,rot2,
                    qureg.stateVec, //upper
                    qureg.pairStateVec, //lower
                    qureg.stateVec); //output
        } else {
            statevec_compactUnitaryDistributed(qureg,rot1,rot2,
                    qureg.pairStateVec, //upper
                    qureg.stateVec, //lower
                    qureg.stateVec); //output
        }
    }
}
References Qureg::chunkId, chunkIsUpper(), exchangeStateVectors(), getChunkPairId(), getRotAngle(), halfMatrixBlockFitsInChunk(), Qureg::numAmpsPerChunk, Qureg::pairStateVec, qreal, Qureg::stateVec, statevec_compactUnitaryDistributed(), and statevec_compactUnitaryLocal().
Referenced by compactUnitary(), statevec_multiRotatePauli(), statevec_rotateAroundAxis(), and statevec_rotateAroundAxisConj().
statevec_compareStates()
int statevec_compareStates (Qureg mq1, Qureg mq2, qreal precision)
Definition at line 1772 of file QuEST_cpu.c.
{
    qreal diff;
    long long int chunkSize = mq1.numAmpsPerChunk;
    for (long long int i=0; i<chunkSize; i++){
        diff = absReal(mq1.stateVec.real[i] - mq2.stateVec.real[i]);
        if (diff>precision) return 0;
        diff = absReal(mq1.stateVec.imag[i] - mq2.stateVec.imag[i]);
        if (diff>precision) return 0;
    }
    return 1;
}
References copyStateFromGPU(), Qureg::numAmpsPerChunk, qreal, and Qureg::stateVec.
Referenced by compareStates().
statevec_controlledCompactUnitary()
void statevec_controlledCompactUnitary (Qureg qureg, int controlQubit, int targetQubit, Complex alpha, Complex beta)
Definition at line 936 of file QuEST_cpu_distributed.c.
{
    // flag to require memory exchange. 1: an entire block fits on one rank, 0: at most half a block fits on one rank
    int useLocalDataOnly = halfMatrixBlockFitsInChunk(qureg.numAmpsPerChunk, targetQubit);
    Complex rot1, rot2;
    // rank's chunk is in upper half of block
    int rankIsUpper;
    int pairRank; // rank of corresponding chunk
    if (useLocalDataOnly){
        // all values required to update state vector lie in this rank
        statevec_controlledCompactUnitaryLocal(qureg, controlQubit, targetQubit, alpha, beta);
    } else {
        // need to get corresponding chunk of state vector from other rank
        rankIsUpper = chunkIsUpper(qureg.chunkId, qureg.numAmpsPerChunk, targetQubit);
        getRotAngle(rankIsUpper, &rot1, &rot2, alpha, beta);
        pairRank = getChunkPairId(rankIsUpper, qureg.chunkId, qureg.numAmpsPerChunk, targetQubit);
        //printf("%d rank has pair rank: %d\n", qureg.rank, pairRank);
        // get corresponding values from my pair
        exchangeStateVectors(qureg, pairRank);
        // this rank's values are either in the upper of lower half of the block. send values to controlledCompactUnitaryDistributed
        // in the correct order
        if (rankIsUpper){
            statevec_controlledCompactUnitaryDistributed(qureg,controlQubit,rot1,rot2,
                    qureg.stateVec, //upper
                    qureg.pairStateVec, //lower
                    qureg.stateVec); //output
        } else {
            statevec_controlledCompactUnitaryDistributed(qureg,controlQubit,rot1,rot2,
                    qureg.pairStateVec, //upper
                    qureg.stateVec, //lower
                    qureg.stateVec); //output
        }
    }
}
References Qureg::chunkId, chunkIsUpper(), exchangeStateVectors(), getChunkPairId(), getRotAngle(), halfMatrixBlockFitsInChunk(), Qureg::numAmpsPerChunk, Qureg::pairStateVec, qreal, Qureg::stateVec, statevec_controlledCompactUnitaryDistributed(), and statevec_controlledCompactUnitaryLocal().
Referenced by controlledCompactUnitary(), statevec_controlledRotateAroundAxis(), and statevec_controlledRotateAroundAxisConj().
statevec_controlledMultiQubitUnitary()
void statevec_controlledMultiQubitUnitary (Qureg qureg, int ctrl, int * targets, int numTargets, ComplexMatrixN u)
Definition at line 575 of file QuEST_common.c.
{
    long long int ctrlMask = 1LL << ctrl;
    statevec_multiControlledMultiQubitUnitary(qureg, ctrlMask, targets, numTargets, u);
}
References statevec_multiControlledMultiQubitUnitary().
Referenced by controlledMultiQubitUnitary().
statevec_controlledNot()
void statevec_controlledNot (Qureg qureg, int controlQubit, int targetQubit)
Definition at line 1077 of file QuEST_cpu_distributed.c.
{
    // flag to require memory exchange. 1: an entire block fits on one rank, 0: at most half a block fits on one rank
    int useLocalDataOnly = halfMatrixBlockFitsInChunk(qureg.numAmpsPerChunk, targetQubit);
    int rankIsUpper;    // rank's chunk is in upper half of block
    int pairRank;               // rank of corresponding chunk
    if (useLocalDataOnly){
        // all values required to update state vector lie in this rank
        statevec_controlledNotLocal(qureg, controlQubit, targetQubit);
    } else {
        // need to get corresponding chunk of state vector from other rank
        rankIsUpper = chunkIsUpper(qureg.chunkId, qureg.numAmpsPerChunk, targetQubit);
        pairRank = getChunkPairId(rankIsUpper, qureg.chunkId, qureg.numAmpsPerChunk, targetQubit);
        // get corresponding values from my pair
        exchangeStateVectors(qureg, pairRank);
        statevec_controlledNotDistributed(qureg,controlQubit,
                    qureg.pairStateVec, //in
                    qureg.stateVec); //out
    }
}
References Qureg::chunkId, chunkIsUpper(), exchangeStateVectors(), getChunkPairId(), halfMatrixBlockFitsInChunk(), Qureg::numAmpsPerChunk, Qureg::pairStateVec, qreal, Qureg::stateVec, statevec_controlledNotDistributed(), and statevec_controlledNotLocal().
Referenced by controlledNot().
statevec_controlledPauliY()
void statevec_controlledPauliY (Qureg qureg, int controlQubit, int targetQubit)
Definition at line 1194 of file QuEST_cpu_distributed.c.
{
        int conjFac = 1;
    // flag to require memory exchange. 1: an entire block fits on one rank, 0: at most half a block fits on one rank
    int useLocalDataOnly = halfMatrixBlockFitsInChunk(qureg.numAmpsPerChunk, targetQubit);
    int rankIsUpper;    // rank's chunk is in upper half of block
    int pairRank;               // rank of corresponding chunk
    if (useLocalDataOnly){
        // all values required to update state vector lie in this rank
        statevec_controlledPauliYLocal(qureg, controlQubit, targetQubit, conjFac);
    } else {
        // need to get corresponding chunk of state vector from other rank
        rankIsUpper = chunkIsUpper(qureg.chunkId, qureg.numAmpsPerChunk, targetQubit);
        pairRank = getChunkPairId(rankIsUpper, qureg.chunkId, qureg.numAmpsPerChunk, targetQubit);
        // get corresponding values from my pair
        exchangeStateVectors(qureg, pairRank);
        // this rank's values are either in the upper of lower half of the block
        if (rankIsUpper){
            statevec_controlledPauliYDistributed(qureg,controlQubit,
                    qureg.pairStateVec, //in
                    qureg.stateVec,
                                        conjFac); //out
        } else {
            statevec_controlledPauliYDistributed(qureg,controlQubit,
                    qureg.pairStateVec, //in
                    qureg.stateVec,
                                        - conjFac); //out
        }
    }
}
References Qureg::chunkId, chunkIsUpper(), exchangeStateVectors(), getChunkPairId(), halfMatrixBlockFitsInChunk(), Qureg::numAmpsPerChunk, Qureg::pairStateVec, qreal, Qureg::stateVec, statevec_controlledPauliYDistributed(), and statevec_controlledPauliYLocal().
Referenced by controlledPauliY().
statevec_controlledPauliYConj()
void statevec_controlledPauliYConj (Qureg qureg, int controlQubit, int targetQubit)
Definition at line 1227 of file QuEST_cpu_distributed.c.
{
        int conjFac = -1;
    // flag to require memory exchange. 1: an entire block fits on one rank, 0: at most half a block fits on one rank
    int useLocalDataOnly = halfMatrixBlockFitsInChunk(qureg.numAmpsPerChunk, targetQubit);
    int rankIsUpper;    // rank's chunk is in upper half of block
    int pairRank;               // rank of corresponding chunk
    if (useLocalDataOnly){
        // all values required to update state vector lie in this rank
        statevec_controlledPauliYLocal(qureg, controlQubit, targetQubit, conjFac);
    } else {
        // need to get corresponding chunk of state vector from other rank
        rankIsUpper = chunkIsUpper(qureg.chunkId, qureg.numAmpsPerChunk, targetQubit);
        pairRank = getChunkPairId(rankIsUpper, qureg.chunkId, qureg.numAmpsPerChunk, targetQubit);
        // get corresponding values from my pair
        exchangeStateVectors(qureg, pairRank);
        // this rank's values are either in the upper of lower half of the block
        if (rankIsUpper){
            statevec_controlledPauliYDistributed(qureg,controlQubit,
                    qureg.pairStateVec, //in
                    qureg.stateVec,
                                        conjFac); //out
        } else {
            statevec_controlledPauliYDistributed(qureg,controlQubit,
                    qureg.pairStateVec, //in
                    qureg.stateVec,
                                        - conjFac); //out
        }
    }
}
References Qureg::chunkId, chunkIsUpper(), exchangeStateVectors(), getChunkPairId(), halfMatrixBlockFitsInChunk(), Qureg::numAmpsPerChunk, Qureg::pairStateVec, qreal, Qureg::stateVec, statevec_controlledPauliYDistributed(), and statevec_controlledPauliYLocal().
Referenced by controlledPauliY().
statevec_controlledPhaseFlip()
void statevec_controlledPhaseFlip (Qureg qureg, int idQubit1, int idQubit2)
Definition at line 3718 of file QuEST_cpu.c.
{
    long long int index;
    long long int stateVecSize;
    int bit1, bit2;
    long long int chunkSize=qureg.numAmpsPerChunk;
    long long int chunkId=qureg.chunkId;
    // dimension of the state vector
    stateVecSize = qureg.numAmpsPerChunk;
    qreal *stateVecReal = qureg.stateVec.real;
    qreal *stateVecImag = qureg.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel for \
    default  (none) \
    shared   (stateVecSize, stateVecReal,stateVecImag, chunkId,chunkSize,idQubit1,idQubit2 ) \
    private  (index,bit1,bit2) \
    schedule (static)
# endif
    for (index=0; index<stateVecSize; index++) {
        bit1 = extractBit (idQubit1, index+chunkId*chunkSize);
        bit2 = extractBit (idQubit2, index+chunkId*chunkSize);
        if (bit1 && bit2) {
            stateVecReal [index] = - stateVecReal [index];
            stateVecImag [index] = - stateVecImag [index];
        }
    }
}
References Qureg::chunkId, extractBit(), Qureg::numAmpsPerChunk, qreal, and Qureg::stateVec.
Referenced by controlledPhaseFlip().
statevec_controlledPhaseShift()
void statevec_controlledPhaseShift (Qureg qureg, int idQubit1, int idQubit2, qreal angle)
Definition at line 3257 of file QuEST_cpu.c.
{
    long long int index;
    long long int stateVecSize;
    int bit1, bit2;
    long long int chunkSize=qureg.numAmpsPerChunk;
    long long int chunkId=qureg.chunkId;
    // dimension of the state vector
    stateVecSize = qureg.numAmpsPerChunk;
    qreal *stateVecReal = qureg.stateVec.real;
    qreal *stateVecImag = qureg.stateVec.imag;
    qreal stateRealLo, stateImagLo;
    qreal cosAngle = cos(angle);
    qreal sinAngle = sin(angle);
# ifdef _OPENMP
# pragma omp parallel for \
    default  (none)              \
    shared   (stateVecSize, stateVecReal,stateVecImag, chunkId,chunkSize, \
                idQubit1,idQubit2,cosAngle,sinAngle ) \
    private  (index,bit1,bit2,stateRealLo,stateImagLo) \
    schedule (static)
# endif
    for (index=0; index<stateVecSize; index++) {
        bit1 = extractBit (idQubit1, index+chunkId*chunkSize);
        bit2 = extractBit (idQubit2, index+chunkId*chunkSize);
        if (bit1 && bit2) {
            stateRealLo = stateVecReal[index];
            stateImagLo = stateVecImag[index];
            stateVecReal[index] = cosAngle*stateRealLo - sinAngle*stateImagLo;
            stateVecImag[index] = sinAngle*stateRealLo + cosAngle*stateImagLo;
        }
    }
}
References Qureg::chunkId, extractBit(), Qureg::numAmpsPerChunk, qreal, and Qureg::stateVec.
Referenced by controlledPhaseShift().
statevec_controlledRotateAroundAxis()
void statevec_controlledRotateAroundAxis (Qureg qureg, int controlQubit, int targetQubit, qreal angle, Vector axis)
Definition at line 326 of file QuEST_common.c.
{
    Complex alpha, beta;
    getComplexPairFromRotation(angle, axis, &alpha, &beta);
    statevec_controlledCompactUnitary(qureg, controlQubit, targetQubit, alpha, beta);
}
References getComplexPairFromRotation(), and statevec_controlledCompactUnitary().
Referenced by controlledRotateAroundAxis(), statevec_controlledRotateX(), statevec_controlledRotateY(), and statevec_controlledRotateZ().
statevec_controlledRotateAroundAxisConj()
void statevec_controlledRotateAroundAxisConj (Qureg qureg, int controlQubit, int targetQubit, qreal angle, Vector axis)
Definition at line 333 of file QuEST_common.c.
{
    Complex alpha, beta;
    getComplexPairFromRotation(angle, axis, &alpha, &beta);
    alpha.imag *= -1;
    beta.imag *= -1;
    statevec_controlledCompactUnitary(qureg, controlQubit, targetQubit, alpha, beta);
}
References getComplexPairFromRotation(), Complex::imag, and statevec_controlledCompactUnitary().
Referenced by controlledRotateAroundAxis().
statevec_controlledRotateX()
void statevec_controlledRotateX (Qureg qureg, int controlQubit, int targetQubit, qreal angle)
Definition at line 342 of file QuEST_common.c.
{
    Vector unitAxis = {1, 0, 0};
    statevec_controlledRotateAroundAxis(qureg, controlQubit, targetQubit, angle, unitAxis);
}
References statevec_controlledRotateAroundAxis().
Referenced by controlledRotateX().
statevec_controlledRotateY()
void statevec_controlledRotateY (Qureg qureg, int controlQubit, int targetQubit, qreal angle)
Definition at line 348 of file QuEST_common.c.
{
    Vector unitAxis = {0, 1, 0};
    statevec_controlledRotateAroundAxis(qureg, controlQubit, targetQubit, angle, unitAxis);
}
References statevec_controlledRotateAroundAxis().
Referenced by controlledRotateY().
statevec_controlledRotateZ()
void statevec_controlledRotateZ (Qureg qureg, int controlQubit, int targetQubit, qreal angle)
Definition at line 354 of file QuEST_common.c.
{
    Vector unitAxis = {0, 0, 1};
    statevec_controlledRotateAroundAxis(qureg, controlQubit, targetQubit, angle, unitAxis);
}
References statevec_controlledRotateAroundAxis().
Referenced by controlledRotateZ().
statevec_controlledTwoQubitUnitary()
void statevec_controlledTwoQubitUnitary (Qureg qureg, int controlQubit, int targetQubit1, int targetQubit2, ComplexMatrix4 u)
Definition at line 563 of file QuEST_common.c.
{
    long long int ctrlMask = 1LL << controlQubit;
    statevec_multiControlledTwoQubitUnitary(qureg, ctrlMask, targetQubit1, targetQubit2, u);
}
References statevec_multiControlledTwoQubitUnitary().
Referenced by controlledTwoQubitUnitary().
statevec_controlledUnitary()
void statevec_controlledUnitary (Qureg qureg, int controlQubit, int targetQubit, ComplexMatrix2 u)
Definition at line 974 of file QuEST_cpu_distributed.c.
{
    // flag to require memory exchange. 1: an entire block fits on one rank, 0: at most half a block fits on one rank
    int useLocalDataOnly = halfMatrixBlockFitsInChunk(qureg.numAmpsPerChunk, targetQubit);
    Complex rot1, rot2;
    // rank's chunk is in upper half of block
    int rankIsUpper;
    int pairRank; // rank of corresponding chunk
    if (useLocalDataOnly){
        // all values required to update state vector lie in this rank
        statevec_controlledUnitaryLocal(qureg, controlQubit, targetQubit, u);
    } else {
        // need to get corresponding chunk of state vector from other rank
        rankIsUpper = chunkIsUpper(qureg.chunkId, qureg.numAmpsPerChunk, targetQubit);
        getRotAngleFromUnitaryMatrix(rankIsUpper, &rot1, &rot2, u);
        pairRank = getChunkPairId(rankIsUpper, qureg.chunkId, qureg.numAmpsPerChunk, targetQubit);
        //printf("%d rank has pair rank: %d\n", qureg.rank, pairRank);
        // get corresponding values from my pair
        exchangeStateVectors(qureg, pairRank);
        // this rank's values are either in the upper of lower half of the block. send values to controlledUnitaryDistributed
        // in the correct order
        if (rankIsUpper){
            statevec_controlledUnitaryDistributed(qureg,controlQubit,rot1,rot2,
                    qureg.stateVec, //upper
                    qureg.pairStateVec, //lower
                    qureg.stateVec); //output
        } else {
            statevec_controlledUnitaryDistributed(qureg,controlQubit,rot1,rot2,
                    qureg.pairStateVec, //upper
                    qureg.stateVec, //lower
                    qureg.stateVec); //output
        }
    }
}
References Qureg::chunkId, chunkIsUpper(), exchangeStateVectors(), getChunkPairId(), getRotAngleFromUnitaryMatrix(), halfMatrixBlockFitsInChunk(), Qureg::numAmpsPerChunk, Qureg::pairStateVec, qreal, Qureg::stateVec, statevec_controlledUnitaryDistributed(), and statevec_controlledUnitaryLocal().
Referenced by controlledUnitary().
statevec_copySubstateFromGPU()
void statevec_copySubstateFromGPU (Qureg qureg, long long int startInd, long long int numAmps)
Definition at line 52 of file QuEST_cpu.c.
{
}
References cudaDeviceSynchronize, cudaMemcpy, cudaMemcpyDeviceToHost, DEBUG, Qureg::deviceStateVec, and Qureg::stateVec.
Referenced by copySubstateFromGPU().
statevec_copySubstateToGPU()
void statevec_copySubstateToGPU (Qureg qureg, long long int startInd, long long int numAmps)
Definition at line 49 of file QuEST_cpu.c.
{
}
References cudaMemcpy, cudaMemcpyHostToDevice, DEBUG, Qureg::deviceStateVec, and Qureg::stateVec.
Referenced by copySubstateToGPU().
statevec_createQureg()
void statevec_createQureg (Qureg * qureg, int numQubits, QuESTEnv env)
Definition at line 1296 of file QuEST_cpu.c.
{
    long long int numAmps = 1LL << numQubits;
    long long int numAmpsPerRank = numAmps/env.numRanks;
    validateMemoryAllocationSize(numAmpsPerRank, __func__);
    size_t arrSize = (size_t) (numAmpsPerRank * sizeof(*(qureg->stateVec.real)));
    qureg->stateVec.real = malloc(arrSize);
    qureg->stateVec.imag = malloc(arrSize);
    if (env.numRanks>1){
        qureg->pairStateVec.real = malloc(arrSize);
        qureg->pairStateVec.imag = malloc(arrSize);
    }
    qureg->numQubitsInStateVec = numQubits;
    qureg->numAmpsTotal = numAmps;
    qureg->numAmpsPerChunk = numAmpsPerRank;
    qureg->chunkId = env.rank;
    qureg->numChunks = env.numRanks;
    qureg->isDensityMatrix = 0;
    validateQuregAllocation(qureg, env, __func__);
}
References Qureg::chunkId, cudaMalloc, Qureg::deviceStateVec, Qureg::firstLevelReduction, Qureg::isDensityMatrix, Qureg::numAmpsPerChunk, Qureg::numAmpsTotal, Qureg::numChunks, Qureg::numQubitsInStateVec, QuESTEnv::numRanks, Qureg::pairStateVec, qreal, QuESTEnv::rank, REDUCE_SHARED_SIZE, Qureg::secondLevelReduction, Qureg::stateVec, validateMemoryAllocationSize(), validateQuregAllocation(), and validateQuregGPUAllocation().
Referenced by createCloneQureg(), createDensityQureg(), and createQureg().
statevec_destroyQureg()
void statevec_destroyQureg (Qureg qureg, QuESTEnv env)
Definition at line 1321 of file QuEST_cpu.c.
{
    qureg.numQubitsInStateVec = 0;
    qureg.numAmpsTotal = 0;
    qureg.numAmpsPerChunk = 0;
    free(qureg.stateVec.real);
    free(qureg.stateVec.imag);
    if (env.numRanks>1){
        free(qureg.pairStateVec.real);
        free(qureg.pairStateVec.imag);
    }
    qureg.stateVec.real = NULL;
    qureg.stateVec.imag = NULL;
    qureg.pairStateVec.real = NULL;
    qureg.pairStateVec.imag = NULL;
}
References cudaFree, Qureg::deviceStateVec, Qureg::firstLevelReduction, Qureg::numAmpsPerChunk, Qureg::numAmpsTotal, Qureg::numQubitsInStateVec, QuESTEnv::numRanks, Qureg::pairStateVec, Qureg::secondLevelReduction, and Qureg::stateVec.
Referenced by destroyQureg().
statevec_getImagAmp()
qreal statevec_getImagAmp (Qureg qureg, long long int index)
Definition at line 224 of file QuEST_cpu_distributed.c.
{
    int chunkId = getChunkIdFromIndex(qureg, index);
    qreal el;
    if (qureg.chunkId==chunkId){
        el = qureg.stateVec.imag[index-chunkId*qureg.numAmpsPerChunk];
    }
    MPI_Bcast(&el, 1, MPI_QuEST_REAL, chunkId, MPI_COMM_WORLD);
    return el;
}
References Qureg::chunkId, cudaMemcpy, cudaMemcpyDeviceToHost, Qureg::deviceStateVec, getChunkIdFromIndex(), Qureg::numAmpsPerChunk, qreal, and Qureg::stateVec.
Referenced by getAmp(), getDensityAmp(), getImagAmp(), and statevec_getProbAmp().
statevec_getProbAmp()
qreal statevec_getProbAmp (Qureg qureg, long long int index)
Definition at line 244 of file QuEST_common.c.
{
    qreal real = statevec_getRealAmp(qureg, index);
    qreal imag = statevec_getImagAmp(qureg, index);
    return real*real + imag*imag;
}
References qreal, statevec_getImagAmp(), and statevec_getRealAmp().
Referenced by getProbAmp().
statevec_getRealAmp()
qreal statevec_getRealAmp (Qureg qureg, long long int index)
Definition at line 214 of file QuEST_cpu_distributed.c.
{
    int chunkId = getChunkIdFromIndex(qureg, index);
    qreal el;
    if (qureg.chunkId==chunkId){
        el = qureg.stateVec.real[index-chunkId*qureg.numAmpsPerChunk];
    }
    MPI_Bcast(&el, 1, MPI_QuEST_REAL, chunkId, MPI_COMM_WORLD);
    return el;
}
References Qureg::chunkId, cudaMemcpy, cudaMemcpyDeviceToHost, Qureg::deviceStateVec, getChunkIdFromIndex(), Qureg::numAmpsPerChunk, qreal, and Qureg::stateVec.
Referenced by getAmp(), getDensityAmp(), getRealAmp(), and statevec_getProbAmp().
statevec_hadamard()
void statevec_hadamard (Qureg qureg, int targetQubit)
Definition at line 1260 of file QuEST_cpu_distributed.c.
{
    // flag to require memory exchange. 1: an entire block fits on one rank, 0: at most half a block fits on one rank
    int useLocalDataOnly = halfMatrixBlockFitsInChunk(qureg.numAmpsPerChunk, targetQubit);
    // rank's chunk is in upper half of block
    int rankIsUpper;
    int pairRank; // rank of corresponding chunk
    if (useLocalDataOnly){
        // all values required to update state vector lie in this rank
        statevec_hadamardLocal(qureg, targetQubit);
    } else {
        // need to get corresponding chunk of state vector from other rank
        rankIsUpper = chunkIsUpper(qureg.chunkId, qureg.numAmpsPerChunk, targetQubit);
        pairRank = getChunkPairId(rankIsUpper, qureg.chunkId, qureg.numAmpsPerChunk, targetQubit);
        //printf("%d rank has pair rank: %d\n", qureg.rank, pairRank);
        // get corresponding values from my pair
        exchangeStateVectors(qureg, pairRank);
        // this rank's values are either in the upper of lower half of the block. send values to hadamardDistributed
        // in the correct order
        if (rankIsUpper){
            statevec_hadamardDistributed(qureg,
                    qureg.stateVec, //upper
                    qureg.pairStateVec, //lower
                    qureg.stateVec, rankIsUpper); //output
        } else {
            statevec_hadamardDistributed(qureg,
                    qureg.pairStateVec, //upper
                    qureg.stateVec, //lower
                    qureg.stateVec, rankIsUpper); //output
        }
    }
}
References Qureg::chunkId, chunkIsUpper(), exchangeStateVectors(), getChunkPairId(), halfMatrixBlockFitsInChunk(), Qureg::numAmpsPerChunk, Qureg::pairStateVec, qreal, Qureg::stateVec, statevec_hadamardDistributed(), and statevec_hadamardLocal().
Referenced by agnostic_applyQFT(), and hadamard().
statevec_initBlankState()
void statevec_initBlankState (Qureg qureg)
Definition at line 1503 of file QuEST_cpu.c.
{
    long long int stateVecSize;
    long long int index;
    // dimension of the state vector
    stateVecSize = qureg.numAmpsPerChunk;
    // Can't use qureg->stateVec as a private OMP var
    qreal *stateVecReal = qureg.stateVec.real;
    qreal *stateVecImag = qureg.stateVec.imag;
    // initialise the state-vector to all-zeroes
# ifdef _OPENMP
# pragma omp parallel \
    default  (none) \
    shared   (stateVecSize, stateVecReal, stateVecImag) \
    private  (index)
# endif
    {
# ifdef _OPENMP
# pragma omp for schedule (static)
# endif
        for (index=0; index<stateVecSize; index++) {
            stateVecReal[index] = 0.0;
            stateVecImag[index] = 0.0;
        }
    }
}
References Qureg::deviceStateVec, Qureg::numAmpsPerChunk, qreal, and Qureg::stateVec.
Referenced by initBlankState(), statevec_applyPauliSum(), and statevec_initZeroState().
statevec_initClassicalState()
void statevec_initClassicalState (Qureg qureg, long long int stateInd)
Definition at line 1575 of file QuEST_cpu.c.
{
    long long int stateVecSize;
    long long int index;
    // dimension of the state vector
    stateVecSize = qureg.numAmpsPerChunk;
    // Can't use qureg->stateVec as a private OMP var
    qreal *stateVecReal = qureg.stateVec.real;
    qreal *stateVecImag = qureg.stateVec.imag;
    // initialise the state to vector to all zeros
# ifdef _OPENMP
# pragma omp parallel \
    default  (none) \
    shared   (stateVecSize, stateVecReal, stateVecImag) \
    private  (index)
# endif
    {
# ifdef _OPENMP
# pragma omp for schedule (static)
# endif
        for (index=0; index<stateVecSize; index++) {
            stateVecReal[index] = 0.0;
            stateVecImag[index] = 0.0;
        }
    }
    // give the specified classical state prob 1
    if (qureg.chunkId == stateInd/stateVecSize){
        stateVecReal[stateInd % stateVecSize] = 1.0;
        stateVecImag[stateInd % stateVecSize] = 0.0;
    }
}
References Qureg::chunkId, Qureg::deviceStateVec, Qureg::numAmpsPerChunk, qreal, and Qureg::stateVec.
Referenced by initClassicalState().
statevec_initDebugState()
void statevec_initDebugState (Qureg qureg)
Initialise the state vector of probability amplitudes to an (unphysical) state with each component of each probability amplitude a unique floating point value.
For debugging processes
Parameters
[in,out] qureg object representing the set of qubits to be initialised
Definition at line 1696 of file QuEST_cpu.c.
{
    long long int chunkSize;
    long long int index;
    long long int indexOffset;
    // dimension of the state vector
    chunkSize = qureg.numAmpsPerChunk;
    // Can't use qureg->stateVec as a private OMP var
    qreal *stateVecReal = qureg.stateVec.real;
    qreal *stateVecImag = qureg.stateVec.imag;
    indexOffset = chunkSize * qureg.chunkId;
    // initialise the state to |0000..0000>
# ifdef _OPENMP
# pragma omp parallel \
    default  (none) \
    shared   (chunkSize, stateVecReal, stateVecImag, indexOffset) \
    private  (index)
# endif
    {
# ifdef _OPENMP
# pragma omp for schedule (static)
# endif
        for (index=0; index<chunkSize; index++) {
            stateVecReal[index] = ((indexOffset + index)*2.0)/10.0;
            stateVecImag[index] = ((indexOffset + index)*2.0+1.0)/10.0;
        }
    }
}
References Qureg::chunkId, Qureg::deviceStateVec, Qureg::numAmpsPerChunk, qreal, and Qureg::stateVec.
Referenced by initDebugState().
statevec_initPlusState()
void statevec_initPlusState (Qureg qureg)
Definition at line 1543 of file QuEST_cpu.c.
{
    long long int chunkSize, stateVecSize;
    long long int index;
    // dimension of the state vector
    chunkSize = qureg.numAmpsPerChunk;
    stateVecSize = chunkSize*qureg.numChunks;
    qreal normFactor = 1.0/sqrt((qreal)stateVecSize);
    // Can't use qureg->stateVec as a private OMP var
    qreal *stateVecReal = qureg.stateVec.real;
    qreal *stateVecImag = qureg.stateVec.imag;
    // initialise the state to |+++..+++> = 1/normFactor {1, 1, 1, ...}
# ifdef _OPENMP
# pragma omp parallel \
    default  (none) \
    shared   (chunkSize, stateVecReal, stateVecImag, normFactor) \
    private  (index)
# endif
    {
# ifdef _OPENMP
# pragma omp for schedule (static)
# endif
        for (index=0; index<chunkSize; index++) {
            stateVecReal[index] = normFactor;
            stateVecImag[index] = 0.0;
        }
    }
}
References Qureg::deviceStateVec, Qureg::numAmpsPerChunk, Qureg::numChunks, qreal, and Qureg::stateVec.
Referenced by initPlusState().
statevec_initStateFromSingleFile()
int statevec_initStateFromSingleFile (Qureg * qureg, char filename[200], QuESTEnv env)
Definition at line 1730 of file QuEST_cpu.c.
{
    long long int chunkSize, stateVecSize;
    long long int indexInChunk, totalIndex;
    chunkSize = qureg->numAmpsPerChunk;
    stateVecSize = chunkSize*qureg->numChunks;
    qreal *stateVecReal = qureg->stateVec.real;
    qreal *stateVecImag = qureg->stateVec.imag;
    FILE *fp;
    char line[200];
    for (int rank=0; rank<(qureg->numChunks); rank++){
        if (rank==qureg->chunkId){
            fp = fopen(filename, "r");
            // indicate file open failure
            if (fp == NULL)
                return 0;
            indexInChunk = 0; totalIndex = 0;
            while (fgets(line, sizeof(char)*200, fp) != NULL && totalIndex<stateVecSize){
                if (line[0]!='#'){
                    int chunkId = (int) (totalIndex/chunkSize);
                    if (chunkId==qureg->chunkId){
                        sscanf(line, REAL_SPECIFIER ", " REAL_SPECIFIER, &(stateVecReal[indexInChunk]),
                                &(stateVecImag[indexInChunk]));
                        indexInChunk += 1;
                    }
                    totalIndex += 1;
                }
            }
            fclose(fp);
        }
        syncQuESTEnv(env);
    }
    // indicate success
    return 1;
}
References Qureg::chunkId, copyStateToGPU(), line, Qureg::numAmpsPerChunk, Qureg::numChunks, qreal, Qureg::stateVec, and syncQuESTEnv().
Referenced by initStateFromSingleFile().
statevec_initStateOfSingleQubit()
void statevec_initStateOfSingleQubit (Qureg * qureg, int qubitId, int outcome)
Initialise the state vector of probability amplitudes such that one qubit is set to 'outcome' and all other qubits are in an equal superposition of zero and one.
Parameters
[in,out] qureg object representing the set of qubits to be initialised
[in] qubitId id of qubit to set to state 'outcome'
[in] outcome of qubit 'qubitId'
Definition at line 1650 of file QuEST_cpu.c.
{
    long long int chunkSize, stateVecSize;
    long long int index;
    int bit;
    long long int chunkId=qureg->chunkId;
    // dimension of the state vector
    chunkSize = qureg->numAmpsPerChunk;
    stateVecSize = chunkSize*qureg->numChunks;
    qreal normFactor = 1.0/sqrt((qreal)stateVecSize/2.0);
    // Can't use qureg->stateVec as a private OMP var
    qreal *stateVecReal = qureg->stateVec.real;
    qreal *stateVecImag = qureg->stateVec.imag;
    // initialise the state to |0000..0000>
# ifdef _OPENMP
# pragma omp parallel \
    default  (none) \
    shared   (chunkSize, stateVecReal, stateVecImag, normFactor, qubitId, outcome, chunkId) \
    private  (index, bit)
# endif
    {
# ifdef _OPENMP
# pragma omp for schedule (static)
# endif
        for (index=0; index<chunkSize; index++) {
            bit = extractBit(qubitId, index+chunkId*chunkSize);
            if (bit==outcome) {
                stateVecReal[index] = normFactor;
                stateVecImag[index] = 0.0;
            } else {
                stateVecReal[index] = 0.0;
                stateVecImag[index] = 0.0;
            }
        }
    }
}
References Qureg::chunkId, Qureg::deviceStateVec, extractBit(), Qureg::numAmpsPerChunk, Qureg::numChunks, qreal, and Qureg::stateVec.
Referenced by initStateOfSingleQubit().
statevec_initZeroState()
void statevec_initZeroState (Qureg qureg)
Definition at line 1533 of file QuEST_cpu.c.
{
    statevec_initBlankState(qureg);
    if (qureg.chunkId==0){
        // zero state |0000..0000> has probability 1
        qureg.stateVec.real[0] = 1.0;
        qureg.stateVec.imag[0] = 0.0;
    }
}
References Qureg::chunkId, Qureg::deviceStateVec, Qureg::numAmpsPerChunk, qreal, Qureg::stateVec, and statevec_initBlankState().
Referenced by initZeroState().
statevec_measureWithStats()
int statevec_measureWithStats (Qureg qureg, int measureQubit, qreal * outcomeProb)
Definition at line 360 of file QuEST_common.c.
{
    qreal zeroProb = statevec_calcProbOfOutcome(qureg, measureQubit, 0);
    int outcome = generateMeasurementOutcome(zeroProb, outcomeProb);
    statevec_collapseToKnownProbOutcome(qureg, measureQubit, outcome, *outcomeProb);
    return outcome;
}
References generateMeasurementOutcome(), qreal, statevec_calcProbOfOutcome(), and statevec_collapseToKnownProbOutcome().
Referenced by measure(), and measureWithStats().
statevec_multiControlledMultiQubitNot()
void statevec_multiControlledMultiQubitNot (Qureg qureg, int ctrlMask, int targMask)
Definition at line 1099 of file QuEST_cpu_distributed.c.
{
    /* operation is the same regardless of control and target ordering, hence
     * we accept only bitMasks (for convenience of caller, when shifting qubits
     * for density matrices)
     */
    // global index of the first basis state in this node
    long long int firstInd = qureg.chunkId * qureg.numAmpsPerChunk;
    /* optimisation: if this node doesn't contain any amplitudes for which {ctrls}={1}
     * (and hence, neither does the pair node), then these pair nodes have nothing to modify
     * nor any need to communicate, and can halt. No ctrls are contained in the node
     * if the distance from the first index, to the next index where {ctrls}=1, is
     * greater than the total contained amplitudes. This is a worthwhile optimisation,
     * since although we must still wait for the slowest node, we have potentially reduced
     * the network traffic and might avoid saturation.
     */
    if ((firstInd|ctrlMask) - firstInd >= qureg.numAmpsPerChunk)
        return;
    /* nodes communicate pairwise, and (ignoring ctrls) swap all their amplitudes with mate.
     * hence we find |pairState> = X_{targs}|firstStateInNode>, determine which node contains
     * |pairState>, and swap state-vector with it (unless it happens to be this node).
     */
    // global index of the corresponding NOT'd first basis state
    long long int pairInd = firstInd ^ targMask;
    int pairRank = pairInd / qureg.numAmpsPerChunk;
    int useLocalDataOnly = (pairRank == qureg.chunkId);
    if (useLocalDataOnly) {
        // swaps amplitudes locally, setting |a>=X|b>, and |b>=X|a>
        statevec_multiControlledMultiQubitNotLocal(qureg, ctrlMask, targMask);
    } else {
        // swaps amplitudes with pair node
        exchangeStateVectors(qureg, pairRank);
        //  modifies only |a>=X|b> (pair node handles the converse)
        statevec_multiControlledMultiQubitNotDistributed(
            qureg, ctrlMask, targMask,
            qureg.pairStateVec, // in
            qureg.stateVec);    // out
    }
}
References Qureg::chunkId, exchangeStateVectors(), Qureg::numAmpsPerChunk, Qureg::pairStateVec, qreal, Qureg::stateVec, statevec_multiControlledMultiQubitNotDistributed(), and statevec_multiControlledMultiQubitNotLocal().
Referenced by multiControlledMultiQubitNot(), and multiQubitNot().
statevec_multiControlledMultiQubitUnitary()
void statevec_multiControlledMultiQubitUnitary (Qureg qureg, long long int ctrlMask, int * targs, int numTargs, ComplexMatrixN u)
This calls swapQubitAmps only when it would involve a distributed communication; if the qubit chunks already fit in the node, it operates the unitary direct.
It is already gauranteed here that all target qubits can fit on each node (this is validated in the front-end)
Todo:
refactor so that the 'swap back' isn't performed; instead the qubit locations are updated.
Definition at line 1516 of file QuEST_cpu_distributed.c.
{
    // bit mask of target qubits (for quick collision checking)
    long long int targMask = getQubitBitMask(targs, numTargs);
    // find lowest qubit available for swapping (isn't in targs)
    int freeQb=0;
    while (maskContainsBit(targMask, freeQb))
        freeQb++;
    // assign indices of where each target will be swapped to (else itself)
    int swapTargs[numTargs];
    for (int t=0; t<numTargs; t++) {
        if (halfMatrixBlockFitsInChunk(qureg.numAmpsPerChunk, targs[t]))
            swapTargs[t] = targs[t];
        else {
            // mark swap
            swapTargs[t] = freeQb;
            // update ctrlMask if swapped-out qubit was a control
            if (maskContainsBit(ctrlMask, swapTargs[t]))
                ctrlMask = flipBit(flipBit(ctrlMask, swapTargs[t]), targs[t]); // swap targ and ctrl
            // locate next available on-chunk qubit
            freeQb++;
            while (maskContainsBit(targMask, freeQb))
                freeQb++;
        }
    }
    // perform swaps as necessary
    for (int t=0; t<numTargs; t++)
        if (swapTargs[t] != targs[t])
            statevec_swapQubitAmps(qureg, targs[t], swapTargs[t]);
    // all target qubits have now been swapped into local memory
    statevec_multiControlledMultiQubitUnitaryLocal(qureg, ctrlMask, swapTargs, numTargs, u);
    // undo swaps
    for (int t=0; t<numTargs; t++)
        if (swapTargs[t] != targs[t])
            statevec_swapQubitAmps(qureg, targs[t], swapTargs[t]);
}
References cudaFree, cudaMalloc, cudaMemcpy, cudaMemcpyHostToDevice, flipBit(), getQubitBitMask(), halfMatrixBlockFitsInChunk(), ComplexMatrixN::imag, maskContainsBit(), Qureg::numAmpsPerChunk, ComplexMatrixN::numQubits, qreal, ComplexMatrixN::real, statevec_multiControlledMultiQubitUnitaryLocal(), and statevec_swapQubitAmps().
Referenced by applyMultiControlledGateMatrixN(), applyMultiControlledMatrixN(), densmatr_applyMultiQubitKrausSuperoperator(), densmatr_applyTwoQubitKrausSuperoperator(), multiControlledMultiQubitUnitary(), statevec_controlledMultiQubitUnitary(), and statevec_multiQubitUnitary().
statevec_multiControlledMultiRotatePauli()
void statevec_multiControlledMultiRotatePauli (Qureg qureg, long long int ctrlMask, int * targetQubits, enum pauliOpType * targetPaulis, int numTargets, qreal angle, int applyConj)
Definition at line 449 of file QuEST_common.c.
  {
    qreal fac = 1/sqrt(2);
    qreal sgn = (applyConj)? 1 : -1;
    ComplexMatrix2 uRx = {.real={{fac,0},{0,fac}}, .imag={{0,sgn*fac},{sgn*fac,0}}}; // Rx(pi/2)* rotates Z -> Y
    ComplexMatrix2 uRy = {.real={{fac,fac},{-fac,fac}}, .imag={{0,0},{0,0}}};        // Ry(-pi/2) rotates Z -> X
    // this function is controlled on the all-one state, so no ctrl flips
    long long int ctrlFlipMask = 0;
    // mask may be modified to remove superfluous Identity ops
    long long int targMask = getQubitBitMask(targetQubits, numTargets);
    // rotate basis so that exp(Z) will effect exp(Y) and exp(X)
    for (int t=0; t < numTargets; t++) {
        if (targetPaulis[t] == PAULI_I)
            targMask -= 1LL << targetQubits[t]; // remove target from mask
        if (targetPaulis[t] == PAULI_X)
            statevec_multiControlledUnitary(qureg, ctrlMask, ctrlFlipMask, targetQubits[t], uRy);
        if (targetPaulis[t] == PAULI_Y)
            statevec_multiControlledUnitary(qureg, ctrlMask, ctrlFlipMask, targetQubits[t], uRx);
        // (targetPaulis[t] == 3) is Z basis
    }
    // does nothing if there are no qubits to 'rotate'
    if (targMask != 0)
        statevec_multiControlledMultiRotateZ(qureg, ctrlMask, targMask, (applyConj)? -angle : angle);
    // undo X and Y basis rotations
    uRx.imag[0][1] *= -1; uRx.imag[1][0] *= -1;
    uRy.real[0][1] *= -1; uRy.real[1][0] *= -1;
    for (int t=0; t < numTargets; t++) {
        if (targetPaulis[t] == PAULI_X)
            statevec_multiControlledUnitary(qureg, ctrlMask, ctrlFlipMask, targetQubits[t], uRy);
        if (targetPaulis[t] == PAULI_Y)
            statevec_multiControlledUnitary(qureg, ctrlMask, ctrlFlipMask, targetQubits[t], uRx);
    }
}
References getQubitBitMask(), ComplexMatrix2::imag, PAULI_I, PAULI_X, PAULI_Y, qreal, ComplexMatrix2::real, statevec_multiControlledMultiRotateZ(), and statevec_multiControlledUnitary().
Referenced by multiControlledMultiRotatePauli().
statevec_multiControlledMultiRotateZ()
void statevec_multiControlledMultiRotateZ (Qureg qureg, long long int ctrlMask, long long int targMask, qreal angle)
Definition at line 3389 of file QuEST_cpu.c.
{
    long long int offset = qureg.chunkId * qureg.numAmpsPerChunk;
    long long int stateVecSize = qureg.numAmpsPerChunk;
    qreal *stateVecReal = qureg.stateVec.real;
    qreal *stateVecImag = qureg.stateVec.imag;
    qreal stateReal, stateImag;
    qreal cosAngle = cos(angle/2.0);
    qreal sinAngle = sin(angle/2.0);
    // = +-1, to flip sinAngle based on target qubit parity, to effect
    // exp(-angle/2 i fac_j)|j>
    int fac;
    long long int index, globalIndex;
# ifdef _OPENMP
# pragma omp parallel \
    default  (none)              \
    shared   (offset, stateVecSize, stateVecReal,stateVecImag, ctrlMask,targMask, cosAngle,sinAngle) \
    private  (index,globalIndex, fac, stateReal,stateImag)
# endif
    {
# ifdef _OPENMP
# pragma omp for schedule (static)
# endif
        for (index=0; index<stateVecSize; index++) {
            stateReal = stateVecReal[index];
            stateImag = stateVecImag[index];
            // states with not-all-one control qubits are unmodified
            globalIndex = index + offset;
            if (ctrlMask && ((ctrlMask & globalIndex) != ctrlMask))
                continue;
            // odd-parity target qubits get fac_j = -1 (avoid thread divergence)
            fac = 1-2*getBitMaskParity(targMask & globalIndex);
            stateVecReal[index] = cosAngle*stateReal + fac * sinAngle*stateImag;
            stateVecImag[index] = - fac * sinAngle*stateReal + cosAngle*stateImag;
        }
    }
}
References Qureg::chunkId, getBitMaskParity(), Qureg::numAmpsPerChunk, qreal, and Qureg::stateVec.
Referenced by multiControlledMultiRotateZ(), and statevec_multiControlledMultiRotatePauli().
statevec_multiControlledPhaseFlip()
void statevec_multiControlledPhaseFlip (Qureg qureg, int * controlQubits, int numControlQubits)
Definition at line 3749 of file QuEST_cpu.c.
{
    long long int index;
    long long int stateVecSize;
    long long int chunkSize=qureg.numAmpsPerChunk;
    long long int chunkId=qureg.chunkId;
    long long int mask = getQubitBitMask(controlQubits, numControlQubits);
    stateVecSize = qureg.numAmpsPerChunk;
    qreal *stateVecReal = qureg.stateVec.real;
    qreal *stateVecImag = qureg.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
    default  (none)              \
    shared   (stateVecSize, stateVecReal,stateVecImag, mask, chunkId,chunkSize ) \
    private  (index)
# endif
    {
# ifdef _OPENMP
# pragma omp for schedule (static)
# endif
        for (index=0; index<stateVecSize; index++) {
            if (mask == (mask & (index+chunkId*chunkSize)) ){
                stateVecReal [index] = - stateVecReal [index];
                stateVecImag [index] = - stateVecImag [index];
            }
        }
    }
}
References Qureg::chunkId, getQubitBitMask(), Qureg::numAmpsPerChunk, qreal, and Qureg::stateVec.
Referenced by multiControlledPhaseFlip().
statevec_multiControlledPhaseShift()
void statevec_multiControlledPhaseShift (Qureg qureg, int * controlQubits, int numControlQubits, qreal angle)
Definition at line 3297 of file QuEST_cpu.c.
{
    long long int index;
    long long int stateVecSize;
    long long int chunkSize=qureg.numAmpsPerChunk;
    long long int chunkId=qureg.chunkId;
    long long int mask = getQubitBitMask(controlQubits, numControlQubits);
    stateVecSize = qureg.numAmpsPerChunk;
    qreal *stateVecReal = qureg.stateVec.real;
    qreal *stateVecImag = qureg.stateVec.imag;
    qreal stateRealLo, stateImagLo;
    qreal cosAngle = cos(angle);
    qreal sinAngle = sin(angle);
# ifdef _OPENMP
# pragma omp parallel \
    default  (none)              \
    shared   (stateVecSize, stateVecReal, stateVecImag, mask, chunkId,chunkSize,cosAngle,sinAngle) \
    private  (index, stateRealLo, stateImagLo)
# endif
    {
# ifdef _OPENMP
# pragma omp for schedule (static)
# endif
        for (index=0; index<stateVecSize; index++) {
            if (mask == (mask & (index+chunkId*chunkSize)) ){
                stateRealLo = stateVecReal[index];
                stateImagLo = stateVecImag[index];
                stateVecReal[index] = cosAngle*stateRealLo - sinAngle*stateImagLo;
                stateVecImag[index] = sinAngle*stateRealLo + cosAngle*stateImagLo;
            }
        }
    }
}
References Qureg::chunkId, getQubitBitMask(), Qureg::numAmpsPerChunk, qreal, and Qureg::stateVec.
Referenced by multiControlledPhaseShift().
statevec_multiControlledTwoQubitUnitary()
void statevec_multiControlledTwoQubitUnitary (Qureg qureg, long long int ctrlMask, int q1, int q2, ComplexMatrix4 u)
This calls swapQubitAmps only when it would involve a distributed communication; if the qubit chunks already fit in the node, it operates the unitary direct.
Note the order of q1 and q2 in the call to twoQubitUnitaryLocal is important.
Todo:
refactor so that the 'swap back' isn't performed; instead the qubit locations are updated.
the double swap (q1,q2 to 0,1) may be possible simultaneously by a bespoke swap routine.
Definition at line 1460 of file QuEST_cpu_distributed.c.
{
    int q1FitsInNode = halfMatrixBlockFitsInChunk(qureg.numAmpsPerChunk, q1);
    int q2FitsInNode = halfMatrixBlockFitsInChunk(qureg.numAmpsPerChunk, q2);
    if (q1FitsInNode && q2FitsInNode) {
        statevec_multiControlledTwoQubitUnitaryLocal(qureg, ctrlMask, q1, q2, u);
    } else if (q1FitsInNode) {
        int qSwap = (q1 > 0)? q1-1 : q1+1;
        // ensure ctrl == qSwap, ensure ctrlMask updates under the swap
        if (maskContainsBit(ctrlMask, qSwap))
            ctrlMask = flipBit(flipBit(ctrlMask, q2), qSwap);
        statevec_swapQubitAmps(qureg, q2, qSwap);
        statevec_multiControlledTwoQubitUnitaryLocal(qureg, ctrlMask, q1, qSwap, u);
        statevec_swapQubitAmps(qureg, q2, qSwap);
    } else if (q2FitsInNode) {
        int qSwap = (q2 > 0)? q2-1 : q2+1;
        // ensure ctrl == qSwap, ensure ctrlMask updates under the swap
        if (maskContainsBit(ctrlMask, qSwap))
            ctrlMask = flipBit(flipBit(ctrlMask, q1), qSwap);
        statevec_swapQubitAmps(qureg, q1, qSwap);
        statevec_multiControlledTwoQubitUnitaryLocal(qureg, ctrlMask, qSwap, q2, u);
        statevec_swapQubitAmps(qureg, q1, qSwap);
    } else {
        // we know with certainty that both q1 and q2 >= 2
        int swap1 = 0;
        int swap2 = 1;
        // if ctrl == swap1 or swap2, ensure ctrlMask updates under the swap
        if (maskContainsBit(ctrlMask, swap1))
            ctrlMask = flipBit(flipBit(ctrlMask, swap1), q1);
        if (maskContainsBit(ctrlMask, swap2))
            ctrlMask = flipBit(flipBit(ctrlMask, swap2), q2);
        statevec_swapQubitAmps(qureg, q1, swap1);
        statevec_swapQubitAmps(qureg, q2, swap2);
        statevec_multiControlledTwoQubitUnitaryLocal(qureg, ctrlMask, swap1, swap2, u);
        statevec_swapQubitAmps(qureg, q1, swap1);
        statevec_swapQubitAmps(qureg, q2, swap2);
    }
}
References flipBit(), halfMatrixBlockFitsInChunk(), maskContainsBit(), Qureg::numAmpsPerChunk, qreal, statevec_multiControlledTwoQubitUnitaryLocal(), and statevec_swapQubitAmps().
Referenced by densmatr_applyKrausSuperoperator(), multiControlledTwoQubitUnitary(), statevec_controlledTwoQubitUnitary(), and statevec_twoQubitUnitary().
statevec_multiControlledUnitary()
void statevec_multiControlledUnitary (Qureg qureg, long long int ctrlQubitsMask, long long int ctrlFlipMask, int targetQubit, ComplexMatrix2 u)
Definition at line 1013 of file QuEST_cpu_distributed.c.
{
    // flag to require memory exchange. 1: an entire block fits on one rank, 0: at most half a block fits on one rank
    int useLocalDataOnly = halfMatrixBlockFitsInChunk(qureg.numAmpsPerChunk, targetQubit);
    Complex rot1, rot2;
    // rank's chunk is in upper half of block
    int rankIsUpper;
    int pairRank; // rank of corresponding chunk
    if (useLocalDataOnly){
        // all values required to update state vector lie in this rank
        statevec_multiControlledUnitaryLocal(qureg, targetQubit, ctrlQubitsMask, ctrlFlipMask, u);
    } else {
        // need to get corresponding chunk of state vector from other rank
        rankIsUpper = chunkIsUpper(qureg.chunkId, qureg.numAmpsPerChunk, targetQubit);
        getRotAngleFromUnitaryMatrix(rankIsUpper, &rot1, &rot2, u);
        pairRank = getChunkPairId(rankIsUpper, qureg.chunkId, qureg.numAmpsPerChunk, targetQubit);
        // get corresponding values from my pair
        exchangeStateVectors(qureg, pairRank);
        // this rank's values are either in the upper of lower half of the block. send values to multiControlledUnitaryDistributed
        // in the correct order
        if (rankIsUpper){
            statevec_multiControlledUnitaryDistributed(qureg,targetQubit,ctrlQubitsMask,ctrlFlipMask,rot1,rot2,
                    qureg.stateVec, //upper
                    qureg.pairStateVec, //lower
                    qureg.stateVec); //output
        } else {
            statevec_multiControlledUnitaryDistributed(qureg,targetQubit,ctrlQubitsMask,ctrlFlipMask,rot1,rot2,
                    qureg.pairStateVec, //upper
                    qureg.stateVec, //lower
                    qureg.stateVec); //output
        }
    }
}
References Qureg::chunkId, chunkIsUpper(), exchangeStateVectors(), getChunkPairId(), getRotAngleFromUnitaryMatrix(), halfMatrixBlockFitsInChunk(), Qureg::numAmpsPerChunk, Qureg::pairStateVec, qreal, Qureg::stateVec, statevec_multiControlledUnitaryDistributed(), and statevec_multiControlledUnitaryLocal().
Referenced by multiControlledUnitary(), multiStateControlledUnitary(), and statevec_multiControlledMultiRotatePauli().
statevec_multiQubitUnitary()
void statevec_multiQubitUnitary (Qureg qureg, int * targets, int numTargets, ComplexMatrixN u)
Definition at line 569 of file QuEST_common.c.
{
    long long int ctrlMask = 0;
    statevec_multiControlledMultiQubitUnitary(qureg, ctrlMask, targets, numTargets, u);
}
References statevec_multiControlledMultiQubitUnitary().
Referenced by applyGateMatrixN(), applyMatrixN(), and multiQubitUnitary().
statevec_multiRotatePauli()
void statevec_multiRotatePauli (Qureg qureg, int * targetQubits, enum pauliOpType * targetPaulis, int numTargets, qreal angle, int applyConj)
applyConj=1 will apply conjugate operation, else applyConj=0
Definition at line 410 of file QuEST_common.c.
  {
    qreal fac = 1/sqrt(2);
    Complex uRxAlpha = {.real = fac, .imag = 0}; // Rx(pi/2)* rotates Z -> Y
    Complex uRxBeta = {.real = 0, .imag = (applyConj)? fac : -fac};
    Complex uRyAlpha = {.real = fac, .imag = 0}; // Ry(-pi/2) rotates Z -> X
    Complex uRyBeta = {.real = -fac, .imag = 0};
    // mask may be modified to remove superfluous Identity ops
    long long int mask = getQubitBitMask(targetQubits, numTargets);
    // rotate basis so that exp(Z) will effect exp(Y) and exp(X)
    for (int t=0; t < numTargets; t++) {
        if (targetPaulis[t] == PAULI_I)
            mask -= 1LL << targetQubits[t]; // remove target from mask
        if (targetPaulis[t] == PAULI_X)
            statevec_compactUnitary(qureg, targetQubits[t], uRyAlpha, uRyBeta);
        if (targetPaulis[t] == PAULI_Y)
            statevec_compactUnitary(qureg, targetQubits[t], uRxAlpha, uRxBeta);
        // (targetPaulis[t] == 3) is Z basis
    }
    // does nothing if there are no qubits to 'rotate'
    if (mask != 0)
        statevec_multiRotateZ(qureg, mask, (applyConj)? -angle : angle);
    // undo X and Y basis rotations
    uRxBeta.imag *= -1;
    uRyBeta.real *= -1;
    for (int t=0; t < numTargets; t++) {
        if (targetPaulis[t] == PAULI_X)
            statevec_compactUnitary(qureg, targetQubits[t], uRyAlpha, uRyBeta);
        if (targetPaulis[t] == PAULI_Y)
            statevec_compactUnitary(qureg, targetQubits[t], uRxAlpha, uRxBeta);
    }
}
References getQubitBitMask(), Complex::imag, PAULI_I, PAULI_X, PAULI_Y, qreal, Complex::real, statevec_compactUnitary(), and statevec_multiRotateZ().
Referenced by applyExponentiatedPauliHamil(), and multiRotatePauli().
statevec_multiRotateZ()
void statevec_multiRotateZ (Qureg qureg, long long int mask, qreal angle)
Definition at line 3347 of file QuEST_cpu.c.
{
    long long int index;
    long long int stateVecSize;
    long long int chunkSize=qureg.numAmpsPerChunk;
    long long int chunkId=qureg.chunkId;
    stateVecSize = qureg.numAmpsPerChunk;
    qreal *stateVecReal = qureg.stateVec.real;
    qreal *stateVecImag = qureg.stateVec.imag;
    qreal stateReal, stateImag;
    qreal cosAngle = cos(angle/2.0);
    qreal sinAngle = sin(angle/2.0);
    // = +-1, to flip sinAngle based on target qubit parity, to effect
    // exp(-angle/2 i fac_j)|j>
    int fac;
# ifdef _OPENMP
# pragma omp parallel \
    default  (none)              \
    shared   (stateVecSize, stateVecReal, stateVecImag, mask, chunkId,chunkSize,cosAngle,sinAngle) \
    private  (index, fac, stateReal, stateImag)
# endif
    {
# ifdef _OPENMP
# pragma omp for schedule (static)
# endif
        for (index=0; index<stateVecSize; index++) {
            stateReal = stateVecReal[index];
            stateImag = stateVecImag[index];
            // odd-parity target qubits get fac_j = -1
            fac = getBitMaskParity(mask & (index+chunkId*chunkSize))? -1 : 1;
            stateVecReal[index] = cosAngle*stateReal + fac * sinAngle*stateImag;
            stateVecImag[index] = - fac * sinAngle*stateReal + cosAngle*stateImag;
        }
    }
}
References Qureg::chunkId, getBitMaskParity(), Qureg::numAmpsPerChunk, qreal, and Qureg::stateVec.
Referenced by multiRotateZ(), and statevec_multiRotatePauli().
statevec_pauliX()
void statevec_pauliX (Qureg qureg, int targetQubit)
Definition at line 1050 of file QuEST_cpu_distributed.c.
{
    // flag to require memory exchange. 1: an entire block fits on one rank, 0: at most half a block fits on one rank
    int useLocalDataOnly = halfMatrixBlockFitsInChunk(qureg.numAmpsPerChunk, targetQubit);
    // rank's chunk is in upper half of block
    int rankIsUpper;
    int pairRank; // rank of corresponding chunk
    if (useLocalDataOnly){
        // all values required to update state vector lie in this rank
        statevec_pauliXLocal(qureg, targetQubit);
    } else {
        // need to get corresponding chunk of state vector from other rank
        rankIsUpper = chunkIsUpper(qureg.chunkId, qureg.numAmpsPerChunk, targetQubit);
        pairRank = getChunkPairId(rankIsUpper, qureg.chunkId, qureg.numAmpsPerChunk, targetQubit);
        //printf("%d rank has pair rank: %d\n", qureg.rank, pairRank);
        // get corresponding values from my pair
        exchangeStateVectors(qureg, pairRank);
        // this rank's values are either in the upper of lower half of the block. pauliX just replaces
        // this rank's values with pair values
        statevec_pauliXDistributed(qureg,
                qureg.pairStateVec, // in
                qureg.stateVec); // out
    }
}
References Qureg::chunkId, chunkIsUpper(), exchangeStateVectors(), getChunkPairId(), halfMatrixBlockFitsInChunk(), Qureg::numAmpsPerChunk, Qureg::pairStateVec, qreal, Qureg::stateVec, statevec_pauliXDistributed(), and statevec_pauliXLocal().
Referenced by pauliX(), and statevec_applyPauliProd().
statevec_pauliY()
void statevec_pauliY (Qureg qureg, int targetQubit)
Definition at line 1144 of file QuEST_cpu_distributed.c.
{
        int conjFac = 1;
    // flag to require memory exchange. 1: an entire block fits on one rank, 0: at most half a block fits on one rank
    int useLocalDataOnly = halfMatrixBlockFitsInChunk(qureg.numAmpsPerChunk, targetQubit);
    int rankIsUpper;    // rank's chunk is in upper half of block
    int pairRank;               // rank of corresponding chunk
    if (useLocalDataOnly){
        statevec_pauliYLocal(qureg, targetQubit, conjFac);
    } else {
        // need to get corresponding chunk of state vector from other rank
        rankIsUpper = chunkIsUpper(qureg.chunkId, qureg.numAmpsPerChunk, targetQubit);
        pairRank = getChunkPairId(rankIsUpper, qureg.chunkId, qureg.numAmpsPerChunk, targetQubit);
        // get corresponding values from my pair
        exchangeStateVectors(qureg, pairRank);
        // this rank's values are either in the upper of lower half of the block
        statevec_pauliYDistributed(qureg,
                qureg.pairStateVec, // in
                qureg.stateVec, // out
                rankIsUpper, conjFac);
    }
}
References Qureg::chunkId, chunkIsUpper(), exchangeStateVectors(), getChunkPairId(), halfMatrixBlockFitsInChunk(), Qureg::numAmpsPerChunk, Qureg::pairStateVec, qreal, Qureg::stateVec, statevec_pauliYDistributed(), and statevec_pauliYLocal().
Referenced by pauliY(), and statevec_applyPauliProd().
statevec_pauliYConj()
void statevec_pauliYConj (Qureg qureg, int targetQubit)
Definition at line 1169 of file QuEST_cpu_distributed.c.
{
        int conjFac = -1;
    // flag to require memory exchange. 1: an entire block fits on one rank, 0: at most half a block fits on one rank
    int useLocalDataOnly = halfMatrixBlockFitsInChunk(qureg.numAmpsPerChunk, targetQubit);
    int rankIsUpper;    // rank's chunk is in upper half of block
    int pairRank;               // rank of corresponding chunk
    if (useLocalDataOnly){
        statevec_pauliYLocal(qureg, targetQubit, conjFac);
    } else {
        // need to get corresponding chunk of state vector from other rank
        rankIsUpper = chunkIsUpper(qureg.chunkId, qureg.numAmpsPerChunk, targetQubit);
        pairRank = getChunkPairId(rankIsUpper, qureg.chunkId, qureg.numAmpsPerChunk, targetQubit);
        // get corresponding values from my pair
        exchangeStateVectors(qureg, pairRank);
        // this rank's values are either in the upper of lower half of the block
        statevec_pauliYDistributed(qureg,
                qureg.pairStateVec, // in
                qureg.stateVec, // out
                rankIsUpper, conjFac);
    }
}
References Qureg::chunkId, chunkIsUpper(), exchangeStateVectors(), getChunkPairId(), halfMatrixBlockFitsInChunk(), Qureg::numAmpsPerChunk, Qureg::pairStateVec, qreal, Qureg::stateVec, statevec_pauliYDistributed(), and statevec_pauliYLocal().
Referenced by pauliY().
statevec_pauliZ()
void statevec_pauliZ (Qureg qureg, int targetQubit)
Definition at line 257 of file QuEST_common.c.
{
    Complex term;
    term.real = -1;
    term.imag =  0;
    statevec_phaseShiftByTerm(qureg, targetQubit, term);
}
References Complex::imag, Complex::real, and statevec_phaseShiftByTerm().
Referenced by pauliZ(), and statevec_applyPauliProd().
statevec_phaseShift()
void statevec_phaseShift (Qureg qureg, int targetQubit, qreal angle)
Definition at line 250 of file QuEST_common.c.
{
    Complex term;
    term.real = cos(angle);
    term.imag = sin(angle);
    statevec_phaseShiftByTerm(qureg, targetQubit, term);
}
References Complex::imag, Complex::real, and statevec_phaseShiftByTerm().
Referenced by phaseShift().
statevec_phaseShiftByTerm()
void statevec_phaseShiftByTerm (Qureg qureg, int targetQubit, Complex term)
Definition at line 3216 of file QuEST_cpu.c.
{
    long long int index;
    long long int stateVecSize;
    int targetBit;
    long long int chunkSize=qureg.numAmpsPerChunk;
    long long int chunkId=qureg.chunkId;
    // dimension of the state vector
    stateVecSize = qureg.numAmpsPerChunk;
    qreal *stateVecReal = qureg.stateVec.real;
    qreal *stateVecImag = qureg.stateVec.imag;
    qreal stateRealLo, stateImagLo;
    qreal cosAngle = term.real;
    qreal sinAngle = term.imag;
# ifdef _OPENMP
# pragma omp parallel for \
    default  (none) \
    shared   (stateVecSize, stateVecReal,stateVecImag, cosAngle,sinAngle, \
                chunkId,chunkSize,targetQubit) \
    private  (index,targetBit,stateRealLo,stateImagLo) \
    schedule (static)
# endif
    for (index=0; index<stateVecSize; index++) {
        // update the coeff of the |1> state of the target qubit
        targetBit = extractBit (targetQubit, index+chunkId*chunkSize);
        if (targetBit) {
            stateRealLo = stateVecReal[index];
            stateImagLo = stateVecImag[index];
            stateVecReal[index] = cosAngle*stateRealLo - sinAngle*stateImagLo;
            stateVecImag[index] = sinAngle*stateRealLo + cosAngle*stateImagLo;
        }
    }
}
References Qureg::chunkId, extractBit(), Complex::imag, Qureg::numAmpsPerChunk, qreal, Complex::real, and Qureg::stateVec.
Referenced by statevec_pauliZ(), statevec_phaseShift(), statevec_sGate(), statevec_sGateConj(), statevec_tGate(), and statevec_tGateConj().
statevec_reportStateToScreen()
void statevec_reportStateToScreen (Qureg qureg, QuESTEnv env, int reportRank)
Print the current state vector of probability amplitudes for a set of qubits to standard out.
For debugging purposes. Each rank should print output serially. Only print output for systems <= 5 qubits
Definition at line 1478 of file QuEST_cpu.c.
{
    long long int index;
    int rank;
    if (qureg.numQubitsInStateVec<=5){
        for (rank=0; rank<qureg.numChunks; rank++){
            if (qureg.chunkId==rank){
                if (reportRank) {
                    printf("Reporting state from rank %d [\n", qureg.chunkId);
                    printf("real, imag\n");
                } else if (rank==0) {
                    printf("Reporting state [\n");
                    printf("real, imag\n");
                }
                for(index=0; index<qureg.numAmpsPerChunk; index++){
                    //printf(REAL_STRING_FORMAT ", " REAL_STRING_FORMAT "\n", qureg.pairStateVec.real[index], qureg.pairStateVec.imag[index]);
                    printf(REAL_STRING_FORMAT ", " REAL_STRING_FORMAT "\n", qureg.stateVec.real[index], qureg.stateVec.imag[index]);
                }
                if (reportRank || rank==qureg.numChunks-1) printf("]\n");
            }
            syncQuESTEnv(env);
        }
    } else printf("Error: reportStateToScreen will not print output for systems of more than 5 qubits.\n");
}
References Qureg::chunkId, copyStateFromGPU(), Qureg::numAmpsPerChunk, Qureg::numChunks, Qureg::numQubitsInStateVec, Qureg::stateVec, and syncQuESTEnv().
Referenced by reportStateToScreen().
statevec_rotateAroundAxis()
void statevec_rotateAroundAxis (Qureg qureg, int rotQubit, qreal angle, Vector axis)
Definition at line 310 of file QuEST_common.c.
{
    Complex alpha, beta;
    getComplexPairFromRotation(angle, axis, &alpha, &beta);
    statevec_compactUnitary(qureg, rotQubit, alpha, beta);
}
References getComplexPairFromRotation(), and statevec_compactUnitary().
Referenced by rotateAroundAxis(), statevec_rotateX(), statevec_rotateY(), and statevec_rotateZ().
statevec_rotateAroundAxisConj()
void statevec_rotateAroundAxisConj (Qureg qureg, int rotQubit, qreal angle, Vector axis)
Definition at line 317 of file QuEST_common.c.
{
    Complex alpha, beta;
    getComplexPairFromRotation(angle, axis, &alpha, &beta);
    alpha.imag *= -1;
    beta.imag *= -1;
    statevec_compactUnitary(qureg, rotQubit, alpha, beta);
}
References getComplexPairFromRotation(), Complex::imag, and statevec_compactUnitary().
Referenced by rotateAroundAxis().
statevec_rotateX()
void statevec_rotateX (Qureg qureg, int rotQubit, qreal angle)
Definition at line 292 of file QuEST_common.c.
{
    Vector unitAxis = {1, 0, 0};
    statevec_rotateAroundAxis(qureg, rotQubit, angle, unitAxis);
}
References statevec_rotateAroundAxis().
Referenced by rotateX().
statevec_rotateY()
void statevec_rotateY (Qureg qureg, int rotQubit, qreal angle)
Definition at line 298 of file QuEST_common.c.
{
    Vector unitAxis = {0, 1, 0};
    statevec_rotateAroundAxis(qureg, rotQubit, angle, unitAxis);
}
References statevec_rotateAroundAxis().
Referenced by rotateY().
statevec_rotateZ()
void statevec_rotateZ (Qureg qureg, int rotQubit, qreal angle)
Definition at line 304 of file QuEST_common.c.
{
    Vector unitAxis = {0, 0, 1};
    statevec_rotateAroundAxis(qureg, rotQubit, angle, unitAxis);
}
References statevec_rotateAroundAxis().
Referenced by rotateZ().
statevec_setAmps()
void statevec_setAmps (Qureg qureg, long long int startInd, qreal * reals, qreal * imags, long long int numAmps)
Definition at line 1254 of file QuEST_cpu.c.
{
    /* this is actually distributed, since the user's code runs on every node */
    // local start/end indices of the given amplitudes, assuming they fit in this chunk
    // these may be negative or above qureg.numAmpsPerChunk
    long long int localStartInd = startInd - qureg.chunkId*qureg.numAmpsPerChunk;
    long long int localEndInd = localStartInd + numAmps; // exclusive
    // add this to a local index to get corresponding elem in reals & imags
    long long int offset = qureg.chunkId*qureg.numAmpsPerChunk - startInd;
    // restrict these indices to fit into this chunk
    if (localStartInd < 0)
        localStartInd = 0;
    if (localEndInd > qureg.numAmpsPerChunk)
        localEndInd = qureg.numAmpsPerChunk;
    // they may now be out of order = no iterations
    // unpacking OpenMP vars
    long long int index;
    qreal* vecRe = qureg.stateVec.real;
    qreal* vecIm = qureg.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
    default  (none) \
    shared   (localStartInd,localEndInd, vecRe,vecIm, reals,imags, offset) \
    private  (index)
# endif
    {
# ifdef _OPENMP
# pragma omp for schedule (static)
# endif
        // iterate these local inds - this might involve no iterations
        for (index=localStartInd; index < localEndInd; index++) {
            vecRe[index] = reals[index + offset];
            vecIm[index] = imags[index + offset];
        }
    }
}
References Qureg::chunkId, cudaDeviceSynchronize, cudaMemcpy, cudaMemcpyHostToDevice, Qureg::deviceStateVec, Qureg::numAmpsPerChunk, qreal, and Qureg::stateVec.
Referenced by initStateFromAmps(), setAmps(), and setDensityAmps().
statevec_setWeightedQureg()
void statevec_setWeightedQureg (Complex fac1, Qureg qureg1, Complex fac2, Qureg qureg2, Complex facOut, Qureg out)
Definition at line 4036 of file QuEST_cpu.c.
{
    long long int numAmps = qureg1.numAmpsPerChunk;
    qreal *vecRe1 = qureg1.stateVec.real;
    qreal *vecIm1 = qureg1.stateVec.imag;
    qreal *vecRe2 = qureg2.stateVec.real;
    qreal *vecIm2 = qureg2.stateVec.imag;
    qreal *vecReOut = out.stateVec.real;
    qreal *vecImOut = out.stateVec.imag;
    qreal facRe1 = fac1.real;
    qreal facIm1 = fac1.imag;
    qreal facRe2 = fac2.real;
    qreal facIm2 = fac2.imag;
    qreal facReOut = facOut.real;
    qreal facImOut = facOut.imag;
    qreal re1,im1, re2,im2, reOut,imOut;
    long long int index;
# ifdef _OPENMP
# pragma omp parallel \
    shared    (vecRe1,vecIm1, vecRe2,vecIm2, vecReOut,vecImOut, facRe1,facIm1,facRe2,facIm2, numAmps) \
    private   (index, re1,im1, re2,im2, reOut,imOut)
# endif
    {
# ifdef _OPENMP
# pragma omp for schedule  (static)
# endif
        for (index=0LL; index<numAmps; index++) {
            re1 = vecRe1[index]; im1 = vecIm1[index];
            re2 = vecRe2[index]; im2 = vecIm2[index];
            reOut = vecReOut[index];
            imOut = vecImOut[index];
            vecReOut[index] = (facReOut*reOut - facImOut*imOut) + (facRe1*re1 - facIm1*im1) + (facRe2*re2 - facIm2*im2);
            vecImOut[index] = (facReOut*imOut + facImOut*reOut) + (facRe1*im1 + facIm1*re1) + (facRe2*im2 + facIm2*re2);
        }
    }
}
References Complex::imag, Qureg::numAmpsPerChunk, qreal, Complex::real, and Qureg::stateVec.
Referenced by setWeightedQureg(), and statevec_applyPauliSum().
statevec_sGate()
void statevec_sGate (Qureg qureg, int targetQubit)
Definition at line 264 of file QuEST_common.c.
{
    Complex term;
    term.real = 0;
    term.imag = 1;
    statevec_phaseShiftByTerm(qureg, targetQubit, term);
}
References Complex::imag, Complex::real, and statevec_phaseShiftByTerm().
Referenced by sGate().
statevec_sGateConj()
void statevec_sGateConj (Qureg qureg, int targetQubit)
Definition at line 278 of file QuEST_common.c.
{
    Complex term;
    term.real =  0;
    term.imag = -1;
    statevec_phaseShiftByTerm(qureg, targetQubit, term);
}
References Complex::imag, Complex::real, and statevec_phaseShiftByTerm().
Referenced by sGate().
statevec_sqrtSwapGate()
void statevec_sqrtSwapGate (Qureg qureg, int qb1, int qb2)
Definition at line 383 of file QuEST_common.c.
{
    ComplexMatrix4 u = (ComplexMatrix4) {.real={{0}}, .imag={{0}}};
    u.real[0][0]=1;
    u.real[3][3]=1;
    u.real[1][1] = .5; u.imag[1][1] = .5;
    u.real[1][2] = .5; u.imag[1][2] =-.5;
    u.real[2][1] = .5; u.imag[2][1] =-.5;
    u.real[2][2] = .5; u.imag[2][2] = .5;
    statevec_twoQubitUnitary(qureg, qb1, qb2, u);
}
References ComplexMatrix4::imag, ComplexMatrix4::real, and statevec_twoQubitUnitary().
Referenced by sqrtSwapGate().
statevec_sqrtSwapGateConj()
void statevec_sqrtSwapGateConj (Qureg qureg, int qb1, int qb2)
Definition at line 396 of file QuEST_common.c.
{
    ComplexMatrix4 u = (ComplexMatrix4) {.real={{0}}, .imag={{0}}};
    u.real[0][0]=1;
    u.real[3][3]=1;
    u.real[1][1] = .5; u.imag[1][1] =-.5;
    u.real[1][2] = .5; u.imag[1][2] = .5;
    u.real[2][1] = .5; u.imag[2][1] = .5;
    u.real[2][2] = .5; u.imag[2][2] =-.5;
    statevec_twoQubitUnitary(qureg, qb1, qb2, u);
}
References ComplexMatrix4::imag, ComplexMatrix4::real, and statevec_twoQubitUnitary().
Referenced by sqrtSwapGate().
statevec_swapQubitAmps()
void statevec_swapQubitAmps (Qureg qureg, int qb1, int qb2)
Definition at line 1433 of file QuEST_cpu_distributed.c.
{
    // perform locally if possible
    int qbBig = (qb1 > qb2)? qb1 : qb2;
    if (halfMatrixBlockFitsInChunk(qureg.numAmpsPerChunk, qbBig))
        return statevec_swapQubitAmpsLocal(qureg, qb1, qb2);
    // do nothing if this node contains no amplitudes to swap
    long long int oddParityGlobalInd = getGlobalIndOfOddParityInChunk(qureg, qb1, qb2);
    if (oddParityGlobalInd == -1)
        return;
    // determine and swap amps with pair node
    int pairRank = flipBit(flipBit(oddParityGlobalInd, qb1), qb2) / qureg.numAmpsPerChunk;
    exchangeStateVectors(qureg, pairRank);
    statevec_swapQubitAmpsDistributed(qureg, pairRank, qb1, qb2);
}
References exchangeStateVectors(), flipBit(), getGlobalIndOfOddParityInChunk(), halfMatrixBlockFitsInChunk(), Qureg::numAmpsPerChunk, qreal, statevec_swapQubitAmpsDistributed(), and statevec_swapQubitAmpsLocal().
Referenced by agnostic_applyQFT(), statevec_multiControlledMultiQubitUnitary(), statevec_multiControlledTwoQubitUnitary(), and swapGate().
statevec_tGate()
void statevec_tGate (Qureg qureg, int targetQubit)
Definition at line 271 of file QuEST_common.c.
{
    Complex term;
    term.real = 1/sqrt(2);
    term.imag = 1/sqrt(2);
    statevec_phaseShiftByTerm(qureg, targetQubit, term);
}
References Complex::imag, Complex::real, and statevec_phaseShiftByTerm().
Referenced by tGate().
statevec_tGateConj()
void statevec_tGateConj (Qureg qureg, int targetQubit)
Definition at line 285 of file QuEST_common.c.
{
    Complex term;
    term.real =  1/sqrt(2);
    term.imag = -1/sqrt(2);
    statevec_phaseShiftByTerm(qureg, targetQubit, term);
}
References Complex::imag, Complex::real, and statevec_phaseShiftByTerm().
Referenced by tGate().
statevec_twoQubitUnitary()
void statevec_twoQubitUnitary (Qureg qureg, int targetQubit1, int targetQubit2, ComplexMatrix4 u)
Definition at line 557 of file QuEST_common.c.
{
    long long int ctrlMask = 0;
    statevec_multiControlledTwoQubitUnitary(qureg, ctrlMask, targetQubit1, targetQubit2, u);
}
References statevec_multiControlledTwoQubitUnitary().
Referenced by applyMatrix4(), statevec_sqrtSwapGate(), statevec_sqrtSwapGateConj(), and twoQubitUnitary().
statevec_unitary()
void statevec_unitary (Qureg qureg, int targetQubit, ComplexMatrix2 u)
Definition at line 897 of file QuEST_cpu_distributed.c.
{
    // flag to require memory exchange. 1: an entire block fits on one rank, 0: at most half a block fits on one rank
    int useLocalDataOnly = halfMatrixBlockFitsInChunk(qureg.numAmpsPerChunk, targetQubit);
    Complex rot1, rot2;
    // rank's chunk is in upper half of block
    int rankIsUpper;
    int pairRank; // rank of corresponding chunk
    if (useLocalDataOnly){
        // all values required to update state vector lie in this rank
        statevec_unitaryLocal(qureg, targetQubit, u);
    } else {
        // need to get corresponding chunk of state vector from other rank
        rankIsUpper = chunkIsUpper(qureg.chunkId, qureg.numAmpsPerChunk, targetQubit);
        getRotAngleFromUnitaryMatrix(rankIsUpper, &rot1, &rot2, u);
        pairRank = getChunkPairId(rankIsUpper, qureg.chunkId, qureg.numAmpsPerChunk, targetQubit);
        // get corresponding values from my pair
        exchangeStateVectors(qureg, pairRank);
        // this rank's values are either in the upper of lower half of the block.
        // send values to compactUnitaryDistributed in the correct order
        if (rankIsUpper){
            statevec_unitaryDistributed(qureg,rot1,rot2,
                    qureg.stateVec, //upper
                    qureg.pairStateVec, //lower
                    qureg.stateVec); //output
        } else {
            statevec_unitaryDistributed(qureg,rot1,rot2,
                    qureg.pairStateVec, //upper
                    qureg.stateVec, //lower
                    qureg.stateVec); //output
        }
    }
}
References Qureg::chunkId, chunkIsUpper(), exchangeStateVectors(), getChunkPairId(), getRotAngleFromUnitaryMatrix(), halfMatrixBlockFitsInChunk(), Qureg::numAmpsPerChunk, Qureg::pairStateVec, qreal, Qureg::stateVec, statevec_unitaryDistributed(), and statevec_unitaryLocal().
Referenced by applyMatrix2(), and unitary().